### ISSUE TITLE
Mamy design okna O Aplikacji

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/specs#10]
Użytkownik może otworzyć okno O Aplikacji. Znajdzie tam następujące dane:
* Wersję aplikacji
* Identyfikator użytkownika (Jest to pierwsza ćwiartka user_id, 8 pierwszych bajtów w formacie hex np. `Identyfikator użytkownika: a809-8c1a-f86e-11da`)
* Przycisk `Prześlij historię` który kieruje do wysyłki danych.

**Comment by Saibamen** [comment]
Jeśli robisz takie issue, że coś mamy, to fajnie by było od razu podlinkować do tego designu albo uploadować bezpośrednio tutaj...

**Comment by jakublipinski** [comment]
Dotyczy nieistniejącego ProteGO 1.0 więc zamykam na prośbę @MateuszRomanow
