### ISSUE TITLE
Jaki jest status aplikacji?

### ISSUE THREAD

**Issue by mpodlasin** [ProteGO-Safe/specs#106]
Hej, wybaczcie, jeśli jakoś śmiecę.

Zacząłem czytać o contact tracingu w Azji i zastanawiałem się czy jest wersja polska i tak po nitce do kłębka trafiłem tutaj.

Trochę mnie niepokoi, że sam musiałem się ostro wysilić, żeby dowiedzieć się, że robimy coś takiego u nas i żeby trafić do tego repo.

Stąd mam pytania:

1) Jaki jest status aplikacji? Czy to jest gotowe do używania? Czy można już namawiać znajomych i ludzi w ogóle od używania? Czy czekamy na coś? A jeśli czekamy, to czy mamy jakąś estymatę kiedy będzie "launch"?

2) Jak to będzie z promocją? Kluczem do sukcesu jest oczywiście zachęcenie większości ludzi do używania aplikacji i zapewnienie ich o bezpieczeństwie / poszanowania prywatności. Czy to jest ogarnięte od strony rządowej / ministerstwa i nie powinienem się tym specjalnie przejmować, czy też jest jakaś potrzeba inicjatywy oddolnej i nagłaśniania tematu wśród ludzi wokół siebie?

3) Widzę, że jest jakaś wersja "web" aplikacji? Do czego ona służy?

Z góry dzięki za odpowiedzi. BTW fajnie gdyby odpowiedzi na 1) i 2) się znalazły w README, bo to są pierwsze pytania osoby która "przypadkowo" tu ląduje.

Dzięki za waszą pracę, jestem pod wrażeniem.

PS. Programuję profesjonalnie w JS i Pythonie, raczej front-end, gdybyście potrzebowali jakiejś dodatkowej pomocy, dajcie znać.

**Comment by AdamStelmaszczyk** [comment]
Zerknij do #104.

**Comment by MateuszRomanow** [comment]
Cześć,
w olbrzymim skrócie: w ciągu ostatnich 4 tygodniu trzy niezależne drużyny pracowały nad różnymi rodzajami wsparcia via technologia przy walce z COVID-19. Finalnie udało nam się połączyć i skupić w ramach tej organizacji. Sprawa jest bardzo świeża, w zasadzie nie ma dnia bez pivota. Brak czasu na np. uzupełnienie README - musimy to nadgonić szybko. 

Dzisiaj ukazał się efekt naszej wspólnej pracy , dowieźliśmy sprint, teraz porządkujemy i jedziemy dalej. 

Aktualizacja ze strony Ministerstwa Cyfryzacji [TUTAJ](https://www.gov.pl/web/cyfryzacja/pokonajmy-razem-koronawirusa--poznaj-protego-safe)

**Comment by mpodlasin** [comment]
Dzięki, a jeszcze jedno pytanie, czy update do rozwiązania Google i Apple będzie się dział w formie automatycznej aktualizacji tej appki, czy też będzie trzeba instalować nowe rozwiązanie?

Widziałem, że to ma być raczej jakieś API od Google i Apple, więc raczej to pierwsze?

**Comment by MateuszRomanow** [comment]
Hej,
ad 1 
niestety - integracja API Googla to będzie trudna misja pod kątem zachowania kompatybilności wstecznej. Nasza misja teraz, to tak przygotować zbieranie danych, żeby jak najbardziej zbliżyć się do ich późniejszego, możliwego użycia w Google&Apple. Więc bliżej nam do drugiego scenariusza z opisanych przez Ciebie. 
ad 2 
W chwili obecnej aplikacja nie ma żadnej formy tracingu. Zapisywanie danych oparte o zmodyfikowany OpenTrace ukaże się w kolejnej wersji apki, możliwość pracy na tych danych w jeszcze kolejnej. Perspektywa kilku-kilkuastu dni. W między czasie wyjdzie iOS i cały czas lecą fixy.

**Comment by Dr-Kownacki** [comment]
@MateuszRomanow 
Dzisiaj w appce dostałem taki komunikat;

"Właśnie dodaliśmy do niej nowe funkcjonalności. **Włącz w swoim telefonie Bluetooth. Dzięki temu wszyscy będziemy ostrzegać się nawzajem.** Nie zmienia się jedno – uzupełnij test oceny ryzyka. Zespół ProteGO Safe"

czy możesz ew. odesłać do jakiegoś referencyjnego wątku/miejsca z info o tym (jak to / czy już? to działa etc. ) ? 

Dzięki z góry i trzymam kciuki za dalszy rozwój aplikacji, bo bardzo się w temat wciągnąłem  :-)

**Comment by MateuszRomanow** [comment]
Kończymy dokument, który wrzucimy do readme - tam będzie to szczegółowo opisane. Od wersji 3.0.0, która jest już publiczna w aplikacji pojawił się moduł OpenTrance który pozwala na anonimowe tworzenie historii anonimowo widzianych przez aplikację innych anonimowych aplikacji. Jeżeli użytkownik aplikacji zostanie zdiagnozowany (medycznie) jako chory na COVID-19 skontaktuje się z nim Centrum Kontaktu (kontakt niezależny od aplikacji). Użytkownik otrzyma instrukcję, w ramach które (dobrowolnie) może zuploadować swoją historię anonimowych urządzeń, z którymi widziała się jego aplikacja. Taki scenariusz gwarantuje, że tylko osoby zweryfikowane jako chore mogą wysłać swoją anonimową historię (brak false positive). Ta informacja zostanie przeliczona przez serwer, a następnie osoby, których anonimowe TempID widziało się z chorym (który to kontakt spełnia odpowiednie parametry: czas, odległość, pewność) zostaną w aplikacji poinformowane o tym, że zmieniła się ich grupa ryzyka. Aplikacja dalej także zaproponuje dalsze działania w zależności od tego w jakiej grupie ryzyka znalazł się użytkownik. 

Dane opuszczają urządzenie tylko wtedy, kiedy użytkownik na to pozwoli. Zrobienie tego ochroni inne osoby jako "system wczesnego ostrzegania".

**Comment by potiuk** [comment]
Czyli jednak tylnym drzwiami, bez informowania opinii publicznej i bez możliwości przejrzenia kodu i stwierdzenia jej anonimowości wprowadziliście coś czego mieliście nie wprowadzać a jedynie używać do testów. No naprawdę. Będzie teraz burza. I cały pomysł aplikacji polegnie. Super Robota. Gratuluję. Właśnie totalnie zniszczyliście zaufanie do tej aplikacji.

**Comment by potiuk** [comment]
Nie wiem jak inni, ale ja mam zamiar skontaktować się z zespołami z Google i Apple i poprosić ich żeby zablokowali applikację w sklepie jako śledzący malware (nie przez aplikację - bezpośrednio z osobami, które mają na to wpływ).

Dziękuję.

**Comment by mateuszjablonski** [comment]
Czyli projekt oficjalnie przestał być otwarty i transparentny, tak?

**Comment by potiuk** [comment]
Niestety, tak to wygląda w tej chwili.

**Comment by mateuszjablonski** [comment]
@potiuk czy masz wiedzę o jakimś alternatywnym, polskim projekcie, w którym nie będzie takich kwiatków?

**Comment by potiuk** [comment]
To musi być aplikacja zaimplemenotowana we współpracy z Health Authorities. Mam nadzieję że jednak docelowo ta (lub inna aplikacja) będzie zaimplementowana za pomocą protokołu Google + Apple  (API być może publicznie dostępne nawet dziś).

**Comment by potiuk** [comment]
Ale w tej chwili sposób działania twórców aplikacji zaprzecza całkowicie otwartości tego rozwiazania. Ja już całkiem straciłem zaufanie do tego, że nie ma tu ukrytych intencji. Szkoda. To był potrzebny projekt a MC i twórcy aplikacji tak cudownie to zepsuli.

**Comment by MateuszRomanow** [comment]
@potiuk dzięki za rozmowę. Tak jak wspominałem:
1) przygotowujemy dokumentację, którą wrzucimy tutaj asap; wszystko do prześwietlenia 
2) kody koledzy wrzucili kilka dni wcześniej tutaj, bez wypychania tego wyżej - zagdza się - błąd popełniony po naszej stronie, szczerze to przyjmujemy. Na przyszłość @qLb @bartosztomczak zawsze potrzebny szeroki update, że wjechała nowa wersja dla uniknięcia wątpliwości 
3) Tak jak pisałem wiele razy wcześniej - dopóki nie ma Google + Apple MC poprosiło o integrację OpenTrace, wspominałem o tym tu #104 , nic się w tym temacie nie zmieniło. Zanim natomiast opublikujemy kolejne wersje, które będą pozwalały na upload danych - wszystko będzie tutaj. 
4) Jak tylko G&A faktycznie opublikuje konkrety, to będziemy się przestawiać na to rozwiązanie - o tym też pisałem, że taki jest kierunek i intencja
5) OpenTrace w naszej implementacji ma zapewniać anonimizację - dlatego nie ma (nie tylko opcjonalnej) ale w ogóle opcji/miejsca/funkcjonalności na podawanie numerów telefonów. 
skanujmy, sprawdzajmy, audytujmy kod - wszystko . Jest dostępne
6) Wszystko co wymaga poprawki i zostanie znalezione - poprawimy, wszystko co wzbudza wątpliwość przedyskutujemy.

**Comment by kolmir** [comment]
> 
> 
> Czyli projekt oficjalnie przestał być otwarty i transparentny, tak?

A kiedyś był? I czy w ogóle ktoś to prowadzi jako **projekt**? ;-)
Czy ktoś widział DoR/DoD, Sprint-log, Risk&issue-log, LL, założenia, nazwiska ekspertów/interesariuszy?, niezależnych audytorów z renomowanej firmy i/lub z NGOs?

**Comment by mpodlasin** [comment]
Yyy. Czy możemy wyjaśnić tę sprawę?

@potiuk 

Jako postronny użytkownik, ciężko mi nawet zrozumieć co zarzucasz projektowi? Rozumiem, że kod który wszedł w nowej wersji aplikacji, nie jest jeszcze opublikowany tutaj?

**Comment by potiuk** [comment]
Został oopublikowany w jednym dużym "rzucie" https://github.com/ProteGO-Safe/android/commit/7590f5be3e942e40deb2548c007d465389821b20 bez dyskusji, zapowiedzi, uaktualnienia specyfikacji i odniesienia się do zastrzeżeń wcześniej zgłaszanych. Dopiero wczoraj po naleganiach i rozmowach pojawiła się specyfikacja która w wieli miejscach dotyczących anonimowości (po dyskusji w #119) oraz zgodności z wytycznymi o których specyfikacja wspomina.

Wczorak też wprowadzono nowe zasady code of conduct i szablony i moje zgłoszenie ze #119 zostało zamknięte z zarzurami (nie konkretnymi) naruszania tego code of conduct który był wrzucony wczoraj. Dziś rano zsyntetyzowałem wszystko co było w dysjusji #119 i stworzyłem dwa "Bug Reports" (podązając za szablonami wrzuconymi wczoraj). 

- #123 -> odnoszący się do niezgodności specyfkacji z implementacją
- #124 -> odnoszący się do niezgodności specyfikacji opisującą przyszłą funkcjonalność QR z wytycznymi EROD (EPDB) do których sama specyfikacja się odwołuje.

Mam nadzieję że  @MateuszRomanow  wywiąże się ze swoich słów:
> 6\. Wszystko co wymaga poprawki i zostanie znalezione - poprawimy, wszystko co wzbudza wątpliwość przedyskutujemy.

Mam nadzieję że błędy, które zgłosiłem zostaną porawione a wątpliwości przedyskutowane.

**Comment by mpodlasin** [comment]
O, to jest świetny komentarz, dzięki wielkie!

**Comment by MateuszRomanow** [comment]
Szybki update:
1. Przedstawiłem dzisiaj do Ministerstwa Cyfryzacji wątpliwości jakie zebrałem z naszych rozmów (interpretowalna komunikacja 110% vs 100% w galeriach, interpretowana nie dobrowolność aplikacji w centrach, wspominania nie dobrowolność, ograniczanie dostępu i obsługi uzależnione od aplikacji). 
2. Wskazałem, że rozwianie wątpliwość sprostowanie tych kwestii jest kluczowe i powinno się odbyć asap. 
3. Wspomniałem, że nie jestem rzecznikiem MC i MC czy MR komunikuje samodzielnie. 

W zamian ze strony MC dostałem dostałem:
- zapewnienie, że w założeniach nic się nie zmieniło, czyli dobrowolność jest pełna na każdym etapie
- sprostowanie zostanie wydane asap 

tldr: czekamy na komunikat, który rozwieje wszelkie wątpliwości w tym obszarze. 

Ze spraw innych - zapraszaliśmy Niebezpiecznik kilkukrotnie w ciągu ostatnich tygodni (także w okresie, kiedy jeszcze developowaliśmy SafeSafe jako oddolną, społeczna inicjatywę) do audytu security. Nie spotkało się to z odpowiedzią. To audyt realnie wpłynie na quality i cały czas liczę, że uda się go zrealizować jeżeli Niebezpiecznik uważa, że ta sprawa jest ważna. Również audyt i konsultacje np. kodów QR.

**Comment by Dr-Kownacki** [comment]
@MateuszRomanow  kilka dni temu zgłosiłem do niebezpiecznik.pl oczywiście ten wątek #109

nie mam odpowiedzi póki co, ale może po prostu z lamerami takimi jak ja nie gadają, chociaż tym ostatnim wpisem trochę mnie tutaj pocieszyłeś i dałeś nadzieję  ;-)

BTW: moje amatorskie-lamerskie obserwacje/testy/uwagi tutaj: #126

**Comment by D0han** [comment]
Nie rozumiem skąd te przywiązanie do niebezpiecznika, ale ten się już wypowiedział w sprawie: https://niebezpiecznik.pl/post/albo-zainstalujesz-rzadowa-aplikacje-protego-safe-albo-nie-wejdziesz-do-sklepu/

Nie jest to wypowiedź specjalnie pochlebna, by nie powiedzieć dosadniej.

**Comment by mpodlasin** [comment]
Artykuł ma wiele ciekawych uwag, ale ten tytuł jest rodem z TVP - manipulacja i straszenie ludzi...

A niby my jesteśmy "Ci lepsi"... 

Szkoda. Ja mam wrażenie, że ludzie wyrobili sobie opinię, jeszcze zanim aplikacja powstała.

**Comment by potiuk** [comment]
> Nie rozumiem skąd te przywiązanie do niebezpiecznika, ale ten się już wypowiedział w sprawie: https://niebezpiecznik.pl/post/albo-zainstalujesz-rzadowa-aplikacje-protego-safe-albo-nie-wejdziesz-do-sklepu/

Chyba właśnie to był audyt. Bardzo konkretny według mnie. 

@MateuszRomanow -> chciałbym żebyś sprecyzował czy prosiłeś o audyt "security" czy "privacy". Podobne już pytanie zadałem Ci przez telefon ale wtedy odpowiedź była inna. Tłumaczę różnicę:

* audyt security - sprawdzenie czy dane są zabezpieczone przed wyciekami, atakującymi etc.
* audyt privacy - sprawdzenie czy aktorzy którzy legalnie mają dostęp do danych nie mogą ich wykorzystać w celu "naruszenia prywatności"

Czy mógłbyś sprecyzować.

**Comment by MateuszRomanow** [comment]
> Artykuł ma wiele ciekawych uwag, ale ten tytuł jest rodem z TVP - manipulacja i straszenie ludzi...
> 
> A niby my jesteśmy "Ci lepsi"...
> 
> Szkoda. Ja mam wrażenie, że ludzie wyrobili sobie opinię, jeszcze zanim aplikacja powstała.

Pojawiło się sprostowanie MC: https://www.gov.pl/web/cyfryzacja/z-protego-safe-do-sklepu---obalamy-mity

W temacie security/privacy - oba. Sprawdzamy oba i szukamy partnerów do audytu w obu obszarach.

**Comment by jasisz** [comment]
Chciałbym bardzo zaudytować backend (to moja działka). Problem jest taki, że... teraz nie jest on publiczny.

**Comment by potiuk** [comment]
> Chciałbym bardzo zaudytować backend (to moja działka). Problem jest taki, że... teraz nie jest on publiczny.

No właśnie - Ten artukuł mówi nieprawdę (z resztą nie jedną). Kod backendu nie jest publiczny i nie wiadomo na jakiej ma być licenciji. Poprzednio miał być na AGPL 

@MateuszRomanow czy mógłbyś sie na ten temat wypowiedzieć ? Osobiście już dziś dziennikarzom kika razy opowiadałem całą historię (będzie jeszcze kilka artykułów na ten temat wkrótce)  i chciałbym móc powiedzieć coś więcej niż że od dwóch tygodni czekam na odpowiedź.

**Comment by Tarvald** [comment]
https://github.com/ProteGO-Safe/backend

Backend dla 4.1 dostępny.
Wątek od dłuższego czasu nieaktywny.
Jeżeli nikt nie ma nic przeciwko, to zamkne go w najbliższym czasie.
A w razie pytań, można założyć nowy wątek, aktualny z obecnymi założeniami.
