### ISSUE TITLE
Wprowadzenie zarażenia do systemu

### ISSUE THREAD

**Issue by matsobdev** [ProteGO-Safe/specs#115]
Czy nie byłoby wskazane, aby zmiana statusu użytkowania na zarażony była możliwa tylko po zeskanowaniu np. wygenerowanego w tym celu kodu QR z wyniku badania? Trzeba by się zastanowić nad tym, jak to zrobić, aby nie powstał do tego np. "keygen" albo chociaż maksymalnie to utrudnić. Oczywiście kod jednorazowy.

W tym QR mogły by być wszystkie inne argumenty zasilające usługę Exposure Notification podczas wywołania funkcji wysyłania DKs na serwer.

PS. W sumie nie musi być to super wysublimowane, bo jak ktoś będzie chciał, to zrobi i tak swoją apkę w oparciu o API... (chyba, że usługa zadziała tylko na certyfikowanej apce z białej listy). Tak tylko żeby ograniczyć głupie żarty i tym podobne zachowania.

**Comment by potiuk** [comment]
Ale tak to właśnie ma wyglądać. Polecam lekturę API G+A (dziś opublikują więcej na ten temat). Kod ma być jednorazowy generowany przez osoby z "Health Authorities" - każde Health Authorities ma stworzyć swój sposób w jaki ten kod będą bezpiecznie generować i przekazywać pacjentom. Ale z zasady - podobnie jak w przypadku BLIK-a czy przelewów bankowych, najlepszym wyjściem będzie jednorazowy kod, ograniczony w czasie i nie generowany jakimś generatorem tylko za każdym razem generowany wtedy kiedy diagnoza jest pozytywna i przypisany do tej konkretnej diagnozy.
