### ISSUE TITLE
Minimalna wymagana interakcja aplikacji z otoczeniem dla uzyskania "zielonego" statusu

### ISSUE THREAD

**Issue by miklobit** [ProteGO-Safe/specs#121]
Tytułowe zagadnienie, ze znakiem zapytania na końcu, jest próbą rozłożenia na czynniki pierwsze scenariusza w którym użytkownik zostanie  w jakim momencie zmuszony/zobligowany do używania aplikacji a niespecjalnie będzie miał na to ochotę.  
Z jednej strony deklaracje rządu i  założenia techniczne aplikacji wskazują, że nie będzie prawnego nakazu  instalacji i używania  (tak jak "kwarantanny domowej") ale z drugiej strony ten sam rząd podkreśla, że będzie chciał maksymalnie upowszechnić jej użycie.  Z zakresu funkcjonalności dla wersji 3.1 wynika, że to "upowszechnianie" odbędzie się poprzez zachęcanie instytucji ( dostaną do tego własną wersję apki), do kontroli swoich klientów przez okazywanie statusu z aplikacji. Na razie te pomysły (czy sugestie) dotyczą "miękkiej" formy kontroli na zasadzie "pokaż status to dostaniesz bonus/pierwszeństwo/extra wejście ponad limit". Ja nie mam żadnych wątpliwości, że to jest pierwszy etap, który ma ludzi przyzwyczaić metodą marchewki,  a kiedy już baza użytkowników przekroczy pewną masę krytyczną to marchewka zostanie stopniowo podmieniona kijem i status z aplikacji nie będzie warunkiem otrzymania bonusu ale np warunkiem wejścia w jakieś miejsce w  ogóle. I tu wracamy do tytułowego pytania. Mamy użytkownika, opornego wobec takich przymusów (ja na pewno zaliczam się to tej grupy...), który chce jednocześnie korzystać ze swoich praw (np. wchodzenia w "bramkowane" miejsca) a równoczesnie minimalizować swoje  interakcję z "systemem" i zostawiane ślady. 
Mamy więc takie szczegółowe pytania: 
- czy aplikacja po początkowej instalacji (kiedy uzyska z serwera swój identyfikator oraz listę TempID na 2tyg. do przodu.) będzie wymagać stałego/okresowego połaczenia z serwerem stałej/okresowej aktywności modułów bluetooth/wifi/gsm ?
- czy dla użyskania zielonego statusu ( = brak kontaktu z potwierdzonymi zakażonymi przez min 14 dni) będzie wymagana jakakolwiek wymiana id przez bluetooth z innym urządzeniem na ktorym jest aplikacja w tym okresie ? Ew czy będzie jakieś wymagane minimum takich interakcji ?
- co się stanie kiedy przez 2tyg telefon będzie odłączony od sieci i pobrana lista tempID się wyczerpie ? Czy to będzie miało jakiś wpływ na zmianę statusu ? 
- czy po uzyskaniu statusu "zielonego" ( 14 dni bez kontaktu z "zarażonym ID ) ten status będzie miał jakiś okres wazności jeśli tel nie będzie miał połaczenia z siecią czyli nie będzie mógł statusu zaktualizować ?
- czy moment generowania statusu w aplikacji ( + kodu QR do weryfikacji) będzie wymagać połaczenia z siecią (czyli ujawniania swojej lokalizacji ,przynajmniej wobec operatora) ? Czy to będzie możliwe np jeśli telefon będzie wtedy miał wyłaczone wszystkie moduły RF (tryb lotniczy) ?  
- czy kod QR ze statusem będzie mieć jakiś znacznik czasowy który druga strona będzie weryfikować ? Czyli np czy bęðzie mozliwy taki scenariusz, że nie mam zamiaru zabierać telefonu więc moge ten swój kod QR pokazać w formie wydruku czy screenshot 'a z inego urządzenia i będzie on ważny przez jakiś czas od momentu wygenerowania ? 
- czy oderwanie id aplikacji od telefonu (generowanie jej na serwerze) oznacza, że po sklonowaniu aplikacji i lokalnych danych na innym telefonie ta druga kopia będzie dalej działać i pokazywać ten sam status co oryginalna ? 

Te wszystkie pytania zmierzają jak widać do ustalenia jakie sa minimalne warunki żeby "zaliczyć" status, który będzie dawał prawo traktowania jako osoba bezpieczna i jednocześnie zminimalizować konieczność "udowodnienia", że aplikacja była realnie używana a nie że np telefon leżał w szufladzie z wyłaczonymi modułami RF

**Comment by SeraMoon** [comment]
Po co im wytykasz te dziury? Im mniej wytkniemy tym więcej wolności nam pozostanie gdy wejdzie **rygor kija**.

**Comment by miklobit** [comment]
@SeraMoon  przecież na pewo wiesz , że na podstawie  tak ogólnej spec nie można wytknąć żadnych dziur a jedynie zadawać pytania. A nie zadając pytań trudno zwrócić uwagę szerszej publiczności na możliwe/prawdopodobne czarne scenariusze, które grożą ludziom kiedy aplikacja będzie w  masowym użyciu. Jeżeli zadane pytania doczekają się prezycyjnych odpowiedzi to będziemy mogli oszacować w jakims stopniu możliwy "potencjał zamordyzmu" i np dać się odnieść do tego organizacjom , które z zamordyzmem i nadzorem  walczą prawnie.

**Comment by qLb** [comment]
@miklobit Ktore z postawionych przez Ciebie pytan ma na celu usprawnienie projektu ProteGO-Safe? Wskaz je jasno i zaznacz najlepiej naglowkiem aby mozna je bylo latwo wskazac w internecie.

**Comment by potiuk** [comment]
> @miklobit Ktore z postawionych przez Ciebie pytan ma na celu usprawnienie projektu ProteGO-Safe? Wskaz je jasno i zaznacz najlepiej naglowkiem aby mozna je bylo latwo wskazac na forum.

Wszystkie. Aplikacja której nikt nie zainstaluję bo będą podejrzenia o inwigilację. Będzie miała dokłądnie 0 sprawności. Nie odpowiadając na te (i moje) pytania wprost sprawiacie wrażenie że chcecie coś ukryć, co ewidentnie nie wpływa na zaufanie do aplikacji.

**Comment by qLb** [comment]
@potiuk poczekajmy az autor wroci do tematu. Twoje opinie sa mi bardzo dobrze znane :) Dziekuje. Ps. Tak nadal nienadazamy z dokumentacja - co nie znaczy, ze nalezy nam to utrudniac.

**Comment by miklobit** [comment]
> @miklobit Ktore z postawionych przez Ciebie pytan ma na celu usprawnienie projektu ProteGO-Safe? Wskaz je jasno i zaznacz najlepiej naglowkiem aby mozna je bylo latwo wskazac na forum.
Moje pytania dotyczą szczegółów działania czegoś czego jeszcze w ogóle nie ma. Nie może być więc mowy o usprawnianiu. Ja na razie oczekuję ujawnienia szczegółów rozwiązań, które potencjalnie będą mieć wpływ na życie milionów ludzi. Twórcy aplikacji powinni widzieć każde swoje działanie właśnie w tym kontekście. Zadałem precyzyjne techniczne pytania (na tyle precyzyjne na ile pozwala moja wiedza i wyobraźnia) i nie widze powodu, żeby je wartościować bo "nie służą usprawnianiu projektu" . Projekt ma służyć ludziom (chociaż najbardziej chyba rządowi) więc jeśli zadałem te pytania w interesie pewnej grupy ludzi-uzytkowników to wolalbym poczytać odpowiedzi a nie dociekania po co te pytania.

**Comment by SeraMoon** [comment]
> 
> 
> @SeraMoon przecież na pewo wiesz , że na podstawie tak ogólnej spec nie można wytknąć żadnych dziur a jedynie zadawać pytania. A nie zadając pytań trudno zwrócić uwagę szerszej publiczności na możliwe/prawdopodobne czarne scenariusze, które grożą ludziom kiedy aplikacja będzie w masowym użyciu. Jeżeli zadane pytania doczekają się prezycyjnych odpowiedzi to będziemy mogli oszacować w jakims stopniu możliwy "potencjał zamordyzmu" i np dać się odnieść do tego organizacjom , które z zamordyzmem i nadzorem próbują walczyć środkami prawnymi.

Obawiam się, że ten temat poleci po nagłośnienia do zamkniętych, których prawie nikt nie przegląda. Warto byłoby stworzyć stronę / repo o tym projekcie i troszkę spozycjonować i napisać co się dzieje - do mediów. Zamordyzm po przeczytaniu tych speków oraz patrzeniu na ręce Ministerstwa Cyfryzacji (obhandlowania z Pocztą Polską bez podstawy faktycznej naszych danych osobowych - jest już prawie pewny. 

Oczywiście zdanie zmieniam i proszę o szczegóły odpowiedzi w tym: 

### czy usługa Protego-Safe będzie używała Tora do anonimizacji IP użytkowników, jak również czy będzie szyfrowała dane w sposób uniemożliwiający rozszyfrowanie przez Cloudflare lub doczeka się serwera w Polsce niezależnego od rządu.

**Comment by jaworowicz** [comment]
Właśnie tutaj rząd nie da Ci przymusu, ale sklepy będą chciały mieć na powierzchni więcej klientów, a wiec podejrzewam, że obowiązek apki będzie obowiązkowy w wieku sklepach/galeriach czy innych miejscach publicznych. Rząd nie skłamie bo przymusu nie da, ale zrobią to za niego inni.

**Comment by mateuszjablonski** [comment]
@jaworowicz ale zaraz, zaraz, jak to nie ma przymusu?

Czy to nie rząd ustala, że do sklepu może wejść X osób? Czyli bezpośrednio zakazuje kolejnym osobom wchodzić do galerii?
Czy to nie rząd ustala, że do sklepu może wejść 10% osób więcej, jeśli mają one zainstalowaną aplikację? Czyli bezpośrednio zmusza ludzi chcących wejść do galerii do instalacji aplikacji?

**Comment by jaworowicz** [comment]
> @jaworowicz ale zaraz, zaraz, jak to nie ma przymusu?
> 
> Czy to nie rząd ustala, że do sklepu może wejść X osób? Czyli bezpośrednio zakazuje kolejnym osobom wchodzić do galerii?
> Czy to nie rząd ustala, że do sklepu może wejść 10% osób więcej, jeśli mają one zainstalowaną aplikację? Czyli bezpośrednio zmusza ludzi chcących wejść do galerii do instalacji aplikacji?

Mówiąc "przymus" miałem na myśli "możesz iść do sklepu czy jechać autobusem, ale tylko z apką".  ;)

**Comment by SeraMoon** [comment]
@jaworowicz @mateuszjablonski Czy muszę przypomnieć #53 Historię początkowo dobrowolnej aplikacji "Kwarantanna Domowa"? Czy wtedy zmusili do instalacji, czy jednak nie? No w sumie też nie zmusili bo wystarczyło podpisać się pod art. 233 KK, że nie posiada się telefonu z Androidem lub iOS lub że nie jest się abonentem sieci. 

Co więcej nie było istotne, że możesz nie umieć telefonu obsłużyć lub być niewidomym z telefonem na bazie Androida i korzystać z klawiatury fizycznej (takie modele jeszcze są). Lub... też mogły wystąpić inne czynniki uniemożliwiające używanie aplikacji (listą tutaj nie pomogę - niech pozostanie tamta aplikacji i oświadczenia wadliwe).

**Comment by potiuk** [comment]
> Czy przed ta kontrybucja poznales zasady komunikacji w ProteGO Safe? Znajdziesz je [tutaj](https://github.com/ProteGO-Safe/specs/blob/master/CONTRIBUTING.md). W przyszlosci silnie zalecam stosowanie sie do zasad dotyczacych zglaszania **rozwiazan**, **usterek** lub **problemow bezpieczenstwa** gdyz watki nieodpowiednio formatowane sa najczesciej zle interpretowane.

@qlb - Zwrócę uwagę że zasady o których mówisz wprowadziłeś 16 godzin temu a wątek ten powstał 18 godzin temu. Wydaje mi się że wymóg przewidywania przyszłości nie jest warunkiem wypowiadania się na tym forum.

**Comment by miklobit** [comment]
> @miklobit
> Czy przed ta kontrybucja poznales zasady komunikacji w ProteGO Safe? 
@qLb 
Poznałem... i chetnie usłyszę od Ciebie do jakiej kategorii chciałbyś wstawić moje pytania. Bo ja takiej nie widzę. Nie jest to ani propozycja, ani usterka, ani tym bardziej problem bezpieczeństwa.
Jest to prośba o wyjasnienie spraw ktore uważam za ważne a których wyjasnienia nie znalazłem ani w drafcie specyfikacji ani też w dokumentach na których bazujecie (np specyfikacji opentrace / bluetrace). 
Jeżeli te pytania są niewygodne to napisz to wprost zamiast używać jakiś argumentów proceduralnych. Ja swoje intencje wyraziłem jasno. Jeżeli aplikacja powoli dryfuje w stronę naruszania wolności wyboru to bedę stał po stronie tych, którym prawo (póki co) daje mozliwość pozostawania off-the-grid. I szukał rozwiązań , które im w tym pomogą. Możemy te kwestie rozważać albo tutaj, z korzyścią dla wszystkich, albo życie wymusi (oby nie) ich przeniesienie w jakieś bardziej ustronne miejsce. Ale wtedy nie będzie mieli z tego feedbacku.

**Comment by MateuszRomanow** [comment]
@miklobit nie jesteśmy rzecznikami MC i nie ręczymy za MC. 
Z deklaracji podczas współpracy z nami, oraz [publicznych ](https://www.gov.pl/web/cyfryzacja/z-protego-safe-do-sklepu---obalamy-mity) wynika jasna komunikacja, że nie ma być żadnych przymusów. Zachęcanie i propagowanie to co innego. Wspomnę jeszcze, że w żądnej specyfikacji nie ma planu sprawdzania koloru aplikacji. Proponuję zamknąć wątek, i otworzyć, jeżeli pojawią się ponownie wątpliwości.

**Comment by potiuk** [comment]
> Natomiast z deklaracji MC podczas współpracy z nami, oraz [publicznych ](https://www.gov.pl/web/cyfryzacja/z-protego-safe-do-sklepu---obalamy-mity)oświadczeń wynika jasna komunikacja, że nie ma być żadnych przymusów. Zachęcanie i propagowanie to co innego. 

@MateuszRomanow - co innego zachęcanie i propagowanie, a co innego dawanie przywilejów i rabatów. Nie zapomnij że brak przywileju jest równoznaczny z dyskryminacją w tym przypadku, zwłaszcza że nie jest niczym uzasadnione.

**Comment by miklobit** [comment]
@MateuszRomanow - antycypowany przymus używania nie był jedynym powodem do w/w pytań. Dopóki bieżąca specyfikacja ,  kod tracingu BT i pomysł wymiany QR kodów nie zostaną wyrzucone i zastąpiąne przez G+A to pytania pozostają aktualne.

**Comment by Tarvald** [comment]
@miklobit 
Hej,
Czy po opublikowaniu #147 ten konkretny temat budzi jeszcze jakieś wątpliwości?
