### ISSUE TITLE
Status prawny użytkownika aplikacji, inne związane z tym niuanse oraz przetwarzanie imienia użytkownika

### ISSUE THREAD

**Issue by matsobdev** [ProteGO-Safe/specs#125]
Zgodnie z regulaminem użytkownikiem może być tylko osoba posiadająca pełną zdolność do czynności prawnych, zatem pełnoletnia (18+ z wyjątkami). Nikt tego nie weryfikuje, ba w aplikacji można być nawet dwulatkiem wypalającym 40 papierosów dziennie. Kategoria wiekowa przypisana aplikacji w Google Play też ma się nijak do tego.

Jest też kwestia imienia. Administrator danych może je przetwarzać w połączeniu z innymi danymi uzyskanymi z aplikacji. Czy aplikacja koniecznie musi się zwracać po imieniu do użytkownika? Domyślam się, że może być to psychologia UX...

Jest jeszcze smaczek, może tylko moje chore poczucie humoru pobudził. Można być w nieciekawym stanie zdrowia, zaznaczać groźne choroby w formularzu i na koniec... "GRATULACJE" - no jak Monty Python ;)

**Comment by SeraMoon** [comment]
> Jest też kwestia imienia. Administrator danych może je przetwarzać w połączeniu z innymi danymi uzyskanymi z aplikacji. Czy aplikacja koniecznie musi się zwracać po imieniu do użytkownika? Domyślam się, że może być to psychologia UX...

Wskażę tylko, że istnieją imiona, które mogą bardzo łatwo deanonimizować użytkownika (rzadsze od najrzadszych polskich nazwisk - głównie zagraniczne), **jednak aplikacja całe szczęście nie pyta o twoje imię ale jakieś imię. 

> 
> Jest jeszcze smaczek, może tylko moje chore poczucie humoru pobudził. Można być w nieciekawym stanie zdrowia, zaznaczać groźne choroby w formularzu i na koniec... "GRATULACJE" - no jak Monty Python ;)

@matsobdev
BTW dopisz "Steps to Reproduce" i całość z standardowej formatki zgłoszenia błędu, jak błąd spowodować: uruchomić aplikację, aby nam nie zarzucili zaraz CoV VNCF lub jak to tam było. qL.b groził, że będzie zamykać wątki, które nie spełniają powyższego. Tekst możesz pozostawić po polsku - języka nie wyspecyfikowano.

**Comment by miklobit** [comment]
> Jak ma się ten regulamin do licencji GPL oraz 3xFREEDOM?

Chyba ma się tak, że będzie musiał być zmieniony bo aktualnie wolno chodzić luzem od wieku lat 13. A 13 latek przecież też powinien mieć prawo wejść do sklepu po okazaniu kodu.

**Comment by qLb** [comment]
Czy jest z waszej strony jakas propozycja w zwiazku ze zgloszonymi watpliwosciami? @matsobdev @miklobit @SeraMoon

**Comment by SeraMoon** [comment]
Z mojej strony - Jak powinno być::
- usunięcie imienia - można pytać o płeć i wyświetlać Drogi użytkowniku / sroga użytkowniczko. Można też się nie zwracać - GIMP do mnie się nie zwraca :-)

Usunąć z regulaminu w myśl zasady FOSS Fredeom 0-2 punkty zakazujące komukolwiek jej używanie. Nawet gdy dziecko używa aplikacji - ono też może mieć "nieodpowiedni" kontakt i powinno pokazać rodzicom, że ma czerwone. **Przypomnę że najmniej grzejników (>37.5) i kaszlących jest wśród dzieci 2-10 lat a te też bywają nosicielami.**

Usunięcie tego napisu "Gratulacje". Na rzecz "jesteś w grupie niskiego ryzyka". Chyba to intuicyjne, nie? 

@matsobdev dodaj coś jeżeli nie wszystko wyłapałam. 

BTW. Aplikacja już jest spalona na gazeta.pl - już opisano jakiej klasy prywatność oferuje w obecnej dostępnej na iOS wersji... Aplikacja ma więc już przesmarkane.

**Comment by miklobit** [comment]
> Czy jest z waszej strony jakas propozycja w zwiazku ze zgloszonymi watpliwosciami? @matsobdev @miklobit @SeraMoon

Co do wymaganego wieku w regulaminie to na pewno uzgodnić regulamin z wymaganiami RODO i faktycznym interesem administratora danych. Jeżeli w tej chwili (wg mojej wiedzy) samodzielna zgoda na przetwarzanie danych może być udzielona przez osobe od  lat 16-tu to albo ten wiek obniżyć  albo przyjąć założenie (i tez to wyraźnie napisać), że osoba udzielająca zgody a użytownik to nie musi być jedno i to samo. Bo jeżeli państwo zachęca do używania aplkacji (a być może zmusi) a 13 latek może samodzielnie poruszać się bez opieki to musi być spójność między prawem a stanem faktycznym. BTW jak to zostało rozwiązane w "kwarantannie domowej" ? Jeśli z rodzicami przechodził kwarantannę nastolatek to musiał mieć osobny telefon czy rodzice wysyłali jego zdjęcia oprócz swoich ?". 
Jeżeli ta aplikacja jest pisana na zlecenie ministerstwa to czy tego regulaminu nie powinni pisać prawnicy z ministerstwa ?  My tu możemy sobie wskazywać nieścisłości lub sugestie ale ktoś potem na końcu się powinien podpisać swoim nazwiskiem. Skoro jest to aplikacja rządowa dla millionów obywateli....

**Comment by qLb** [comment]
gotcha! Uderze w stol, zobaczymy, ktore nozyce sie odezwa. 
Stay tuned!

**Comment by SeraMoon** [comment]
> 
> 
> zobaczymy, ktore nozyce sie odezwa.

Czuję, że żadne, w sytuacji kiedy Ministerstwo Cyfryzacji założyło kaganiec i nie odpowiada **Panoptykonowi ani "łącznikowi z MC**, który złożył tutaj dymisję.

**Comment by qLb** [comment]
@SeraMoon on it!

**Comment by matsobdev** [comment]
@qLb Ja bym wprost zaproponował dziennik zdrowia offline, bez przesyłania danych

**Comment by SeraMoon** [comment]
> @qLb Ja bym wprost zaproponował dziennik zdrowia offline, bez przesyłania danych i konieczności administrowania nimi.

To obecnie jest on wysyłany na serwer? o.O 😱

**Comment by Dr-Kownacki** [comment]
@matsobdev - "dziennik zdrowia off-line" to chyba jest najlepszy pomysł, bo danymi zdrowotnymi/sensytywnymi to nie "każdy" może sobie administrować raczej, są odpowiednie regulacje w tym zakresie (szpitale i ich pracownicy etc.) i rzeczywiście jak piszesz chyba lepiej zostawić to każdemu do samodzielnego prowadzenia (off-line) i w przypadku "upload'u" ew. jakiegoś tych danych (teoria tylko - podkreślam) - to byłby prostu jakiś "wydruk" (ale nie login/wgranie do bazy), który użytkownik sam mógłby wykonać np. jakiś "export do PDF" i to już użytkownika sprawa czy/jak to przekaże np.podczas wywiadu lekarskiego. Może po prostu przeczytać z aplikacji. 
W ten sposób zapobiega się ryzyku że (nawet za zgodą użytkownika) takie dane trafią do kogoś kto "nie ma prawa ich mieć formalnie". W dodatku są jakieś nadrzędne przepisy UE że taki serwer musi być fizycznie na terenie UE co rodzi dodatkowe okoliczności/potencjalny kłopot chyba...

**Comment by qLb** [comment]
Niestety nie planujemy przesylania danych dotyczacych dziennika zdrowia. Mimo swej anonimowosci sa one niewatpliwa wlasnoscia uzytkownika i szanujemy jego prawa. 
Powtarzam, aplikacja ProteGO Safe nie posiada funkcji upload'u danych z "dziennika zdrowia".

**Comment by Dr-Kownacki** [comment]
@qLb , jasne mi chodziło o moment jak ktoś już jest "u lekarza" i tą aplikacją mógłby się potencjalnie wspomóc podczas zbierania wywiadu. 

Jest jednak pewien "punkt styku" - czy na serwerze jest gdziekolwiek zaznaczone KTO uploaduje klucze - "zezwala na to technicznie" (piszę tu o docelowym rozwiązaniu G+A) ? Chodzi mi o sam proces po "skatalizowaniu" wysyłki tych danych jeśli użytkownik się zgodzi. Jak rozumiem przekazanie danych wymaga "odblokowania" tej funkcji w aplikacji. No a jeżeli ktoś jest "odblokowywany" i może to zrobić, to po prostu jest zarażony a to już jest formalnie dana medyczna...

Pytanie gdzie/czy jest "styk" kwestii ogólnych-informatycznych a gdzie "zaczyna się medycyna" jak to ma być docelowo rozwiązane ? Właścicielem serwera i administratorem danych będzie chyba zatem jak rozumiem  "w całości" SANEPID ?

**Comment by SeraMoon** [comment]
> triage poprzez api skupiajace zalecenia WHO.
Warto zaznaczyc, ze api do oceny triage z zaleceniami zgodnymi z WHO i serwery realizujace usluge "Opentrace" sa kompletnie odrebnymi systemami (na poziomie sprzetu, os jak i oprogramowania).

A czy ta część nie może odbywać się lokalnie w kodzie Protego-safe? W mojej opinii da się napisać kod na licencji GPL-3, który wykona tą ocenę. Nie jest istotne czy wysyłamy część dziennika czy całość. Podobnie jak w danych biometrycznych nie ma znaczenia czy wyślemy cały czyjś odcisk palca czy jego "zahaszowany skrót".

**Comment by qLb** [comment]
@SeraMoon Ciezko wtedy zapewnic zgodnosc z wytycznymi WHO, poza tym nie my sie tym zajmujemy tylko zewnetrzny podmiot z wiekszym doswiadczeniem i lepszymi, sprawdzonymi metodami.

**Comment by SeraMoon** [comment]
> @SeraMoon Ciezko wtedy zapewnic zgodnosc z wytycznymi WHO, poza tym nie my sie tym zajmujemy tylko zewnetrzny podmiot z wiekszym doswiadczeniem i lepszymi, sprawdzonymi metodami.

Metody powinny być open source i wbudowane w aplikację  i powinny być po prostu pobierane na bieżąco jako aktualizacja, gdy jest to potrzebne. Tyle w temacie. 

Niestety ale powyższy argument ma długość zero, czyli null. Nie przekonuje mnie więc powyższe.

**Comment by qLb** [comment]
@SeraMoon 
Czy zdajesz sobie sprawe ile tra proces legislacyjny zwiazany z ustalaniem otwartych standardow w dziedzinie medycyny? Przepraszam, ze czesc pracy zostala juz przez kogos wykonana a my na tym skorzystalismy. Wszystko pozostaje w pamieci twojego urzadzenia czyli dzieje sie lokalnie.

**Comment by SeraMoon** [comment]
> @SeraMoon
Czy zdajesz sobie sprawe ile trwa proces legislacyjny zwiazany z ustalaniem otwartych standardow w dziedzinie medycyny? Przepraszam, ze czesc pracy zostala juz przez kogos wykonana a my na tym skorzystalismy. Wszystko pozostaje w pamieci twojego urzadzenia czyli dzieje sie lokalnie.

Chwila, medycyny? Mówimy o ocenie ryzyka a nie stawianiu diagnozy. 

### Rozmawiamy o prywatności?

Jeżeli tak, na pewno da się ten algorytm skopiować. Widzę, że całość też stoi za Cloudflare lub czymś podobnym

To że korzystacie z czegoś jest podobnie argumentem nie powiem z czego, w sytuacji gdy aplikacja ma spełniać 7 filarów prywatności (odsyłam na stronę panoptykon.org). Skoro skorzystano - pora to przenieść na lokalny kod. 

A jak pozostaje w pamięci mojego urządzenia pokazałam w temacie #127. Na konkretnym przykładzie.

**Comment by qLb** [comment]
Pozwolmy panoptykonowi samemu ocenic sytuacje. Mysle, ze nas do tego nie potrzebuja. A zrobia to wierz mi i to w najblizszych dniach.

#127 
Odpisalem ci w tym temacie. Twoje urzadzenie to Twoja sprawa a F12 i informacje z cache'u o niczym nie mowia. Przedstaw dowody jakie sa wrazliwe dane, ktore naruszylismy, w jaki sposob to zrobilismy i skonczmy raz na zawsze produkowac fakenews'y.

**Comment by SeraMoon** [comment]
> 
> 
> Pozwolmy panoptykonowi samemu ocenic sytuacje. Mysle, ze nas do tego nie potrzebuja. A zrobia to wierz mi i to w najblizszych dniach.
> 
> #127
> Odpisalem ci w tym temacie. Twoje urzadzenie to Twoja sprawa a F12 i informacje z cache'u o niczym nie mowia. Przedstaw dowody jakie sa wrazliwe dane, ktore naruszylismy, w jaki sposob to zrobilismy i skonczmy raz na zawsze produkowac fakenews'y.
> 
> PS. No chyba, ze nie potrafisz bo sama nie rozumiesz co piszesz.

Czy są to fakenewsy, już wypowiedzieli się inni. Przykro mi, że zamykasz ludziom usta, mimo, że mają rację. Nie mnie pierwszej. Wnoszę o zmianę osoby, która będzie "zamykała" issues.

**Comment by qLb** [comment]
Zajmuje sie ocena ryzyka systemow informatycznych od dawna i wiem, jak niektorzy tu obecni, ze nie bierze sie na poczatek State-level adversary jako wroga w projektach rzadowych bo nie da sie wtedy zrealizowac zadnego funkcjonalnego systemu informatycznego. Panstwu sie ufa - po to sie je wybiera (w demokratycznych wyborach zachowujacych poufnosc wyboru 🤭).

**Comment by potiuk** [comment]
> Zajmuje sie ocena ryzyka systemow informatycznych od dawna i wiem, jak niektorzy tu obecni, ze nie bierze sie na poczatek State-level adversary jako wroga w projektach rzadowych bo nie da sie wtedy zrealizowac zadnego funkcjonalnego systemu informatycznego. Panstwu sie ufa - po to sie je wybiera (w demokratycznych wyborach zachowujacych poufnosc wyboru ).

Bardzo bym prosił żebyś trzymał się nie przedstawiał swoich opinii jako "faktów" i "prawd objawionych" bez powoływania się na źródła.

Zarzucałeś mi kiedyś chwyty retoryczne a tu masz - teraz ty to stosujesz. Nie podajesz źródeł i próbujesz przekonać innych że "tak jest", "państwi się ufa", "po to się je wybiera". Twoje "nie bierze się" kiedy nie podajesz źródeł jest tylko opinią a brzmi jakby było prawdą objawioną. Gdybyś napisał "Moim zdaniem" na przykład, to było zupełnie co innego.

Ja akurat jestem zwolennikiem innego podejścia - państwo się wybiera żeby nam - obywatelom - służyło. Nie żeby mu ufac. [Monteskiusz](https://pl.wikipedia.org/wiki/Podzia%C5%82_w%C5%82adz#Koncepcja_Monteskiusza) właśnie po to wprowadził trójpodział władzy, żeby "jednej" władzy nie trzeba było ufać - bo były organy kontrolujące. Niestety trójpoział władzy w naszym kraju jest obecnie mocno zachwiany więc tym bardziej należy władzy patrzeć na ręce.

Moim skromnym zdaniem w tym projekcie osobom które stoją za projektem (czyli MC) nie należy ufać. Choćby dlatego że już kilka razy MC nas oszukało i nie dotrzymało obietnic. Znam co najmniej dwa przypadki:

1) Zapowiadana dyskryminacja ludzi bez aplikacji mimo że zapowiadano że nic takiego nie będzie. Źródlo https://niebezpiecznik.pl/post/albo-zainstalujesz-rzadowa-aplikacje-protego-safe-albo-nie-wejdziesz-do-sklepu/). 

2) Późniejsze dementi w którym mówi że nic takiego nie było chociaż historia internetu pokazuje inaczej (to samo źródło co wyżej)

Oprócz tego dopóki wypowiadacie się Wy - a nie osoba decyzyjna z MC to niestety nie wierzę w to co mówicie. Najpierws mówicie że "coś będzie" a potem mówicie że jesteście tylko łącznikami i nie odpowiadacie za to co MC robi. Przez to rozdwojenie, ja nie mam absultnie zaufania że tak się stanie jak mówicie. Po prostu nie jesteście wiarygodni co do kierunku rozwoju tego projektu - i sami o tym mówicie że nie odpowiadacie za decyzje.

Żeby nie być gołosłownym - na przykład w kwestii właśnie Galerii Handlowych @MateuszRomanow również był wprowadzony w błąd.  Ten komentarz: https://github.com/ProteGO-Safe/specs/issues/119#issuecomment-621450307 oraz https://github.com/ProteGO-Safe/specs/issues/119#issuecomment-621398875 wynika że nic nie wiedział o tym co tak naprawdę szykuje nam MC i że szykują nam dyskryminację. 

Dlatego dopóki protokół G+A nie będzie zaimplementowany (zwłaszcza że chcecie implementować QR-kody, które w praktyce są nie do zaimplementowania w G+A) nie wierzę że tak się stanie.
Podobnie - dopóki tego nie zobaczę - nie wierzę że zaimplementujecie to w sposób prywatny. Nie dlatego że myślę że kłamiecie. Po prostu wiem że nie macie mocy dezyzyjnych (sami to potwierdziliście).

**Comment by Tarvald** [comment]
Czy temat jest nadal aktualny? Czy moge go zamknąć z powodu długiej nieaktywności?
Zrobie to jeżeli nikt nie wyrazi wyraźnego sprzeciwu w najbliższym czasie ;)
