### ISSUE TITLE
Umowa o wykonanie aplikacji ProteGo Safe

### ISSUE THREAD

**Issue by tomekziel** [ProteGO-Safe/specs#128]
Proszę o ujawnienie treści umowy o wykonanie aplikacji ProteGo Safe. Prośbę uzasadniam troską o przejrzystość projektu, gdyż - jak widzieliśmy w czwartek 29.04.2020 - nawet twórcy projektu kontaktujący się bezpośrednio z Ministerstwem Cyfryzacji są zaskakiwani takimi wrzutkami, jak wpuszczanie 10% więcej klientów do sklepu, o ile ci wpuszczani dodatkowo mają zainstalowaną aplikację ProteGo Safe.

Znajomość umowy pozwoli opinii publicznej poznać zakres odpowiedzialności wykonawców aplikacji, dzięki czemu nie będą oni wzywani do wyjaśnień decyzji i działań, które leżą poza zakresem ich kompetencji.

Odpowiedni wniosek o informację publiczną został już przeze mnie wysłany do MC, ale ten proces trwa tygodnie. Mi zależy na jak najszybszym poznaniu okoliczności, w jakich rozwijany jest projekt.

Tomasz Zieliński
www.informatykzakladowy.pl

**Comment by potiuk** [comment]
Jestem absolutnie za!

**Comment by Tarvald** [comment]
Ze względu na zmianę zakresu projektu i decyzję o skupieniu się na implementacji G+A umowa będzie miała aneks porządkujący nowy zakres. 
Wtedy wrócimy do publikacji :)

**Comment by tomekziel** [comment]
Proszę o publikację istniejącej umowy teraz a aneksów - gdy zostaną podpisane.

**Comment by limakzi** [comment]
@Tarvald , jako @sysdogs, popieramy wniosek Pana @tomekziel. Prosimy o publikację umowy bądź przekazanie umowy Panu @tomekziel . Podpisanie aneksu nie powinno być blokerem do publikacji aktualnej umowy. 

Kamil Zabielski
sysdogs.com

**Comment by kolmir** [comment]
Też poproszę o umowe oraz o wstepną specyfikację wymagań + opis business case.

Będzie można go zestawić w ramach _reality-check_ z merytoryczną check-listą a propos prywatności i wykonalności/skuteczności od jednego z NGOs https://www.accessnow.org/privacy-and-public-health-the-dos-and-donts-for-covid-19-contact-tracing-apps/

**Comment by jasisz** [comment]
Może też wystąpić o informacje o tej "identyfikowanej kampanii mającej na celu dyskredytację przygotowanej przez @MC_GOV_PL aplikacji ProteGO Safe" 😄 
https://twitter.com/StZaryn/status/1257681533974073345

**Comment by tomekziel** [comment]
Wolałbym umowę. Nadal nie dostałem.

**Comment by archasek** [comment]
@tomekziel dostałeś już umowę? Kiedy mija termin?

**Comment by tomekziel** [comment]
> dostałeś już umowę?

Nie

> Kiedy mija termin?

13 maja

**Comment by tomekziel** [comment]
Wiecie co? Nie wierzę w dobre intencje nikogo zaangażowanego w ten projekt.

![image](https://user-images.githubusercontent.com/1764747/83420776-639af180-a427-11ea-8799-ca062d98e020.png)

**Comment by tomekziel** [comment]
Jednocześnie informuję, że jako redaktor naczelny czasopisma "Informatyk Zakładowy" będę miał obowiązek zachowania w tajemnicy tożsamości osoby, która przyśle mi kopię umowy o produkcję ProteGO Safe i zastrzeże nieujawnianie informacji o swojej tożsamości.

Dane kontaktowe tutaj: https://informatykzakladowy.pl/kontakt/

**Comment by potiuk** [comment]
Pdoba mi się Twój tok rozumowania @tomekziel  :). Ciesze się że jesteś dziennikarzem.

**Comment by kwiszowaty** [comment]
@tomekziel tak sobie myślę, że tych dokumentów może po prostu jeszcze nie ma bo projekt nie skończony i nikt nie wie jaką kwotę trzeba będzie wstawić tam na końcu by się wszystkim zgadzało ;-)

Miał być żart, a teraz tak naprawdę się nad tym zastanawiam...

**Comment by jasisz** [comment]
Na spotkaniu Minister Zagórski mówił, że umowa będzie udostępniona w tym tygodniu, najpewniej w środę. "Społeczność GitHub" trzyma za słowo, a zegarek tyka ;)

**Comment by archasek** [comment]
> > Kiedy mija termin?
> 
> 13 maja

Jaka jest przewidziana prawnie sankcja za takie wybryki? ;-)

**Comment by Tarvald** [comment]
@jasisz 
> umowa będzie udostępniona w tym tygodniu, najpewniej w środę. "Społeczność GitHub" trzyma za słowo

Dostałem własnie informacje że umowa poszła do @tomekziel

**Comment by walaf71110** [comment]
>ps. temat troche zakopany, interweniowałbym już dużo wcześniej
_Interweniowałbym_? _Interwencja_ w ogóle nie powinna być potrzebna...

**Comment by Tarvald** [comment]
@walaf71110 
Miałem na myśli to że @jasisz napisał posta dużo dużo wcześniej a on mi umknął pod natłokiem innych. Tyle ;)

**Comment by tomekziel** [comment]
> Dostałem własnie informacje że umowa poszła do @tomekziel

Haha. Nope.

> ps. temat troche zakopany, interweniowałbym już dużo wcześniej

Dzięki, stary, ale wiesz, w poniedziałek 8-go czerwca przypomniałem o temacie ministrowi Zagórskiemu, i on obiecał, że umowę dostanę w środę lub piątek i gdyby ktoś dał sobie za tę obietnicę rękę uciąć, to by teraz nie miał ręki.

https://www.youtube.com/watch?v=PEHW2Jbcpo8

**Comment by jasisz** [comment]
@tomekziel Może listem wysłali! Miałem już taką sytuację, że na wniosek mailowy o udostępnienie informacji publicznej dostałem odpowiedź listem, chociaż danych adresowych nie podawałem ;)

**Comment by SeraMoon** [comment]
> chociaż danych adresowych nie podawałem

Jak to ma się do RODO? 😕 
Przecież masz prawo przebywać za granicą i skoro podajesz adres mailowy jako kontaktowy (przy wniosku o informację publiczną nie ma obowiązku podawania miejsca zamieszkania) - to na ten właśnie adres powinni odpowiedzieć, bo taki wskazujesz... 

Moim zdaniem taką odpowiedź można potraktować jako brak odpowiedzi z pełnymi tego skutkami - bo nie ma obowiązku aktualizowania adresu pobytu, by zapytać o informację publiczną. 😾

@jasisz, jaką drogą ustali, że to Ty pytasz a nie inna osoba o tym samym imieniu i nazwisku? Po IP?

**Comment by SeraMoon** [comment]
> chociaż danych adresowych nie podawałem

Jak to ma się do RODO? 😕 
Przecież masz prawo przebywać za granicą i skoro podajesz adres mailowy jako kontaktowy (przy wniosku o informację publiczną nie ma obowiązku podawania miejsca zamieszkania) - to na ten właśnie adres powinni odpowiedzieć, bo taki wskazujesz... 

Moim zdaniem taką odpowiedź można potraktować jako brak odpowiedzi z pełnymi tego skutkami - bo nie ma obowiązku aktualizowania adresu pobytu, by zapytać o informację publiczną. 😾

@jasisz, jaką drogą ustali, że to Ty pytasz a nie inna osoba o tym samym imieniu i nazwisku? Po IP? 

>  i gdyby ktoś dał sobie za tę obietnicę rękę uciąć, to by teraz nie miał ręki.

Może już dali sobie uciąć rękę za tą obietnicę i teraz nie mają czym napisać Ci odpowiedzi 😹 

> Na spotkaniu Minister Zagórski mówił, że umowa będzie udostępniona w tym tygodniu, najpewniej w środę. "Społeczność GitHub" trzyma za słowo, a zegarek tyka ;)

Jak tyka, skoro jest zbity? 
![zbity zegar](https://oko.press/app/themes/oko/assets/images/fc/zbity_zegar.svg)
Czy na prawdę Ministerstwu tak trudno zrobić skan i wysłać mailem lub umieścić na GitHubie z pomocą łącznika? 

**Proszę o odpowiedź @MateuszRomanow (jako łącznik z Ministerstwem), dlaczego tak długo oczekujemy na tak proste działanie, które można wykonać w ciągu 2 dni (nie będę się sprzeczała, że starczy 1 godzina)?**

**Comment by tomekziel** [comment]
Dla informacji - dostałem pliki. Jeszcze nie czytałem.

**Comment by Tarvald** [comment]
@tomekziel 
Czy temat dostarczenia umowy uważasz za zamknięty?
Jeżeli tak, to prosiłbym o zamknięcie tematu w celu uporządkowania GH. :)

Dzięki

**Comment by jasisz** [comment]
@tomekziel Czy planujesz udostępnienie innym tej umowy? Być może w formie posta na Twoim blogu? pytam, bo jeżeli nie, to sam też wyślę wniosek.

**Comment by tomekziel** [comment]
Kwota którą podawano wcześniej (2 miliony zł z kawałkiem) jest prawdziwa. Umowy wrzucę w kolejną blogonotkę poświęconą ProteGO Safe i Contact Tracingowi, ale najpierw planuję zebrać trochę innych materiałów - na przykład dać protokołowi G+A okrzepnąć by zaczął robić robotę. Na razie jakoś malusio tych opublikowanych Temporary Keys (patrz https://exp.safesafe.app/).

**Comment by SeraMoon** [comment]
@tomekziel a dlaczego nie udostępnisz treści tej umowy tutaj jawnie dla społeczności Github? Skoro nie udostępniasz, to po co w ogóle był ten wątek? 

Ze wsojej strony @Tarvald proszę o re-open tego wątku, bowiem chciałabym znać zapisy umowy nie tylko odnośnie ceny, ale pozostałych warunków.

**Comment by SeraMoon** [comment]
@Tarvald minęły 2 dni od mojej prośby o otwarcie wątku bez reakcji. Ponieważ również chcę zobaczyć umowę o wykonanie ProteGO-Safe w całości. Czy w związku z brakiem otwarcia wątku powinnam "zdublować byty"?

Jutro otwieram nowy wątek w przypadku braku reakcji - wyszczególniając, że chcę zobaczyć całą treść umowy i chcę aby pojawiła się w repozytorium wraz z [audytami prywatności](https://github.com/ProteGO-Safe/specs/issues/209).

**Comment by Tarvald** [comment]
Umowa nie będzie zwarta w repozytorium bo to nie miejsce na to, natomiast można je otrzymać oficjalną drogą od ministerstwa cyfryzacji.
Ponad 100 stronicowa umowa jest w opracowaniu przez informatykzakladowy.pl
