### ISSUE TITLE
Zleceniodawca (MC) kłamie - zastanówcie się dla kogo kodujecie

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#133]
**Describe the bug**
Ministerstwo Cyfryzacji (zleceniodawca dla tego projektu) napisał, że Niebezpiecznik kłamie jakoby osoby z aplikacją ProteGO-Safe miały mieć większe przywileje. 

Dowód: 
https://www.gov.pl/web/cyfryzacja/z-protego-safe-do-sklepu---obalamy-mity
https://niebezpiecznik.pl/post/albo-zainstalujesz-rzadowa-aplikacje-protego-safe-albo-nie-wejdziesz-do-sklepu/

Tymczasem na archive.today zachowana została zawartośc strony wraz ze znacznikiem czasowym, która udowadnia, że taka treść była dostępna online (każdy samodzielnie może zażądać zrobienia screenów do celów dowodowych za darmo, nie da się treści zmanipulować): 

Dowód: 
https://web.archive.org/web/20200430064824/https://www.gov.pl/web/rozwoj/centra-handlowe
https://archive.fo/V0xrC

Jako obywatelka tego kraju (zwanego jeszcze Polską, nie Chinami i nie Koreą Północną) apeluję do programistów zaangażowanych w rozwój ProteGO-Safe o zakończenie prac nad tym projektem. Błagam, nie szykujcie nam gehenny i narzędzia do inwigilacji oraz narzędzia do dyskryminowania ludzi, którzy nie będą chcieli dać się inwigilować. Ten projekt ma zaszywane funkcje inwigilacyjne podczas pisania kodu właściwego, choćby przez wskazaną korelację żądań do api z IP użytkownika, a MC posiada MOŻLIWOŚĆ żadania danych osobowych związanych z IP. 

### Błagam zamknijcie ten projekt, chyba nie chcecie przykładać ręki do inwigilowania nas?

Takiemu projektowi należy pokazać o taką SOLIDARNOŚĆ:
![Solidarność](https://bi.im-g.pl/im/05/1b/15/z22133253V,Logo--3xNIE-.jpg)

**To Reproduce**
Obejrzenie wskazanych stron. 

**Expected behavior**
Projekt zamknięty ze względu na fakt, że jest to narzędzie rozwijane dla instytucji o złych zamiarach, która okłamuje obywateli w sposób, który nie wytrzymał próby czasu. Kłamstwo wprost w oczy!

**Screenshots**
https://www.gov.pl/web/cyfryzacja/z-protego-safe-do-sklepu---obalamy-mity
https://web.archive.org/web/20200430064824/https://www.gov.pl/web/rozwoj/centra-handlowe
https://archive.fo/V0xrC

**Desktop (please complete the following information):**
Skompromitowany

**Smartphone (please complete the following information):**
Skompromitowany

**Additional context**
Używajcie archive.is do kolekcjonowania dowodów na Ministerstwa i Rząd - archive.is nie usuwa żądanych treści, archive.org potrafi je usunąć na żadanie. 

Wspomnę tylko, że to, co powyżej zrobiono, okłamując ludzi, że nie wprowadzono takiego zapisu (**który wróci w mocniejszym wydźwięku**) to jest double kill:
- kill dla projektu ProteGO-Safe opłacanego przez Ministerstwo Cyfryzacji
- kill dla zaufania dla Ministerstwa i Rządu jako administratora danych  i wydawcy aplikacji. 

Nie wspomnę już o innych kłamstwach, które tu i ówdzie przeczytałam z zapewnieniami, że aplikacja gwarantuje 100% prywatności.

**Comment by KonoromiHimaries** [comment]
@SeraMoon  https://github.com/VerifiedJoseph/Save-to-the-Wayback-Machine#readme

**Comment by Tarvald** [comment]
Ze wzgledu na bezpoosrednie oskarzenie instytucji panstwowej - to jest forum opinio-tworcze i nie mozemy pozwalac na manifesty w takim stylu.

CoC excerpt:
Przykładowe zachowania, które są nieakceptowalne:

Używanie języka lub obrazów o podtekście seksualnym,

Ataki osobiste,

Trollowanie, obraźliwe bądź urągające komentarze,

Nękanie, zarówno na forum publicznym, jak i prywatnie,

Publikowanie danych osobistych innych osób — takich jak adres fizyczny, czy elektroniczny — bez ich wyraźnej zgody,

Inne zachowania nieetyczne lub nieprofesjonalne.

**Comment by sub-zero-pl** [comment]
>Inne zachowania nieetyczne lub nieprofesjonalne

Dobrze zrozumiałem, obwiniasz o to twórców protego sfe? W sumie, chyba trudno się z Tobą nie zgodzić w tej kwestii. Miłego dnia :)
