### ISSUE TITLE
[Prywatność] Aplikacja blokuje urządzenia rootowane

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#135]
**Describe the bug**
Błąd zgłaszam za użytkownikiem Niebezpiecznika, który żali się, że aplikacja odmawia uruchomienia na rootowanym smartfonie. 

Poniżej cytat: 

> “Użytkownicy ProteGO Safe są anonimowi. Do tego, aby ją uruchomić nie jest wymagane jakiekolwiek uwierzytelnienie, np. podanie numeru telefonu”.
> 
> Tymczasem w Google Play jeden z użytkowników skarży się, że aplikacja nie działa i wyświetla komunikat “Nie Można Zweryfikować Urządzenia”.
> 
> MC odpowiada: “Dziękujemy za komentarz. Ze względów bezpieczeństwa blokujemy działanie niezweryfikowanych urządzeń, np.: rootowanych”.

Takie działanie nie ma nic wspólnego z dbaniem o prywatnośc ani z równością obywateli - tak OBYWATELI, bo aplikacja jest kierowana przez rząd do obywateli. 

**To Reproduce**
Uruchomienie aplikacji na telefonie z podmienionym systemem operacyjnym. 

**Expected behavior**
Aplikacja powinna działać tak samo jak na Google'owej wersji Androida. 

**Screenshots**
https://niebezpiecznik.pl/post/albo-zainstalujesz-rzadowa-aplikacje-protego-safe-albo-nie-wejdziesz-do-sklepu/#comment-738568

**Desktop (please complete the following information):**
Nie dotyczy

**Smartphone (please complete the following information):**
Rootowany z Androidem, np. AOSP, w tym jego pochodnymi. 

**Additional context**
The Orwell Coronavirus COVID-1984.

**Comment by miklobit** [comment]
W komentarzach do ocen w sklepie play (gdzie mnóstwo ludzi jest wkur* na blokowanie zarówno roota jak i VPNów ) już się wycofali rakiem z blokowania  roota: 
![Screenshot(588)](https://user-images.githubusercontent.com/1035161/80893598-22061200-8cd4-11ea-89b8-861eb3a586aa.png)

**Comment by SeraMoon** [comment]
@miklobit dzięki za info. To co mogę stwierdzić - blokowany jest czasami Tor na safesafe.app i nie da się wtedy wypełnić ankiety. Czyli część o VPN-ach może nadal być prawdą, dla częśći VPN-ów.

**Comment by potiuk** [comment]
@qlb - czy mógłbym prosić o wyjaśnienie, dlaczego pewne issues są zamykane ? Przydało by się żeby jednak podać powody. Wcześniej pisaliście że będziecie zamykać issue które nie spełniają wymogów a nagle zamykacie issue z niewiadomych powodów.

**Comment by Tarvald** [comment]
Hej,
Aplikacja już nie blokuje zrootowanych urządzeń.
Własnie sprawdziłem to na dystrybucji Lineage OS 16.

Pozdrawiam i dziękujemy za zaangażowanie :)
