### ISSUE TITLE
Issue zamykane bez podania powodów

### ISSUE THREAD

**Issue by potiuk** [ProteGO-Safe/specs#136]
**Describe the bug**
Ostatnio kilka issue zostały zamknięte bez podania powodów (lub z powodów niezgodnych z faktami).

W mojej opini zamykanie issue bez podania powodów jest działaniem, które utrudnia pomoc w projekcie - nie wiadomo dlaczego dane issue są zamykane, więc nie wiadomo czy w ogóle warto zgłaszać problemy i propozycje. 

Nawet jeśli issue zgłaszane są w pełni zgodne z zasadami opisanymi w 
https://github.com/ProteGO-Safe/specs/blob/master/CONTRIBUTING.md . W znaczący sposób utrudnia to zgłaszanie wartościowych uwag, bo nie wiadomo które z uwag autorzy aplikacji uznają za wartościowe i jakie mają kryteria.

Poniżej przedstawiam listę tych issue które zostały zamknięte wraz z ich tytułami. Dopóki jasno nie będzie opisane dlaczego zostały zamknięte, postaram się tą listę utrzymywać w miarę aktualną (uwzględniając również przyszłe issue):

**To Reproduce**
Zajrzenie do poniższych issue:
* #135  - [Prywatność] Aplikacja blokuje urządzenia rootowane
* #133  - Zleceniodawca (MC) kłamie - zastanówcie się dla kogo kodujecie
* #132  - Implementacja protokołu Google + Apple zamiast własnego rozwiązania BT i QR Code
* #116  - Naruszenie prywatności - Łączenie adresu IP osób zdrowych z ich TempID w obecnej implementacji (OpenTrace) 
* #110 - Możliwe szpiegowanie przez rząd

**Expected behavior**

Każde z issue powinno mieć wyjaśnienie, dlaczego zostało zamknięte. Wyjaśnienie to powinno być rzetelne, uzasadnone i odnosić się do całości zgłoszonego problemu a nie wybiórczo do jego fragmentów (tak na przykład było w przypadku #116). Wyjaśnienie powinno być zgodne z zasadami opisanymi w https://github.com/ProteGO-Safe/specs/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by SeraMoon** [comment]
Dołączam się do pytania / apelu. Ale czuję że odpowiedź będzie [BOT AK](https://nonsa.pl/wiki/Bo_tak).

**Comment by Tarvald** [comment]
@potiuk @SeraMoon 
Niektóre z nich zostały zamknięte przez niezgodność z
https://github.com/ProteGO-Safe/specs/blob/master/.github/CODE_OF_CONDUCT.md

A część z powodu zamknięcia tematu od strony projektowej.
Do wylistowanych issue dołączymy notkę z powodem zamknięcia.
A przyszłe  nie pozostawimy bez odpowiedzi :slightly_smiling_face:

Dodatkowo w najbliższych dniach będą prowadzone prace porządkowe na GH.

**Comment by potiuk** [comment]
@Tarvald  - Zanim dołączycie wyjaśnienia, żeby uprzedzić dalsze wydarzenia, ,am pytanie od razu co do https://github.com/ProteGO-Safe/specs/blob/master/.github/CODE_OF_CONDUCT.md

Zapewne będzie wiele kontrowersji czy faktyczne wypowiedzi go naruszają i niektóre osoby mogą się od jednoosobowej decyzji czy tak jest odwołać (bo code of conduct takie prawo zapewnia)

Wasz Code of Conduct odwołuje się wprost do [code-of-conduct CNCF](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)  w którym istnieje instytucja "Code of Conduct Committe". https://github.com/kubernetes/community/tree/master/committee-code-of-conduct . Wprost, z imienia i nazwiska i linka na githubie wymienione są tam osoby, które w tym komitecie zasiadają. 

Kiedy możemy oczekiwać że ogłosicie publicznie listę osób które w tym komitecie zasiadają (bo na razie takiej listy nie ma).

Bez tego, każda decyzja o zamknięciu z powodu łamania Code of Conduct jest ułomna,

**Comment by potiuk** [comment]
Oczywiście ludzie mogą się odwoływac do członków Kubernetesowego Code of Conduct, ale zakładam że tego nie chcecie.

**Comment by Tarvald** [comment]
@potiuk 
Co do naszego Code of Conduct Committe, dodamy to do kolejki zadań.

Dzieki!

**Comment by SeraMoon** [comment]
> Dodatkowo w najbliższych dniach będą prowadzone prace porządkowe na GH.

Proponuję zamiast nich - prace porządkowe w projekcie celem usunięcia elementów inwigilacyjnych z kodu. Skoro nie ma spotkania z Google w sprawie API - czas najwyższy się zająć tymi tematami.

**Comment by Tarvald** [comment]
@SeraMoon 
Niestety prace porządkowe na githubie już rozpoczęte. W projekcie nie ma elementów inwigalcyjnych. 
Wszystkie elementy mają związek z ratowaniem życia ludzkiego i pokonaniem COVID.

W Code of Conduct jest wspomniany @MateuszRomanow

**Comment by potiuk** [comment]
> W Code of Conduct jest wspomniany @MateuszRomanow

Uprzejmie donoszę @Tarvald, że mocno się mylisz. Chyba nie przeczytałęś tego co tam napisaliście.

W obecnym "Code of Conduct":

> Instances of abusive, harassing, or otherwise unacceptable behavior across GitHub SafeSafe-app organization may be reported by contacting the SafeSafe-app Code of Conduct Committee via community@safesafe.app. For other projects, please contact apropriate project maintainer or our mediator - Mateusz Romanów mr@safesafe.app.

W oryginalnym Code of Conduct CNCF Ten fragment brzmi tak:

> Instances of abusive, harassing, or otherwise unacceptable behavior in Kubernetes may be reported by contacting the [Kubernetes Code of Conduct Committee](https://git.k8s.io/community/committee-code-of-conduct) via conduct@kubernetes.io. For other projects, please contact a CNCF project maintainer or our mediator, Mishi Choudhary mishi@linux.com.

W oryginalnym code of conduct, Mishi jest kontaktem do "innych projektów". Jeśli chodzi o Kubernetes to jest odpowiednie ku temu "Committee". Podobnie w waszym "Code Of Conduct" @MateuszRomanow jest kontaktem do "innych projektów". Nie wiem o jakie "inne projekty" chodzi, natomiast włąściwy do zgałaszania problemów dotyczących "GitHub SafeSafe-app organization" jest "SafeSafe-app Code of Conduct Committee via community@safesafe.app.". Ponownie - nie wiemy jeszcze kto jest w owym "committe" i problem ten zgłaszałem już powyżej i mam nadzieję że wkrótce się dowiemy.

**Comment by Tarvald** [comment]
@potiuk 
Napewno zajmimy się sprawą Code of Conduct.
Sam nie jestem ekspertem w tej dzidzienie więc nie moge się zabardzo wypowiedzieć.

Wątek już dawno odbiegł od głównego tematu więc podsumuje:

Issue nie bedą zamykane bez powodu. Zawsze dołączymy notke.

Pozdrawiam
