### ISSUE TITLE
Natychmiastowe wyłączenie zbierania danych w obecnej formie

### ISSUE THREAD

**Issue by potiuk** [ProteGO-Safe/specs#137]
**Is your feature request related to a problem? Please describe.**

Jako że @MateuszRomanow  zapowiedział w https://github.com/ProteGO-Safe/specs/issues/134 że zaraz zostanie zmieniony mechanizm generacji Temporary ID. Zgłaszam prośbę o natychmiastowe wyłączenie obecnej funkcjonalności zbierania danych przez Bluetooth. 

Obecnie zbierane dane są w formacie, który będzie niekompatybilny z obecnie rozgłaszanymi ID i przydatność obecnego systemu do contact tracing jest żadna. Nawet bardziej niż to opisano tu: https://blog.kurasinski.com/2020/05/protego-safe-dlaczego-nie-nalezy-instalowac-aplikacji-ministerstwa-cyfryzacji/ zbieranie danych w chwili obecnej można uzasadnić jedynie chęcią inwigilacji.

Żeby zabezpieczyć się przed takimi oskarżeniami i budować zaufanie społeczne (co twórcy aplikjacji oraz MC deklarują od początku) należałoby moim zdaniem natychmiast wyłączyć funkcję śledząca. 

Rozumiem że takich zmian nie można wprowadzić od razu (dystrybucja przez sklep Play/AppStore). Za to bardzo łatwo to zrobić na serwerze w taki sposób. żeby wszyscy dostawali z serwera te same TempID - najlepiej żeby było to tak jak było w przypadku błędu z poprzedniej wersji aplikacji - kiedy aplikacja nadawała cały czas "Missing TempID".

**Describe the solution you'd like**
Natychmiastowa zmiana na serwerze która sprawi że wszystkie telefony będą nadawać to samo cały czas.

Lub

Całkowite wyłączenie funkcjonalności Bluetooth.

**Describe alternatives you've considered**
Pozostawienie obecnej implementacji. Naraziło by to Twórćów aplikacji na eskalację oskarżeń o bycie "aplikacją inwigilującą".

Aktualizacja: właśnie w sprawę włączyłą się była minister Cyfryzajci Anna Streżyńska i wyraziła swoje zaniepokojenie: https://www.linkedin.com/posts/annastrezynska_protego-safe-dlaczego-nie-nale%C5%BCy-instalowa%C4%87-activity-6662730656147218432-Rdwp 
 https://www.facebook.com/anna.strezynska/posts/3089320444422168 więc myślę że czym prędzej tą "funkcję śledzącą" trzeba wyłączyć żeby takich ostarżeń nie było więcej.

**Comment by SeraMoon** [comment]
Jestem za, **ankiety też wyłączyć, bo należy im się przebudowa**.

**Comment by potiuk** [comment]
> Jestem za, **ankiety też wyłączyć, bo należy im się przebudowa** w zakresie miejsca przetwarzania.

@SeraMoon -> proponuję zrób po prostu nowe issue zgodne z szablonem i bez emocji. To uniemożliwi jego zamknięcie z powodu naruszenia "Code of Conduct".

**Comment by jasisz** [comment]
Nie wiem na ile właściwe jest w ogóle łączenie tych funkcji w jednej aplikacji. Rozumiem, że jest to o tyle lepsze, że łatwiej ludzi namówić do instalacji i jest dwa w jednym, ale:
- trudniej jest coś takiego audytować, prowadzić, śledzić zmiany i issues
- istnieje ryzyko korelowania danych z backendu do ankiet i backendu do contact tracing

**Comment by potiuk** [comment]
> Nie wiem na ile właściwe jest w ogóle łączenie tych funkcji w jednej aplikacji. Rozumiem, że jest to o tyle lepsze, że łatwiej ludzi namówić do instalacji i jest dwa w jednym, ale:
> 
> * trudniej jest coś takiego audytować, prowadzić, śledzić zmiany i issues
> * istnieje ryzyko korelowania danych z backendu do ankiet i backendu do contact tracing

@jasisz Jeśli tylko było by to wprowadzane jako odzielne PR-y i zupełnie rozdzielone w kodzie to nawet ma to sens - ale tylko jeśli jest to uwzględnione w  obliczeniach "Exposure Risk Level". W API G+A jest nawet miejsce na przekazanie wyników tego "self-assesment" do API:

https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-FrameworkDocumentationv1.2.pdf

> Transmission Risk — An app-defined flexible value to tag a specific positive key. This value could be
> tagged based on symptoms, level of diagnosis verification, or other determination from the app or a health authority.

**Comment by Tarvald** [comment]
@potiuk apleujesz o wyłączenie funkcjonalności BL
@SeraMoon a ty o wyłączenie ankiet.

Te dwie częsci to całkiem spora częśc obecnej aplikacji, która potencjalnie może uchronić przed zarażeniem oraz uratować komuś życie. 

Dane w obecnej formie, są potrzebne do wykorzystania https://github.com/opentrace-community.

Na tą chwile google/apple API nie jest produktem gotowym i nie możemy pokładać w nim całej nadzieji.
Ludzie chcą wyjść z lockdown'u a miliony seniorów potrzebują pomocy.

**Comment by potiuk** [comment]
> @potiuk apleujesz o wyłączenie funkcjonalności BL
> @SeraMoon a ty o wyłączenie ankiet.
> 
> Te dwie częsci to całkiem spora częśc obecnej aplikacji, która potencjalnie może uchronić przed zarażeniem oraz uratować komuś życie.
> 
> Dane w obecnej formie, są potrzebne do wykorzystania https://github.com/opentrace-community.

Nie są. Nie wysyłacie nigdzie danych i macie zamiar totalnie zmienić aplikację (chyba że @MateuszRomanow napisał nieprawdę w #134). Więc te dane nie są do niczego potrzebne. 

> Na tą chwile google/apple API nie jest produktem gotowym i nie możemy pokładać w nim całej nadzieji.
> Ludzie chcą wyjść z lockdown'u a miliony seniorów potrzebują pomocy.

Powtórzenie czegoś wiele razy nie sprawia że jest to zgodne z prawdą.

Nawet jeśli miało by tak być to zgodnie z #134 i tak zmieniacie działanie aplikacji i te dane są bezużyteczne. Apeluję włąśnie ot to żeby to wyłączyć. Albo nie wiesz o czym mówisz, albo świadomie mówisz nieprawdę. Nie wiem co gorsze w kontekście potencjalnych milionów osób używających tę aplikację.

**Comment by SeraMoon** [comment]
> Ludzie chcą wyjść z lockdown'u a miliony seniorów potrzebują pomocy.

Jakoś Niemcy wychodzą z lockdownu bez apki XD i jakoś im się to udaje. 
Zdradzę pewną tajemnicę odnośnie tej krzywej zachorowań na COVID-19. 35-45 dni od pierwszych 10 przypadków występuje szczyt zachorowań, potem jest spadek. Póki co nie sprawdza się dla 2 większych państw - w których skutecznie ubito wirusa identyfikując osoby chore i potencjalnie zarażone przez zamiejscowych. 

Do przemyślenia pozostawiam więc określenie na ile skuteczny jest lock-down. 

Poza tym polecam poczytać o G6PDD (na to "choruje" większość Włochów) - stąd u nich jest tak źle z liczbami, poza tym nie mieli przygotowanych szpitali podobnie jak my - gdyby tu szły liczby w tysiące byłoby tak jak tam. 

Warto też będąc na czasie poczytać o syndromie Kawasakiego indukowanym przez COVID-19 - niedodiagnozowane dzieci - bo tak one chorują tą nową "odmianę grypy" - grypy koronawirusowej.. 

### a jeżeli chcemy ratować życia ludzkie

to trzeba więcej respiratorów oraz więcej szpitali i lekarzy - obecne działania rządu temu nie sprzyjają. Bo jeżeli nie zachorują teraz to zachorują za 1-2 miesiące i jeżeli mieli umrzeć i tak umrą...

**Comment by Tarvald** [comment]
@SeraMoon 
To nie miejsce na rozmowy o tym czy lockdown jest potrzebny, ani w jaki sposób niemcy wychodzą z lockdownu bez apki.
Nie dotyczy to bezpośrednio aplikacji.

@potiuk 
Nie wyłączymy zbierania danych w obecnej formie, ponieważ protokół G+A nie został oficjalnie wydany. Ba! Nie ma nawet oficjalnej daty premiery.

Nie wyłączymy funkcji bluethooth ponieważ jest ona niezbędna do działania:
https://github.com/opentrace-community/opentrace-cloud-functions

Na tą chwile na tym rozwiązaniu opieramy działanie aplikacji i modułu BL.

Ale dzięki za feedback!

**Comment by potiuk** [comment]
@Tarvald - nie zgadzam się z tym wyjaśnieniem  i zamknięciem issue . @MateuszRomanow  powiedział w #134 że zmieniacie działanie open trace i to potrzebuje wyjaśnienia

**Comment by potiuk** [comment]
@Tarvald -> czy istnieje możliwość otwarcia tego i zajęcia się (na szybko) włączenia trybu "anonimowy" w aolikacji tak aby przynajmniej nie rozgłaszała zmieniających się Temp ID ?

**Comment by Tarvald** [comment]
@potiuk 
W związku z #147 wątek zostaje ponownie otwarty.

Temat jest analizowany i na dniach będzie omówiony.

**Comment by potiuk** [comment]
Czy można wiedzieć co z wyłączeniem ? Aplikacja dalej niepotrzebnie zbiera dane a wyłaczenie tego jest banalne.

**Comment by Tarvald** [comment]
@potiuk 
Na pewno będzie to usunięte przy wersji G+A.

Prowadzone są rozmowy wewnątrz zespołu developerskiego, czy nie zrobić dodatkowego wdrożenia, z rozwiązaniem tylko tego problemu. 

Problem został zgłoszony już tutaj:
https://github.com/ProteGO-Safe/android/issues/113

Został też ten problem zaraportowany w wewnętrznych systemach, także na platformie iOS.

Niebawem, powiążemy wszystkie issue z GH z wewnętrznymi systemami i postaramy się informować społeczność o zmianach z nimi związanymi :)

**Comment by generatorkartwyborczych** [comment]
> Niebawem, powiążemy wszystkich raportów problemów z GH z wewnętrznymi systemami

Minister pisał: "_prace nad nią [aplikacją są] w pełni transparentne_". To kolejna rzecz, w której deklaracje rozjeżdżają się z praktyką. Nie widzimy prac nad aplikacją. Widzimy tylko cykliczną wrzutę kodu bez historii, kontekstu ani powiązania z ticketami.

Jeśli chodzi o aplikację Androidową, to nie da się jej zbudować z dostarczonych źródeł - brakuje wartości wszystkich stałych pchanych do BuildConfig OpenTrace.

**Comment by Tarvald** [comment]
@generatorkartwyborczych 
> Jeśli chodzi o aplikację Androidową, to nie da się jej zbudować z dostarczonych źródeł - brakuje wartości wszystkich stałych pchanych do BuildConfig OpenTrace.

Twój błąd został zgłoszony.

> Minister pisał: "prace nad nią [aplikacją są] w pełni transparentne". To kolejna rzecz, w której deklaracje rozjeżdżają się z praktyką. Nie widzimy prac nad aplikacją. Widzimy tylko cykliczną wrzutę kodu bez historii, kontekstu ani powiązania z ticketami.

Będziemy cały czas usprawniać ten proces.
Jeżeli masz pomysł albo sugestie jak ten proces (realnie) ulepszyć to, daj znać w nowym wątku :)

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.

Open trace został wycięty z aplikacji w wersji 4.1.1
