### ISSUE TITLE
Ratingi aplikacji lecą na łeb na szyję

### ISSUE THREAD

**Issue by potiuk** [ProteGO-Safe/specs#140]
**Describe the bug**
Z tego co widzę to ratingi aplikacji lecą na łeb na szyję

https://play.google.com/store/apps/details?id=pl.gov.mc.protegosafe&gl=PL

Dwa dni temu było bardzo słabe 2.3 a dziś jest już "poziom malware" 1.9.
Lektura komentarzy wskazuje na to, że zdewcydowana większość 1-gwiazdkowych ocen dotyczy obaw użytkowników o naruszenie prywatności.

Mam nadzieję że Twórcy Aplikacji ale również Ministerstwo Cyfryzacji planują działania mające na celu przywrócenie "społecznej akceptacji aplikacji"? 

**To Reproduce**
Odwiedzenie https://play.google.com/store/apps/details?id=pl.gov.mc.protegosafe&gl=PL

**Expected behavior**

Rating powyżej 3 (obawiam się że nie ma możliwości żeby było lepiej niż to)

**Screenshots**

![Screenshot from 2020-05-03 21-03-20](https://user-images.githubusercontent.com/595491/80923086-8e8b1a80-8d81-11ea-8999-1d6d86efaa96.png)

**Comment by SeraMoon** [comment]
@potiuk Ministerstwo wszystko "zdementuje", a ślepy lud pójdzie za ich slowami.

**Comment by KonoromiHimaries** [comment]
@potiuk jedyna sensowna możliwość w tej sytuacji https://github.com/ProteGO-Safe/specs/issues/127#issuecomment-623150087

**Comment by puwalski** [comment]
Nie sądzę, by można było osiągnąć średnią ocenę na poziomie trzech gwiazdek w sposób inny niż kupując fałszywe opinie. Niestety raz utraconego zaufania praktycznie nie da się odbudować. Osobiście żal mi osób, które w dobrej wierze zaangażowały się w ten projekt - naiwnie wierząc, że akurat ich obecna władza nie wydyma.

**Comment by potiuk** [comment]
Jedyna sensowna możliwość to docelowe rozwiązanie G+A które docelowo nie wymaga aplikacji w ogóle. Polecam lekturę https://www.apple.com/covid19/contacttracing/ i dyskusji w #132 gdzie wyjaśniam wszystko w szczegółach łącznie z obrazkami wyjętymi ze specyfikacji (niestety już zamknięte przez Twórców aplikacji)

**Comment by potiuk** [comment]
> Nie sądzę, by można było osiągnąć średnią ocenę na poziomie trzech gwiazdek w sposób inny niż kupując fałszywe opinie. Niestety raz utraconego zaufania praktycznie nie da się odbudować. Osobiście żal mi osób, które w dobrej wierze zaangażowały się w ten projekt - naiwnie wierząc, że akurat ich obecna władza nie wydyma.

Osobiście nie napisałbym tego w taki sposób publicznie. ale przyznam że podobne argumenty już dawno padały w prywatnych konwersacjach a w naszej prywatnej korespondencji pojawił się w tym kontekście motyw więzienia i mydła.

**Comment by SeraMoon** [comment]
Inna aplikacja Ministerstwa Cyfryzacji w tym sklepie ma ocenę 1.4 - to już OrwellWare. Obrzucili to jajami.

**Comment by Tarvald** [comment]
> **Describe the bug**
> Z tego co widzę to ratingi aplikacji lecą na łeb na szyję
> 
> https://play.google.com/store/apps/details?id=pl.gov.mc.protegosafe&gl=PL
> 
> Dwa dni temu było bardzo słabe 2.3 a dziś jest już "poziom malware" 1.9.
> Lektura komentarzy wskazuje na to, że zdewcydowana większość 1-gwiazdkowych ocen dotyczy obaw użytkowników o naruszenie prywatności.
> 
> Mam nadzieję że Twórcy Aplikacji ale również Ministerstwo Cyfryzacji planują działania mające na celu przywrócenie "społecznej akceptacji aplikacji"?
> 
> **To Reproduce**
> Odwiedzenie https://play.google.com/store/apps/details?id=pl.gov.mc.protegosafe&gl=PL
> 
> **Expected behavior**
> 
> Rating powyżej 3 (obawiam się że nie ma możliwości żeby było lepiej niż to)
> 
> **Screenshots**
> 
> ![Screenshot from 2020-05-03 21-03-20](https://user-images.githubusercontent.com/595491/80923086-8e8b1a80-8d81-11ea-8999-1d6d86efaa96.png)

Z takim pytaniem, zapraszamy do ministerstwa cyfryzacji.
Zespół projektowy nie zajmuje się kreowaniem opini w internecie.

**Comment by potiuk** [comment]
Bardzo proszę: @MinistersfwoCyfryzacji .prosimy o odpowiedź. A może jednak @MateuszRomanow jako łącznik to przekaże - bo chyba taka rola łącznika żeby przekazywać takie problemy ?

**Comment by SeraMoon** [comment]
Dla tej aplikacji nie widzę nadziei - proponuję by osoby które umieją jednocześnie:
- programować
- analizować i identyfikować miejsce powstania danych

zebrały się nad nową aplikacją, która wypełni wymogi prywatności i contact-tracingu na cele zwalczania SARS-CoV-2. 

W polityce prywatności nic o administratorze danych (bo jeżeli danych nie zbieramy, nie ma ADO, aplikacja niezależna od Ministerstw, a Ministerstwo poprosimy tylko o jej upowszechnienie bez dostępu do "rządania" czegokolwiek.

**Comment by potiuk** [comment]
> "rządania" 

Tu poproszę jednak o poprawkę na "żadania", bo trochę kłuje w oczy ;)

**Comment by potiuk** [comment]
A przepraszam. Zrozumiałem :)

**Comment by SeraMoon** [comment]
@potiuk rząd "rząda" a przeglądarka "żąda" zasobów. Chodzi o charakter upolityczniony tego "rządania" XD.

**Comment by potiuk** [comment]
> @potiuk rząd "rząda" a przeglądarka "żąda" zasobów. Chodzi o charakter upolityczniony tego "rządania" XD.

Tak tak . Załapałem, Trochę póżno bo cały weekend zajmowałem się informowaniem ludzi co ta aplikacja naprawdę robi i jestem odrobinę zmęczony...

**Comment by potiuk** [comment]
> @potiuk Co to za motyw? Mogę prosić na nasz z polskiego?

Polecam Google: "więzienie mydło" -> pierwsze wyniki

**Comment by Tarvald** [comment]
@potiuk 
https://www.gov.pl/web/cyfryzacja/

Tam znajdziesz kontakt do ministerstwa cyfryzacji, github to nie jest ich kanał komunikacyjny.

**Comment by potiuk** [comment]
> @potiuk
> https://www.gov.pl/web/cyfryzacja/
> 
Jak pisałem wcześniej nie odpisywali nawet fundacji Panoptykon. Więc raczej nie spodziewam się odpowiedzi na moją wiadomość.  Ale wcześniej @MateuszRomanow jako łacznik oferował się przekazywać takie rzeczy. Więc uprzejmie proszę.

**Comment by SeraMoon** [comment]
@Tarvald skoro Ministerstwo Cyfryzacji jest autorem tej aplikacji wg Google Play, oraz na stronie koronawirus.gov.pl zapraszało nas do wyrażania opinii właśnie tutaj w tych Issues, to dlaczego mamy tam pisać? **Może pora aby Ministerstwo aktywnie uczestniczyło w tychdyskusjach**? Podało taki a nie inny kontakt w sprawie "ProteGo".

**Comment by Tarvald** [comment]
@potiuk 
Obecnie cały zespół ProteGo jest bardzo bardzo zajęty developmentem aplikacji.
My wciąż w lockdownie, ludzie tracą prace, miliony osób potrzebuje ochrony.

@SeraMoon 
@MateuszRomanow jest łącznikiem i nie podał się do dymisji. Prosiłbym o nie wprowadzanie społeczności w błąd :)

Aplikacja jest na tyle krótko w sklepie, a do tego brak zmian przez G+A powoduje jej duże problemy, że nie dziwota że aplikacja ma takie słabe oceny.
Będzie coraz lepiej, gwarantuje wam.

W celu ustalenia przyczyn takiego odbioru aplikacji prosiłbym o kontakt z kimś z ministerstwa.
Ta grupa ProteGo obecna na githubie, stara się dostarczyć rozwiązanie które będzie ratować życia i majątki ludzkie.

**Comment by SeraMoon** [comment]
> @potiuk
> Obecnie cały zespół ProteGo jest bardzo bardzo zajęty developmentem aplikacji.
> My wciąż w lockdownie, ludzie tracą prace, miliony osób potrzebuje ochrony.

To niech developerzy zajmą się usuwaniem inwigilacyjnych wtrętów z tej aplikacji. 

> @SeraMoon
> @MateuszRomanow jest łącznikiem i nie podał się do dymisji. Prosiłbym o nie wprowadzanie społeczności w błąd :)

Sam napisał w jednym Isseu, że nie otrzymuje odpowiedzi od Ministerstwa i przestaje być łącznikiem. Skoro zrezygnował z funkcji sam o tym pisząc to jest czy nie jest? Muszę poszukać tego komentarza? 

> Aplikacja jest na tyle krótko w sklepie, a do tego brak zmian przez G+A powoduje jej duże problemy, że nie dziwota że aplikacja ma takie słabe oceny.

Zacytuję kilka wypowiedzi które dają te minusy - pora usunąć inwigilację na zawsze: 

Patryk Siewiera
April 30, 2020 7
how to sell your data 101

Barbara Puwalska
May 2, 2020 5
Aplikacja do totalnej inwigilacji użytkowników. Autorzy próbują mydlić oczy faktem, że aplikacja ma otwarte źródła, ale to w niczym nie zmienia faktu, że nas szpieguje i wysyła dane na rządowe serwery, gdzie pisia władza zrobi z nimi, co zechce. Niekoniecznie z pożytkiem dla użytkownika.

Jarosław K
April 30, 2020 17
NIEBEZPIECZNE!!!! kradną prywatność i wolność pod przykrywką walki z wirusem! zastanówcie się dlaczego politycy nie noszą masek i nie przestrzegają własnych restrykcji. na razie tylko doją i niszczą przedsiębiorców. pokażmy im kto tworzy Polskę - nie potrzebujemy ich "opieki"

Dawid Cyron
April 30, 2020 25
Wirus stał się argumentem do odebrania prywatności obywatelom oraz przyznawania uprawnień tym, którzy tą prywatność poświęcają. Aplikacja powinna zostać usunięta ze sklepu

### Czy tu nie widać, gdzie jest problem?

> W celu ustalenia przyczyn takiego odbioru aplikacji prosiłbym o kontakt z kimś z ministerstwa.

Możesz to sam zrobić. Lub może to zrobić łącznik @MateuszRomanow o ile jest łącznikiem. 

> Ta grupa ProteGo obecna na githubie, stara się dostarczyć rozwiązanie które będzie ratować życia i majątki ludzkie.

### To niech nie ratuje setek żyć kosztem prywatności milionów ludzi, szczególnie, że można to uczynić bez narażania prywatności.

**Comment by potiuk** [comment]
> @potiuk
> Obecnie cały zespół ProteGo jest bardzo bardzo zajęty developmentem aplikacji.
> My wciąż w lockdownie, ludzie tracą prace, miliony osób potrzebuje ochrony.
> Ta grupa ProteGo obecna na githubie, stara się dostarczyć rozwiązanie które będzie ratować życia i majątki ludzkie.

Po raz kolejny apeliuję żeby nie manipulować faktami. Nie wiem skąd masz taką wiedzę że aplikacja ta ma "ratować życie". Ja słyszałem tą retorykę od samego początku projektu i według mnie to jest manipulacja żeby wprowadzać inwigilację.

Większość ekspertów na świecie (choćby 300 wiodących naukowców, którzy podpisali się pod tym listem: https://drive.google.com/file/d/1OQg2dxPu-x-RZzETlpV3lFa259Nrpk1J/view?fbclid=IwAR0uTvKD7HIbxo2QhyBQQaWdn2dCT-Q1-wVQiE3n8BuMGX_f0WCxvER-tUE )
mówią o tym że aplikacja "contact tracing" może jedynie wspomagać to co robi rząd za pomocą "klasycznego contact tracing".  I że to rozwiązanie jest efektywne dopiero jak jest powszechne. 

Wy macie zamiar (podobno ) zastąpić ro rozwiazaniem G+A, które docelowo ma działać BEZ APLIKACJI. Więc mówienie o tym że aplikacja ratuje życie jest zdecydowanie manipulacją. 

Nawet to, że zobowiązaliście się wprowadzić wasze zdecentralizowane rozwiązanie (jako kolejny zwrot akcji jako rezultat mojego wywiadu https://blog.kurasinski.com/2020/05/protego-safe-dlaczego-nie-nalezy-instalowac-aplikacji-ministerstwa-cyfryzacji/) powoduje że zbieranie danych w tej chwili jest niepotrzebne i powinno być natychmiast wyłączone (Zgłosiłem to w #137). Czekam na reakcję w tej sprawie. To akurat leży w gestii programistów chyba.

**Comment by SeraMoon** [comment]
> Wy macie zamiar (podobno ) zastąpić ro rozwiazaniem G+A, które docelowo ma działać BEZ APLIKACJI. Więc mówienie o tym że aplikacja ratuje życie jest zdecydowanie manipulacją.

@potiuk sorry, umknęło mi - faktycznie jest tak jak mówisz i aplikacja już nic nie ratuje a obecnie służy do inwigilacji.

**Comment by Tarvald** [comment]
@SeraMoon @potiuk 
Aplikacja nie służy do inwigilacji, a pomaga chronić ludzi przed COVID19.
Pomyłiliście aplikacje.

I tak, moim zdaniem aplikacja może uratować komuś życie.

**Comment by puwalski** [comment]
> Aplikacja jest na tyle krótko w sklepie, a do tego brak zmian przez G+A powoduje jej duże problemy, że nie dziwota że aplikacja ma takie słabe oceny.
> Będzie coraz lepiej, gwarantuje wam.

No cóż, jeśli ktoś rozpowszechni informację, że jakaś dziewczyna się puszcza, to udowodnienie, że jest inaczej jest raczej trudne. Podobnie jest z ProteGO Safe - niemal wszyscy już się dowiedzieli, że to aplikacja szpiegująca i nawet jeśli tak do końca nie jest - nie wydaje się możliwe usunięcie przylepionej łatki. Oczywiście można użyć brudnych chwytów, żeby poprawić statystyki w Google Play, można podkupić portale by entuzjastycznie wypowiadały się aplikacji, można też ogłosić, że już 3 czy 4 miliony Polaków używają aplikacji... Który wariant jest planowany, skoro już dziś możliwe jest zagwarantowanie, że "będzie lepiej"?

**Comment by Tarvald** [comment]
@puwalski 
Prowadzone są audyty bezpieczeńśtwa, dokumentacja na githubie, będzie aktualizowana i wiele wiele innych. 
Aplikacja nie służy do inwigilacji, to tylko błedna medialna kreacja.

**Comment by jasisz** [comment]
> Obecnie cały zespół ProteGo jest bardzo bardzo zajęty developmentem aplikacji.
Dlaczego tego nie widać w Github? Nie twierdzę, że nic nie robicie, tylko że słabo jest to widoczne. Czy to jest developowane gdzieś poza tymi repozytoriami, a kod jest przenoszony tutaj cherry-pickami tak jak to miało miejsce z kodem aplikacji 3.0?

> Ta grupa ProteGo obecna na githubie, stara się dostarczyć rozwiązanie które będzie ratować życia i majątki ludzkie.

Ratowanie majątków ludzkich wydaje się ściśle powiązane z https://github.com/ProteGO-Safe/specs/issues/140 - dobra, ten głupi żart proszę mi wybaczyć, ale nie mogłem się powstrzymać ;)

> Ta grupa ProteGo obecna na githubie, stara się dostarczyć rozwiązanie które będzie ratować życia i majątki ludzkie.

Niestetu od początku (również wtedy gdy za aplikacją stała Polidea) członkowie ProteGO nie są jawni jako członkowie organizacji na GitHub. Teraz jest o tyle gorzej, że dodatkowo część z nich (w tym np. zdaje się sam łącznik) nie są nawet wymienieni w https://github.com/ProteGO-Safe/specs/blob/master/CONTRIBUTORS.md

**Comment by Tarvald** [comment]
@jasisz 
Tak, prace są prowadzone na wewnętrznych repozytoriach, a kod później aktualizowany.
Narazie procesy są w wewnątrz.

Ale to nie rodzi żadnych problemów abyscie panowie @jasisz @potiuk @SeraMoon utworzyli pull request i zaproponowali zmiany.

**Comment by jasisz** [comment]
@Tarvald 
Bardzo chętnie, ale jak pisałem w https://github.com/ProteGO-Safe/backend/issues/82 niestety nie mam dostępu do tej części aplikacji, w której rzeczywiście mógłbym coś zdziałać.

**Comment by Tarvald** [comment]
@jasisz 
Prosze bardzo:
https://github.com/opentrace-community/opentrace-cloud-functions

**Comment by KonoromiHimaries** [comment]
> I tak, moim zdaniem aplikacja może uratować komuś życie

Niebieskie światło zmniejsza ryzyko samobójstw, polecam zacząć od tego.

**Comment by SeraMoon** [comment]
> Ale to nie rodzi żadnych problemów abyscie panowie @jasisz @potiuk @SeraMoon utworzyli pull request i zaproponowali zmiany.

Przypomnę zgodnie z CoC CNCF aby zwracać się do mnie zgodnie z płcią, identyfikacją seksualną i orientacją seksualną.

**Comment by Tarvald** [comment]
> Mam napisać do Comittee?

Możesz pisać, to była zwykła pomyłka. Pisząc to, nie znałem jeszcze twojej płci.

**Comment by SeraMoon** [comment]
> 
> 
> > Mam napisać do Comittee?
> 
> Możesz pisać, to była zwykła pomyłka. Pisząc to, nie znałem jeszcze twojej płci.

Dziwne, bo piszę tu bardzo długo z tobą. Tylko gbur nie napisze zwykłego "przepraszam". Tyle wystarczyło + edycja.

**Comment by Tarvald** [comment]
@SeraMoon 
Przepraszam. 
Jestem zajęty wieloma innymi rzeczami równocześnie, oraz jest późna godzina.
Btw. Nie jesteś pępkiem świata :)
A do tego dość mocno spamujesz w tym wątku i mocno odbiegasz o tematu.

**Comment by SeraMoon** [comment]
>@SeraMoon
Przepraszam.
Jestem zajęty wieloma innymi rzeczami równocześnie, oraz jest późna godzina.
Btw. Nie jesteś pępkiem świata :)
A do tego dość mocno spamujesz w tym wątku i mocno odbiegasz o tematu.

OK. Comittee się tym zajmie. Obawiam się, że pępkiem świata to jest ktoś inny - KOLEJNA WYCIECZKA OSOBISTA @Tarvald

**Comment by potiuk** [comment]
> @jasisz
> Tak, prace są prowadzone na wewnętrznych repozytoriach, a kod później aktualizowany.
> Narazie procesy są w wewnątrz.
> 
> Ale to nie rodzi żadnych problemów abyscie panowie @jasisz @potiuk @SeraMoon utworzyli pull request i zaproponowali zmiany.

Faktycznie trochę przykro widzieć to "panowie" kiedy @SeraMoon wyraźnie i często używa formy "ona" (niezależnie od tego jaka jest jej faktyczna płeć). Naruszenie Code of Conduct jest tu dość jasne. I o ile samo przepraszam jest cool, to już łączenie go z "Pępkiem świata"  już nie najlepiej świadczy o przestrzeganiu "Code of Conduct".

A wracając do meritum - zrobienie PR robi mnóstwo problemów 

1) Po pierwsze:  zdaje się trzeba coś podpisać. Co prawda nie wiadomo co bo https://github.com/ProteGO-Safe/specs/blob/master/CONTRIBUTORS.md wspomina o dokumencie, którego już nie ma. Jeszcze niedawno było ale zniknęło, więc nie wiadomo co podpisać. Dodam też że mogę chcieć nie podpisać żadnych dokumentów jeśli uznam że nie są ok. Mam do tego prawo.
To jest dokładnie w CONTRIBUTORS.md:

> Lista osób które podpisały [oświadczenie o udzieleniu licencji](https://github.com/ProteGO-Safe/specs/blob/master/CONTRIBUTING.md#O%C5%9Bwiadczenie-o-udzieleniu-licencji) i wprowadziły zmiany w projekcie:

b) jedyny PR w którym komentowałem został zamknięty https://github.com/ProteGO-Safe/specs/pull/118  - z takim oto komentarzem

> Mozemy wyciagnac te zmiany na branch lub osobny PR i je przedyskutowac?
Z repozytorium korzysta ministerstwo cyfryzacji i nalegaja by opublikowac tresci przygotowane w oryginalym PR.

To ciekawy argument, ale nie podoba mi się. Wydawało mi się że MC nie korzysta z tego repozytorium (bo inaczej mogliby tu komentować a tymczasem odsyłacie nas do maili). Nie wzbudza to mojego zaufania że wysiłek włożony w stworzenie PR-a zostanie w jakikolwiek sposób zaaprobowane jeśli "ministerstwo cyfryzacji będzie nalegać".

c) Po 10 dniach w których pracujecie "dużo", zakładam, że jest sporo zmian, więc PR do zmian już nieaktualnych jest słabym pomysłem. W moim projekcie [Apache Airflow](https://github.com/apache/airflow) gdzie tempo pracy jest "normalne" juz po kilku dniach jest problem z rebase. Trudno z resztą commitować do czegoś co nawet nie ma spójnych założeń - @Tarvald i @MateuszRomanow na razie twierdzą co innego  (jak opisane w https://github.com/ProteGO-Safe/specs/issues/139#issuecomment-623195451) nie wiadomo jak się ma obecna do przyszłej implementacji, więc trudno robić jakieś PR-y nie wiedząc co jest planowane.

**Comment by miklobit** [comment]
> Aplikacja nie służy do inwigilacji, to tylko błedna medialna kreacja.

@Tarvald 
Ta "błedna medialna kreacja" nie wzięła się z sufitu tylko jest sumą fakapów z których jedne są widocznym gołym  okiem dla każdego usera aplikacji  a inne wymagają nieco wyobraźni  i analizy, w których to zadaniach pomagają zgłaszane tu uwagi.
Fakapy widoczne z kosmosu to np. kwestia żądania przez aplikację dostępu do lokalizacji. Jeżeli user dostaje na dzień dobry popup z OS'a:  "Czy zezwolić aplikacji.... na dostęp do lokalizacji twojego urządzenia?" to jakim cudem chcecie w nim wzbudzić zaufanie, że naprawdę nie chodzi o zbieranie przez (nie)rząd danych o lokalizacji tylko możliwość skanowania BT ? Skoro aplikacja dostała od usera uprawienie to pierwszą zasadą ograniczonego zaufania jest założenie, że w jakimś momencie z tego uprawnienia skorzysta w pełnym jego zakresie. Jeżeli będziecie publicznie twierdzić, ze jest inaczej to cały wysiłek wkładany w edukację ludzi na temat  bezpieczenstwa w sieci idzie na marne. 
Skoro mamy więc potencjalnie otwartą (macie klucz) furtkę pt. "zbieranie danych o lokalizacji"  i połaczymy to z furtką "wysyłanie na serwer danych medycznych które mogą zidentyfikować konkretną osobę" , która to furtka już nie jest tylko potencjalna ale jest zamierzona by-design, to dostajemy wszystko co trzeba żeby twoerdzenie "aplikacja może służyć do inwigilacji" było absolutnie prawdziwe.

**Comment by SeraMoon** [comment]
@miklobit a czy w czasie aktualizacji aplikacji - ta pyta ponownie o udzielenie zgody na "Lokalizację"? Jak to wygląda na amarkfonie dla innych aplikacji? Przecież podczas aktualizacji można dołożyć złe funkcje... Stąd było moje pytanie do google do #134 Google czy planuje tą usługę Contact-Tracingu wyszczególnić jako oddzielną funkcję. Jednak odpowiedzi nie posiadamy.

**Comment by miklobit** [comment]
> @miklobit a czy w czasie aktualizacji aplikacji - ta pyta ponownie o udzielenie zgody na "Lokalizację"? 

No właśnie nie pyta. Czyli dajemy apce dostęp do lokalizacji i musimy wierzyć twórcom (aka nie-rządowi) na słowo, że nigdy z tego nie skorzystają. To jest mniej więcej ten sam rodzaj zaufania który sie marzy nie-rządom w zakresie szyfrowania. Że będą mieć jakiś master-key schowany w sejfie, z którego obiecują nigdy nie skorzystać. No chyba, że w celu ścigania terrorystów  :smile: .

**Comment by Tarvald** [comment]
Hej
Wątek już dawno odbiegł głównego tematu i trudno się w nim połapać.

Więc podsumuje:

Ministestwo oraz zespół ProteGo widzi problem w postaci niskich ratingów oraz obaw w postaci privacy oraz data security.

Pracujemy nad tym ulepszając takie obszary jak:

1. Transparentność
2. Aktualna specyfikacja na gihubie
3. Praca z nie zależnymi ekspertami od data security oraz data privacy

@SeraMoon @potiuk @miklobit 
Następnym razem prosilibyśmy o zakładanie osobnych wątków na poszczególne nieścisłości, a najbardziej zachęcamy do tworzenia pull requestów ze zmianami!

Ale dziękuje za zaangażowanie :)

**Comment by sub-zero-pl** [comment]
Jako osoba nie kodująca dziękuję @SeraMoon @potiuk i innym że otworzyliście mi oczy. Wątki zacząłem czytać od zamkniętych.

Jeszcze raz dziękuję.

**Comment by Tarvald** [comment]
Wątek ponownie otwarty do merytorycznej dyskusji zgodnej z #147 :)

**Comment by sub-zero-pl** [comment]
Rating wczoraj w nocy 1,9 dzisiaj rano 2,6 przy czym ilość nowych negatywnych komentarzy (wraz z ocena) przytłoczyła te pozytywne... 

Było prawie 400 ocen, dziś rano jest 448

**Comment by MateuszRomanow** [comment]
Zastanawiam się, czy skoro wszyscy mamy dostęp do informacji o [ocenie](https://play.google.com/store/apps/details?id=pl.gov.mc.protegosafe&hl=en_US)w Google Play to jest sens trzymać wątek, w którym wyświetlamy te same informacje?

Aplikacja - jak każda inna - jest wciąż instalowana przez nowe osoby, te osoby mają swoje opinie, są to opinie 1* wypominające o zagrożeniu prywatności, co nie jest faktem (nie ma możliwości na wykorzystanie danych bluetooth ponieważ nie ma możliwości ich wysłania ani przewtorzenia; jak będzie możliwość wysłania - będzie się to działo już w oparciu o DiagnosisKey po integracji z API G+A i dużej aktualizacji). Natomiast pamiętajcie proszę, że pośród kilkudziesięciu milionów osób, które mogą zainstalować aplikację, duża grupa ceni sobie możliwość wykonania testu oceny ryzyka, przygotowania się do ewentualnej hospitalizacji, oraz chce przyspieszyć odmrażanie gospodarki i dlatego wspiera aplikację. Tacy użytkownicy dają 5* lub 3-4* i raportują błędy, które są przyjmowane i fixowane w kolejnych wydaniach. **W związku z tym ocena w czasie zawsze będzie się zmieniała. Nie tylko w tej ale każdej innej aplikacji, w której użytkownicy się wypowiadają.** 

@potiuk ponieważ jesteś autorem, czy możesz zamknąć wątek?

**Comment by jasisz** [comment]
@MateuszRomanow To po co audyt, skoro juz wiadomo że zagrożenie prywatności nie jest faktem? Oczywiście, że jest. Ba! przy pełnym rozwiązaniu Google i Apple dalej istnieją zagrożenia prywatności, trudno stwierdzić jeszcze które konkretnie i jak poważne, bo my maluczcy nie znamy takich szczegółów implementacji.
W obecnym rozwiązaniu trzymanie historii identyfikatorów po stronie serwera jest czymś co pozwala stronie rządowej (albo ewentualnemu włamywaczowi) na bardzo proste śledzenie lokalizacji użytkownika przez odbiorniki Bluetooth w terenie. Mówienie, że jest inaczej to zaklinanie rzeczywistości.

**Comment by kierepka** [comment]
A tu taki piękny tekst:
https://www.zdnet.com/article/mobile-apps-and-contact-tracing-these-tools-are-helping-to-end-the-lockdown/

**Comment by potiuk** [comment]
> Zastanawiam się, czy skoro wszyscy mamy dostęp do informacji o [ocenie](https://play.google.com/store/apps/details?id=pl.gov.mc.protegosafe&hl=en_US) w Google Play to jest sens trzymać wątek, w którym wyświetlamy te same informacje?
>  
> @potiuk ponieważ jesteś autorem, czy możesz zamknąć wątek?

Tak, choć myślę że problem nie jest rozwiązany ale już przynajmniej jest adresowany i są otwarte issue, które tego dotyczą i założenia które to adresują w #147.  Myślę że w tym kontekście spokojnie to można zamnkąć.

**Comment by SeraMoon** [comment]
> Rating wczoraj w nocy 1,9 dzisiaj rano 2,6 przy czym ilość nowych negatywnych komentarzy (wraz z ocena) przytłoczyła te pozytywne...

Po zdjęciu aplikacji z Play Google nie powinno się dać głosować. Ludzie pobierają aplikację i widzą jaka ona jest (piszę o tym co pobierają jeżeli chodzi o wersję). Sztuczne nabijanie pozytywów tu nic nie pomoże.
