### ISSUE TITLE
Audit Request - audyt bezpieczeństwa i prywatności aplikacji

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#141]
**Is your feature request related to a problem? Please describe.**
for(var $i=[140](https://github.com/ProteGO-Safe/specs/issues/140); $i>=[80](https://github.com/ProteGO-Safe/specs/issues/80); $i--) 
  browse("https\://github.com/ProteGO-Safe/specs/issues/"+$i); 

**Describe the solution you'd like**
Aplikacja przejdzie audyt bezpieczeństwa i prywatności przeprowadzony przez odpowiednich **niezależnych** ekspertów, aplikacja zostanie podpisana cyfrowo oraz zostanie podany jej SHA-256 publicznie, aby umożliwić sprawdzenie użytkownikowi, czy korzysta z tego samego rozwiązania. 

Audytorzy sprawdzą też, czy i jakie dane (i jakiej klasy dane) są przesyłane do ewentualnych serwerów. 

SHA-256 znajdzie się również w treści przeprowadzonych audytów. 

Audytorzy wraz z prawnikami sprawdzą również zapisy licencji czy jest zgodna z wynikami audytu. Prawnik wystawi wytyczne odnośnie poprawy tekstu licencji. Prawnik sprawdzi również, jakie uprawnienia do uzyskania danych osobowych (na podstawie IP) ma Ministerstwo Cyfryzacji oraz inni właściciele serwerów i uwzględni to w opinii współpracując z ekspertem od prywatności. 

**Describe alternatives you've considered**
Jeżeli aplikacja ma być bezpieczna i ma zapewniać prywatność nie obędzie się bez audytu. Opcją jest jedynie jej zakończenie lub brak zaufania do aplikacji 

**Additional context**

**Comment by Tarvald** [comment]
@SeraMoon 
Hej,
Dzięki za informacje.
Jak skończycie chętnie dowiemy się co tam w trawie piszczy.

30 marca bieżącego roku kontaktowaliśmy się z niebezpieczynikiem w celu społecznego audytu ale niestety nam odmówiono. Nie dawno także znów próbowaliśmy się z nimi skontaktować ale niestety brak odpowiedzi ;(

Obecnie prowadzone są prace z firma Securitum w zakresie data privacy i data security.
Prowadzone są także rozmowy z firmą LogicalTrust.

Jeżeli ty lub my będziemy mieli jakieś wnioski oraz raporty na pewno dajmy o tym znać społeczności!

Pozdrawiamy i dziękujemy za pomoc

**Comment by SeraMoon** [comment]
@potiuk czy to, że się rzekomo kontaktowali (a Niebezpiecznik nie przeprowadza audytów za darmo) to oznacza, że wątek ten można zanknąć? @potiuk Co powinnam w tej sytuacji zrobić? 

Przecież nie dostałam tu wyników audytu.

**Comment by SeraMoon** [comment]
"Closed" i jednocześnie "0 of 7 tasks complete". Super.

**Comment by SeraMoon** [comment]
"Closed" i jednocześnie "0 of 7 tasks complete". Super.

**Comment by mimi89999** [comment]
Czy próbowaliście się też kontaktować z organizacjami lub firmami, które są znane z audytowania projektów OSS, np https://radicallyopensecurity.com/, który audytował ich kilka: https://radicallyopensecurity.com/portfolio.htm?

**Comment by Tarvald** [comment]
Wątek ponownie otwarty do merytorycznej dyskusji zgodnej z #147 :)

**Comment by pfk-beta** [comment]
To kto jest audytorem?

**Comment by jasisz** [comment]
Czy audyt zawiera w sobie ocenę skutków dla ochrony danych (Data Protection Impact Assessment - DPIA)?

**Comment by kolmir** [comment]
> 
> 
> To kto jest audytorem?

W #147 w punkcie C są podane szczegóły. Niestety nie ma tam NGO jak np. EFF czy tej org od audytów OSS wspomnianej powyżej.
Jest tylko wspomniane, ze odpowiadają na pytania Panoptykon - szczegółów na razie brak.

**Comment by kolmir** [comment]
Tu mamy uwagi EFF co do samego namierzania bliskości przez BT w kontekście API A+G https://www.eff.org/deeplinks/2020/04/apple-and-googles-covid-19-exposure-notification-api-questions-and-answers - warto się zapoznać.

**Comment by pingwinwzakiecie** [comment]
@SeraMoon To był ten audyt czy go nie było?

**Comment by jasisz** [comment]
Podbijam - aplikacja już wyszła, a nie mamy nawet DPIA.

**Comment by MateuszRomanow** [comment]
Informacyjnie - DPIA jest na stronie gov.pl, ale nie wiem od kiedy dokładnie https://www.gov.pl/web/protegosafe/dokumenty -> https://www.gov.pl/attachment/748bd66d-2345-4644-927b-299227ae74a3

**Comment by jasisz** [comment]
@MateuszRomanow To DPIA to jakiś zlepek starej i nwoej wersji...

W jednym miejscu czytamy o Exposure Notification od Google i Apple, żeby w innym przeczytać np. że "Serwer nadający anonimowe identyfikatory oraz serwer przesyłający klucze diagnostyczne nie są ze sobą połączone", albo "Serwer ProteGO Safe (Backend) nie umożliwia identyfikacji użytkownika, ani tym bardziej przechowywania lub połączenia (porównania) kluczy dziennych z kluczami diagnostycznymi. Klucze diagnostyczne są przechowywane na serwerze ProteGO Safe przez okres retencji wynoszący 14 dni w postaci zaszyfrowanej."

Takich kwiatków jest więcej.

**Comment by jasisz** [comment]
Do punktu `Użytkownik otrzymuje fałszywy komunikat, że został narażony na zarażenie COVID-19` dodać trzeba wielokrotnie tu wałkowany scenariusz, w którym klucz nie jest tylko nadawany na większą odległość, ale np. klucze z izby przyjęć szpitala zakaźnego są live nadawane w metrze. Taki atak do powodzenia nie wymaga wcale tego:

>  Aby zakończyć atak, osoba atakująca musi upewnić się, że spotkania między jej urządzeniem a innymi urządzeniami są oznaczone jako spotkania kwalifikujące się do wysłania komunikatu o spotkaniu z osobą chorą na COVID-19.

**Comment by tomekziel** [comment]
> Informacyjnie - DPIA jest na stronie gov.pl, ale nie wiem od kiedy dokładnie

@MateuszRomanow a co z publikacją wyników testów bezpieczeństwa? Kto je w ogóle zamawiał - Ministerstwo Cyfryzacji, inny organ państwowy, TYTANI24 czy jeszcze ktoś inny?

**Comment by potiuk** [comment]
Tak. Czekamy na wyniki bo na razie są tylko deklaracje. A z rozmów z potencjalnymi aydytujacymi wynika ze jeszcze nawet nie ma zakresu tych audytów. Z resztą przy aplikacji offline PWA to może lepiej zrobić to po tym jak już będzie to zrobione. Bo inaczej to trochę strata pieniedzy i czasu podatników. 

Ale w DPIAjest dla odmiany napisane że audyty były .. warto by upublicznić co tam jest.

**Comment by jasisz** [comment]
@potiuk Sekurak pisał na fejsie (w komentarzach do https://www.facebook.com/sekurak/posts/4490216434337816 ) że 

> my też w pewien sposób atakujemy tę aplikację - trzymajmy kciuki żeby była zgoda na publikację raportu

Czyli jakiś raport zrobili (?)

**Comment by potiuk** [comment]
Poczekamy zobaczymy. W. DPIA piszą o już zdaje się o przeprowadzonych audytach. Chętnie obejrzę

**Comment by potiuk** [comment]
SOA#1 U mnie działa :). DPIA pobierałem. Więc chyba nie to. 

@jasisz Prawdopodobnie zupgradowałeś Mac-a i masz ustawienie które priorytetuje IPV6:

https://stackoverflow.com/questions/48987512/ssl-connect-ssl-error-syscall-in-connection-to-github-com443

A z tego by wynikało że gov.pl jeszcze nad swoją konfiguracją IPV6 musi popracować - bo mają już adres IPV6 ale go nie obsługują.  W linku ze SO masz "rozwiązanie". Ciekaw jestem, czy to to.

**Comment by SeraMoon** [comment]
@jasisz jeżeli Ci nie działa i zgubiłeś ten dokument po drodze - użyj Tor Browsera - działa. 

Rozwiąże też SOA#1 nawet gdyby faktycznie zablokowano Cię.

**Comment by Tarvald** [comment]
Audyty dostępne 

#223

**Comment by SeraMoon** [comment]
@Tarvald temat pozostaje otwarty bowiem nie widzę tam audytu prywatności. Dla zaufania społecznego - najważniejszego. Gdybyście zrobili audyt prywatności, nie wynikłby problem #215. Na 100% zostałoby to znalezione.

**Comment by kamilgthecoders** [comment]
Raport prywatności: 
https://www.gov.pl/attachment/c0af6e36-96bf-4640-838a-cf08348f7acc

Temat zamykam
