### ISSUE TITLE
Dostęp do treści umowy NDA podpisanej przez autorów projektu z A&G

### ISSUE THREAD

**Issue by tomekziel** [ProteGO-Safe/specs#145]
Proszę o udostępnienie treści umowy o zachowaniu poufności, którą przedstawiciele Ministerstwa Cyfryzacji i/lub wykonawcy aplikacji ProteGO Safe podpisali w ramach konsultacji z Google/Apple w sprawie wdrożenia protokołu Exposure Notification (aka Contact Tracing) w aplikacji.

Prośbę uzasadniam troską o przejrzystość projektu, którego kluczowym elementem ma być Exposure Notification. Chcę poznać ograniczenia, jakim poddano swobodę działań i wypowiedzi osób odpowiedzialnych za rozwój projektu.

Odpowiedni wniosek o informację publiczną został już przeze mnie wysłany do MC, ale ten proces trwa tygodnie. Mi zależy na jak najszybszym poznaniu okoliczności, w jakich rozwijany jest projekt.

**Comment by limakzi** [comment]
Dlaczego Państwa odpowiedź jak również komentarze mój oraz @tomekziel zostały skasowane?

Czy uważają Państwo ze są to standardy prowadzenia projektu w sposób otwarty i transparentny?

**Comment by limakzi** [comment]
Popieramy wniosek Pana @tomekziel. 

Kamil Zabielski
sysdogs.com

**Comment by SeraMoon** [comment]
Podnoszę temat - kiedy doczekamy się na treść zapisów umowy NDA? Czy jest ona tyle czasu teraz edytowana dla nas tak abyśmy nie mieli zastrzeżeń, mimo, że treść rzeczywista może być inna? 

Tyle czasu trwa zeskanowanie umowy i zamazanie danych osób, które nie są osobami publicznymi? 

#189 #147

### Minął już prawie miesiąc!

**Comment by Tarvald** [comment]
Wracam z przykrą wiadomością, ale nie otrzymaliśmy zgody na publikację treści NDA ani ze strony Google ani ze strony Apple.

**Comment by Tarvald** [comment]
Wracam z (przykrą) wiadomością, na którą nie mamy wpływu, ale nie otrzymaliśmy zgody na publikację treści NDA ani ze strony Google ani ze strony Apple. Jednocześnie przekazaliśmy sugestię do Ministrestwa Cyfryzacji żeby w piśmie do G i A przekazało, że community w PL prosi o upublicznienie tych dokumentów

**Comment by SeraMoon** [comment]
> 
> 
> Wracam z (przykrą) wiadomością, na którą nie mamy wpływu, ale nie otrzymaliśmy zgody na publikację treści NDA ani ze strony Google ani ze strony Apple. Jednocześnie przekazaliśmy sugestię do Ministrestwa Cyfryzacji żeby w piśmie do G i A przekazało, że community w PL prosi o upublicznienie tych dokumentów

Żyjemy w Polsce. Rządowe dokumenty bez rangi tajemnicy wojskowej powinny być w Polsce jawne. Jeżeli doszło do podpisania umowy przez Ministerstwo Cyfryzacji (lub inny organ państwowy), to właśnie ten organ mimo braku zgody - **musi udostępnić** ten dokument, jako że nie został on wcześniej oficjalnie zdefiniowany jako tajny. 

Czy dobrze rozumiem, że w tym przypadku dochodzi do sojuszu polskiego Z"łego Ministerstwa" z zagranicznymi poza-EOG i poza-EU firmami? 

@tomekziel  postaraj się, jako, że Ty złożyłeś ten wniosek, gdzie Ministerstwo nie odmówiło ze względu na tajemnicę ani skomplikowaną sprawę w terminie 15 dni, skierować tą sprawę do WSA. Jeżeli miałby ktoś inny z nas to robić musi czekać 15 dni i niewykluczone, że w powyższej "grze w grę" będzie musiał przejść przez pola 2-4, które znacznie utrudnią czasowo sprawę. 

Zapraszam jednocześnie, aby inni (+Panoptykon), którzy wspierali (+!) Tomka Ziela - złożyli pozew zbiorowy (o ile kpa przewiduje to).

**Comment by tomekziel** [comment]
> Wracam z (przykrą) wiadomością, na którą nie mamy wpływu, ale nie otrzymaliśmy zgody na publikację treści NDA ani ze strony Google ani ze strony Apple.

Wyborne, milordzie. NDA w załączeniu, ponieważ ja nie muszę nikogo pytać.  [Umowa - Development NDA - załącznik do wniosku.pdf](https://github.com/ProteGO-Safe/specs/files/4737900/Umowa.-.Development.NDA.-.zalacznik.do.wniosku.pdf)

Mam dwa pytania:
1. Czy do tego były jakieś załączniki, których nie dostałem?
2. Czy jakiś polski urzędnik z MC podpisał umowę, w której poddaje się jursydykcji stanu Kalifornia? Czy MC w takiej sytuacji dostarczy mu pomoc prawną, zaleci unikanie USA czy też puści sprawy na żywioł?

**Comment by tomekziel** [comment]
> pozew zbiorowy (o ile kpa przewiduje to)

W KPA są skargi, nie pozwy. Przyjdzie czas i na to.

**Comment by SeraMoon** [comment]
@tomekziel leci na Archive.fo :)

**Comment by RMalczynski** [comment]
@SeraMoon proszę, daruj sobie takie propagandowe komentarze. @Tarvald istnieje szansa na moderowanie takich wpisów?

**Comment by SeraMoon** [comment]
Wrzucam informacje o dokumencie NDA pobrane z metatagów: 
Author: Google Employee
Title: NON-DISCLOSURE AGREEMENT
Creator: Microsoft Word 2013
Creation Date: 2020-05-18 11:56:16+02:00
Data modyfikacji: 2020-05-18 11:56:16+02:00

### Zastanawiająca jest więc data powstania dokumentu... 18 maj, podczas gdy temat jest z 4 maja.

**Comment by Tarvald** [comment]
@RMalczynski 
Masz rację, ten post jest obraźliwy i mocno polityczny 

@tomekziel 
Napewno, odpowiemy na twoje pytania. 
Stay tuned

**Comment by tomekziel** [comment]
> @tomekziel potrafisz to wyjaśnić?

18 maja dostałem ten dokument z Ministerstwa Cyfryzacji. 

> Masz rację, ten post jest obraźliwy i mocno polityczny

Robicie teraz w polityce, gratulacje. Powołajcie rzecznika prasowego i niech on to przemilczy w Waszym imieniu.

**Comment by Tarvald** [comment]
> > @tomekziel potrafisz to wyjaśnić?
> 
> 18 maja dostałem ten dokument z Ministerstwa Cyfryzacji.
> 
> > Masz rację, ten post jest obraźliwy i mocno polityczny
> 
> Robicie teraz w polityce, gratulacje. Powołajcie rzecznika prasowego i niech on to przemilczy w Waszym imieniu.

Panie @tomekziel to jest nadal forum dotyczące wytwarzania oprogramowania. 
Takie posty też nie są zgodne z naszym CoC.

**Comment by tomekziel** [comment]
> Takie posty też nie są zgodne z naszym CoC.
> 
> https://github.com/ProteGO-Safe/specs/wiki/Code-of-conduct

My zaś rozmawiamy po polsku o oprogramowaniu zamówionym przez rząd Rzeczpospolitej Polskiej, bądź więc łaskaw przetłumaczyć tego "CoCa" na język polski, dziękuję.

**Comment by Tarvald** [comment]
@tomekziel 
Proszę bardzo 
https://www.google.pl/search?sxsrf=ALeKk01tKuIAnifSMEvT1V4RKXqS1B0x3w%3A1591391481523&source=hp&ei=-bTaXtm9HeGcjLsP_sKe4AY&q=code+of+conduct+po+polsku&oq=code+of+co&gs_lcp=ChFtb2JpbGUtZ3dzLXdpei1ocBABGAEyBQgAEMsBMgUIABDLATICCAAyBQgAEMsBMgIIADIFCAAQywEyBQgAEMsBMgIIADoHCCMQ6gIQJzoECCMQJzoFCAAQkQI6BQguEJECOgIILjoICC4QkQIQkwI6BQguEMsBOggILhDLARCTAlCYCVjPFmCsH2gAcAB4AIABnwGIAbYLkgEEMC4xMZgBAKABAbABDw&sclient=mobile-gws-wiz-hp

Rozmawiajmy kulturalnie, jesteśmy skorzy na współpracę.

**Comment by Tarvald** [comment]
> > Takie posty też nie są zgodne z naszym CoC.
> > https://github.com/ProteGO-Safe/specs/wiki/Code-of-conduct
> 
> My zaś rozmawiamy po polsku o oprogramowaniu zamówionym przez rząd Rzeczpospolitej Polskiej, bądź więc łaskaw przetłumaczyć tego "CoCa" na język polski, dziękuję.

https://github.com/ProteGO-Safe/specs/blob/master/.github/CODE_OF_CONDUCT.md

**Comment by SeraMoon** [comment]
> Panie @tomekziel to jest nadal forum dotyczące wytwarzania oprogramowania.
Takie posty też nie są zgodne z naszym CoC.

> https://github.com/ProteGO-Safe/specs/wiki/Code-of-conduct

A gdzie jest #143 ? "Spróbujemy w tym tygodniu" a temat nadal otwarty...

**Comment by SeraMoon** [comment]
Przykra jest ta gra w informację publiczną - kolejny temat po #128 gdzie nie dostajemy odpowiedzi od Ministerstwa. 😾😾😾😾😾
