### ISSUE TITLE
Aplikacja nadal szpieguje użytkowników

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#146]
**Is your feature request related to a problem? Please describe.**
Cytuję użytkowników. 

- [ ]  Aplikacja nie działa, bezużyteczna!! "nie można zweryfikować urządzenia". Kolejny gniot ministerstwa cyfryzacji za publiczne pieniądze Re: Niby co ma przeszkadzać zrootowane urządzenie do aplikacji ProteGO, które w swoim założeniu ma szukać i parować inne urządzenia? Dodatkowo, dlaczego miałbym zrez…

- [ ]  Gdy wifi w tel wyłączone wyskakuje komunikat o braku połączenia z internetem (mimo dostępnej transmisji danych od operatora). Posiadam VPN. Wersja 3.0.3 po aktualizacji błąd dalej występuje.

- [ ]  Apka po aktualizacji nadal ma problem z VPN adguard. Po rozłączeniu VPN problem znika. Także ocena zostaje |Edit Nauczcie się programować. Bo jak narazie to apka ma problem że mam vpn na telefonie i nie działa. A z VPN nie mam zamiaru rezygnować.

**Describe the solution you'd like**
Aplikacja powinna pozwalać łączyć się przez Tor oraz przez VPN. Obecnie często odmawia tego - sprawdzone własnoręcznie - przestaje ładować ankiety po zmianie IP. Takie działanie można uznać za inwigilację, szczególnie, gdy Ministerstwo Cyfryzacji MOŻE wnosić o dane osobowe z telekomów powiązane z IP osoby, która korzysta, na podstawie ustawy o Policji oraz na podstawie ustawy o COVID-19 - od firmy infermedica.pl na podstawie poleceń, sanepidu, które nie wymagają uzasadnienia. 

**Describe alternatives you've considered**
Ankiety wypełniane bez potrzeby kontaktu z backendem. W sieci można znaleźć dokumenty ECDC oraz WHO - jak wykonać triage dotyczący stanu zdrowia. 

**Additional context**
#143, #142, #141 #137

**Comment by Tarvald** [comment]
Ze wzgledu na bezpoosrednie oskarzenie instytucji panstwowej - to jest forum opinio-tworcze i nie mozemy pozwalac na manifesty w takim stylu.

CoC excerpt:
Przykładowe zachowania, które są nieakceptowalne:

Używanie języka lub obrazów o podtekście seksualnym,

Ataki osobiste,

Trollowanie, obraźliwe bądź urągające komentarze,

Nękanie, zarówno na forum publicznym, jak i prywatnie,

Publikowanie danych osobistych innych osób — takich jak adres fizyczny, czy elektroniczny — bez ich wyraźnej zgody,

Inne zachowania nieetyczne lub nieprofesjonalne.

**Comment by SeraMoon** [comment]
Wnoszę odwołanie od decyzji o zamknięciu wątku.

**Comment by Tarvald** [comment]
@SeraMoon powyżej udowodniłaś dwie rzeczy:

1. Nie jesteś na bieżąco, bo aplikacja działa na zrootowanych telefonach. Sam posiadam zainstalowanego lineageOs
2. Aplikacja nie działa z VPN. Ale to nie znaczy że szpieguje, to jest błąd który zostanie prawdobonie naprawiony.

Ucinam temat, bo jest nie aktualny (rooty), obraźliwy (oskarżenie o szpiegostwo) oraz nie prawdziwy (bug jako element inwigilacji)

**Comment by SeraMoon** [comment]
Cytuję komentarze z ostatnich dni. Temat zrootowanych urządzeń poruszałam, a użytkownicy dalej się na to żalą. Prawdziwość ocenił Niebezpiecznik, oceni też Panoptykon.

**Comment by tajchert** [comment]
> to jest błąd który zostanie prawdobonie naprawiony.

Sprawdziłem i nie ma takiego zgłoszenia otwartego, więc powyższe zgłoszenie @SeraMoon  jest zasadne:
![image](https://user-images.githubusercontent.com/2962633/80976454-c8acf880-8e23-11ea-8759-594955ca7f49.png)

**Comment by Tarvald** [comment]
@tajchert 
Bug jest zgłoszony w wewnętrznym systemie.
Prosze się nie martwić. :)

**Comment by viroos** [comment]
@Tarvald nie rozumiem, czemu ten bug nie może być tutaj.

Czasami zdarza się, że dyskusje prowadzi się w wewnętrzny systemie, ale poza podaniem uzasadnienia, dobrą praktyką jest podanie numeru zgłoszenia z wewnętrznego systemu.

Pomaga to:
a) zapewnić transparentność,
b) odnieść się do zgłoszenia w przyszłości,

Proszę o podanie numeru zgłoszenia z wewnętrznego systemu.

**Comment by Tarvald** [comment]
@viroos
Będziemy ulepszać ten proces z czasem. 
Prowadzone są prace porządkowe na GH. 

Więcej informacji wkrótce.

**Comment by SeraMoon** [comment]
> 
> 
> @tajchert
> Bug jest zgłoszony w wewnętrznym systemie.

Winno być 

Bóg się zgłosił do wewnętrznego systemu. Powyższe tylko świadczy o tym, że nie ma pracy transparentnej i prawda jest ewidentnie ukrywana. To jest otwarte oprogramowanie (niestety tylko w specyfikacji, bo kodu wszystkich - intermedica - serwerów nie znamy, więc wszystkie issue powinny być otwarte na widoku i skoro niezafixowane to otwarte. 

Odejście od tego nosi miano stanu klęski transparentności (Projekt Ciężkiej Porażki).

**Comment by mimi89999** [comment]
Osobiście uważam, że _Aplikacja nadal szpieguje użytkowników_ jest bardzo złym tytułem chociażby dlatego, że jest zbyt ogólny.

**Comment by SeraMoon** [comment]
@mimi89999 proszę - zmienione. Co nie zmienia stanu rzeczy, że aplikacja szukając czy telefon jest rootowany de facto szpieguje użytkownika sprawdzając czego używa i skąd się łączy! 

Zwracam uwagę ponadto na równicę "naprawiane" i "naprawione". Pierwsze wskazuje na niedokonanie / nieukończenie operacji. Niedokończonych issue się nie zamyka.

**Comment by Tarvald** [comment]
@SeraMoon 
Aplikacja nie blokuje zrootowanych telefonów. Sam taki posiadam.
Jeżeli na twojej platformie nie działa root to prosimy o założenie tematu w repo android lub ios

**Comment by miklobit** [comment]
VPN'y sa nadal blokowane a to też było treścią zgłoszenia więc nie powinno być zamykane. Ja rozumiem, że to niejest kwestia aplikacji tylko blokowania przez CloudFlare (i wtedy aplikacja nie może się dobić do serwera) ale fakt jest faktem : VPN'y są nadal blokowane (test wczoraj przy użyciu AiVPN )

**Comment by Tarvald** [comment]
@miklobit 
Załóż nowy wątek w /ios albo /android, jezeli możesz. 

Dzięki :)

**Comment by pingwinwzakiecie** [comment]
> @tajchert
> Bug jest zgłoszony w wewnętrznym systemie.

Myślałem że ProteGo to oprogramowanie Open Source.

**Comment by pingwinwzakiecie** [comment]
Mylę się?
