### ISSUE TITLE
Wdrożenie i udokumentowanie rozwiązań dotyczących prywatności

### ISSUE THREAD

**Issue by Tarvald** [ProteGO-Safe/specs#148]
W odpowiedzi na głos społeczności #142 otwieramy wątek zbiorczy issues, co do których społeczność ma wątpliwości. Więcej szczegółów w samych wątkach.

Wątki, które zostaną otwarte:
#141 - Audit Request
#140 - Ratingi aplikacji lecą na łeb na szyję

Jednocześnie w wątku #140 zostaną ukryte odpowiedzi niedotyczące samego ratingu oraz te, które są niezgodne z wymaganiami projektowym pod #147.

Ukryte odpowiedzi każdy będzie mógł rozwinąć i zobaczyć czego dotyczyły.

Wątki nie aktualne, gdyż implementacja QR została porzucona:
#124 - Planowany sposób użycia kódów QR łamie wytyczne EDPB
#132 - Implementacja protokołu Google + Apple zamiast własnego rozwiązania BT i QR Code

Wątki które nie są zgodne z celami projektowymi dostępnymi pod #147:
#139 - Natychmiastowe wyłączenie wysyłania danych z ankiet do api.safesafe.app
#116 - Naruszenie prywatności - Łączenie adresu IP osób zdrowych z ich TempID w obecnej implementacji (OpenTrace) tu czekamy aż obecne rozwiązanie zostanie usunięte
#110 - Możliwe szpiegowanie przez rząd - czekamy na wyjaśnienia, dokumenty, plan zarządzania jakością, niezależne opinie etc.

Zamknięcie wątków zostało spowodowane pracami porządkowymi na GH o których mowa była tutaj:
https://github.com/ProteGO-Safe/specs/issues/136#issuecomment-623113661

Prace porządkowe nadal trwają, staramy się doprowadzić GH do porządku i wyczyścić go z nie aktualnych informacji.

Zachęcamy do merytorycznej dyskusji zgodnej z #147.

**Comment by kolmir** [comment]
Hej, gwoli ścisłości, to w #147 opisane są cele projektu (AKA uzasadnienie biznesowe), a nie założenia.

Które powinny wyglądać np. tak:
1. Zakładamy, że BT adekwatnie wykryje kontakt bezpośredni i odróżni go od bliskości przez ścianę albo w samochodzie obok na światłach
2. Zakładamy, że API A+G będzie dostępne od XX.XX.XX
3. Zakładamy, że IP użytkownika nie będzie przekazane organom rządowym

Itd, itp. Można by wtedy zweryfikować takie założenia w czasie audytu.
Więcej o https://dzone.com/articles/assumptions-risks-and-dependencies-in-user-stories

Kolejny punkt do uwzględnienia w audycie, tu są użyteczne zalecenia od NGO a propos prywatności oraz sensowne rozważania nad użytecznością apki tego typu - godne do wzięcia pod uwagę https://www.accessnow.org/privacy-and-public-health-the-dos-and-donts-for-covid-19-contact-tracing-apps/

**Comment by MateuszRomanow** [comment]
> * Zakładamy, że BT adekwatnie wykryje kontakt bezpośredni i odróżni go od bliskości przez ścianę albo w samochodzie obok na światłach
> * Zakładamy, że API A+G będzie dostępne od XX.XX.XX
> * Zakładamy, że IP użytkownika nie będzie przekazane organom rządowym

Pozwolę sobie skorzystać z Twoich rekomendacji i dodać je do #147 . Rozszerzenie ich o pozostałe założenia, wymaga ich zweryfikowania w obliczu integracji z G+A. Będziemy to robić day by day.
