### ISSUE TITLE
SCREEN'y z API A+G  ?!

### ISSUE THREAD

**Issue by Dr-Kownacki** [ProteGO-Safe/specs#150]
Zobaczcie, takie coś dzisiaj znalazłem, wrzucam tu dla referencji, może się przyda w dyskusji coś "realnego" bardziej już - ale nie wiem czy może to od dawna lata po sieci i to żadna nowość ? :-)

Jakieś FAQ "nowe" (z maja) ? tutaj:

https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ExposureNotification-FAQv1.0.pdf

Pozdrawiam

![screen-iOS](https://user-images.githubusercontent.com/63192074/81017667-48a68300-8e63-11ea-8fa2-743df67f21dd.jpg)

![screen-Android](https://user-images.githubusercontent.com/63192074/81017684-50662780-8e63-11ea-87e4-c065210bd778.jpg)

**Comment by Tarvald** [comment]
@Dr-Kownacki ja coś tam widzialem, ale fajnie że wrzuciłeś te screeny. Chociaż sam nie wiem czym tak naprawdę one sa. 
Chociaż wygląda jak customowa aplikacja, możliwe że wykorzystująca Google Api

**Comment by Dr-Kownacki** [comment]
Jeszcze taki:

![exposure-notification-setting](https://user-images.githubusercontent.com/63192074/81018573-185fe400-8e65-11ea-932d-09a4589fcb7e.jpg)

**Comment by Tarvald** [comment]
@Dr-Kownacki super to wygląda. Do tego napisane ile razy został wykryty kontakt :)

**Comment by potiuk** [comment]
Tak @Dr-Kownacki - > wczoraj Apple i Google ogłosili aktualizację (łącznie z tym, że zabronili aplikacjom korzystających z ich API używania lokalizacji/BT bezpośrednio). 
Pisał już o tym wczoraj @tomekziel https://github.com/ProteGO-Safe/specs/issues/129#issuecomment-623630235 .

A wersji androidowej jest nawet przykładowa aplikacja (https://github.com/ProteGO-Safe/specs/issues/129#issuecomment-623639394) więc jeszcze lepiej niż screeny,

**Comment by mpodlasin** [comment]
@potiuk Pytałem o już trochę to na LinkedIn, ale wciąż nie rozumiem jaka jest ostateczna odpowiedź.

Czy dobrze rozumiem, że nie będzie potrzeby instalacji jakiejkolwiek aplikacji, żeby otrzymać powiadomienie o kontakcie z osobą chorą? Po prostu update systemu do wersji z contact tracingiem?

**Comment by jasisz** [comment]
Z tego co wiem:
- nie potrzeba będzie aplikacji, żeby rozsyłać swoje identyfikatory i zbierac identyfikatory innych, ale aplikacja jest potrzebna żeby dostać powiadomienie
- ma być jedna aplikacja na kraj (Apple sie ponoć uparło)

**Comment by potiuk** [comment]
> * nie potrzeba będzie aplikacji, żeby rozsyłać swoje identyfikatory i zbierac identyfikatory innych, 

Tak.

> ale aplikacja jest potrzebna żeby dostać powiadomienie

Nie. 

Do tego też aplikacja nie będzie potrzebna.  API na poziomie systemu operacyjnego będzie miało wystarczająco dużo informacji żeby dać użytkownikowi notyfikację. Z tego co wiem to plany są takie że notyfikacja będzie miała również link do instalacji aplikacji z danego regionu - tak żeby ją na przykład można było zainstalować i (jak w ProteGO) dokonać samooceny zdrowia. 

Ale tak naprawdę aplikacja będzie potrzebna tylko po to żeby - po podaniu kodu wygenerowanego przez "Health Authority" użytkownik poprosił API o wysłanie danych na serwer (Ministerstwa Cyfryzacji w naszym przypadku). To wszystko "per region" - patrz niżej.

> * ma być jedna aplikacja na kraj (Apple sie ponoć uparło)
Tak. Lub region w danym kraju jeśli kraj tak sobie życzy. I tak Apple się uparło. Rozmawiałem osibiście z jedną z wysoko postawionych osób z Developer Relations w Apple i powiedział że bardzo im na tym zależy, bo oni muszą tym potem zarządzić - zwłaszcza jak już to będzie w systemie operacyjnym. Trzeba wiedzieć skąd w danym regionie pobierać dane i musi to być jedno miejsce dla wszystkich. Ma to też znaczenie w przypadku notyfikacji powyżej oraz w przypadku w przyszłości "federated" contact tracing. W którym przemieszczamy się między regionamu (w każdym regionie trzeba pobierać dane z tego regionu właśnie za dni w których się w danym regionie było). To wszystko jest dużo łatwiejsze do ogarnięcia jak masz jedną apkę na region.

**Comment by jasisz** [comment]
@potiuk Dzięki, tym bardziej podbijam https://github.com/ProteGO-Safe/specs/issues/153

**Comment by lukasz-szyszkowski** [comment]
Dla przejrzystości, polecam najpierw to: https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf
A dla zainteresowanych jak to implementować to: 
https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure

**Comment by potiuk** [comment]
@lukasz-szyszkowski -> dzięki. Zaraz czytam jak zwykle z wypiekami na twarzy!

**Comment by lukasz-szyszkowski** [comment]
> @lukasz-szyszkowski -> dzięki. Zaraz czytam jak zwykle z wypiekami na twarzy!

Super, w razie wątpliwości w implementacji kodu postaram się pomóc. Można pytać.

**Comment by mpodlasin** [comment]
czyli czy można będzie robić tak, że:
* mam contact tracing na telefonie ale nie mam appki
* potem łapię "grypę" idę na badanie i - bum! - okazuje się, że mam koronawirusa
* no to instaluję aplikację na 5 minut, wysyłam to co tam ma wysłać, po czym od razu odinstalowywuję?

Strasznie dziwnie to brzmi, tak prawie nie jest potrzebna aplikacja, ale jednak jest potrzebna...

**Comment by Tarvald** [comment]
@mpodlasin 
No i dokładnie tak to będzie wyglądać.

Jeżeli jednak będziesz osobą która się będzie czuć zagrożona, będziesz mógł korzystać np. z modułu profilaktycznego i nie odinstalowywać aplikacji.
Po czym jeżeli w twoim otoczeniu zrobi się bezpiecznie, odinstalować, aby później zainstalować ją znów wobec narastającego zagrożenia :)

**Comment by Tarvald** [comment]
@mpodlasin
No i dokładnie tak to będzie wyglądać.

Jeżeli jednak będziesz osobą która się będzie czuć zagrożona, będziesz mógł korzystać np. z modułu profilaktycznego i nie odinstalowywać aplikacji.
Po czym jeżeli w twoim otoczeniu zrobi się bezpiecznie, odinstalować, aby później zainstalować ją znów wobec narastającego zagrożenia :)

**Comment by potiuk** [comment]
Przy czym tak to będzie wyglądać na wszystkich IPhone'ach i na wszystkich Androidach w których Google dogada się z producentem. żeby to zintegrowali ze swoimi zmianami i wypuścili aktualizację. Myślę że to dla nich będzie priorytet i że tego rodzaju aktualizacja jest prostsza niż inne (zupełnie nowa funkcjonalność) więc będzie szybciej niż zwykle i więcej telefonów będzie zaktualizowanych.

W telefonach bez aktualizacji systemu Exposure Notification będzie najprawdopodobniej wymagało aplikacji żeby EN działało. Ale tu mogą pewnie być trochę różne warianty tego co google w Play Services umieści i jak to będzie działało.

Swoją drogą to też bęðzie ciekawy test jeśli będą na ten temat statystyki - ile % jakich telefonów dostanie aktualizację.
