### ISSUE TITLE
FAQ: tekst odnosnie kasowania danych uzytkownika

### ISSUE THREAD

**Issue by henrydcase** [ProteGO-Safe/specs#152]
Z FAQ: 

> 10) Czy użytkownik może wyłączyć, skasować dane w każdej chwili?
> Tak. Aplikacja umożliwia usunięcie wszystkich danych do niej wprowadzonych.

Czy mozecie wyjasnic w jaki sposob usuwane sa dane historyczne? Powiedzmy, ze chcialbym usunac wszystkie dane dot. mojego ID - wlaczajac te ktore zostaly wygenerowane przez  aplikacje osoby ktora zarejestrowala moja obecnosc. Takie dane nie zostaly wygenerowane przez moj telefon, a jednak bezposrednio dot. mojej osoby.

Oczywistym jest iz kazda taka aplikacja z **centralnym** serwerem stwarza mozliowsc wytworzenia mapy ID osob ktore przebywaja/przebywaly w kontakcie. Kazde ID moze byc przypisane do telefonu wlasciciela. Wlasciciele telefonow sa  powiazani z kartami SIM... Oczywistym jest ze utrata prywatnosci moze nastapic i protokol implementowany przez ProteGO nie ma zadnych funkcji zeby temu zapobiec.

**Comment by pingwinwzakiecie** [comment]
Czy te dane lecą na jakieś serwery np. MZ?

No bo jeśli tak to dane trzeba też **usunąć z serwera**, ale z drugiej strony jeśli ma serwerze jest jakiś backend to może za jego pośrednictwem **dałoby się nawiązać połączenie z telefonem osoby która miała z tobą kontakt i wyczyścić tamte dane**? Chociaż im dłużej to piszę tym bardziej wydaje mi się to nierealne.


PS. Zaznaczam że choć trochę umiem z programowania to nigdy nie pracowałem nad niczym na poważnie i nie jestem zbyt w temacie.

**Comment by potiuk** [comment]
Komentarz:

* w rozwiązaniu G+A (które według zapewnień @MateuszRomanow  i Ministerstwa Cyfryzacji) będzie wdrożone w wersji 4.0 na serwer wysyłane są tylko DiagnosisKeys osób zdiagnozownych. Na tym polega zdecentralizany protokół Exposure Notification. Dane o tym kogo się widziało, nigdy nie opuszczają Twojego telefonu.

* Wszyscy użytkownicy pobierają te same dane. DiagnosisKeys natychmiast po (zautoryzowanym) wysłaniu stają się publicznie dostępne i  wszyscy je mogą pobrać (nawet osoby które nie używają aplikacji - niepotrzebna jest do pobierania żadna autoryzacja). Z tych danych nic nie można wywnioskować na temat kontaktów, lokalizacji etc. osoby zarażonej, wiadomoe jedynie że w tych konrektnych dniach, te konkretne Diagnosis Keys to były osoby zarażone.

Jedynie strona rządowa (potencjalnie - jeśli będą przechowywać połączenia PIN/osoba zarażona i przechowywać PIN podczas upload-u) może połączyć konkretne DiagnosisKeys z konkretnymi osobami (za pomać kodu PIN). Ale to w zasadzie nie ma sensu bo nic z tych danych nie daje więcej niż to co strona rzadowa już ma, a tylko zwiększa niepotrzebnie ryzyko że ktoś te połączenia wykradnie. Zakładam że nie będą tego robili.

Ewentualne "nadużycie" tych - publicznych - danych DiagnosisKeys z serwera jest bardzo mało prawdopodobne. Jedyny znany mi przypadek to tak zw. "Single encounter". To może spowodować że ktoś kto będzie aktywnie logował kto się znajduje dookoła (łącznie z notowaniem fiycznie kto jest w okolicy) , może powiązać konkretny DiagnosisKey z osobą - ale tylko w przypadkach w których nie ma innych użytkowników w pobliżu (ale to bardzo mało praktyczne i raczej mało przydatne IMHO, bo daje to tylko możliwość zidentyfikowania że dana osoba konkretnie jest zarażona, nie daje to dodatkowych informacji  na temat spotkań, czy lokalizacji danej osoby). Zwykły użytkownik aplikacji tego nie może zrobić - jedynie ktoś kto będzie celowo zbierał i przechowywał wszystkie dane za pomocą oddzielnego urządzenia (i dodatkowo musi być spełniony ten warunek "single encounter" - jeśli w zasięgu  urządzenia znajdzie się kilka osób z aplikacją będzie to trudne albo niemożliwe),

* Nie wiem, czy twórcy aplikacji przewidzieli możliwość skasowania tych danych - to pytanie do @MateuszRomanow . Ale w świetle tego, że dane te natychmiast po wysłaniu na serwer stają się publicznie dostępne, jest to bezcelowe, ktokolwiek mógłby napisać skrypt który te dane bedzie pobierał i zapisywał codziennie.

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.

Jeżeli ktoś ma coś przeciwko to niech da znać, lub założy wątek zgodny z obecnymi założeniami.
Mam nadzieje że rozproszony system oraz i tak publiczne klucze rozwiązują problem, nie potrzeby kasowania tych danych :)
