### ISSUE TITLE
Jak ma wyglądać przejście na rozwiązanie Google i Apple?

### ISSUE THREAD

**Issue by jasisz** [ProteGO-Safe/specs#153]
Aplikacja działa teraz w sposób, który nie jest kompatybilny z, jak to rozumiem, docelowym rozwiązaniem Google i Apple.

Rodzi to wiele niełatwych pytań:
1. Czy identyfikatory i spotkania używane teraz, przed wejściem nowego rozwiązania, będą jakoś używane później?
2. Jeżeli tak, to jak będa używane? Czy będzie na ich podstawie również stwierdzane zagrożenie? Nie widzę w rozwiązaniu G+A opcji "zasilenia" go starymi identyfikatorami (by design), więc czy alert o zarażeniu będzie przez jakiś czas kombinacją alertu ze starego scentralizowanego systemu i nowego zdecentralizowanego? Może to budzić duże wątpliwości, nie wiadomo też czy Google i Apple w ogóle pozwolą na coś takiego w aplikacji używającej ich API.
3. Co z problemami z adopcją? Ktoś może dalej nosić przy sobie starą wersję myśląc, że jest chroniony i rozgłaszać identyfikatory, które dawno nikogo już nie obchodzą.
4. Co z okresem przejściowym, w którym o zagrożeniu może decydować połączenie danych ze starego i nowego podejścia (np. miałem jedno spotkanie na starym rozwiązaniu i jedno na nowym, a dopiero łączna ich długość stanowi o niebezpieczeństwie)?

**Comment by potiuk** [comment]
Zgadzam się i tu podbiłbym #137 , Wydaje się że po przejściu na G+A dane obecnie zbierane są kompletnie nieużytecznie i lepiej je wyłączyć?

**Comment by jasisz** [comment]
Też mam wrażenie, że obecnie zbierane niestety są bezużyteczne. Nie widzę chyba żadnego pozytywu w tym, że rozwiązanie odpalono wcześniej.

Oczywiście nie mogę winić twórców o to, że nie mają szklanej kuli, która powiedziałaby kiedy będzie gotowe rozwiązanie G+A, ale to tylko pokazuje, że zdeployowanie takiego niekompletnego rozwiązania tylko "aby narazie zbierało spotkania" (a coś takiego było i proponowane na samym początku tego projektu, za poprzedniej ekipy), nie ma żadnego sensu.

Jakie jest teraz uzasadnienie działania aplikacji, skoro nie spełnia ona żadnej roli, bo nie jest zaimplementowana część odpowiadająca za faktyczne powiadomienie kogoś o możliwości zarażenia, a danych nie będzie się dało użyć potem?

**Comment by Dr-Kownacki** [comment]
Już wcześniej sygnalizowałem (m.in. #126 i więcej), ale może dobitniej tutaj zapytam - CO KONKRETNIE DZIAŁA ?  :-)  (w BLE oczywiście).

Czy jest jakiś opis konkretny już (m.in. **"na co się zgadza użytkownik włączając tą opcję - skanowanie/rozgłaszanie i co dalej z tym będzie/może być"**).

Ja tego nigdzie nie widziałem dotąd. Mam 3.0.3, chyba że jest nowsza wersja mówiąca o tym użytkownikowi ? (sprawdzę zaraz jeszcze, jeśli jest to z góry przepraszam :)  )

Ponieważ aplikacja nie ma żadnego (postulowanego przeze mnie wcześniej) "licznika", który "nabijałby nam" - liczbowo/eventami po prostu fakt że: 

**a) "rozgłosiliśmy się" - Y razy**

**b) "usłyszeliśmy kogoś"  - X razy**

To dla mnie jest zasadnicze pytanie czy w końcu coś działa, czy nie (i CO?) bo ja już się w tym totalnie pogubiłem (jako lamer), za co tradycyjnie przepraszam prosząc zawodowców jak zwykle o oświecenie mnie  ;-))))

Dzięki z góry ! :-)

**Comment by jasisz** [comment]
Znalazłem stosowny paragraf w https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf
```
You and Your Contact Tracing App may not combine, correlate, link, use or otherwise associate any user data collectedin another App through the useof the Apple Software (e.g.,location data accessed through the location-based APIs may not be combined with user data from a Contact Tracing App, even if You own or operate the corresponding App)with user data collected or otherwise obtained in YourContact Tracing App, unless otherwise agreed by Apple and withuser consent(e.g., for purposes of moving from an existing COVID-19 App to a Contact Tracing App).
```

**Comment by Dr-Kownacki** [comment]
A co z CZASEM (momentem ekspozycji), bo o ile mogłem zrozumieć to zgodnie z API G+A  czas jest logowany i finalnie przez to "centralnie" przechowywany po wygraniu "zakażonych kluczy" ?

Pisałem o tym w innym wątku (zaraz znajdę) na przykładzie przysłowiowych "Vadima, Ludmiły i Nataszy". Zaraz odnajdę i wstawię, chodzi o to że jak Vadima na/(za)raził "skutecznie"  Nataszę to ich klucze wzajemnie narobią "match" czasowy jakby ktoś się zawziął (Wielki Brat) i z puli "zakażonych kluczy"/pacjentów na serwerze (przypominam że one tam już nie są anonimowe) da się potencjalnie ciekawe informacje zrobić.

Czy Waszym zdaniem "czas trafienia wzajemnego" przy dwóch osobach hospitalizowanych/rozpoznanych w ciągu np. 5 dni (obie osoby wgrywają klucze swoje bo obie są chore) nie pozwoli "dopasować" Vadima do Ludmiły ?

**Comment by jasisz** [comment]
Ministerstwo Cyfryzacji odpowiedziało na to pytanie, ale dopiero w komentarzach na Play Store.
<img width="657" alt="Zrzut ekranu 2020-06-9 o 20 19 30" src="https://user-images.githubusercontent.com/939644/84185092-0255cc80-aa7e-11ea-8eb1-fe283fac3a7f.png">
Szkoda, że tutaj nie doczekalismy się odpowiedzi przez miesiąc.

**Comment by Tarvald** [comment]
@jasisz 
Przykro mi, faktycznie mogło to być tutaj jasno napisane.
Jednak teraz wszystko się wyjasniło. Możemy zamknąć ten wątek?

Dzięki.
