### ISSUE TITLE
Aplikacja nie przejdzie audytu Google

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#154]
**Is your feature request related to a problem? Please describe.**
#129 #141 

**Describe the solution you'd like**
Wysyłanie danych do firmy Infermedici trzeba ukrócić, inaczej zgodnie z [zapowiedzią Panoptykonu](https://panoptykon.org/protego-safe-ryzyka), który wylicza kolejne wpadki, aplikacja nie przejdzie audytu zgodności z założeniami Google przeciw śledzeniu użytkowników. 
Aplikacja korzystająca z tego protokołu może jedynie przechowywać dane lokalnie i nie może ich nigdzie wysyłać. 

**Describe alternatives you've considered**
Aplikacja poza sklepem Google i będzie się usypiać wraz z zaciemnieniem ekranu smartfonu przestając korzystać z api G+A. Tym samym nie osiągnie też wymaganego zaufania społecznego. 

**Additional context**
\-

**Comment by Tarvald** [comment]
@SeraMoon 
Mogę Ci zagwarantować że aplikacje przejdzie audyt Google.
Takim temat wprowadzasz opinie publiczną w błąd.

Proponuje zmienić nazwę tematu na:
"Aplikacja w obecnej formie może nie przejść audytu Google"

**Comment by sub-zero-pl** [comment]
To po co audyt? Nie wystarczy ludziom gwarancja Tarvalda? ;)

**Comment by Tarvald** [comment]
@sub-zero-pl 
Audyty są potrzebne.
Pewność z jaką to napisałem wynika z #147

To kto jest czego gwarantem nie jest przedmiotem tego wątku.

**Comment by MateuszRomanow** [comment]
Fakty:
Aplikacja przeszła audyt Google. 
Aplikacja jest cały czas audytowana przez Google (każda wersja). 
Aplikacja jest konsultowana bezpośrednio z Google w obszarze integracji z z ENAPI.
Aplikacja jest jedyną oficjalną rządową aplikacją, która może korzystać z ENAPI co zostało zgłoszone na prośbę G+A. 

Tytuł twierdzący, jak i (potencjalnie) pytający jest nieprawdą. Treść jest opinią. Czy naprawdę możemy  poświęcać czas na merytoryczne dyskusje a nie ucinanie i prostowanie takich informacji? Przecież to czas nas wszystkich, który możemy poświęcać na rzeczy efektywne, lub bezproduktywne. Ten czas nie jest z gumy. Prośba do autora o zamknięcie wątku.

**Comment by jasisz** [comment]
Approve aplikacji w sklepie to jeszcze nie audyt. Natomiast pojawiały się informacje, że Google zapowiedziało, że będzie oferować audyt aplikacjom korzystającym z ENAPI, więc wątpliwości są ciągle zasadne.

**Comment by MateuszRomanow** [comment]
Jeżeli to co napisałem, nie jest zrozumiałe, to w tym temacie nic merytorycznego już nie dodam. 
Ja piszę o audycie, do tego wielokrotnym, Ty piszesz o approve'alu. That's it.

**Comment by jasisz** [comment]
Pewnie audyt nie jest jawny, ale może moglibyśmy się dowiedzieć jakiego typu to był audyt, co wchodziło w jego zakres i jakie były jego wyniki?

**Comment by miklobit** [comment]
Dopóki aplikacja nie korzysta z contact-tracingu od G+A to cały czas tytułowa wątpliwość jest aktualna. Zobaczymy co się stanie jeśli spróbujecie zintegrować to co jest z G+A.

**Comment by Tarvald** [comment]
Chyba sprawa jest jasna. 
Aplikacja przeszła audyt razem z wersją 4.1.1
Zamykam. ;)
