### ISSUE TITLE
Opisanie jak finansowany jest projekt, w tym podwykonawcy

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#160]
**Is your feature request related to a problem? Please describe.**
#155 z postów @miklobit'a oznaczonych jako offtopic, #128 

**Describe the solution you'd like**
- [ ] Chcę zobaczyć dokumentację jak z publicznych pieniędzy finansowany był (i czy był) był projekt ProteGO-Safe oraz czy z publicznych pieniędzy zostało cokolwiek przekazane firmie Infermedica lub innym. Jeżeli tak - uzasadnienie dlaczego kod wytworzony (i uzyskane dane do jego działania) przez zewnętrzne firmy nie jest dostępny publicznie

- [ ] jeżeli cokolwiek w temacie zostało sfinansowane z publicznych pieniędzy - chcę poznać kod (i dane) które zostały wytworzone z pomocą tego dofinansowania - najlepiej jako kod open-source. 

- [ ] proszę podać też sumy jakie zostały przeznaczone na projekt i dla podwykonawców (rozliczenia finansowe). 

**Describe alternatives you've considered**
\-

**Additional context**
\-

**Comment by pingwinwzakiecie** [comment]
> * [ ]  Chcę zobaczyć (...) czy z publicznych pieniędzy zostało cokolwiek przekazane firmie Infermedica (...). 

Nie zostało. #161
Chyba. @porz Prawda?

**Comment by porz** [comment]
> @porz Czy ProteGo brało od Infermedica jakieś usługi itd oprócz darmowego API?

Nie.

**Comment by pingwinwzakiecie** [comment]
> > @porz Czy ProteGo brało od Infermedica jakieś usługi itd oprócz darmowego API?
> 
> Nie.

 No to @SeraMoon na jedno pytanie masz już odpowiedź. Infermedica nic nie dostało.
