### ISSUE TITLE
Infermedica - stanowisko firmy

### ISSUE THREAD

**Issue by porz** [ProteGO-Safe/specs#161]
Dzień dobry,

Nazywam się Piotr Orzechowski - jestem prezesem oraz założycielem firmy Infermedica. Nie wiem, czy GitHub to najlepsze do tego miejsce, ale chciałem podzielić się pokrótce moim stanowiskiem odnośnie poruszanych tutaj kwestii. Nazwa naszej firmy przewija się w kontekście ProteGO parokrotnie, więc chcąc być pomocny i otwarty postanowiłem do Was napisać.

Przede wszystkim dziękuję wszystkim za ożywioną dyskusję i inicjatywę w kwestii bezpieczeństwa i poufności. Bardzo niewiele wiem na temat projektu ProteGO, ale z tego co rozumiem uczestnicy dyskusji starają się zapewnić maksymalne bezpieczeństwo aplikacji na poziomie jej design'u oraz szczegółowej implementacji. To dobrze, że projektowi, który (z tego co rozumiem) rozwijany jest w porozumieniu z agencją rządową przyglądają się eksperci zewnętrzni.

Odnosząc się teraz do kilku szczegółowych kwestii:

Re: #160 

1. Nie ujmując tutaj nic nikomu tylko pozostając obiektywnym:
- Nie jesteśmy autorami aplikacji ProteGO.
- Nie jesteśmy i nie byliśmy zaangażowani w projektowanie aplikacji ProteGo.
- Osobiście nie znam też założeń funkcjonalnych aplikacji ProteGO.
- Nie wiem, kto ani w jaki sposób finansuje ProteGo.
- Nie endorsujemy aplikacji ProteGO.

2. Nie mamy żadnej komercyjnej relacji z ProteGO. ProteGO nic nam też nie płaci ani nigdy nie płaciło. Nie realizujemy dla ProteGO też żadnych usług na zamówienie. 

ProteGO jest wyłącznie _użytkownikiem_ naszej darmowej usługi, która nazywa się COVID-19 API. Usługa opisana jest tutaj:
https://developer.infermedica.com/docs/covid-19

W każdej chwili możecie się zarejestrować i zacząć korzystać z COVID-19 API. Obecnie korzysta z niego ponad 200 aktywnych developerów na całym świecie. Wspieramy ponad 20 wersji językowych.

Stworzone przez nas API dla COVID-19 jest dostępne _nieodpłatnie_ dla każdego. API pozwala na zbudowanie formularza do zbierania wstępnego wywiadu medycznego i oceny ryzyka objawów koronawirusa. Protokół oparty jest o wytyczne WHO oraz CDC oraz jest na bieżąco aktualizowany przez zespół lekarzy, których zatrudniamy w firmie.

Nasze API dla COVID-19 nie jest też monetyzowane w żadnej sposób. Pomaga nam jednak popularyzować działalność komercyjną naszej firmy, którą jest dystrybucja API "głównego", które przeprowadza wstępny wywiad dla ponad 660 innych jednostek chorobowych (głównie w obszarze medycyny rodzinnej). Nasze API "komercyjne" nie było i nie jest składnikiem ProteGO.

3. W związku z powyższym zwracam się z prośbą do uczestników dyskusji o nie linkowanie naszej firmy z projektem ProteGO w sposób, który sugerowałby, że jesteśmy jego współautorem lub podwykonawcą.

Re: #155 

1. O tym już było trochę na Niebezpieczniku, ale chciałbym jeszcze raz powtórzyć.

Nasze API wspiera tylko część funkcjonalności aplikacji ProteGO. Aplikacja ProteGO komunikuje się z naszym API z ich back-endu (co jest sugerowanym rozwiązaniem ze względu na konieczność autentykacji w API). Z naszej perspektywy widzimy tylko IP backendu, który robi zapytania do naszego API. Nie widzimy więc żadnych adresów IP użytkowników aplikacji.

Ponad to nasze API nie przyjmuje żadnych informacji identyfikujących - jedynie odpowiedzi na pytania, płeć i wiek. Nie zbieramy żadnych imion, adresów etc.

Wszelkie pytania o architekturę przetwarzania danych w aplikacji ProteGO proszę kierować oczywiście do twórców tej aplikacji.

2. Dlaczego nasze API pyta o płeć i wiek (takie pytanie się pojawiało)?

W chwili obecnej zaimplementowane w naszym API drzewo decyzyjne nie bierze pod uwagę płci ani wieku - jedynie odpowiedzi na pytania obrazujące kryteria WHO. Zdecydowaliśmy się jednak dodać takie pola, ponieważ nie można wykluczyć, że w przyszłości takie dane będą wykorzystywane do lepszej rekomendacji (np. osoba starsza z chorobami serca, która zaczęła kaszleć może mieć wyższy poziom triage'u). Just in case, na ten moment akceptowalne jest wysyłanie do API zawsze tej samej płci i tego samego wieku. 

Re: #137 

1. Ponieważ nie jesteśmy autorami ani nie uczestniczyliśmy w projektowaniu aplikacji ProteGO pozostanę neutralny w kwestii, czy taka funkcjonalność powinna się w aplikacji znajdować. Zwróciliśmy jednak uwagę na pytanie, czy "dałoby się takie API zaimplementować offline". Odpowiedź brzmi oczywiście, że tak.

W przeciwieństwie do naszego "głównego" API (dla 660 jednostek chorobowych), API dla COVID-19 to **nie jest rocket science**. Całe drzewo decyzyjne (na obecną wersję 4.0) znajduje się tutaj (plik można otworzyć w diagrams.net):
https://drive.google.com/file/d/11DF9VpsUvxY1PGZ5tDGAkxmrGp3N6agI/view

Tutaj nie mówimy o żadnym AI ani machine learning, tylko fachowo opracowanym przez lekarzy drzewie decyzyjnym. _Nie mamy problemu z tym (a i nawet zachęcamy), aby ktoś to drzewo zaimplementował samemu w postaci komponentu offline, jeśli ma to służyć dobru obywateli w Polsce_.

To co nasze API jednak daje:
- Content jest up-to-date i upraszcza utrzymanie wersji. WHO zmienia wytyczne raz na jakiś czas. Wtedy aktualizujemy drzewo.
- Wspieramy ponad 20 wersji językowych i je na bieżąco aktualizujemy / synchronizujemy.

Dla wyjaśnienia nasze API jednak nie jest niestety open source i nie będzie, ponieważ korzysta z komponentów naszej "komercyjnej" oferty.  Pozostawiam temat powyżej ocenie Twórców aplikacji i służymy pomocą w razie chęci implementacji offline.

---

Na ten moment to chyba wszystko z mojej strony. Mam nadzieję, że przekazałem w jakiś sposób przydatne informacje. Postaram się w miarę możliwości tutaj zaglądać i odpisać raz na jakiś czas, jeżeli pojawią się pytanie związane z naszą firmą.

Pozdrawiam!

**Comment by Tarvald** [comment]
Witam panie Piotrze,
Dziękuje, za stanowisko! 
Rozwiał pan bardzo wiele wątpliwości.

Jako że temat jest gorący, a pan porusza w nim bardzo wiele kwestii, to pozwolę sobie zamknąć tutaj konwersacje i w razie wątpliwości albo nie jasności, poproszę o otwieranie nowych wątków.

**Comment by Tarvald** [comment]
W wersji 4.1 aplikacja już nie korzysta z infermedica API.
Diagnozowanie COVID-19 zostało zaimplementowane lokalnie.

**Comment by Tarvald** [comment]
W wersji 4.1 aplikacja nie korzysta z API Infermedica. 
Samoocena ryzyka zarażenia COVID-19 została zaimplementowana lokalnie.
