### ISSUE TITLE
Implementacja oceny ryzyka zachorowania COVID - lokalnie

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#163]
**Is your feature request related to a problem? Please describe.**
#162 #129 

**Describe the solution you'd like**
- [ ] Przeprowadzić audyt grafu pozostawionego w issue #162 na podstawie dostarczonych tam danych jak według CDC i WHO oceniany jest stan zdrowia,
- [ ] Zaimplementować lokalną ocenę stanu zdrowia,
- [ ] Usunąć pytania o niepotrzebne dane za #161. Pytanie o płeć można pozostawić, gdy planowane jest zwracanie się -łeś/-łaś do użytkownika, choć nie każdemu może to odpowiadać - warto dążyć do takich sformułowań, które są płciowo neutralne (niestety programiści często zapominają o istnieniu kobiet - nie wiem czemu...). 

**Describe alternatives you've considered**
\-

**Additional context**
#162

**Comment by Tarvald** [comment]
@SeraMoon 
1. Jak chcesz załatwić sytuacje w której któś nie zaktualizuje w ogóle aplikacji?
2. Za API infermedica stoii mała albo i większa armia lekarzy, chcesz żeby został stworzony osobny duży zespół medyczny, zamiast korzystać z gotowego, polskiego rozwiązania?

**Comment by porz** [comment]
Ja tylko informacyjnie, że zatrudniamy 20 lekarzy i przez COVID-19 API zrobiliśmy prawie pół miliona wywiadów na całym świecie. Więc jeśli chodzi o wkład merytoryczny do grafu to naprawdę zainwestowalibyśmy bardzo wiele uwagi i pracy.

**Comment by SeraMoon** [comment]
@Tarvald 
1. Aplikację należy aktualizować i może ona z serwera pobierać ocena-ryzyka.js i go wykonać. Można też zastosować pobierany template - jak pisałam - takie rozwiązanie z template udało mi się skutecznie zastosować w firmie do obsługi nazwijmy to "zmieniających się standardów". **Nie ma czegoś takiego jak aplikacja pozostawiona na pastwę losu i nieaktualizowana. Choćby o kwestie bezpieczeństwa.** 

2. Jak widzisz coś już dostaliśmy, trzeba tylko to sprawdzić, zaimplementować i aktualizować, gdy wytyczne CDC / WHO się zmienią.

**Comment by Tarvald** [comment]
@SeraMoon 
Mówie o aplikacji, nie zaktualizowanej z winy użytkownika.

**Comment by SeraMoon** [comment]
> 
> 
> @SeraMoon
> Mówie o aplikacji, nie zaktualizowanej z winy użytkownika.

Przypominać o aktualizacji! Czy aplikacja nie może sprawdzać czy nie ma aktualizacji i wyświetlać odpowiedniego komunikatu, gdy nie ma połączenia? Jeżeli nie ma połączenia, obecnie i tak nie zadziała.

**Comment by Tarvald** [comment]
Moim osobistym zdaniem, nie wymyślałbym koła na nowo.
Bardziej niebezpieczne (ze względów zdrowotnych), może być developowanie i utrzymywanie czegoś takiego, niż utrzymanie bardzo prostego proxy, na którego podobieństwo działa 99% internetu.
A wtedy diagnozowanie pozostawiamy lekarzom a programowanie programistą.

Bardziej bym to widział jako ulepszenie w którejś z kolejnej wersji, a na razie polegałbym na infermedica.
Szczególnie że mamy do czynienia z nowym wirusem, którego charakterystyka będzie się zmieniać, praktycznie z dnia na dzień, ale z czasem może się to ustabilizować.

Ale sprawa jest świeża i otwarta.
Nie jestem lekarzem.

**Comment by miklobit** [comment]
> Bardziej niebezpieczne (ze względów zdrowotnych), może być developowanie i utrzymywanie czegoś takiego, niż utrzymanie bardzo prostego proxy, na którego podobieństwo działa 99% internetu.
Z pubktu widzenia kilku milionów userów to bardziej niebezpieczne jest puszczanie wszystkich ich danych przez pół internetu gdzie po drodze niektórzy operatorzy (np. Cloudflare) mają do nich pełny wgląd, identyfikację usera i mogą z nimi robić co chcą.

**Comment by Tarvald** [comment]
@SeraMoon 
Zgłoszenie jest przyjęte.
Wewnętrzny numer zgłoszenia to: PSAFE-849

**Comment by SeraMoon** [comment]
> A wtedy diagnozowanie pozostawiamy lekarzom a programowanie programistą.

Ale przecież wcześniej pisano co innego - że aplikacja nie jest od diagnozowania. FACEPALM. 
Zgadzam się z @miklobit'em. 

https://www.youtube.com/watch?v=LQMzhA_1GPQ

**Comment by D0han** [comment]
> Wewnętrzny numer zgłoszenia to: PSAFE-849

Przepraszam, jaki wewnętrzny numer zgłoszenia?  
Czy ProteGo Safe jest prowadzony i rozwijany pod https://github.com/ProteGO-Safe/ czy w innym miejscu?

**Comment by miklobit** [comment]
> > Wewnętrzny numer zgłoszenia to: PSAFE-849
> 
> Przepraszam, jaki wewnętrzny numer zgłoszenia?
> Czy ProteGo Safe jest prowadzony i rozwijany pod https://github.com/ProteGO-Safe/ czy w innym miejscu?

Jeżeli zgłoszenie jest przyjęte w jakimś systemie do którego nie mamy wglądu to skąd wiemy jaka jest treść tego wewnętrznego zgłoszenia ? Czy ono obejmuje coś więcej niż link do tego tutaj #163 ? Np wybór metody implementacji - czy graf decyzji będzie zaszyty w aplikacji i modyfikacja grafu będzie oznaczać wypuszczenie nowej wersji czy też np graf  będzie jakoś pobierany z zewnątrz w formie danych lub gotowego kodu ? Bo jeśli to drugie to pozostaje dalej pytanie o korzystanie np CloudFlare , tym razem już nie do danych osobowych ale nadal do danych w których jakiś zewnętrzny podmiot może sobie grzebać (jak wskazano w #165 )

**Comment by jasisz** [comment]
> Przepraszam, jaki wewnętrzny numer zgłoszenia?
> Czy ProteGo Safe jest prowadzony i rozwijany pod https://github.com/ProteGO-Safe/ czy w innym miejscu?

Z commitów wiadomo że przynajmniej web ma swój prawdziwy "upstream" na https://github.com/SafeSafe-app/pwa jestteż wymione np. w Code of Conduct https://github.com/ProteGO-Safe/specs/blob/master/.github/CODE_OF_CONDUCT.md (który jak rozumiem skoro tak nie obowiazuje tutaj ;) )

**Comment by Tarvald** [comment]
@miklobit 
> Jeżeli zgłoszenie jest przyjęte w jakimś systemie do którego nie mamy wglądu to skąd wiemy jaka jest treść tego wewnętrznego zgłoszenia.

Treścią zgłoszenia jest ten wątek z komentarzami.
Forma jest ciągle rozpatrywana.
Temat jest bardzo świeży.

@D0han 
> Czy ProteGo Safe jest prowadzony i rozwijany pod https://github.com/ProteGO-Safe/ czy w innym miejscu?

Tak, ProteGo jest wytwarzany za pomocą wewnętrznych (bardzo wielu) narzędzi, z których korzysta konsorcjum firm. Po więcej zapraszam #147

**Comment by D0han** [comment]
Czytałem #147 jak tylko się pojawił, ale dziękuję za podlinkowanie.

Natomiast jeśli projekt jest otwarty, i tworzy go wspomniane już konsorcjum wraz z zainteresowaną społecznością, to nie widzę powodu by konsorcjum używało zupełnie osobnego systemu ticketów. Transparentność i wzajemna pomoc inaczej będzie ciężka.  
Chyba, że źle zrozumiałem, i jest to projekt na który możemy popatrzeć tylko przez szybkę.

**Comment by pingwinwzakiecie** [comment]
> > Wewnętrzny numer zgłoszenia to: PSAFE-849
> 
> Przepraszam, jaki wewnętrzny numer zgłoszenia?
> Czy ProteGo Safe jest prowadzony i rozwijany pod https://github.com/ProteGO-Safe/ czy w innym miejscu?

Ja nie pracuję nad tą aplikacją tylko przeglądam repo w czasie wolnym ale też myślałem że jest opracowywana tutaj na GitHubie. Czyli GitHub to tylko Bug Report a @Tarvald jest przedstawicielem jakiejś prywatnej firmy? No cóż, z was wszystkich jestem na 100% najgorszy w programowaniu, ale czy nie było by łatwiej opracować własny interfejs do zgłaszania błędów? Bo takto to nie dość że bałagan to jeszcze @miklobit i @SeraMoon pomyśleli że oni też pracują nad ProteGo.

**Comment by Tarvald** [comment]
@pingwinwzakiecie 
> Czyli GitHub to tylko Bug Report a @Tarvald jest przedstawicielem jakiejś prywatnej firmy? 

Nie jestem przedstawicielem żadnej firmy.
Z protego związałem parę dni  po tym jak wybuchła pandemia.
Szukali ludzi do pomocy przy aplikacji "koronazglowy".
I tak zostałem :)

ProteGo nie jest rozwijane tylko na GH.
Poproszę kogoś z zespołu żeby to lepiej wyjaśnił.

**Comment by SeraMoon** [comment]
> ProteGo nie jest rozwijane tylko na GH.

Może więc pora aby było rozwijane tylko na githubie aby była transparentność działań.

**Comment by pkleczko** [comment]
zmiany zostały już jakiś czas temu wprowadzone w aplikacji i działa wyłącznie lokalnie. pozwolę sobie zamknąć wątek.
