### ISSUE TITLE
Wydajność Proxy i darmowego API Intermedica

### ISSUE THREAD

**Issue by potiuk** [ProteGO-Safe/specs#166]
**Describe the bug**
Zgodnie z dyskusją w #162 wydaje się że aplikacja nie jest przemyślana pod kątem wydajnościowym jeśli chodzi o moduł diagnostyczny. 

Czekamy jeszcze na #155  żeby powiedzieć coś więcej, ale z pobieżnych wyliczeń (opartych na zgadywaniu)  przedstawionych w https://github.com/ProteGO-Safe/specs/issues/162#issuecomment-626678774 wynika że przy sukcesie aplikacji, zarówno Darmowe API Intermedica jak i proxy (NGINX) ProteGO będą miały spory problem wydajnościowy. 

Obliczenia 'na odwrocie koperty" wskazują że mówiimy o potecjalnym ruchu 40.000 żądań na sekundę w "peaku". 

**To Reproduce**

Powtórzenie obliczeń z https://github.com/ProteGO-Safe/specs/issues/162#issuecomment-626678774 z mniej "zgadniętymi" wartościami.

**Expected behavior**
Liczby które wyjdą powinne być zweryfikowane pod kątem wydolności zastosowanych rozwiązań.

**Comment by MateuszRomanow** [comment]
Informacyjnie - w poniedziałek dostaliśmy zgodę z MC na przepisanie modułu do samooceny tak, żeby funkcjonalność działała lokalnie. Jest to w procesie. Wspominam o tym tutaj, ponieważ bezpośrednio wpływa to na dezaktualizowanie wątków związanych z wydajnością API. 
Produkcyjne wdrożenie będzie w wersji 4.0.0.

**Comment by kierepka** [comment]
Ok - pytanie czy będzie dostępny moduł samooceny w formie kodów?

**Comment by potiuk** [comment]
Dzięki za informację @MateuszRomanow. Zamknę jak będzie zreleasowane.

**Comment by porz** [comment]
Ja tylko informacyjnie powiem, że Infermedica **nie jest zaangażowana** w tworzenie wersji offline. O decyzji dowiaduję się z tego wątku, ale koncepcyjnie zgadzam się, że jest to właściwy kierunek w przypadku aplikacji ProteGO.

Dziękuję zatem wszystkim za dyskuję i będę trzymał kciuki za powodzenie projektu.

**Comment by MateuszRomanow** [comment]
@kierepka tak, na pewno trafi do repo w tej organizacji. 
@porz w wątku MC<>Infermedica ten temat czeka na ruch ze strony MC. Tak więc my też czekamy, niezależnie będziemy się kontaktować z Tobą/Wami

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.

Jeżeli ktoś ma coś przeciwko to niech da znać, lub założy wątek zgodny z obecnymi założeniami.
Ocena ryzyka została zaimplementowana lokalnie w 4.1.1

**Comment by SeraMoon** [comment]
@Tarvald skoro firma ta nie świadczy nam usług - temat jest chyba zamknięty? 
@potiuk miałeś coś jeszcze na myśli w tym temacie odnośnie Proxy w stanie z wersji 4.1.1

**Comment by Tarvald** [comment]
@SeraMoon 
Racja, zamykam.
