### ISSUE TITLE
Aplikacja ProteGO Safe jako "przepustka" i "QR cody" w restauracjach

### ISSUE THREAD

**Issue by potiuk** [ProteGO-Safe/specs#169]
**Describe the bug**
@MateuszRomanow  - mamy powrót dyskryminacji i zmuszania firm do promowania aplikacji i wielki powrót QR-kodów (z których przecież zrezygnowaliście).

Prosiłbym o zlikwidowanie tego buga - mam nadzieję, że znowu w ciągu 3 h uda się uzyskać informację że to była nieprawda i że w ogóle tego nie było.

> Plany MR oraz GIS zakładają identyfikacje oraz ewidencję gości lokali gastronomicznych. Projektodawcy planują zalecić wszystkim pracownikom danego lokalu zainstalowanie rządowej aplikacji ProteGo Safe oraz nakazać umieszczenie przy wejściu do lokalu urządzenia z zainstalowaną aplikacją ProteGo Safe w celu zarejestrowania każdego klienta będącego użytkownikiem aplikacji. W wypadku braku możliwości wystawienia takiego urządzenia – rekomenduje się wydrukowanie kodu QR wygenerowanego z aplikacji ProteGO Safe do zeskanowania przez wchodzących klientów. W odniesieniu do klientów i pracowników, którzy nie posiadają aplikacji, lokal ma być zobowiązany do prowadzenia ich imiennej listy (!). Ma ona zawierać imię, nazwisko i numer telefonu obecnych klientów (!).
> 
> Zwracamy uwagę, że przetwarzanie danych osobowych oraz zapewnienie bezpieczeństwa tych danych przez lokale gastronomiczne, stanowić będzie dodatkowe obciążenie administracyjne i kosztowe dla już dziś mocno dotkniętych finansowo restauratorów. Wielu z nich nie będzie w stanie ponieść tego obciążenia i nie zdecyduje się na otwarcie swojego lokalu.
> 
> Sama aplikacja ProteGO Safe i mechanizmy jej działania wzbudzają wiele kontrowersji w zakresie prywatności obywateli i monitorowania ich przemieszczania się. Z perspektywy biznesu restauracyjnego szczególnie problematyczny jest fakt, że brak wcześniejszego dostępu do aplikacji nie pozwala nabrać pewności co do mechanizmów jej działania, a co za tym idzie wypracowania mechanizmów funkcjonowania w lokalach, przeszkolenia załogi oraz uporządkowania procesu przyjęcia gości.

**To Reproduce**
Przeczytać artykułł:

https://zpp.net.pl/stanowisko-zpp-ws-propozycji-wytycznych-dla-funkcjonowania-gastronomii-w-trakcie-epidemii-covid-19-w-polsce/

**Expected behavior**
Posiadanie, lub nie aplikacji ProteGO-Safe nie powinno być powodem do dyskryminacji ludzi. W tym wypadku, jest to absolutne naruszenie tego warunku,

**Comment by potiuk** [comment]
Niebezpiecznik już wie, Panoptykon wie, parę innych osób też wie. Dziś wieczorem sprawa będzie mocno dyskutowana z osobą z zarządu Helsińskiej Fundacji Praw Człowieka.

@MateuszRomanow dobrze by to było wyjaśnić w miarę szybko, bo to już nawet nie jest śmieszne.  A przed wieczorem warto by było wiedzieć skąd to się wzięło.

**Comment by kierepka** [comment]
@potiuk zwłaszcza bazując na wiedzy co dają takie narzędzia i w sumie o czym piszemy od początku i w sumie też naszego projektu:
[https://www.nytimes.com/2020/05/11/technology/coronavirus-worker-testing-privacy.html ](https://www.nytimes.com/2020/05/11/technology/coronavirus-worker-testing-privacy.html )

**Comment by MateuszRomanow** [comment]
Z dziennikarskiego obowiązku sprawdziłem co jest w wytycznych opublikowanych dzisiaj po konferencji KPRM dla gastronomii ( https://www.gov.pl/web/rozwoj/gastronomia ) i nie ma tutaj nic takiego. 

Czy udało ci się skontaktować z ZPP żeby sprawdzić źródło takich informacji przed podaniem tego dalej? Sam chciałbym się tego dowiedzieć. 

Niezależnie - Link, który podałeś wysłałem do MC z prośbą o wyjaśnienie.

**Comment by potiuk** [comment]
@MateuszRomanow - Nie szukałem dalej, bo po co ? 

Wydaje mi się że oficjalne stanowisko ZPP jest doś wiarygodnym źródłem chyba. Czy  masz jakieś wątpliwości co do ich wiarygodności ? 
"Zaufało nam 51 889 firmy, które zatrudniają 576 917 pracowników"

**Comment by potiuk** [comment]
Za to w międzyczasie Gosia Frazer (która jest dziennikarką i relacjonuje sprawę) zapytała : https://twitter.com/GosiaFraser/status/1260559066285342722

**Comment by potiuk** [comment]
Mam nadzieję że wkrótce się wyjaśni co i jak .... Myślę że dobrze że podnosimy temat jak najszybciej, bo wszelka dezinformacja w tej sprawie, tylko szkodzi.

**Comment by MateuszRomanow** [comment]
> @MateuszRomanow - Nie szukałem dalej, bo po co ?

Mogę odpowiedzieć tylko za siebie "po co" ja to robię - ja weryfikuję informacje dla zwykłej rzetelności. Żeby zweryfikować coś z 2-3 źródeł i mieć pewność, że to prawda. Tylko tyle.

**Comment by potiuk** [comment]
> Mogę odpowiedzieć tylko za siebie "po co" ja to robię - ja weryfikuję informacje dla zwykłej rzetelności. Żeby zweryfikować coś z 2-3 źródeł i mieć pewność, że to prawda. Tylko tyle.

Sprawdziłem to jedno źródło. Rzetelnie. W życiu bym nie postował informacji z niewiarygodnego źródła. ZPP jest na tyle poważnym źródłęm, że samo w sobie  wystarczy według mnie, żeby podnieść alarm.  Czy ja, czy kto inny zaraz by to podchwycił. A ja naprawdę nie mam czasu ani możliwości żeby dzwonić po ludziach. Według mnie, to właśnie praca osób takich jak Ty (jednak twarz projektu i osoba która odpowiada jakoś za wizerunek projektu a na dodatek to twoja praca za którą dostajesz pieniądze). Albo  dziennikarzy żeby takie (poważne i sprawdzone źródła) weryfikować. 

Mam nadzieję że to rozumiesz i że widzisz to jako "dobre" że zamiast spędzać sam czas na dzwonieniu po ludziach dałem od razu znać Tobie innym, żebyś natychmiast mogli się tym zająć? 

Czy uważasz że coś żle zrobiłem?

**Comment by MateuszRomanow** [comment]
Tu mówisz o roli rzecznika Ministerstwa Cyfryzacji czy Ministerstwa Rozwoju. Liczę, że pojawi się jakaś informacja w tej sprawie. Niezależnie - dostałem odpowiedź od MC, że "Nic takiego nie jest planowane". 

Update: z informacji na TT wynika, że ten wpis nie bazuje na aktualnych wytycznych. Być może to ta sama notatka, która została opublikowana  4 maja i mimo zdementowania dalej gdzieś w sieci "żyje".

**Comment by potiuk** [comment]
> Tu mówisz o roli rzecznika Ministerstwa Cyfryzacji czy Ministerstwa Rozwoju. Liczę, że pojawi się jakaś informacja w tej sprawie. Niezależnie - dostałem odpowiedź od MC, że "Nic takiego nie jest planowane".

Jesteś "Łącznikiem" - więc założyłem (raczej słusznie bo to zrobiłeś) że przez Ciebie będzie najszybciej. Właśnie o to Cię poprosiłem: 

"Prosiłbym o zlikwidowanie tego buga - mam nadzieję, że znowu w ciągu 3 h uda się uzyskać informację że to była nieprawda i że w ogóle tego nie było."

> 
> Update: z informacji na TT wynika, że ten wpis nie bazuje na aktualnych wytycznych. Być może to ta sama notatka, która została opublikowana 4 maja i mimo zdementowania dalej gdzieś w sieci "żyje".

Data jest dzisiejsza: https://zpp.net.pl/stanowisko-zpp-ws-propozycji-wytycznych-dla-funkcjonowania-gastronomii-w-trakcie-epidemii-covid-19-w-polsce/ 

Warszawa, 13 maja 2020 r.

Mam nadzieję że to szybko uda się wyjaśnić.

**Comment by jasisz** [comment]
ZPP wrzuciło https://zpp.net.pl/wytyczne-dla-funkcjonowania-gastronomii-w-trakcie-epidemii-sars-cov-2-bez-kontrowersyjnych-zapisow/ więc widocznie dostali wcześniejszą wersję do konsultacji.

**Comment by potiuk** [comment]
Super @jasisz  . To zamykam :)

**Comment by SeraMoon** [comment]
Chyba Ministerstwo oraz czeka na bółki z pilnikiem w środku, Już się chce powiedzieć w tym temacie "a nie mówiłam"... 😡 . Pora chyba nagłośnić sprawę ostro, skoro nadal brak jest bezwarunkowego zapewnienia, że aplikacja będzie dobrowolna. #149 Nie o takie zapewnienia prosiliśmy.
