### ISSUE TITLE
Poprawna PiSownia nazwy wirusa

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#172]
**Describe the bug**
W spekach napisane jest Sars-Cov-2, pojawiają się gdzie nie gdzie jeszcze inne wersje

**To Reproduce**
1. Otwórz specs
2. Przescrolluj w dół.

**Expected behavior**
Jedyną poprawną pisownią nazwy wirusa jest SARS-CoV-2 (pisownia dużymi literami z wyjątkiem litery "o" oraz obecność myślników). 

**Screenshots**
Zbędne

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
\-

**Comment by pingwinwzakiecie** [comment]
Dla czego "PiSownia"? CO błędne zapisanie nazwy wirusa ma do PiS-u?

**Comment by SeraMoon** [comment]
@pingwinwzakiecie 
nie CO tylko CoV 📦 
Pokazałam właśnie w temacie jaki wpływ na znaczenie ma zaPiS 📦 
W medycynie, genetyce i chemii wielkość literek i obecność lub nie - myślników ma duże znaczenie. CO<sub>2</sub> to co innego niż Co<sub>2</sub>.

A jaki ma Ministerstwo Cyfryzacji związek z PiS to sobie odpowiedz sam 😉

**Comment by pingwinwzakiecie** [comment]
> A jaki ma Ministerstwo Cyfryzacji związek z PiS to sobie odpowiedz sam 😉

Jaki MC ma związek to wiem. Nie pytałem o MC tylko o niepoprawny zapis nazwy wirusa:

> W spekach napisane jest Sars-Cov-2, pojawiają się gdzie nie gdzie jeszcze inne wersje
> Jedyną poprawną pisownią nazwy wirusa jest SARS-CoV-2 (pisownia dużymi literami z wyjątkiem litery "o" oraz obecność myślników).


> nie CO tylko CoV 📦

Nie CoV("CoV ma wspólnego niepoprawny zapis wirusa"?) tylko Co. Co, Kto, itd.


> W medycynie, genetyce i chemii wielkość literek i obecność lub nie - myślników ma duże znaczenie. CO2 to co innego niż Co2.

Ale jak ktoś przeczyta o "wirusie Sars-Cov-2" to będzie wiedział o co chodzi a nie "Aaaa tobie chodziło o SARS-CoV-2 a ja myślałem że jest jakiś nowy wirus o nazwie jak koronawirus tylko małymi literkami".

**Comment by SeraMoon** [comment]
@pingwinwzakiecie zamiast offtopować, poprawi ktoś tą nazwę wirusa wszędzie gdzie znajdzie "sars" (case insensitive) albo cov (case insensitive)?

**Comment by qLb** [comment]
@SeraMoon

W związku ze złamaniem reguł Kodeksu Postępowania obowiązujących w społeczności ProteGO-Safe w **tytule zgłoszenia wzywam do niezwłocznej zmiany tytułu zgłoszenia i zaniechania łamania reguł w przyszłości** gdyż może skutkować to podjęciem kolejnych kroków korekcyjnych.

Wskazuje także dotyczące tego wykroczenia ustępy w/w Kodeksu Postępowania:
## Nasze Standardy

Wśród przykładów zachowania, które przyczyniają się do tworzenia pozytywnego środowiska dla społeczności, są:

* Wykazywanie empatii wobec innych członków społeczności
* Okazywanie szacunku dla różnych punktów widzenia i osobistych doświadczeń
* Przyjmowanie konstruktywnej krytyki z wdzięcznością
* Przyjmowanie odpowiedzialności za nasze błędy, wyciąganie wniosków z ich doświadczenia oraz wyrażanie współczucia tym, których dotknęły
* Skupianie się na tym, co dobre dla całej społeczności, a nie jednostki społecznej

Wśród przykładów zachowania, którego nie będziemy akceptować, są:

* Używanie języka i grafik o podtekście seksualnym, okazywanie niepożądanego zainteresowania seksualnego, a także zaloty
* Trollowanie, obraźliwe bądź urągające komentarze oraz ataki osobiste bądź polityczne
* Nękanie, zarówno na forum publicznym jak i prywatne
* Publikowanie danych osobistych innych osób — takich jak adres fizyczny czy elektroniczny — bez ich wyraźnej zgody
* Naruszenie jakichkolwiek praw lub wolności innych osób, w tym w szczególności naruszanie prawa powszechnie obowiązującego
* Inne zachowania, które mogłyby zostać uznane za nieodpowiednie w kontekście profesjonalnym

**Comment by RMalczynski** [comment]
@SeraMoon, patrząc z perspektywy tego, że już dość długo udzielasz się w issues - tak niesmacznie upolityczniane wjazdy tylko ujmują Twojemu wizerunkowi w dyskusjach. Z szacunku do siebie i innych zamknąłbym/przeredagował to issue.

**Comment by qLb** [comment]
W związku z brakiem dobrowolnego kontaktu z opiekunami społeczności ProteGO-Safe i/lub osób zainteresowanych zamykam ten issue i po raz trzeci wzywam autora @SeraMoon do **samokorekty tytułu oraz wypowiedzi** w tym wątku z szacunku do forum dyskusyjnego, do którego się zwraca.

Brak reakcji może skutkować podjęciem kolejnych kroków korekcyjnych.
