### ISSUE TITLE
Wiki nie chce się otworzyć

### ISSUE THREAD

**Issue by pingwinwzakiecie** [ProteGO-Safe/specs#173]
Urządzenie: laptop Lenovo ThinkPad
System: Windows 10
Przeglądarka: Google Chrome

Na stronie głównej repo jest że jest wiki ale kiedy w nie wchodzę przekierowuje mnie na stronę główną.

1. Czy tylko ja tak mam?
2. Jeśli nie - czy to efekt zamierzony?
3. Jeśli nie - czy da się to jakoś naprawić?

**Comment by Tarvald** [comment]
@pingwinwzakiecie 
Urządzenie: PC 
System: Ubuntu
Przeglądarka: Google Chrome

U mnie jak klikam w wiki, to przekierowuje mnie na adres: 
https://github.com/ProteGO-Safe/specs/wiki

**Comment by pingwinwzakiecie** [comment]
@Tarvald U mnie też ale z https://github.com/ProteGo-Safe/specs/wiki od razu spowrotem na https://github.com/ProteGo-Safe/specs.

**Comment by Tarvald** [comment]
@pingwinwzakiecie 
Urządzenie: Macbook
System: Catalina
Przeglądarka: Google Chrome / Safari

Drugi komputer i nadal wszystko działa.
Bardzo dziwne, mógłbyś się skontaktować z kimś z GH.
Jednak na tą chwile nasze wiki jest puste.

**Comment by LIttleAncientForestKami** [comment]
Wydaje mi się, że już rozwiązane i można zamknąć: https://github.com/ProteGO-Safe/specs/wiki działa.

@pingwinwzakiecie jak jest u Ciebie?

**Comment by Tarvald** [comment]
@pingwinwzakiecie @LIttleAncientForestKami 
Niedawno zaczęliśmy prace nad wiki. 
Mam nadzieję że teraz się naprawiło dzięki temu ;)

**Comment by Tarvald** [comment]
@pingwinwzakiecie 
Daj znać jakbys miał problem w wiki.
Tymczasm zamykam.
