### ISSUE TITLE
[CONTACT TRACING] - nie tylko dla COVID-19 ?

### ISSUE THREAD

**Issue by Dr-Kownacki** [ProteGO-Safe/specs#175]
Wiemy że API A+G po (miejmy nadzieję) wygaśnięciu pandemii COVID-19 ma zostać docelowo (również przez producentów) "wyłączone".

**Zastanawia mnie jednak potencjalnie duże (?) zastosowanie/przydatność tej technologii w kontroli innych chorób zakaźnych jak chociażby grypa czy gruźlica (tak, wokół nas są w społeczeństwie prątkujące osoby...), ospa wietrzna i wiele innych ...**

Oczywiście podniosą się głosy że "są szczepionki" ale niestety poziom wyszczepienia populacji np. na grypę jest niewielki. Na pewno różnice w programach szczepień różnych krajów (nawet wewnątrz UE) są bardzo duże. Jest wiele chorób zakaźnych o różnej etiologii którymi zarazić się można przez bliski kontakt, podobnie jak COVID-19.

W moim przekonaniu cały wysiłek wykorzystany na wprowadzanie aktualnie przez wiele państw programu wykorzystania "exposure notification" dla COVID-19 można potencjalnie bardzo dobrze wykorzystać również do innych chorób po wygaśnięciu (pobożne życzenie) aktualnej pandemii ale być może nawet wcześniej, bo przecież inne choroby zakaźne "nie zniknęły" tylko dlatego że nie są aktualnie medialne.

**Jak wcześniej pisałem w #168 w moim przekonaniu jednym z potencjalnych (niedocenionych ?) atutów tracingu jest powiadomienie narażonej potencjalnie osoby wobec czego np. nie zlekceważy ona jakichś pierwszych symptomów u siebie, szybciej trafi do lekarza i oczywiście poprzez adekwatne działania zapobiegnie zarażeniu innych osób.**

Moja propozycja jest taka, aby zgłosić do Apple+Google jakąś możliwość przypisywania potencjalnym warningom jakiejś "flagi" która pozwalałaby przypisać ostrzeżenie do adekwatnej jednostki chorobowej (ICD10 z rozkodowaniem lokalnie w aplikacji?)

W ten sposób pacjent hospitalizowany/leczony ambulatoryjnie z powodu "jakiejś" choroby zakaźnej z udokumentowanym wynikiem rozpoznania (to oczywiście musiałoby być KONKRETNE rozpoznanie na podstawie wyników laboratoryjnych np. wirusa grypy /(wręcz konkretnie jakiej), **miałby wgrywane do systemu klucze z odpowiednim oznaczeniem - "flagą" jaka to choroba.** Co więcej system powinien dostosowywać do tej "flagi" również czas po jakim te klucze "przedawniają się" (różne modele zakaźności pacjentów w różnych chorobach i różne sutuacje).

Jako lekarz widzę tutaj jakąś dużą szansę na potencjalnie zaadresowanie na pewno wielu chorób zakaźnych, które być może nie są tak "spektakularne-medialne" jak COVID-19, ale przecież w ostatniej dekadzie w skali świata na pewno zebrały (i będą zbierać) łącznie o wiele większe żniwo zarówno przypadków śmiertelnych jak i groźnych powikłań typu chociażby zapalenie mięśnia serca. 
Akurat z tym ostatnim powikłaniem często mam styczność podczas badań rezonansu magnetycznego serca (jedno z głównych wskazań do badania) więc wiem dokładnie o czym piszę.

Stąd postuluję niniejszym rozważenie sytuacji, w której wypracowywana aktualnie technologia - przy założeniu spełnienia wysokich norm bezpieczeństwa, prywatności etc. (czyli wszystkiego o czym tutaj dyskutujemy), nie zostałaby z założenia "wyłączona" przez Apple+Google (jak jest to obecnie zakładane), ale byłaby potencjalnym narzędziem w walce z rozprzestrzenianiem się wielu innych chorób.

W moim przekonaniu na pewno jest technicznie prosta możliwość "dopisania" kawałka kodu, który pozwalałby na "różnicowanie" aplikacji użytkownika różnych kodów, których aktualizacja mogłaby nawet nawet następować poprzez jakiegoś pobieranie realnego"wzorca kodów" wspólnego dla całego świata. 

W ten sposób podczas "wgrywania kluczy" przez umocowaną instytucję służby zdrowia wpisywany byłby adekwatny kod (ICD10 ?) choroby zakaźnej zwł. mogącej szerzyć się drogą kropelkową który modulowałby automatycznie w jaki sposób ma z tymi kluczami postąpić serwer (kiedy je "przedawnić" / albo w jakim zakresie dni pacjent był zakaźny, w zależności od rozpoznania i wywiadu - kiedy/które klucze były "aktywne").

Takie warningi spływające do wielu osób (przy pełnym rozpowszechnieniu tej technologii) mogłyby mieć także istotny wpływ psychologiczny na społeczeństwa o niskich wskaźnikach wyszczepienia (ludzie zaczęliby się szczepić w większym odsetku?), ponieważ wtedy pojawi się REALNY feedback ze środowiska jak wiele jest w środowisku potencjalnych narażeń.

Stąd taki temat zgłoszę również do wątku "Pytania do Google + Apple".

Zdaję sobie sprawę że aplikacja nie jest panaceum na choroby zakaźne o podobnym do COVID-19 sposobie rozprzestrzeniania się, ale skoro technologia "będzie gotowa" czy nie warto byłoby ją szerzej wykorzystać ?

Gdyby (odpukać) po/równolegle do COVID pojawiła się kolejna epidemia/pandemia to wszystko byłoby już naturalnie "gotowe i wdrożone" i jakąś pomocą na pewno byłoby dla służby zdrowia i organów sanitarnych. Wielu ekspertów postuluje że "COVID-19" to dopiero początek (i tak nie najgorszy z możliwych), od dawna temat nagłaśniał też Bill Gates...

Z czarnym humorem zacytuję jednego z polskich eksperów-zakaźników wypowiadającego jakś czas temu w TV - "Nie wiemy co będą jeść.... - Raz jedzą węże, raz nietoperze."  Moim zdaniem coś w tym jest niestety...

Podkreślam, że "utrzymanie powszechnej funkcjonalności tracingu" dla innych celów (jak i samo jego wprowadzenie w COVID-19) **powinno mieć miejsce dopiero po spełnieniu wszystkich założeń bezpieczeństwa i prywatności w powszechnie akceptowanym społecznie modelu.**

W powyższym zagadnieniu na pewno (przynajmniej w wymiarze polskim) mogłoby mieć swój udział "ciało/towarzystwo/fundacja" postulowane w #168 w ścisłej współpracy z lekarzami zakaźnikami.

**Dodatkowym potencjalnie ciekawym aspektem upowszechnienia "exposure notification" w COVID-19 (ale i nie tylko, j.w.) są kwestie psychologiczne (jak się nawet postuluje ostatnio psychiczne-psychiatryczne).** 
Na pewno istotna społecznie liczba osób poprzez przedłużone przebywanie w izolacji/kwarantannie i torpedowana nieustannie w mediach złymi doniesieniami, może docelowo unikać wszelkiej aktywności społecznej i interakcji nawet wtedy, kiedy realne ryzyko zakażenie będzie pomijalne.

**W moim przekonaniu posiadanie telefonu z aktywną opcją tracingu może być dla takich osób również jakąś formą "terapii" i namacalnego dowodu że może rzeczywiście "nie jest tak źle".** 

Taki aspekt dla użytkownika może być niezmiernie ważny i dawać poczucie jakiegoś większego bezpieczeństwa / otuchy oraz pozwolić (zupełnie bez nadzoru specjalisty nawet, niejako "automatycznie") na wykonywanie "małych kroków trapeutycznych" czyli: 1) wyszedłem do sklepu - w ciągu kilku dni brak warningu 2) jechałem autobusem... 3) poszedłem do galerii handlowej itd.

Na pewno taki aspekt tracingu też powinien być brany pod uwagę podczas oceny jego społecznych implikacji - po prostu jakieś "urealnienie zagrożenia" i odniesienie tego narażenia personalnie do jednostki a nie tylko "statystyczne oszacowanie" - po prostu REALNY odczuwalny feedback ze środowiska.

Ciekaw jestem Waszych opinii w powyższych tematach.

@MateuszRomanow : czy w zakresie znanych Wam realiów API A+G jest tam potencjalna "przestrzeń" na jakieś zmodyfikowanie (dodanie "flagi choroby zakaźnej") już na obecnym etapie aby rozważyć w Polsce taki bardziej "uniwersalny" model wykorzystania przy uprzednim oczywiście zaakceptowani tego przez Ministerstwo Zdrowia / Ministerstwo Cyfryzacji ???

**Comment by pkleczko** [comment]
@Dr-Kownacki na tym etapie moim zdaniem to niewykonalne - API czegoś takiego nie przewiduje i patrząc na to jak dużo jeszcze pracy jest przed Google i Apple żeby ustabilizować i wypuścić release produkcyjny API nie sądzę żeby chcieli dodawać kolejny poziom komplikacji.
Teoretycznie byłoby to do zrobienia przez nas. Przy wysyłce kluczy na serwer, moglibyśmy samemu dodać sobie informacje o dodatkowej/innej chorobie. Po drugiej stronie pobierając dane do analizy, moglibyśmy przy wyniku wysokiego ryzyka powiązać to z tymi danymi. Trzeba by natomiast takie klucze analizować oddzielnie, w tym momencie analiza bazuje na wystawianych przez serwerach specjalnych plikach, które w założeniu będą zawierały cały zestaw kluczy od różnych osób a nie pojedyńczych jednostek (co nie znaczy że nie byłoby to do wykonania). 
Natomiast nie znając dokładnie sposobu działania analizy ryzyka rozwiązania A+G nie wiemy czy np. przy jego szacowaniu nie są brane pod uwagę analizy dla innych kluczy w tym wypadku dla choroby X ryzyko było np. 3, dla innej choroby 4, ale API zwróci ich "sumę" bo uznaje że obie analizy dotyczą tej samej choroby i ryzyko jest np. 5. Myślę, że trzeba zacząć od podstawowego case'u i w ogóle ocenić społeczną akceptowalność rozwiązania - które jak wiemy będzie działać dobrze tylko wtedy kiedy osiągnie wysoki procent używalności.

**Comment by Dr-Kownacki** [comment]
@pkleczko dzięki za odpowiedź, oczywiście rozumiem i tak przypuszczałem że jest na pewno wiele do zrobienia przy "samym" COVID-19 i ogólnie "rozruchu" tematu w skali ogólnoświatowej i każda "dodatkowa" opcja jest do wzięcia pod uwagę jak już "baza" skutecznie ruszy.

Jeśli chodzi o "inne choroby" zakaźne to nawet w początkowym etapie nie opierał bym tematu na jakimś "liczeniu ryzyka" dla nich ale tylko na prostej informacji że np. "był potencjalny kontakt z osobą chorą na ospę wietrzną" - najlepiej jeszcze z info "kiedy dikladnie" ale tutaj znów kwestie "prywatnościowe" dochodzą więc albo tylko "dzień" albo wręcz bez żadnej dokładnej daty a jedynie "że był w okresie kiedy kontakt z zebranego klucza już potencjalnie zarażał".

W moim przekonaniu - jako lekarza, to w wieku jednostkach chorobowych i w różnych rejonach świata mogłoby być niezmiernie pomocne.

Wiadomo że grupę osób/firm które aktualnie realizują zlecenie dla MC najbardziej interesuje aktualne skuteczne i akceptowalne społecznie "dowiezienie tematu COVID-19" ale jeśli pomyśleć perspektywicznie to nawet kiedy ta pandemia przemianie, to wciąż Wasze rozwiązanie byłoby użyteczne i temat warty jest implementacji może nawet na światową skalę w przyszłości.

Po obecnym armagedonie nawet jak pandemia zostanie skutecznie zwalczona, będzie szczepionka/skuteczne leki etc. to jestem przekonany że **choroby zakaźne na wiele dekad pozostaną "trendy"** stąd mielibyście gotowe rozwiązanie przynajmniej dla skali całej Polski i na prawdę jest potencjał żeby coś ciekawego osiągnąć (być może niewielkim dodatkowym wysiłkiem) bazując na wcześniejszych "podstawowych" rozwiązaniach.

Na pewno warto perspektywicznie/biznesowo brać to pod uwagę bo jest tutaj niemała szansa dla Was :-)

W moim przekonaniu za dużo było/jest stresu i zbyt wielka trauma społeczna żeby (dobre i dobrze wyjaśnione oraz **"certyfikowane społecznie" np. w mechanizmie #168** ) rozwiązanie contact tracingu nie zostało skutecznie rozpropagowane w społeczeństwie.

Jeżeli tak się stanie, to będzie świetna baza dla innych chorób zakaźnych, ponieważ wszyscy będą teraz bardziej i tym myśleć stąd można zakładać że społeczna akceptacja do takiego podejścia może być duża.

Przede wszystkim warto jednak już teraz mieć z tyłu głowy taką opcję i myślę że warto do G+A takie podejście (nawet na obecnym etapie) zgłosić chociażby tylko po to aby z innej perspektywy spojrzeli na postulowany plan "wyłączenia tej opcji" jak minie problem COVID-19.

**Comment by potiuk** [comment]
Myślę że w tej chwili w ogóle chcemy sprawdzić, czy to ma sens i będzie działać. Na razie to jeden wielki eksperyment, który ma na celu sprawdzenie czy technologia może być w takiej sytuacji pomocna. Myślę @Dr-Kownacki - że podobnie jak w przypadku badań klinicznych - zobaczmy czy to zadziała, i jeśli tak, to potem wszyscy publicznie będziemy się zastanawiać nad tym, czy i co dalej z tym zrobić. W tej chwili jest zdecydowanie za wcześnie żeby zastnawiać się co dalej jak nawet jeszcze nie zrobiliśmy pierwszego kroku.

**Comment by potiuk** [comment]
Jeszcze jeden komentarz @Dr-Kownacki  - w przypadku sotware'u naprawdę nie trzeba myśleć o 10 kroków do przodu - wystarczy 1, 2. Zawsze można wszystko przepisać od nowa. Naprawdę, to żaden problem i większość działających systemów software'owych jest przeisywana wielokrotnie, czasem od zera. Naprawdę teraz chcemy sprawdzić czy w ogóle takie rozwiązanie ma sens. Myślimy że tak, ale nie wiemy. Sprawdźmy, zobaczmy. nauczmy się, wyciągnijmy wnioski. 

Jeszcze jedno - pisałem o tym już kilkukrotnie - ten system ma dość unikalną właściwość - wszystkie dane stają się nieaktualne po 14 dniach. W związku z tym jest zupełnie ok, żeby za miesiąc, format etc. był mocno zmieniony w stosunku do tego co jest teraz. Skupmy się na tym co tu i teraz, a jeśli bedzie trzeba coś zmienić - i z publicznej dysusji wyjdzie, że trzeba - to będzie zmienione.

**Comment by pkleczko** [comment]
w związku z brakiem aktywności w wątku i brakiem planów na reużycie technologii do innych zastosowań pozwolę sobie zamknąć wątek.
