### ISSUE TITLE
Współdzielony smartfon a ProteGO-Safe - skutki

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#177]
**Describe the bug**
Aplikacja jest zawsze włączona, a czasem istnieje potrzeba pożyczenia telefonu znajomemu, innemu pracownikowi, dziecku, babci - komukolwiek - oczywiście w teren. Nastąpi naliczenie spotkanych identyfikatorów nie tej osobie "co trzeba". 

**To Reproduce**
1. Pożycz komuś telefon
2. Spotkał osobę chorą
3. Masz alert o pilną potrzebę zgłoszenia się do Sanepidu, ale po 10 dniach nie pamiętasz komu i czy pożyczony był smartfon

**Expected behavior**
Do rozważenia - możliwość przełączania kont w aplikacji, co na to protokół EN (G+A)? 

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS: Any
 - Browser None
 - Version 96.96.96.99

**Smartphone (please complete the following information):**
 - Device: Współdzielony
 - OS: None
 - Browser None
 - Version 96.96.96.99

**Additional context**
Przemyślenia podczas rozmowy #168, przemyślenia błędów aplikacji "Kwarantanna Domowa" innych niż jej obowiązkowość, 2 smartfony w domu na 4 osoby używające (powód: ubogość, brak opłaconych rachunków za 3 z 5 telefonów w ubogiej rodzinie - 3 przestały więc działać z powodu centralizacji serwera rozwiązania G+A, telefon czyjś mógł ulec awarii, wyjazd  i potrzeba aby staruszek - ten najbardziej zagrożony COVID-em - miał kontakt).

**Comment by Tarvald** [comment]
@SeraMoon 
Jeżeli jedna osoba w domu będzie potencjalnie zarażona to i reszta rodziny może być zagrożona. 
Nie mogę sobie wyobrazić scenariusza pożyczania telefonu w którym przy zakarzeniu jednej ze stron drugą miała by nie być zagrożona.

**Comment by SeraMoon** [comment]
Ta sytuacja występuje w pracy i nazywa się telefonem służbowym. Są firmy, gdzie 1 telefon =/= jeden pracownik, a są ludzie którzy mają tylko służbowy.

**Comment by Tarvald** [comment]
@SeraMoon 
Wydaje mi się że to bardzo ekstremalnie rzadkie przypadki, które tak czy inaczej chyba powinny zostać powiązane w śledztwie epidemiologicznym.

**Comment by Dr-Kownacki** [comment]
Ale przecież jakikolwiek smartfon BEZ SIM też będzie działał z API A+G ? Jakikolwiek iPhone 6s za 300pln używka wystarczy i pewnie docelowo Android za 50pln. ...
Więc nawet osoba bez "własnego/zarejestrowanego na siebie" numeru jeżeli zechce brać udział w tracingu to być może wyposaży się w jakieś urządzenie (?) I SIM za 5pln....

**Comment by SeraMoon** [comment]
@Dr-Kownacki tak, szczególnie wystarczy tym, którzy zostali wywaleni na bruk - czyli bezrobotnym i splajtowanym przedsiębiorcom, w tym tym ukaranym karami 10-30 tys. złotych za legalny strajk (rozporządzenie nie ma prawa nadpisywać niezwiązanej z nim ustawy o zgromadzeniach. 

Odstępy były zachowane na obu manifestacjach (jedna czteroosobowa) dopiero policja zacieśniając kordon uniemożliwiła im to, użyła gazu (w stosunku do jednej manifestacji) i "zaciągnęła do suki" (cytat). Szczególnie te osoby (jedna po zawale - spowodowanym tymi działaniami) będzie ich stać na zakupienie telefonu i płacenie za kartę SIM. 

Stać będzie na płacenie:
- bezrobotnych,
- bankrutów,
- osoby zobowiązane natychmiastowo zapłaci.ć sanepidowi 10-30 tys. złotych dzięki policjantom-listonoszom "pełniącym czynności". 

Opisuję tu rzeczywistość, która miała miejsce w tym i poprzednim miesiącu - nie ma tu wtrętów politycznych. Każdy wie kto za to powinien ponieść odpowiedzialność. 

BTW. Wiedząc, że mogę dostać mandat za nieprzestrzeganie 2 metrów (co nie jest zależne tylko ode mnie (wąskie chodniki, czekanie na czerwonym) i możliwość dostania [listu od policji](https://www.youtube.com/watch?v=y7SWR6TFSfk) sama nie zamierzam wydawać pieniędzy bo nie mam oszczędności a mandat realny przy każdym wyjściu do sklepu.

**Comment by Dr-Kownacki** [comment]
O, przepraszam ale w #101 ja akurat proponowałem rozwiązanie darmowe dla wszystkich i pomyślałem właśnie o wszystkich.

**Comment by SeraMoon** [comment]
@Dr-Kownacki nie do Ciebie piję tutaj. Potraktowałam twoją wypowiedź w kontekście obecnego kształtu aplikacji. Reszta jest tylko zwróceniem uwagi, że niedługo nie każdy będzie miał internet czy nawet komórkę, bo ludzie bankrutują, stają się bezrobotni i w rodzinach kilkuosobowych na pewno nastąpi redukcja do minimum wydatków na "telekomy" jako zbędne (jeden czy 2 telefony na rodzinę wystarczą, gdy trzeba żyć od 1 do 1).

**Comment by okrystian** [comment]
> Są firmy, gdzie 1 telefon =/= jeden pracownik
> Telefon zabiera od znajomego wyjeżdżając do Niemiec

To chyba logiczne, że na takim telefonie po prostu nie powinno się instalować tej aplikacji?

**Comment by pkleczko** [comment]
w związku z brakiem aktywności w wątku pozwolę sobie zamknąć wątek. w razie dalszych wątpliwości w temacie "pożyczania" telefonu proszę o utworzenie nowego.
