### ISSUE TITLE
Umowa KNF na czipowanie a ProteGO-Safe - czy będzie integracja?

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#178]
**Is your feature request related to a problem? Please describe.**
Czy projekt ProteGO-Safe będzie zintegrowany z tym systemem:
http://biznes.pap.pl/espi/pl/reports/view/2,441237

**Describe the solution you'd like**
Odpowiedź bez sformułowań typu "nie planujemy", "prawdopodobnie", "chyba" oraz innych, które nie dają bezwzględnego zobowiązania dla ludzi. Jestem przeciwniczką czipowania ludzi, zaś dokument powołany przez Państwową Agencję Prasową mówi jasno o wszczepianiu czipa pomiędzy kciuk i palec wskazujący w związku z COVID/MERS/SARS. 

**Describe alternatives you've considered**
Jeżeli takiego zobowiązania Ministerstwa nie dostaniemy - warto przemyśleć, czy programiści chcą się dokładać do takiego zdeptania prywatności obywateli. Niewątpliwym jest też, że czip będzie narażał prywatność obywateli bardziej niż IP. 

**Additional context**
#148 #149

**Comment by Dr-Kownacki** [comment]
Ale to nie jest "umowa KNF", to jest po prostu wymagana (?) prawnie moim zdaniem "normalna-zwykla" informacja.gieldowa że jakaś spółka akcyjna coś podpisała z inną spółką...

Generalnie wiele firm próbuje w obecnym momencie "coś z COVID" robić, a taki komunikat jako że temat jest "trendy" jest obliczony na wzrost kursu ich (obu stron umowy) akcji jako spółki akcyjnej.

**Comment by Tarvald** [comment]
Zgodnie z założeniami dostępnymi w wątku #147, nie ma planów w/w integracji.
Po więcej informacji zapraszam do bezpośredniego kontaktu z MC.

W trosce o przejrzystość i porządek na repozytorium informuję, że temat ten nie jest w żaden sposób powiązany z rozwojem aplikacji ProteGO Safe. W związku z powyższym proszę autora o zamknięcie tematu.
