### ISSUE TITLE
[enhancement] Dodanie urządzeń 'hubów' - urządzeń BT w miejscach publicznych

### ISSUE THREAD

**Issue by milist** [ProteGO-Safe/specs#18]
Dodanie funkcjonalności pozwalającej na ustawienie urządzenia BT w sklepie / transporcie publicznym - pozwoli to na powiadomienie osób, które mogły zetknąć się z wirusem w przestrzeni publicznej.

W ten sposób będziemy w stanie znaleźć osoby korzystające z tego samego sklepu/tramwaju/autobusu. Trzeba natomiast dobrze 'dobrać' czasy ekspozycji dla takich urządzeń, aby nie 'zainfekować' wszystkich użytkowników będących w danym miejscu przez ostatnie 14 dni, natomiast wskazać potencjalne ryzyko tym, którzy mogli mieć bliski kontakt przez dotykanie rzeczy.

**Comment by kierepka** [comment]
Tu wykorzystałbym już istniejące BT Adver. np. beacony różnych instytucji. Dokładnie tak powinno być w Autobusach, pociągach itp. Przy czym uważam, że powinno być jak w #63  ;)

**Comment by jakublipinski** [comment]
Jeśli osoby w sklepie/transporcie publicznym będą miały aplikację, ProteGO powinno to wykryć bez dodatkowych urządzeń.

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku, 
zostanie on automatycznie zamknięty w najbliższym czasie.
