### ISSUE TITLE
Zmuszanie ludzi do instalacji ProteGO - RPO

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#180]
**Describe the bug**
Aplikacja miała być calkowicie dobrowolna. **Tymczasem do RPO spływają skargi na zmuszanie ludzi do instalacji "aplikacji śledzącej ProteGO" po odbyciu kwarantanny.** Ponieważ znalazła się ta informacja na stronie tak ważnego i wiarygodnego rządowego organu jak RPO, stwierdzam,że założenia #147 oraz #149 (brak zapewnienia) nie zostały spełnione

**To Reproduce**
1. Wejdź na stronę https://www.rpo.gov.pl/pl/content/lkoronawirus-faq-odc-36-testy-i-sanepid-kwarantanna
2. wciśnij Ctrl+F, a następnie wpisz "ProteGO". 
3. Jeżeli nie znajdziesz tej informacji, zamiast strony podanej w punkcie 1, wejdź na archiwum: https://archive.is/tLroH i powtórz punkt 2. 

**Expected behavior**
Dobrowolna aplikacja, koniec wydawania przez sanepid nakazów instalacji aplikacji ProteGO lub zakończenie projektu bez dalszego rozwoju - gdyż aplikacja używana jest do odbierania wolności ludziom i ich nękania. Na stronie safesafe.app oraz w ekranie powitalnym aplikacji powinna pojawić się informacja "Aplikacja ProteGO-Safe jest aplikacją w pełni dobrowolną do śledzenia stanu własnego zdrowia" lub podobny określający, że aplikacja jest dobrowolna. **To samo powinno znaleźć się w opisie w sklepie Google oraz Apple, aby ludzie mogli nakazodawcy pokazać, że aplikacja jest darmowa i nie można nikogo przymuszać.** 

**Screenshots**
https://archive.is/tLroH#selection-783.0-783.168

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version 3.0.3

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version 3.0.3

**Additional context**
Ewentualne wątpliwości należy wyjaśniać z RPO, nie ze mną - ja tylko pośredniczę w przekazaniu tak ważnej informacji.

**Comment by miklobit** [comment]
@SeraMoon To chyba jednak pomyłka na tej stronie RPO nastąpiła. Bo w tytule jest ProteGO ale opis okoliczności jednoznacznie świadczy że skarżącemu chodziło o aplikacje "kwarantanna domowa". 
![Screenshot(607)](https://user-images.githubusercontent.com/1035161/82611520-f84c5680-9bc0-11ea-8b89-4f9228c0e659.png)

**Comment by SeraMoon** [comment]
**"Oba te rozwiązania niepokoją zarówno Rzecznika Praw Obywatelskich, jak i obywateli..."**

Mowa jest ze strony Rzecznika o obu rozwiązaniach, więc prawdopodobnie chodzi zarówno o ProteGO jak i Kwarantannę Domową (w ostatnich miesiącach nie pojawiło się więcej produktów Ministerstwa Cyfryzacji. 

Sprawę zna RPO - tam należy wyjaśniać. Ja się jednak nie zdziwię, w sytuacji gdy Policja i Sanepid nie znają (lub nie chcą znać) treści rozporządzeń i ustaw zmienianych co tydzień - że mogło dochodzić do zmuszania ludzi do instalacji ProteGO - jest to całkiem możliwe, ponieważ na gov.pl/koronawirus - przez 1 lub 2 dni wisiała informacja że będą przywileje związane z aplikacją - więc nazwę mogli pamiętać. 

Myślę, że twórcy ProteGO mają maila do RPO (jest na jego stronie) i mogą zapytać RPO, dlaczego mówi o obu rozwiązaniach, a nie tylko o jednym? Może dlatego, że faktycznie ludzie są zmuszani do instalacji obu aplikacji?

**Comment by Tarvald** [comment]
@SeraMoon 

> instaluje na swoim urządzeniu mobilnym udostępnione przezministra właściwego do spraw informatyzacji oprogramowanie służące do potwierdzania realizacji obowiązku przestrzegania kwarantanny
Czy zarówno aplikacja ProteGO jak i "Home Quarantine" nie spełniają tego zapisu? 

ProteGo napewno nie spełnia tego zapisu.
Aplikacja nigdy nie była i nie będzie służyła do kontrolowania kwarantanny.

**Comment by SeraMoon** [comment]
> ProteGo napewno nie spełnia tego zapisu.
Aplikacja nigdy nie była i nie będzie służyła do kontrolowania kwarantanny.

A mają tą wiedzę Policjanci, tacy szeregowi bez większego wykształcenia i wiedzy medycznej oraz informatycznej? Nazwa aplikacji powinna być wpisana w ustawie. Teraz mamy sytuację, że komuśPolicja (bo oni przychodzą do nowych kwarantanniarzy) kazała instalować aplikację. Prawdopodobnie nie był to jedyny przypadek i musiał być udokumentowany, skoro sprawą zajmuje się RPO i UODO również. Obecnie przez brak wskazania w sklepach z aplikacjami faktu która aplikacja jest obowiązkowa dla kwarantaniarzy - mamy sytuację, że po tyłku dostaną prawdopodobnie obie aplikacje. W sytuacji gdy się okaże, że Policja faktycznie zmusza kwarantanniarzy do instalacji tego oprogramowania lub obu programów (najbardziej prawdopodobna opcja, czytając tekst RPO) - aplikacja już stoi na prostej drodze do zakończenia swojego bytu. Teraz i na zawsze. 

**Czekam od osób odpowiedzialnych za projekt na wieści co ustalono z RPO w sprawie.**

**Comment by Tarvald** [comment]
> A mają tą wiedzę Policjanci, tacy szeregowi bez większego wykształcenia i wiedzy medycznej oraz informatycznej?
> Czekam od osób odpowiedzialnych za projekt na wieści co ustalono z RPO w sprawie.

Obawiam się, że osoby odpowiedzialne za projekt które są skupione wokół społeczności GitHub, nie są odpowiednimi osobami co do ustaleń w związku z edukacją polskiej policji.

Bezpośredni kontakt z ministerstwem cyfryzacji lub ministerstwem zdrowia, wydaje się lepszym pomysłem.

**Comment by SeraMoon** [comment]
Kontakt w tym temacie nie jest w moim interesie. Nie mam czasu dla projektu i prawdę mówiąc nie zależy mi na tym projekcie. Mieszkam obecnie poza Polską więc poziom edukacji Policji mnie też nie interesuje. Zgłosiłam tutaj jaką opinię o aplikacji ma RPO. To wszystko co mogę zrobić. Można to oczywiście olać ciepłym moczem i zamknąć, ale już inne portale piszą o tej sytuacji i nawet Panoptykon nazwał tą aplikację - aplikacja odbierającą pieniędze na aplikację o wątpliwej skuteczności - z pieniędzy które można było przeznaczyć na akcję pomagasie+#hot16challenge2. 

Myślę, że wszystko wyjaśniłam w tym temacie, resztę pozostawiam innym osobom i idę zająć się ważniejszymi projektami.

**Comment by Tarvald** [comment]
@SeraMoon 
20 dni i nikt nie skarżył się przymusową instalacja.
Również sama aplikacja jest reklamowana jaka dobrowolna.
**Czy można uznać to za pomyłkę i zamknąć temat?**
Nie wygląda to najlepiej na GH i może innych wprowadzać w błąd.
Nikt do niczego nie zmusza.

**Comment by SeraMoon** [comment]
@Tarvald czy ktokolwiek z zespołu kontaktował się z RPO? Adres RPO jest publiczny, można też zadzwonić. UODO faktycznie zajmuje się też sprawą ProteGO, więc sądzę, że temat jest nadal aktywny i może nie być to pomyłką

**Comment by kamilgthecoders** [comment]
To ewidentna pomyłka osoby - Aplikacja ProteGO Safe jest dobrowolna - temat zamykam.
