### ISSUE TITLE
Dodanie funkcjonalności tworzenia mapy ognisk epidemii

### ISSUE THREAD

**Issue by pjujeczko** [ProteGO-Safe/specs#186]
Szanowni Państwo,

na początku kwietnia wpadł mi do głowy pomysł, który zacząłem rozwijać. Chodziło o zbudowanie mapy, na której wizualizowałyby się aktualne statystyki zachorowań na Covid. Okazało się, że Koreańczycy mają takie mapy: [Data Science for Covid-19](https://github.com/ThisIsIsaac/Data-Science-for-COVID-19) to aplikacja pokazująca statystyki dla dzielnic Seulu, a [corona-nearby.com](https://corona-nearby.com/) pokazuje dokładne miejsce zamieszkania osób zakażonych z informacją o tym ile mieli kontaktów. 

Tutaj pojawia się pomysł dla ProteGO. Można by tworzyć statystykę dla dzielnic dużych miast z informacji o zakażeniach. Co więcej, po tym jak minie epidemia Covid-19 można pozostawić takie funkcje np. dla grypy (jak proponował @Dr-Kownacki).

W Polsce takie rozwiązanie jak w Korei nie mogłoby mieć miejsca z.wzg. na RODO i brak społecznej akceptacji dla takich ruchów jak umieszczenie przez rząd prawie dokładnego adresu chorego (i nie tylko, Koreańczycy na corona-nearby.com podają nawet wiek, płeć i jego narodowość...). Natomiast gdyby zachować odpowiednie "rozmycie" dokładności myślę, że wiele osób mogłoby się zgodzić na podzieleniem się informacją gdzie mniej-więcej są ogniska z wykorzystaniem informacji o ich chorobie. Szczególnie dla miast takich jak Warszawa, czy konurbacja śląska, podanie samych statystyk z powiatów czy miast to trochę mało.

Z mojej strony jest pomysł, który zrealizowałem, ale w przeciwieństwie do ProteGO nie mam możliwości weryfikacji danych, więc mój projekt spalił na panewce. Podział dużego miasta na dzielnice, albo duże obszary, potem sumowanie wyników i robienie heat-mapy jak w Data Science for Covid-19. Stronę można zobaczyć na [mapaognisk.pl](http://mapaognisk.pl), gdzie dzielę duże miasto na plastry o przekątnej 3km.

~~Wcześniej był pomysł w stylu corona-nearby.com, ale go zarzuciłem z uwagi na ryzyko ostracyzmu. Strona, na której można zaznaczać kołowe markery o średnicy 400m w miejscu gdzie się przebywało będąc zakażonym: [mapa-markery](http://mapaognisk.pl/markery). W dużym mieście 400m to wystarczająco dużo, żeby nie dało się określić o kogo chodzi, a dodawanie przypadków jest dobrowolne.~~ To wykreślam, bo widzę, że już sam pomysł budzi kontrowersje...

Tak jak mówię, po Covidzie funkcjonalność może zostać przeniesiona na grypę. Myślę, że to fajny przypadek takiego "Big Data" dla ludności, a dla osób w grupie ryzyka coś co może im uratować zdrowie. Użytkownicy ProteGO jako grupa otwarta na innowacje już są - może skorzystanie z tego byłoby użyteczne.

Pozdrawiam,
Paweł

**Comment by Dr-Kownacki** [comment]
Pomysł niby dobry dla miasta dużego, chociaż tam też są dzielnice, i jak się rozleje hejt to "blokersi z ławeczek" urządzić mogą blokadę ekipom z "zapowietrzonej dzielni"...
Zrobi się eskalacja typu - "O tam mieszka ta pielęgniarka, to na pewno ona" (i już Seicento nie ma szyb i powietrza w kołach...).

O mniejszych miejscowościach / wioskach z gospodarstwami nawet nie wspomnę...

Technicznie pomysł OK, ale realnie chyba strach...
Ciekawe jak w Korei to zadziałało i jakie powstały napięcia społeczne

Jeśli chodzi o "skażenie dzielnic/ulic" i ogólne monitorowanie przebiegu epidemii dla dużych obszarów to najlepsza jest analiza... ścieków (!).
Oznaczenie miana wirusa bo jest z kałem wydalany tak samo u chorych jak bezobjawowych nosicielki. W ten sposób można "namierzyć" jakąś szczególnie trafioną ulicę i tam przebadać wszystkich zanim mają objawy. Ponoć można o kilka dni takie ognisko wcześniej wykryć i jest wielki potencjał.

Genialnie prosta i skuteczna rzecz, ale nie wiem czy gdziekolwiek te info jest upubliczniane, bo stygmatyzacja tak samo b.realna ...

Ten kij ma moim zdaniem dwa końce niestety...

**Comment by SeraMoon** [comment]
> Koreańczycy na corona-nearby.com podają nawet wiek, płeć i jego narodowość...). Natomiast gdyby zachować odpowiednie "rozmycie" dokładności myślę, że wiele osób mogłoby się zgodzić na podzieleniem się informacją gdzie mniej-więcej są ogniska z wykorzystaniem informacji o ich chorobie. Szczególnie dla miast takich jak Warszawa, czy konurbacja śląska, podanie samych statystyk z powiatów czy miast to trochę mało.

Szkoda, że nie podają jeszcze rasy, religii i czy wyznaje ideologię gender oraz czy wierzy w latającego potwora spaghetti i daty ostatniej miesiączki. Jeżeli aplikacja ma używać tylko BT, a takie były obecne założenia (z serwera pobierana tylko lista tempID rozwiązania G+A) to nie jest wykonalne stworzenie takiej mapy. Wystarczy brak zgody osoby, która ma pozytywny test oraz niezgłoszenie się do sanepidu osób, które dostały "czerwone" powiadomienia. 

**3xNIE** (wersję graficzną sobie daruję) dla takiego rozwiązania.

Przypomnę tylko, że w jednym mieście oznaczano miejsca kwarantanny i zaprzestano tego, bo ludzie padali ofiarami hejtu. Niestety w Polsce mamy 36 do 51% hejterów (tak wynika z sondaży). Ten kraj jest bardzo agresywny.

**Comment by pjujeczko** [comment]
@Dr-Kownacki Dziękuję za odpowiedź. Nie zaznaczyłem, że faktycznie taka mapa byłaby tylko dla dużych miast i tylko w sytuacji gdy ogniska faktycznie są, a nie w momencie gdy mamy po kilka przypadków tu i tam. To jest opcja na powrót epidemii - oczywiście tego sobie i innym nie życzę, ale jak myślałem o tym, to atmosfera w kraju była dużo bardziej napięta. Może warto być przygotowanym.

@SeraMoon bardzo proszę jakieś dane na temat tych sondaży, bo nic nie udało mi się znaleźć, a informacja wydaje się, że może być fake-newsem (przynajmniej ja mam zupełnie inne doświadczenia z naszym krajem (raczej ludzie są mili), choć oczywiście w strachu rodzą się różne patologie).

**Comment by Dr-Kownacki** [comment]
@pjujeczko akurat mam coś pod ręką ;-)

https://github.com/ProteGO-Safe/specs/issues/96#issuecomment-615728260

**Comment by RMalczynski** [comment]
@pjujeczko, nie jesteśmy w stanie wdrożyć proponowanej funkcjonalności choćby poprzez ograniczenia narzucone przez samo ExposureNotification - korzystając z EN nie możemy jednocześnie korzystać z lokalizacji.

**Comment by SeraMoon** [comment]
> Tak jak mówię, po Covidzie funkcjonalność może zostać przeniesiona na grypę.

Czym się różnią te 2 choroby? Ilością śmierci na świecie się nie różnią. Różnią się tylko wyglądem wirusa i tym, że przy grypie wszyscy są objawowi?

**Comment by pjujeczko** [comment]
@RMalczynski Dziękuję za odpowiedź. Myślę, że tego nie powinno się robić przez ExposureNotification też przez względy potencjalnego nadużycia. Jeśli ProteGO ma dostęp do bazy z zachorowaniami, z tej samej bazy mógłby też pobierać miejsce, w którym przebywa osoba na kwarantannie.

Ps czy mogę prosić o zablokowanie też pierwszego komentarza SaraMoon? Autorka zakłada chyba, że jestem jej wrogiem (tak samo jak w drugim komentarzu) i stara się mnie obrazić...

**Comment by SeraMoon** [comment]
@pjujeczko przypomnę, że jesteśmy na forum, na którym panuje wolnośąć wypowiedzi, więc ja na podstawie tej wolności wypowiedzi proponuję o zablokowanie twojego posta powyżej. 

Wskażę, że w przypadku miejscowości typu "Pcim dolny podwrocławski" to już samo wskazanie miejscowości (do 200 osób) może na represje wystawić osobę, która zostanie zdiagnozowana. Informacje się po takich wsiach rozchodzą jak ciepłe bułeczki a hejt tam bywa niemniejszy (im bliżej wschodniej granicy kraju tym więcej). Toteż dla takiego rozwiązania tym razem w formie graficznej: 

![3xNIE](https://bi.im-g.pl/im/05/1b/15/z22133253V,Logo--3xNIE-.jpg)

Wirus nie rozchodzi się dzielnicami, tylko gdy się pojawi w bardziej zaludnionym miejscu, w kilka dni opanuje okoliczne wioski i miasteczka. Jeżeli ma już być raportowane to ziarnistością powinny być powiaty lub województwa i tak to jest obecnie podawane. Nie problem by aplikacja wyświetlała tą właśnie mapę, którą znaleźć można na wikipedii. Jednak dla dokładności co do dzielnicy / wsi - **3xNIE**.

**Comment by SeraMoon** [comment]
@pjujeczko przypomnę, że jesteśmy na forum, na którym panuje wolnośąć wypowiedzi, więc ja na podstawie tej wolności wypowiedzi proponuję o zablokowanie twojego posta powyżej. Nieprawdą jest, że zarzucam tobie bycie wrogiem. Rozwiązanie które proponujesz jednak jest wrogiem prywatności ludzi a to już całkiem co innego (szczegóły na końcu tego posta).

Wskażę, że w przypadku miejscowości typu "Pcim dolny podwrocławski" to już samo wskazanie miejscowości (do 200 osób) może na represje wystawić osobę, która zostanie zdiagnozowana. Informacje się po takich wsiach rozchodzą jak ciepłe bułeczki a hejt tam bywa niemniejszy (im bliżej wschodniej granicy kraju tym więcej). Toteż dla takiego rozwiązania tym razem w formie graficznej: 

![3xNIE](https://bi.im-g.pl/im/05/1b/15/z22133253V,Logo--3xNIE-.jpg)

Wirus nie rozchodzi się dzielnicami, tylko gdy się pojawi w bardziej zaludnionym miejscu, w kilka dni opanuje okoliczne wioski i miasteczka. Jeżeli ma już być raportowane to ziarnistością powinny być powiaty lub województwa i tak to jest obecnie podawane. Nie problem by aplikacja wyświetlała tą właśnie mapę, którą znaleźć można na wikipedii. Jednak dla dokładności co do dzielnicy / wsi - **3xNIE**. 

By nie być gołosłowną - wskażę, że problem istniał z "pacjentem zero" - podano jego dzielnicę i już 2 dni później krążyło po sieci jego zdjęcie oraz imię i nazwisko. Wszystko do znalezienia w Google, łącznie z jego nazwiskiem. Tym na pewno nie zachęcisz by ludzie udawali się z chorobą do szpitali - wręcz przeciwnie - zaczną się bać i będą chorować nawet ciężko w domu, pomijając już sam fakt, że testy wymazowe na covid są przewspaniale bolesne (ze względu na nietypowe miejsce pobrania materiału genetycznego wirusa).

**Comment by pkleczko** [comment]
nie ma planów na taką funkcjonalność. w związku z brakiem aktywności w wątku pozwolę sobie go zamknąć.
