### ISSUE TITLE
Kod aplikacji w wersji 4.1.0

### ISSUE THREAD

**Issue by jasisz** [ProteGO-Safe/specs#188]
Pojawił się dzisiaj, jakoś bez żadnego ogłoszenia:
https://github.com/ProteGO-Safe/ios/tree/release/4.1.0-rc.1
https://github.com/ProteGO-Safe/android/tree/release/4.1.0-rc.1
https://github.com/ProteGO-Safe/web/tree/release/4.1.0

Także w każdym repozytorium potężna dawka nowego kodu, co ciekawe z rozbiciem na setki commitów z tymi "wewnętrznymi" numerami issues.

Dalej brakuje jakiegokolwiek kodu backendowego. Ktoś wie co się stało z wersją 4.0?

**Comment by kwiszowaty** [comment]
@MateuszRomanow Jak rozumiem projekt przestał być publiczny i idziecie w stronę zasady: jak nie pokażemy nic, to nie będę komentować. A przecież dodaliście kolejne osoby do "zespołu odpowiadającego".

Pomimo Waszych zapewnień o przejrzystości kolejny raz obserwujemy podejście, że mówicie jedno a robicie zupełnie co innego.
Ja nie wyobrażam sobie efektywnej pracy bez specyfikacji i jak wydajecie kod, to taka musi istnieć. Więc po prostu nie chcecie jej udostępnić, bo innego powodu braku jej tutaj (#147) nie widzę.

Myślałem, że to już idzie w dobrym kierunku, ale chyba się przeliczyłem. :(

**Comment by Tarvald** [comment]
@kwiszowaty @jasisz 
Będzie ogłoszenie, będzie dokumentacja.

Cierpliwości.

**Comment by kwiszowaty** [comment]
@Tarvald 
Będzie, będzie - wiem, że kiedyś w końcu będzie, bo musi.

Chodzi mi o kolejność pojawiania się informacji. W Waszej specyfikacji, którą zobowiązaliście się aktualizować, jest cisza od prawie miesiąca. Czy to oznacza, że nic nie robicie? Pewnie nie. Czy to oznacza, ze coś chcecie ukryć? Tak to może wyglądać...

Jak nie macie nic do ukrycia, to nie wiem dlaczego nie można tego udostępnić wcześniej a dopiero po wydaniu kodu? Weźmy za przykład G+A - oni zaczęli od dokumentów. Dobrze je przemyśleli zanim zaczęli prace. A nawet jak coś się zmieniało w trakcie, to uaktualniali dokumentację jak najszybciej.

**Comment by MateuszRomanow** [comment]
@kwiszowaty od wczoraj zdecydowanie więcej updatów będzie wjeżdżało tutaj - między innymi dokumentacja właśnie, na tym nam bardzo zależy, żebyśmy wszyscy mieli tą samą dokumentację. 

Więcej opisałem w #189 .

**Comment by Tarvald** [comment]
@jasisz 
Zamykam w związku z #189.

**Comment by Tarvald** [comment]
@jasisz 
Jeżeli #189 rozwiązuje twój problem to prosiłbym o zamknięcie.
Ma bardzo podobny temat jak #189

**Comment by jasisz** [comment]
Proponuję więc zamknąć https://github.com/ProteGO-Safe/specs/issues/189 jako duplikat.

**Comment by Tarvald** [comment]
#189 odpowiada na wiele pytań z tego wątku. 
W razie wątpliwości zapraszam do zadawania pytań w #189

**Comment by SeraMoon** [comment]
> Będzie ogłoszenie, będzie dokumentacja.

wSzystko będzie, gdy nastąpi święte nigdy. Nie trzymacie się założeń #147 . 

### Zaufanie #149 #141 #145 #148 #157 #142 #136 #129 już całkowicie straciliście.

**Comment by Tarvald** [comment]
> wszystko będzie, gdy nastąpi święte nigdy. Nie trzymacie się założeń #147 .

Ogłoszenie już jest.
A dokumentacja będzie wraz z oficjalnym wydaniem (a nawet wcześniej).
Narazie publikujemy kod w wersji RC!

Podkreślam ### RC
