### ISSUE TITLE
Audyt bezpieczeństwa i prywatności Exposure Notification

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#193]
**Is your feature request related to a problem? Please describe.**
#141 #135 #145 #146 #129 #191

**Describe the solution you'd like**
Niezależny polski ekspert (np. Niebezpiecznik) dokona audytu **modułu** oprogramowania w oparciu o otwarty kod źródłowy rozwiązania Exposure Notification, potwierdzając tym samym, że kod wykonuje tylko to do czego został stworzony, zaś chwilowe diagnosis key nie są agregowane nigdzie z jakimkolwiek innym identyfikatorem lub danymi pozwalającymi stwierdzić kim jest jego posiadacz.  

**Describe alternatives you've considered**
W przypadku braku pozytywnego wyniku audytu - rozwój własnego protokołu do Contact Tracingu. 

**Additional context**
\x00

**Comment by MateuszRomanow** [comment]
> Mój komentarz: Tak jak wielokrotnie już pisałem w ciągu ostatnich paru dni - to po stronie rządu teraz jest piłeczka żeby naciskać G+A na a) audyt b) docelowe jak największe otwarcie kodu. Jak widać rządy mają narzędzia do tego, żeby iść w tym kierunku i Google i Apple im to umożliwiają bo zależy im na tym, żeby ich rozwiązanie było jak najbardziej (w miarę możliwości na chwilę obecną) otwarte.

@potiuk temat otwartej rozmowy z Google i Apple w tym obszarze jest dla nas ważny, dlatego jak wspominałem, pilotowałem żeby Ministerstwo Cyfryzacji formalną drogą było w kontakcie. Poprosiłem o ska tego co zostało wysłane. Poniżej list napisany i wysłany w tej sprawie przez Ministra Zagórskiego. 

[List MMZ.pdf](https://github.com/ProteGO-Safe/specs/files/4774206/List.MMZ.pdf)
