### ISSUE TITLE
Prezentacja ProteGO Safe dla community GitHub

### ISSUE THREAD

**Issue by kamilgthecoders** [ProteGO-Safe/specs#194]
Cześć,
mam dla was świetną wiadomość. 

W poniedziałek o godzinie 15:00 zostanie zorganizowana i przeprowadzona prezentacja ProteGO Safe dla community GitHub przed premierą aplikacji.

Spotkanie odbędzie się w obecności 
- Ministra Marka Zagórskiego, 
- przedstawicieli Ministerstwa Cyfryzacji 
- oraz zespołu wykonującego aplikację. 

Termin: poniedziałek 08.06.2020 od 15:00 do 16:00.
Spotkanie będzie trwało równo 60 minut więc ilość pytań jest ograniczona czasowo. 

Prośba, do tych którzy są zainteresowani wzięciem udziału w prezentacji o **potwierdzenie w komentarzu swojego udziału**. 

Chcemy poznać przybliżoną liczbę chętnych (to nie są zapisy).

Prezentacja będzie dostępna przez link do wideokonferencji.
Link zostanie podany wkrótce.

**Comment by potiuk** [comment]
Czy można będzie wyrażać wątpliwości i zadawać pytania ?

**Comment by kamilgthecoders** [comment]
@potiuk tak

**Comment by potiuk** [comment]
OK. To wstępnie potwierdzam.

**Comment by potiuk** [comment]
A czy będzie to nagrane? Myślę że warto takie rzeczy nagrywać i publikować dla tych, którzy nie będą mogli uczestniczyć na żywo. W zasadzie wszystkie narzędzia do wideo konferencji mają to wbudowane.

**Comment by kamilgthecoders** [comment]
Spotkanie nie będzie nagrywane.

**Comment by SeraMoon** [comment]
@potiuk i inni, którzy chcą mieć nagrane, polecam więc OBS Studio i potem publikację na YouTube.

**Comment by MateuszRomanow** [comment]
Kamil widzę dość lakonicznie odpowiedział, postaram się rozwinąć. 

Żeby nagrywać spotkanie potrzebna by była zgoda wszystkich obecnych, głosy, wizerunki - przecież nie jesteśmy osobami publicznymi - dużo papierologii. Architekci aplikacji nie mają na tą chwilę przestrzeni na organizowanie takiego eventu - zależy nam na pokazaniu tego co będzie publikowane i dyskusji. Jeżeli ktoś chce nagrywać innych bez ich zgody... ja tego nie będę robił na pewno. 

Niezależnie - takie pytanie przekażę zaraz do Ministerstwa Cyfryzacji, żeby chociaż kierunkowo zasygnalizować temat.

**Comment by SeraMoon** [comment]
To spotkanie ma sens tylko wtedy gdy będzie nagrywane i najlepiej gdy będzie nagrywane przez kogoś niezależnego stąd - niezależnego od zespołu i niezależnego od Ministerstwa, aby nagranie potem nie przepadło. Wciąż polecam OBS Studio. Spotkanie powinno być jak najbardziej oficjalne. 
 
Głosy innych osób i ich wizerunki - wizerunek osób pytających jest zbędny - kamerką można zakleić (najszybsze co można wykonać, aby nie bawić się w BIOS-y, wirtualne kamery itp. 

Głos można albo zniekształcić albo też posłużyć się lektorem elektronicznym czytającym to co napiszemy. 

Przy linku należy uprzedzić, że konferencja jest nagrywana i wchodząc tam, zgadzamy się na to, na utrwalenie oraz publikację (podać gdzie). Nikt ze strony Ministerstwa nie powinien zasłaniać się anonimowością przed obywatelami.

**Comment by jasisz** [comment]
Postaram się wpaść jak mi robota nie stanie okoniem.

**Comment by potiuk** [comment]
@MateuszRomanow ? 

Ale rozumiem że nie ma problemu żeby nagrywać głos a potem zrobić z tego publiczną transkrypcję w stylu "osoba a powiedziała x" "osoba b powiedziała y". obecne technologie na to pozwalają. Można to robić ręcznie, ale transkrypcja automatyczna też zadziała. 

Rozumiem że osoby uczestniczące w tym (publicznym) wydarzeniu nie będą miały żadnych ograniczeń co do publikacji informacji i treści które na tym spotkaniu padną?

Prosiłbym o potwierdzenie bo nie chciałbym być zaskoczony tuż przed wejściem na spotkanie że zobowiązuję się do czegoś, do czego nie chciałbym się zobowiązywać.

**Comment by sub-zero-pl** [comment]
Robi się coraz ciekawiej. Nie można nagrywać bo rodo...ewenement na skalę światową.

Jeśli mniej istotne konferencje sobie z tym radzą to świadczy tylko i wyłącznie o czyjejś nieudolności.

Pozdrawiam

**Comment by AlanAjverson** [comment]
Witam,
Śledzę projekt od dłuższego czasu. 
Chętnie wziąłbym udział w takim spotkaniu, jednak wolałbym aby nie było nagrywane. Mam parę pytań ale obawiam się represji że strony "dziennikarzy" którzy ewidentnie szukają sensacji na tym forum aby zwiększyć zasiegi swoich kont w socjal mediach. Wymuszanie zgodny na nagrywanie na użytkownikach odstraszy ludzi z uczestnictwa a z tego co wiem to nie jest tajne spotkanie więc jego przebieg i tak będzie ujawniony ze zgodą czy bez.

**Comment by potiuk** [comment]
@MateuszRomanow  - padła wcześniej prośba, żeby informować ile osób będzie więc ja od razu powiem że zaprosiłem sporo osób. W świetle #189 ale przede wszystkim #195 możecie się spodziewać jeszcze paru osób. Nie wiem czy przyjdą ale zaproszenie dostały osoby ewidentnie zainteresowane rozwojem aplikacji i zarówno tematami bezpieczeństwa jak i prywatności.

Myślę że dobrze by było żebyście byli dobrze przygotowani do pytań które będą zadane - i najpewniej będą się koncentrować dookoła tych dwóch punktów (a w zasadzie jednego - online PWA i jego konsekwencji w kwestiach bezpieczeństwa i prywatności).

Zaprosiłem:

* Artura Kurasińskiego - robił ze mną wywiady w https://blog.kurasinski.com/2020/05/protego-safe-dlaczego-nie-nalezy-instalowac-aplikacji-ministerstwa-cyfryzacji/ i https://blog.kurasinski.com/2020/05/jarek-potiuk-musimy-zaufac-technologii/

* 2 osoby z https://niebezpiecznik.pl/

* publicystkę zajmująca sie prywatnością - ostatnio napisała ten artykuł https://www.dw.com/en/coronavirus-contact-tracing-reignites-polish-privacy-debate/a-53600913

* jednego z członków zarządu Helsinskiej Fundacji Praw Człowieka - bardzo zainteresowany całą sprawą od paru tygodni

* 2 osoby z developer relations z Google i Apple z którymi rozmawiałem wcześniej i którzy monitorowali sprawy review w Apple i Google

* minister Annę Streżyńską z którą rozmawiałem żeby zrozumieć jak powstają projekty w Ministerstwie Cyfryzacji

* o prezentacji poinformowałem też Europejskiego Inspektora Ochrony Danych osobowych - nie wiem czy będzie zainteresowany na tym etapie, ale może ktoś się od niego pojawi

Więc potencjalnie będzie z mojej strony do 10 osób.

**Comment by kwiszowaty** [comment]
Potwierdzam chęć wzięcia udziału w spotkaniu.

Do społeczności mam jedną uwagę: może przygotujmy sobie listę pytań posegregowaną wg priorytetów (które można wspólnie ustalić)? Myślę, że niektóre z pytań jakie zadał @potiuk w #189 będą u góry listy. Z doświadczenia wiem, że jak jest dużo ludzi, to jest dużo pytań, przez co wiele z nich ginie w gąszczu dyskusji, a prowadzący wybierają tylko te najbardziej im pasujące. Czasu na pewno nie starczy na wszystkie...

**Comment by miklobit** [comment]
> Żeby nagrywać spotkanie potrzebna by była zgoda wszystkich obecnych, głosy, wizerunki - przecież nie jesteśmy osobami publicznymi - dużo papierologii. Architekci aplikacji nie mają na tą chwilę przestrzeni na organizowanie takiego eventu - zależy nam na pokazaniu tego co będzie publikowane i dyskusji. Jeżeli ktoś chce nagrywać innych bez ich zgody... ja tego nie będę robił na pewno.
Proszę uprzejmie nie wprowadzać czytelników w błąd.
Żeby nagrywać spotkanie w którym się samemu uczestniczy nie jest potrzebna niczyja zgoda. Co innego udostępnianie nagrania poza grono uczestników. 
Inna sprawa jak zamierzacie wyegzekwować swój brak zgody na upublicznienie takiego nagrania (które na 100% będzie nagrywane bo nie macie żadnych technicznych środków aby komuś to uniemożliwić lub sprawdzić czy nagrywa) ?
Bierzecie udział w projekcie finansowanym w 100% z publicznych pieniedzy,  wszyscy twórcy są podpisani z imienia i nazwiska (https://github.com/ProteGO-Safe/specs/blob/master/CONTRIBUTORS.md), aplikacja ma otwarty kod, MC twierdzi ,że "Kluczowe są dla nas pełna przejrzystość, transparentność..." ( https://www.gov.pl/web/cyfryzacja/protego-safe--pobierz-zainstaluj-przetestuj ) , wszystko co dotyczy projektu JEST INFORMACJĄ PUBLICZNĄ
a my tu czytamy (w publicznym BTW issue), że prezentację mamy traktować jak prywatny event ?
Czy wasz zespół razem z MC zdaje sobie sprawę, że takimi zagraniami tracicie resztki jakiejkolwiek przyzwoitości ?
Tak technicznie i konkretnie 
- link do konferencji będzie podany tutaj publicznie ? 
- osoby chcące dołączyć do transmisji będą musiały się zidentyfikować jakimiś danymi ( imie nazwisko, konto GH ) ?

**Comment by kamil98** [comment]
@kamilgthecoders Gdzie dokładnie będzie podany link?

**Comment by kamilgthecoders** [comment]
@miklobit @kamil98 Link będzie podany na GH w poście tego wątku.

**Comment by Tarvald** [comment]
@miklobit 
> a oczekujecie (w publicznym BTW issue), żebyśmy prezentację traktowali jak prywatny event 

Nikt tego nie oczekuje, event jest publiczny, każdy będzie mógł w nim wziąć udział.

> Chciałbym oglądać prezentację i NIE zobowiązuję się do jej nie-nagrywania.

Jesteś wolnym człowiekiem, możesz zrobić co chcesz.

> Inna sprawa jak zamierzacie wyegzekwować swój brak zgody na upublicznienie takiego nagrania.

**To nie jest brak zgody!!!** My poprostu nie będziemy tego nagrywać.
Jeżeli ktoś chce łamać prawo to jest jego prywatna sprawa.

> link do konferencji będzie podany tutaj publicznie ?

Tak

@potiuk 
> Więc potencjalnie będzie z mojej strony do 10 osób.

O taką informacje nam chodziło :)

> Ale rozumiem że nie ma problemu żeby nagrywać głos a potem zrobić z tego publiczną transkrypcję w stylu "osoba a powiedziała x" "osoba b powiedziała y". obecne technologie na to pozwalają. Można to robić ręcznie, ale transkrypcja automatyczna też zadziała.

Jeżeli to jest zgodne z prawem i nie wymaga nikogo zgody to tak.

@kwiszowaty 
> Do społeczności mam jedną uwagę: może przygotujmy sobie listę pytań posegregowaną wg priorytetów

Jeżeli taką liste zrobicie, to bardzo chętnie przypne wątek żeby był lepiej widoczny. Jeżeli potrzebujesz innej formy pomocy to też daj znać.

@AlanAjverson 
> Wymuszanie zgodny na nagrywanie na użytkownikach odstraszy ludzi z uczestnictwa a z tego co wiem to nie jest tajne spotkanie więc jego przebieg i tak będzie ujawniony ze zgodą czy bez

Zgadzam się, jest to publiczne spotkanie i napewno będzie dyskutowane szeroko na tym forum.
Pan @potiuk zaprosił 10 osób a kto wie ile jeszcze przyjdzie, nie każdy może mieć chęć bycia nagrywanym.

**Comment by Tarvald** [comment]
@miklobit 
> a oczekujecie (w publicznym BTW issue), żebyśmy prezentację traktowali jak prywatny event 

Nikt tego nie oczekuje, każdy będzie mógł w nim wziąć udział.

> Chciałbym oglądać prezentację i NIE zobowiązuję się do jej nie-nagrywania.

Jesteś wolnym człowiekiem, możesz zrobić co chcesz.

> Inna sprawa jak zamierzacie wyegzekwować swój brak zgody na upublicznienie takiego nagrania.

**To nie jest brak zgody!!!** My poprostu nie będziemy tego nagrywać.
Jeżeli ktoś chce łamać prawo to jest jego prywatna sprawa.

> link do konferencji będzie podany tutaj publicznie ?

Tak

@potiuk 
> Więc potencjalnie będzie z mojej strony do 10 osób.

O taką informacje nam chodziło :)

> Ale rozumiem że nie ma problemu żeby nagrywać głos a potem zrobić z tego publiczną transkrypcję w stylu "osoba a powiedziała x" "osoba b powiedziała y". obecne technologie na to pozwalają. Można to robić ręcznie, ale transkrypcja automatyczna też zadziała.

Jeżeli to jest zgodne z prawem i nie wymaga nikogo zgody to tak.

@kwiszowaty 
> Do społeczności mam jedną uwagę: może przygotujmy sobie listę pytań posegregowaną wg priorytetów

Jeżeli taką liste zrobicie, to bardzo chętnie przypne wątek żeby był lepiej widoczny. Jeżeli potrzebujesz innej formy pomocy to też daj znać.

@AlanAjverson 
> Wymuszanie zgodny na nagrywanie na użytkownikach odstraszy ludzi z uczestnictwa a z tego co wiem to nie jest tajne spotkanie więc jego przebieg i tak będzie ujawniony ze zgodą czy bez

Zgadzam się, jest to publiczne spotkanie i napewno będzie dyskutowane szeroko na tym forum.
Pan @potiuk zaprosił 10 osób a kto wie ile jeszcze przyjdzie, nie każdy może mieć chęć bycia nagrywanym.

**Comment by SeraMoon** [comment]
@AlanAjverson 
Zauważ, że dałam Ci rozwiązanie - zadaj pytania poprzez lektora elektronicznego - jest kupa stron online czytających tekst, jak też apek, jest też coś w Windowsie (nie wiem jak uruchomić, ale jest coś co czyta zawartość okna i wystarczy aktywować to + notatnik - używam Linuxa). 

Wizerunek - zaklej po prostu kamerkę - zadziała wszędzie nawet na smartfonie. 

Identyfikacja po koncie - zależnie od platformy po prostu załóż sobie konto "anonimowe" czyli z innym nickiem z innej przeglądarki lub z Tora. Załatwione - **nie bęrdziesz represjonowany, bo nie będą wiedzieli kogo represjonować... 

Co zaś do osób z rządu - reprezentują kraj - nie ma tu mowy o tym, aby media nie miały dostępu do ich wypowiedzi i decyzji. To decyzje o nas obywatelach, za nasze pieniądze i **transparentność się nam należy**. 

Odnośnie transkrypcji - jest to coś ale nie wszystko. nie mamy pewności co zostało wycięte, ma też wpływ intonacja, inne sprawy. Przykład:
- "żyć nie, (ostęp czasowy) umierać"
- "żyć, (odstęp czasowy) nie umierać"
Chyba robi diametralną różnicę? 

@potiuk 
zaproś proszę kogoś z Panoptykonu jeżeli masz z nimi kontakt :-)

> Żeby nagrywać spotkanie potrzebna by była zgoda wszystkich obecnych, głosy, wizerunki 
(i pokrewne)

załatwie zaklejenie kamerki, użycie lektora, niewchodzenie ze swojego oficjalnego konta. Mediom (Panoptykon, Niebezpiecznik, dziennikarze) raczej nie będzie przeszkadzało, że są nagrywani - sami się nagrywają i publikują.

**Comment by potiuk** [comment]
Jeśli chodzi o listę pytań w trakcie dzisiejszej prezentacji, to wydaje mi się że nie będzie czasu ani zadawać szczegółowych pytań technicznych dotyczących bezpieczeństwa - tu na odpowiedzi czekam w wątku #189, ani takie które sprowokowały by "rozmydlanie spraw". 

Nawet ostatnie dyskusje dotyczące online PWA są ewidentnie i konsekwentnie rozmydlane przez @MateuszRomanow który ciągle przekierowuje dyskusję na "PWA" vs.  "native" tam gdzie go w ogóle nie powinno być - mimo kilkukrotnego podkreślania że to nie jest tematem dyskusji. Nie chcę wnikać w to, dlaczego się tak dzieje (choć mam swoje domysły). Ale chciałbym tego uniknąć.

Zakładam że będzie sporo uczestników więc proponuję skupić się na najważniejszych kwestiach. To pierwsze spotkanie na którym (podobno) społeczność będzie mieć możliwość zadania pytania Ministrowi Zagórskiemu - który de-facto decyduje o rozwoju aplikacji. On nie jest w stanie odpowiedzieć na żadne pytania techniczne (ale do tego GitHub jest o wiele lepszy niż tego rodzaju prezentacja).

Jeśli chodzi o Twórców aplikacji, to według mnie - w ogóle  nie powinniśmy zadawać im pytań w  tej rozmowie - wielokrotnie mówili że oni nie podejmują żadnych decyzji - wszystkie podejmuje MC.

Dlatego proponowałbym żebyśmy się skupili na zadaniu pytań tylko i wyłącznie Ministrowi Zagórskiemu - w taki sposób żeby mógł na nie odpowiedzieć sam, bez wyręczania się kimkolwiek z zespołu Twórców aplikacji.

Moje propozycje są takie:

1) W jaki sposób rząd przygotowuje logistykę dla osób które aplikacja zidentyfikuje jako zagrożone. W  szczególności: 
   * Jakie zalecenia osoby zidentyfikowane jako zagrożone będą otrzymywać? Czy będą darmowe testy dla tych osób ?
   * Jaki będzie czas w którym osoba zidentyfikowana będzie mogła przeprowadzić badania?
   * W jaki sposób rząd zamierza zapewnić że będzie to fizycznie łatwe dla tych osób.

2)  Jak dużo tradycyjnych "contact tracerów" rząd zamierza przeznaczyć/zatrudnić do "contacttracing". Jak wielokrotnie dyskutowaliśmy aplikacja może być tylko dodatkiem do tradycyjnego "contact tracing" I jak podkreślają eksperci i doświadczenia innych państw jej użyteczność jest tylko "pomocnicza" -  co rząd robi w tej sprawie ?

3) Czy rząd świadomie wybrał rozwiązanie (online PWA) w którym możliwe jest z ich strony personalna identyfikacja osób które aplikację mają zainstalowaną ? Czy wiedzą że to jest niezgodne z wytycznymi EU, 7 filarami zaufania Panoptykonu, i czy wiedzą że rozwiązanie proponowane przez niezależnych programistów (embedded PWA) spełnia dokładnie taką samą rolę w "kontakt tracing" ale bez możliwośći identyfikacji tych osób? Czy zdają sobie sprawę że ta jedna decyzja spowoduje że społeczność będzie nawoływała do nie instalowania tej aplikacji ?

4) Czy rząd zdaje sobie sprawę z zagrożeń bezpieczeństwa wynikających z wyboru online PWA i z tego, że alternatywa ("embedded PWA") zaproponowana przez niezależnych programistów jest bardzo łatwa do wprowadzenia i rozwiązuje zdecydowaną większość problemów z bezpieczeństwem aplikacji?

To by były moje pytania.

**Comment by SeraMoon** [comment]
@potiuk @tomekziel @kamilgthecoders może warto zadać pytanie #149 ? To jest typowe nietechniczne pytanie o zapewnienie, że aplikacja nigdy nie stanie się przymusowa z przymusem włączenia EN i Bluetooth? Należy uważać na wyrażenia zwodnicze typu "nie planujemy", "prawdopodobnie" itp.

**Comment by kwiszowaty** [comment]
@potiuk 
Masz racę - to nie będzie miejsce na techniczną rozmowę. Tą zostawmy na GH.
Jak dla mnie Twoje pytania są OK, ale ja bym proponował inną kolejność: 3, 4, 1, 2.
Pomimo, że uważam pytania 1 i 2 za bardzo ważne, to boję się, że odpowiedzi na nie mogą "zjeść" nasz cały czas antenowy - wyobrażam sobie, że można na nie bardzo długo odpowiadać (niekoniecznie na temat).

A nam chyba chodzi o to by na spotkaniu o aplikacji poruszyć najbardziej newralgiczną kwestię jaką jest prywatność i bezpieczeństwo - tak by aplikacja byłą szeroko akceptowalna przez społeczeństwo.
Pytania 1 i 2 dotyczą bardziej całego procesu, a to można zostawić dziennikarzom czy innym instytucjom mniej technicznym.

**Comment by D0han** [comment]
Nie wiem czy będę w stanie się pojawić na prezentacji, więc proszę o zadanie pytania:
- Dlaczego rozwój tego 'otwartego' projektu jest prowadzony w większości za zamkniętymi drzwiami zamiast w sposób otwarty wzorem GitLab?

**Comment by potiuk** [comment]
@SeraMoon @kwiszowaty @D0han ^^ zaktualizwane za waszymi sugestiami.

**Comment by D0han** [comment]
@potiuk wymień proszę GitLab z nazwy, ponieważ tam w publicznych issue podejmowane są też decyzje czy spisywane podsumowania ze spotkań. Tego tutaj nie ma, a jest potrzebne jeśli faktycznie projekt miałby być prowadzony wraz ze społecznością.

**Comment by potiuk** [comment]
@D0han . Spoks. -> dorzuciłem tam też mój Apache Airflow jako przykład.

**Comment by MateuszRomanow** [comment]
Hej,
agenda jest następująca:
1. Wprowadzenie - Minister Zagórski 
2. Prezentacja Aplikacji - team deweloperski
3. Prezentacja Centrum Kontaktu - Ministerstwo Cyfryzacji 
4. Pytania i odpowiedzi - techniczne
5. Pytania i odpowiedzi - do Ministerstwa Cyfryzacji 

ze strony deweloperskiej jest większy zespół, więc jak najbardziej techniczny charakter spotkania też jest przewidziany. Ze strony Ministerstwa podobnie. 

Będziemy zgłaszać się do pytań i odpowiedzi przez "Podnieś rękę" w oknie rozmowy Teams. 
Moderację poprowadzimy wraz z @pwicherski
ps na pytania zebrałem odpowiedzi w  #189 

Do usłyszenia!

**Comment by sub-zero-pl** [comment]
>Czy Ministerswo może się zobowiązać że nigdy aplikacja nie bęðzie przymusowa i że nie będzie się z nią wiązały żadne formy dyskryminacji lub teź benefitów wynikających z faktu zainstalowania aplikacji (dotyczy to również promocji aplikacji przez podmioty prywatne tak jak to było w przypadku wytycznych do sklepów opublikowanych przez mnisterstwo rozwoju czy planów na "odmrażanie" gospodarki ujawnione przez Związek Przedsiębiorców i Pracodawców


Dodaj proszę na wstępie "wiemy że tego nie planujecie ale...."

Bo inaczej odpowiedz będzie zapewne w stylu "nie ma takich planów".

Pozdrawiam

**Comment by kamilgthecoders** [comment]
Link do spotkania: 
https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZDA2MDc2MDgtMGY0Zi00ZTgwLTkzYTYtNDdlOWNmMjMwNTRj%40thread.v2/0?context=%7b%22Tid%22%3a%22a9cf8755-a7b8-4b4d-babb-7057868c9563%22%2c%22Oid%22%3a%22c016eef2-ca79-4d1c-8180-081eac984cbd%22%7d

Prosimy o kulturę w dyskusji.
Spotkanie będzie moderowane.

**Comment by kierepka** [comment]
Trochę późno przyszedł link. Czy można oglądnąć spotkanie?

**Comment by MateuszRomanow** [comment]
Jeszcze raz - wielkie dzięki za bardzo merytoryczne spotkanie! 
Mam nadzieję, że w dalszych dyskusjach tutaj będziemy kontynuować ten klimat z prezentacji. 
Sorry za przynudnawe opowiadanie, ale trudno o tym opowiedzieć w emocjonujący sposób, kiedy sama aplikacja jest już dość "nudna". 

Formuła się sprawdziła :)

**Comment by MateuszRomanow** [comment]
> Trochę późno przyszedł link. Czy można oglądnąć spotkanie?

Link poszedł dokładnie tak jak był zapowiadany - o 14:50 .

**Comment by tomekziel** [comment]
> Hej,
> agenda jest następująca:

@MateuszRomanow, dzięki za organizację i przeprowadzenie prezentacji - no i sam wynik dyskusji bardzo obiecujący. Dobra robota!

**Comment by rafake** [comment]
@tomekziel @potiuk - czy ktoś nagrywał w końcu tę dyskusję i będzie dostępne nagranie?
Pozdro dla całego zespołu i komentatorów - działacie we wspólnej sprawie i to jest mega fajne.

**Comment by potiuk** [comment]
Tak. Prezentacja była nagrana przez organizatorów @MateuszRomanow - może warto ją opublikować, Jakby co to ja wyrażam zgodę.

**Comment by RMalczynski** [comment]
@potiuk koniec końców po wejściu na spotkanie w Teams u góry wyświetlał się baner z informacją, że uczestnicząc w spotkaniu wyrażasz zgodę na nagrywanie - z tego co rozumiem, to nikt nie powinien mieć nic przeciwko publikacji nagrania 🙂

**Comment by miklobit** [comment]
> Tak. Prezentacja była nagrana przez organizatorów @MateuszRomanow - może warto ją opublikować, Jakby co to ja wyrażam zgodę.
Biorąc pod uwagę, że organizatorzy to sami nagrywali a także kilka "mocnych" wyjaśnień MC ,które mogą zainteresować opinię publiczną (np to, że rzad nie przygotował żadnej ścieżki gwarantującej przetestowanie zagrożenej osobie, "chyba, że mieszka pod kopalnią w której jest ognisko") to spotkanie powinno być oficjalnie opublikowane.

**Comment by SeraMoon** [comment]
@miklobit niestety u mnie nie wypaliło - osoby, które miały wbić były nietechniczne, ja miałam poważne zajęcie i nie mogłam być. Od obu osób dostałam komunikat, że ich przeglądarka nie jest obsługiwana i że nie chce działać meeting. 

**Tak więc ja też się zapytam - gdzie znajdę nagranie by zapoznać się z treścią telekonferencji.** 

Też uważam, że powinna być publiczna w sytuacji, gdy omawiane były sprawy dotyczące rządowej aplikacji.

**Comment by miklobit** [comment]
@SeraMoon  https://t.me/ProteGOSafe/13
