### ISSUE TITLE
Alternatywa - Zainstaluj Protego-Safe, bo inaczej wrócimy do obostrzeń"

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#200]
**Describe the bug**
https://www.gazetaprawna.pl/artykuly/1482315,szumowski-aplikacja-protego-safe-powrot-do-obostrzen.html

To nie jest dobrowolna aplikacja, skoro powiedziano powyższe. Dobrowolna to taka, gdzie nikt niczym nie straszy i nie robi alternatywy względem jej używania ani obecnie ani na przyszłość.  

> Jeśli będziemy używać aplikacji ProteGo Safe, to nie będzie konieczności powrotu do obostrzeń

Po pierwsze: nie można zagwarantować, że ProteGO-Safe cokolwiek da. Nikt na świecie nie udowodnił, że aplikacje tego typu przyczyniają się do znacznego wykrycia zakażeń. Wręcz przeciwnie - można znaleźć informacje, że wpływ był marginalny - rzędu wykrytych kilku osób na kilka tysięcy - wykrytych tradycyjnymi metodami. 

Taka wypowiedź tylko straszy "Jeżeli tego nie zainstalujecie - wrócimy mentalnie do marca-kwietnia 2020". Aż się prosi przywołać ten archive.is z zapowiedzią 10% więcej klientów za wchodzenie z aplikacją. 

Obecny wydźwięk "dobrowolności": **albo to zainstalujecie, albo damy wam popalić** (z polskiego na "nasz" obywatelski). 

**To Reproduce**
1. Po prostu wejść na stronę lub obejrzeć wystąpienie ministra Łukasza Szumowskiego

**Expected behavior**
Odwołanie przez Ministra Zdrowia swoich słów publicznie lub przemyślenie czy dalszy rozwój oprogramowania ma sens i czy z czasem nie podzielimy sytuacji Chin i programu "wechat" (tam każdy musi obowiązkowo używać) oraz czy ProteGO nie podzieli losu aplikacji "Kwarantanna Domowa" która była też dobrowolna a po kilku dniach obowiązkowa. 

Obowiązkiem społeczności (głównie twórców) jest reagowanie na nadużycia w związku z aplikacją, którą rozwija. 

**Screenshots**
https://www.gazetaprawna.pl/artykuly/1482315,szumowski-aplikacja-protego-safe-powrot-do-obostrzen.html

**Desktop (please complete the following information):**
 - OS: None
 - Browser Any
 - Version Any

**Smartphone (please complete the following information):**
 - Device: None
 - OS: None
 - Browser Any
 - Version ProteGO-Safe 4.1.1

**Additional context**
\x00

**Comment by miklobit** [comment]
Dodatkowy i przykry kontekst tej "propozycji nie do odrzucenia" jest taki, że rząd nie przygotował dla użytkowników żadnej gwarantowanej ścieżki pomocy w momencie uzyskania z apki powiadomienia o kontakcie z zakażonym. Na prezentacji pan. Zagórski sugerował, że wszystko będzie zależało od okoliczności i miejsca. Czyli ktoś kto mieszka w pobliżu stwierdzonego ogniska pewnie będzie szybko przetestowany ale ktoś inny  za używanie aplikacji może może w nagrodę zostać udupiony na 2tyg. kwarantannie. Wszystko "po uważaniu" sanepidu. Takie podejście nigdy nie zbuduje zaufania obywateli do aplikacji.

**Comment by sub-zero-pl** [comment]
"Indicates that an issue or pull request is no longer relevant"

Znaczy że co, przeprosił, odwołał i zapewnił że nigdy przenigdy czy po prostu rezygnujecie z dalszego rozwoju apki?

**Comment by SeraMoon** [comment]
@miklobit myślę, że jak na razie to po otrzymaniu "wskazówek" od aplikacji to można jedynie pozostać w domu i poczekać na objawy (zazwyczaj jest to 3-7 dni) i dopiero wtedy prosić o test (wcześniej i tak wyjdzie ujemny). Według WHO najbardziej zakaźni jesteśmy przy początkowych objawach, zaś bezobjawowi stanowią niskie ryzyko infekcji. 

Inną sprawą jest, że powinno gdzieś w rozporządzeniu się znaleźć, że test dla osób posiadających czerwony status dostępny jest bezpłatnie i bezzwłocznie. Powinny być punkty laboratoryjne w Polsce (takich nie ma), gdzie pobierane są jedynie wymazy na choroby zakaźne i powinien móc tam się udać obywatel pieszo lub własnym samochodem na taki wymaz. 

Jednak co jeszcze ludzi będzie zniechęcać - spora bolesność wymazu na COVID-19, stąd skuteczność aplikacji będzie i tak mocno ograniczona, bo gdy chory nie chuje duszności i przechodzi to jak grypę i nie jest w grupie ryzyka - po prostu przechoruje to w domu (i oby w domu, bo wielu chorych na grypę potrafi dalej chodzić do pracy czy do sklepu). 

**Jednak na co próbuję zwrócić uwagę - rząd sam torpeduje swoje działania**. A jak to robi wg chronologii:
- dawał specjalne prawa dla osób z aplikacją (nierówność, dyskryminacja),
- próbował nam wmówić, że media kłamały,
- nie usunął wadliwej ze względu na anonimowość aplikacji z play (odpowiedzi zdrowotne trafiały na serwer wraz z IP),
- wypuścił wersję 4.1.1 zapewniając o jej pełnej anonimowości, eksperci od bezpieczeństwa wskazali na brak anonimowości mimo zapewnień w polityce prywatności,
- zrobił akcję promocyjną przez nieistniejących profesorów i doktorów, 
- daje "propozycję nie do odrzucenia". 

Czuję, że po tylu działaniach mających na celu wepchnięcie ludziom wadliwej (i prawnie i technicznie) aplikacji - gdy już powstanie nawet idealna wersja - zainstaluje ją może 2% obywateli i nic aplikacja nie da. 

Prośbą więcej wskurasz niż podstępem i groźbą - praktycznie w każdej dziedzinie. Takie jest życie. Teraz ludzie się bardziej boją tej aplikacji niż samego koronawirusa. Gdyby od początku się nie spieszono i zadbano o każdy szczegół aplikacji - ludzie by to ściągnęli z powodu tego, że bali się wirusa. Czasu jednak już cofnąć się nie da. 

BTW. Jeżeli zespół ProteGO-Safe nie zamierza wszcząć interwencji u Ministra Zdrowia (lub nie posiada narzędzi, np. danych kontaktowych) celem odwołania słów i w ten sposób zakończenia torpedowania przez rząd tego projektu - napiszcie o tym i zamknijcie ten wątek 😉.

**Comment by PawelLitwinski** [comment]
Ale tak naprawdę tak wygląda ta alternatywa ;-)
Możliwości są dwie:

- dobrowolna,
- obowiązkowa. 

Moim zdaniem, aplikacja nie powinna być dobrowolna, bo zgoda na jej używanie nie jest zgodą dobrowolną wobec pewnej presji na jej instalację (dzisiaj ta presja jest mniejsza, ale 2 miesiące temo wobec pewnych inicjatyw GIS była ogromna). Pisałem o tym 7 kwietnia w DGP. A więc z perspektywy prawa ochrony danych osobowych można twierdzić, że zgoda jest wadliwa. A skoro tak, to pozostaje ... obowiązkowa. A tego nikt nie chce zrobić z wielu powodów. 

I co w tej sytuacji?

**Comment by MateuszRomanow** [comment]
> Ale tak naprawdę tak wygląda ta alternatywa ;-)
> Możliwości są dwie:
> 
> * dobrowolna,
> * obowiązkowa.

Do dnia dzisiejszego aplikacja ani przez moment nie była niedobrowolna, taka też ma pozostać zgodnie z zapowiedziami Ministerstwa Cyfryzacji. Co nie zmienia faktu, że żebyśmy byli gotowi jako społeczeństwo na (potencjalny) odpór nawrotu pandemii potrzebujemy mieć pokrycie społeczne, na którym wszystkim nam powinno zależeć. W zwiążku z czym argumentacja "ochrońmy się (higiena, dezynfekcja, aplikacja) bo inaczej będzie źle" wydaje się zasadne. 

Swoją drogą - nie jest to dyskusja związana z częścią funkcjonalną aplikacji ( a do tego służy to forum) tylko jest to dyskusja publicystyczna - do czego zdecydowanie nie służy to forum. W związku z czym proszę autora wątku o zamknięcie go. 

@PawelLitwinski 
Dzięki, za dołączenie do naszej społeczności!

**Comment by sobaw98247** [comment]
>Swoją drogą - nie jest to dyskusja związana z częścią funkcjonalną aplikacji ( a do tego służy to forum) tylko jest to dyskusja publicystyczna - do czego zdecydowanie nie służy to forum. W związku z czym proszę autora wątku o zamknięcie go.

To gdzie możemy o tym porozmawiać? Jakby nie patrzeć, ma to duży związek z aplikacją...

**Comment by SeraMoon** [comment]
Przyłączam się do zadanego pytania, bowiem pewne słowa wypowiedziane przez osoby oficjalne (a nie losowe nieznane osobistości) mogą doprowadzić zarówno do zaufania jak i jego utraty względem aplikacji, zaś rozwój aplikacji, która straci do zera zaufanie - jest zazwyczaj syzyfową pracą - bowiem ludzie mają tendencję do pamiętania bardziej negatywnych niż pozytywnych przekazów odnośnie rozwiązań technologicznych. 

Przykładowo w banku - będą pamiętali bardziej jeden atak hakerski, czy jeden wyciek danych ze sklepu np. morele niż to, że latami chroniono jego bezpieczeństwo. Toteż każdy zapamięta wypowiedź o jakiejś niedobrowolności lub zagrożeniu niedobrowolnością niż 1000x powtórzone, że jest dobrowolne. 

> Możliwości są dwie:
>   dobrowolna,
>  obowiązkowa.

Myślę, że są 3:
- dobrowolna (jedyna korzyść z aplikacji to ochrona siebie samodzielnie i własną decyzją,
- obowiązkowa (czyli coś się z tego ma, np. zniżki, dodatkowe wejścia lub postawione właśnie jest ultimatum "albo wóz albo przewóz")
- przymusowa (gdy za brak aplikacji grozi kara - przykładem może być aplikacja "Kwarantanna Domowa") - istnieje bowiem mechanizm przymusu do instalacji tamtej apki....

**Comment by PawelLitwinski** [comment]
Nie, możliwości są nadal dwie. Obowiązek bez sankcji za jego naruszenie nie jest efektywnym obowiązkiem, a więc aplikacja nadal jest dobrowolna. "Coś się z tego ma" oznacza też, że tego czegoś się nie ma, nie mając aplikacji, więc cały czas obracamy się wokół kary za niemanie. 

Może wyraziłem się nie dość jasno, może trzeba by przeczytać ten tekst z DGP, o którym pisałem: zgoda jako podstawa korzystania z aplikacji ma sens wyłącznie wtedy, kiedy jest dobrowolna. Dzisiaj ta zgoda jest dobrowolna, bo nie rozmawiamy w trybie przypuszczającym (notabene, to jest oczywiste, że jeżeli rozwiązanie A nie zadziała, to trzeba będzie stosować rozwiązanie B). Proszę zobaczyć, jakie były pomysły w rekomendacjach GIS, wtedy ujawni się w pełnej krasie ten problem. 

Z mojej perspektywy obawy oparte o to, że jak aplikacja nie będzie skuteczna, to trzeba będzie pomyśleć o innym rozwiązaniu, są zupełnie bezzasadne - aplikacja jest dobrowolna.

**Comment by SeraMoon** [comment]
> Nie, możliwości są nadal dwie. Obowiązek bez sankcji za jego naruszenie nie jest efektywnym obowiązkiem, a więc aplikacja nadal jest dobrowolna.

Więc dobrowolną aplikacją będzie ta, która pozwala na wpuszczenie do 50% więcej klientów, gdy mają aplikację, a jeżeli nie mają, to mają stać w kolejce? Moim zdaniem nie, bo powstało ograniczenie. A na pewnie nie takiej "dobrowolności" oczekujemy od ProteGO. 

> zgoda kiedy jest dobrowolna

Czy zatem zgoda u pracodawcy (już wg Kodeksu Pracy mogą takie dane przetwarzać) na pobranie twojego odcisku palca jest dobrowolna, gdy wiesz, że odmawiając możesz (ale tego nie powiedziano) skończyć pracę w ciągu 1 lub 3 miesięcy? Jaka jest definicja dobrowolności zgody? Dlaczego więc "albo używacie aplikacji, albo wracamy do obostrzeń" jest dobrowolne / niedobrowolne? 

> Z mojej perspektywy obawy oparte o to, że jak aplikacja nie będzie skuteczna, to trzeba będzie pomyśleć o innym rozwiązaniu, są zupełnie bezzasadne - aplikacja jest dobrowolna.

Nie. Sformułowanie nie brzmiało, że aplikacja będzie skuteczna, ale że będzie instalowana przez minimum 60-80% obywateli. 

Poza tym: postawiono wprost obowiązek przed obywatelem (tak samo niekaralny jak niedopełnienie meldunku) - **zobowiązanie** do używanie aplikacji po to aby inni nie padli ofiarą "obostrzeń" - które z mojego punktu widzenia i utraty źródła utrzymania jest dotkliwe.

Przy zobowiązaniu nie możemy mówić o dobrowolności, bo nie mogę dać dobrowolnej zgody podobnie jak w rzeczonej wyżej pracy nie dać odcisku palca.

Albo coś jest **w pełni dobrowolne** albo obowiązkowe (stoi za tym obowiązek / zobowiązanie** albo też przymusowe. Pewne jest to, że w tym przypadku nie mamy do cztnienia z opcją numer 3.

**Comment by MadryPan1987** [comment]
> Jeśli będziemy używać aplikacji ProteGo Safe, to nie będzie konieczności powrotu do obostrzeń

To zdanie jest wyrwane z kontekstu! Nikt tego nie pilnuje?
Szumowski powiedział to w kontekście że jak będziemy używać narzędzi wspomagających w walke z covid to jest mniejsza szansa że wrócimy do obostrzeń.
Ten temat wprowadza w błąd i powinien zostać usunięty!
Ktoś wejdzie i automatycznie zostanie odstraszony od aplikacji...

**Comment by pkleczko** [comment]
@SeraMoon czy masz jakieś dalsze pytania dotyczące tego tematu? Tak jak zauważyłaś zapewne, aplikacja nadal jest i pozostanie dobrowolna, w związku z tym proponuję zamknąć to Issue.
