### ISSUE TITLE
Pełna decentralizacja części serwerowej

### ISSUE THREAD

**Issue by KonoromiHimaries** [ProteGO-Safe/specs#203]
**Is your feature request related to a problem? Please describe.**

Brak wsparcia dla p2p

**Describe the solution you'd like**

W związku z zamknięciem https://github.com/ProteGO-Safe/specs/issues/127#issuecomment-643687178 https://github.com/ProteGO-Safe/specs/issues/123

**Describe alternatives you've considered**

Prosiłbym o wsparcie dla technologii ipfs https://github.com/ipfs/js-ipfs#readme https://github.com/hsanjuan/ipfs-lite#readme https://github.com/embarklabs/embark#readme

**Additional context**

Zgodnie z założeniem aplikacji https://github.com/ProteGO-Safe/specs#anonimowo%C5%9B%C4%87-i-bezpiecze%C5%84stwo

**Comment by SeraMoon** [comment]
Od siebie dodam, że zamykanie nierozwiązanych wątków (wątek 127 był o aplikacji na stronie safesafe.app) , jest nieprofesjonalne i łamie to standardy zapisane w [CoC CNCF](https://github.com/ProteGO-Safe/specs/blob/master/.github/CODE_OF_CONDUCT.md) - wnoszę do @Tarvald'a o poprawę zachowania. Od moderatora wymaga się zachowanie profesjonalnego. Tymczasem zamknięto mi tamten wątek bez jego rozwiązania, jak też nazwano niewinny związek frazeologiczny - epitetem. 

Powyższy apel popieram - wprowadzenie I2P (ipfs) lub ostatecznie obsługi Tora.

**Comment by Tarvald** [comment]
@SeraMoon 
Nie mineły nawet 24h od twojej prośoby o ponowanie otwarcie i przeniesie wątku do /web.
Proźba o zaprzestanie ciągłego offtopowania.
Wątek #127 został otwarty i przeniesiony.

**Comment by qLb** [comment]
Nie do konca rozumiem jak mialo by to wygladac? Czy moge prosic o objasnienie, ktora czesc implementacji [exposure-notifications-server](https://github.com/google/exposure-notifications-server) mialaby korzystac z ipfs do realizacji swoich zalozen?

**Comment by KonoromiHimaries** [comment]
Może przy pomocy technologii WASM https://wasmer.io/

**Comment by KonoromiHimaries** [comment]
https://wasmer.io/ https://github.com/wasm3/wasm3#readme

**Comment by qLb** [comment]
@Mtq
Znam `WebAssembly` , a w paru projektach zdarzylo mi sie implementowac `ipfs`.
To co staram sie zrozumiec, to gdzie dokladnie mialyby one zastosowanie i jak pomoglyby realizowac zalozenia juz instniejacych elementow systemu `exposure-notifications-server`?

Prosze jeszcze o klaryfikacje w odniesieniu do takiej implementacji jak na zalaczonym obrazku:

<img width="2110" alt="google_cloud_run" src="https://user-images.githubusercontent.com/1850546/84642890-686aa580-aefd-11ea-8be3-64808c97a40f.png">

---

!MHO: warto zauwazyc, ze poszczegolne komponenty `exposure-notifications-server` napisane sa w `golang`'u - nie jestem przekonany o dojrzalosci `WASM` dla `golang`'a jesli mam byc szczery.

**Comment by KonoromiHimaries** [comment]
Wydaje mi się że w 'Cloud Storage' i 'CDN' 
'''
https://ipfs.github.io/public-gateway-checker/
'''

Co do reszty to chyba trzeba by było przepisać komponenty google, ale tylko tyle wiem.

**Comment by qLb** [comment]
Cloud Storage, czyli CDN - dostepny publicznie - jest to endpoint w technologii S3 (Simple Storage Server), na ktorym znajduja sie cyfrowo podpisane i odpowiednio skompresowane archiva z kluczami potwierdzonymi przez GIS. Paczki jak juz napisalem sa publicznie dostepne dla kazdego do pobrania. Nie rozumiem jaki sens mialoby zmienianie struktury objektowej na strukture plikow w przypadku gdy same objekty/pliki musza byc dostepne publicznie w internecie.

**Comment by SeraMoon** [comment]
> Co do reszty to chyba trzeba by było przepisać komponenty google, ale tylko tyle wiem.

@KonoromiHimaries Problem jest w tym, że Google oraz Apple odmówiły nam udostępnienia kodu źródłowego Exposure Notification i na dzień dzisiejszy nie pojawi się on otwarty w sieci. Uniemożliwia więc to użycie tam ipfs. Być może możliwe jest użycie Tor over VPN lub możliwe, że Tora, o ile na Androidzie da się edytować iptables (dla nietechnicznych: moduł trasowania pakietów internetowych). 

Staje się więc niemożliwe użycie ipfs w tym miejscu. Zaś [otwartość kodu źródłowego](https://github.com/ProteGO-Safe/specs/issues/191) aplikacji pozostaje pod znakiem zapytania, skoro moduły są zamknięte, zaś Google zapowiedział, że nie będzie wpuszczał do swojego sklepu aplikacji do śledzenia kontaktów opartych o inne rozwiązania. 😾

**Comment by KonoromiHimaries** [comment]
@SeraMoon aha. czyli się nie da.

**Comment by KonoromiHimaries** [comment]
@SeraMoon aha. czyli się nie da bez napisania od nowa, chyba że google udostępni kod źródłowy.

**Comment by jasisz** [comment]
Endpoint to jest https://exp.safesafe.app/ - tam można ściągać paczki zzipowanych kluczy w formacie opisanym tutaj https://developers.google.com/android/exposure-notifications/exposure-key-file-format trochę się przed sekundą pobawiłem żeby to odcyfrowywać i działa https://github.com/jasisz/contact-tracing-experiments/blob/master/decode_keys.py

**Comment by pkleczko** [comment]
wspomniane technologie nie zostaną wprowadzone w rozwiązaniu aplikacji ProteGO Safe - czy mogę zamknąć to issue?
