### ISSUE TITLE
Przejrzystość komunikacji - rozwijajmy skróty przy pierwszym użyciu w danym issue

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#204]
**Is your feature request related to a problem? Please describe.**
Wątki z rozmową zawierają niezrozumiałe skróty oraz użycie słów w dziwnym kontekście (post pisany po polsku i nagle natrafiamy na dziwne angielskie słowo), które nie rozwiązują się lub rozwiązują niepoprawnie po wpisaniu ich do Google. Np. PLC - czy na pewno w wątku #201 chodziło o sterowniki programowalne lub komunikację po sieci energetycznej? 

**Describe the solution you'd like**
Rozmowa powinna być przejrzysta dla każdego, Wszelkie użyte skomplikowane (dla zwykłego śmiertelnika) wyrażenia i skróty powinny zostać rozwinięte z użyciem nawiasu - przy pierwszym ich użyciu w **wątku**, dla przejrzystości rozmowy (obecna forma nie sprzyja przejrzystości). 

**Describe alternatives you've considered**
Stworzenie słownika z tego typu terminami i skrótami i ich wyjaśnienie w oddzielnym **podwieszonym** (pinned) wątku. 

**Additional context**
\x00

**Comment by Tarvald** [comment]
https://github.com/ProteGO-Safe/specs/wiki/Dictionary

**Comment by SeraMoon** [comment]
@Tarvald strasznie biedny ten Dictionary (słownik). Brakuje w nim między innymi terminów:
- PLC (wciąż nie znam właściwego rozwinięcia), 
- PLA (termin stworzony przez użytkownika - Progressive Local App),
- PWA (progressive Web App),
- EN (exposure notification - ktoś może pomyśleć, że chodzi o język angielski...),
- wielu innych

Nie jest podwieszony w issues, aby każdy mógł go łatwo znaleźć (nawet nie wiedziałam o istnieniu tego pliku).

**Comment by qLb** [comment]
@SeraMoon
**PLC** - Pozwolilem sobie wyedytowac ta literowke, rozumiem, ze to rozwiazuje problem. Prosze zrobic to samo by nie tworzyc nowych nieporozumien.

ps. Ten Dictionary jest po angielsku poniewaz programujemy w tym jezyku. Jesli zawartosc naszej dokumentacji jest niewystarczajaca zapraszamy do partycypacji. 
**Osobiscie** - polecam skupic swe dzialania mniej na krytykowaniu a wiecej na kreowaniu tresci w internecie. Pozdrawiam.

**Comment by SeraMoon** [comment]
> @SeraMoon
> **PLC** - Pozwolilem sobie wyedytowac ta literowke, rozumiem, ze to rozwiazuje problem. Prosze zrobic to samo by nie tworzyc nowych nieporozumien.

Oznaczyłam wyżej PLC jako nieaktualne. 

> ps. Ten Dictionary jest po angielsku poniewaz programujemy w tym jezyku. Jesli zawartosc naszej dokumentacji jest niewystarczajaca zapraszamy do partycypacji.

Tak - wnoszę o utworzenie aktualizowanego słownika w ramach issues - tłumaczącego używane terminy i skróty, **tak aby były przez to zrozumiałe dla przeciętnego śmiertelnika** - skoro stawialiśmy na transparentność tworzenia projektu - te issues są jego częścią - toteż obywatelowi należy się możliwość zrozumienia o czym rozmawiamy jak psu kość. 

> **Osobiscie** - polecam skupic swe dzialania mniej na krytykowaniu a wiecej na kreowaniu tresci w internecie. Pozdrawiam.

Obowiązkiem moderatorów (i projektantów) - jest zgodnie z CoC CNCF "Przyjmowanie konstruktywnej krytyki z wdzięcznością". 

Moim obowiązkiem nie jest kreowanie treści w internecie - w wolnym czasie - zgłaszam znalezione błędy ponieważ jestem częścią **społeczności obywateli** i lubię zajmować się **kontrolowaniem kontrolujących**. 😸 

Toteż dziękuję za wyjaśnienie błędu i proszę o utworzenie słownika slangu używanego na tym forum, tak aby każdy mógł zrozumieć o czym rozmawiamy.

**Comment by qLb** [comment]
@SeraMoon W imieniu swoim i tworcow, dziekuje.

**Comment by qLb** [comment]
@SeraMoon W imieniu swoim jesli moge jeszcze o cos prosic, to prosze o nieuzywanie paraboli, przenosni lub przerzutni, w ktorej przyrownuje sie ludzi ze zwierzetami. 
Zwierzeta glosu nie maja, ale moga sobie tego nie zyczyc.

**Comment by SeraMoon** [comment]
> @SeraMoon W imieniu swoim jesli moge jeszcze o cos prosic, to prosze o nieuzywanie paraboli, przenosni lub przerzutni, w ktorej przyrownuje sie ludzi ze zwierzetami.

To tutaj jest coś czego mogę używać? Prosisz o nieużywanie cenzuralnej polszczyzny. No cóż. A ja proszę o uszanowanie polszczyzny, bowiem aplikację tworzymy [głównie] dla Polaków (mnie też mierżą te angielskie wtręty w środku zdania i nie mówię tutaj o "Exposure Notification" i innych znakach towarowych oraz terminach nieprzetłumaczalnych typu "VPN" i jakoś przemilczam to). Przykładów teraz nie podam bo nie mam czasu na szczegółowe przejrzenie 100 wątków. Szanuj różnorodność, w tym cenzuralny język innych użytkowników. Mniemam, że parabolą, przenośnią czy przerzutnią nie łamię CoC (akurat przerzutni nie stosuję, bo utrudnia rozumienie tekstu). 

> Zwierzeta glosu nie maja, ale moga sobie tego nie zyczyc.

No właśnie tak się czuję, gdy mówisz mi, abym nie stosowała związków frazeologicznych, paraboli, przenośni itp... BTW. To chyba ryby głosu nie miały ;)

Życzę miłej (i krótkiej) pracy przy przygotowywaniu słownika slangu - bowiem nie wnoszę o tak rozległe tłumaczenie jak w Dictionary wyżej, lecz głównie rozwinięcie skrótów i przykładowo dodanie linków do odpowiedniego artykułu Wikipedii, gdzie jest to wszystko wyjaśnione. 

BTW. muszę odnaleźć temat o urządzeniach zrootowanych bowiem pomyliłam terminy i muszę to wyjaśnić. Chodziło o systemy pochodne od Androida odguglowane (Ungoogled), niekoniecznie pracujące w trybie administratora (root).

**Comment by Tarvald** [comment]
Polski słownik będzie niebawem dostępny i zostanie uzupełniony o brakujące stwierdzenia.
Wrzucę link do PR do tego wątku jak będzie gotowe.

**Comment by SeraMoon** [comment]
@Tarvald popieram - stanowisko w sprawie firmy nie jest już potrzebne aż tak eksponowane, gdyż temat wygasł śmiercią naturalną ;)

Tu tylko jeszcze raz zaznaczę - nie chodzi o terminu używane w regulaminach itp. sprawach - a terminy, które używamy tutaj w issues. 

> Po wydaniu 4.1.1 na iOS

Jest sens wydawać tą wadliwą wersję, gdy niebawem będzie dostępna 4.2?

**Comment by qLb** [comment]
@SeraMoon urzadzenia odgooglowane nie maja google exposure notifications api, a moze sie myle?

**Comment by SeraMoon** [comment]
> 
> 
> @SeraMoon urzadzenia odgooglowane nie maja google exposure notifications api, a moze sie myle?

A mieć powinny, gdy AOSP zostanie skompilowany wraz z kodem Exposure Notification - o to w tamtym wątku chodziło. Odnajdę tamten wątek to wyjaśnię.

**Comment by Tarvald** [comment]
Pull request z polskim oraz angielskim słownikiem. 
https://github.com/ProteGO-Safe/specs/pull/207

**Comment by SeraMoon** [comment]
@Tarvald przewidziałeś link do podania do aktualnych wersji obu słowników? Gdzie konkretnie znajdziemy słownik i kiedy będzie podwieszony zamiast "stanowiska firmy"?

**Comment by Tarvald** [comment]
@SeraMoon 
Przypięty słownik pojęć #208
