### ISSUE TITLE
Jak skasować swoje dane o kontaktach i medyczne w ProteGO Safe

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#205]
**Is your feature request related to a problem? Please describe.**
Jak w temacie - jak usunąć w ProteGO-Safe swoje dane zarówno związane z komunikacją po BT (w inny sposób niż owinięcie telefonu folią aluminiową i czekanie 21 dni) oraz jak skasować swoje dane wprowadzone do dziennika zdrowia? 

Mam ochotę bez przywracania ustawień fabrycznych - pożyczyć telefon kumplowi lub babci lub też rezygnuję z używania ProteGO-Safe i nie chcę by te dane pozostały na telefonie. 

Niestety Regulamin ani Polityka Prywatności nie wyjaśnia jak usunąć swoje lokalne dane i gdzie się one znajdują. 

W przypadku danych medycznych - wskazany też eksport i import tych danych do/z plików tekstowych. Przydatne choćby w przypadku zepsucia się telefonu. 

**Describe the solution you'd like**
Czytelny opis jak to zrobić - w regulaminie lub polityce prywatności + odpowiednia funkcja. 
Myślę, że oba typy danych powinny być czyszczone oddzielnie. 

**Describe alternatives you've considered**
\x00

**Additional context**
\x00

**Comment by qLb** [comment]
@SeraMoon 
Temat jest juz opracowany i aktualnie w fazie testow UAT.

**Comment by pkleczko** [comment]
Usuwanie danych w aplikacji, w tym przekierowanie do ustawień telefonu gdzie można skasować klucze TEK jest już dawno wprowadzone. W związku z tym zamykam wątek, w razie dalszych pytań proszę o otworzenie nowego.
