### ISSUE TITLE
Problem z proszeniem o GPS / lokalizację w Androidzie

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#206]
**Describe the bug**
**Być może** powinno być to zgłoszone gdzie indziej, jednak nie zajmuję się stricte zgłaszaniem baboli w Androidzie toteż zgłaszam tu bo wpływa mocno na ocenę aplikacji. 

Dlaczego użytkownik jest proszony o włączenie GPS / lokalizacji - podnosiłam w którymś komentarzu (dawno), że odbije się to na ocenie, bo ludzie alergicznie reagują na próbę śledzenia ich **lokalizacji** i większość rozumie to jako GPS. Wytłumaczenia Ministerstwa nie trafiają - jest już kilkadziesiąt tego typu postów i każdy lajkowany x20 do x100. 

**To Reproduce**
1. Zajrzyjcie do google Play tej aplikacji... 

**Expected behavior**
Android pytać powinien o:
- śledzenie COVID-19 (Exposure Notification),
- możliwość połączenia się z internetem,
- możliwość startu wraz z systemem,
- pozostanie aktywnym w czasie uśpienia
- (tu lista powinna się skończyć)

**Screenshots**
![Bułki](https://i.ibb.co/QjWQh8Z/safe.jpg)

**Desktop (please complete the following information):**
 - OS: None
 - Browser Any
 - Version None

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Android
 - Browser None
 - Version ProteGO-Safe 4.1.1

**Additional context**
Gdy to nie zostanie naprawione to połamiecie zęby na bułkach z pilnikiem rozdawanych przez użytkowników, którzy pobrali aplikację i się wystraszyli już przy próbie jej uruchomienia i wystawili Wam pałę w Google Play. Aplikacja podzieli los Kwarantanny Domowej, która ma jeszcze niższą ocenę. 

Ludzie trafnie zauważają, że nie chcą mieć włączonego GPS, a "lokalizacja" włącza wszystko, nie tylko BLE. Apelowałam dawno o to aby prosić Google o rozdzielenie tego zanim jeszcze zrobili Exposure Notification.

**Comment by tomekziel** [comment]
> Dlaczego użytkownik jest proszony o włączenie GPS / lokalizacji 
> [... wielki ciach ...]
> Apelowałam dawno o to aby prosić Google o rozdzielenie tego zanim jeszcze zrobili Exposure Notification.

Wskazówka - być może okazało się niemożliwe z powodu decyzji architektonicznych podjętych 10 i 5 lat temu (system uprawnień i system uprawnień dynamicznych). W tym projekcie lekko licząc połowa ticketów i komentarzy jest Twojego autorstwa, a od pewnego czasu jakość wyraźnie przeszła w ilość. Na miejscu twórców ProteGO Safe zamknąłbym ticketa od razu jako "out of scope".

**Comment by RMalczynski** [comment]
@tomekziel w pełni popieram, mam wrażenie że issues i komentarzy produkcji tego użytkownika już nawet nie warto na bieżąco śledzić, bo niestety mała część jest jeszcze jakkolwiek merytoryczna.

**Comment by Tarvald** [comment]
Zgadzam się, że to realny problem całego softu.
Niestety developerzy nie mają na to wpływu z poziomu kodu. 

Powinno to zostać poruszone na linie MC <-> Google

Pytanie o lokalizacje najprawdopodobniej ma znaczenie lokalizacji pomiędzy urządzeniami (blisko/daleko) a nie w znaczeniu GPS.
Nie mniej ni więcej, i tak jest to źle zakomunikowane. 

Zgadzam się również z @tomekziel że może być to z wyniku decyzji architektonicznych podjętych X lat temu.

**Comment by sobaw98247** [comment]
>W tym projekcie lekko licząc połowa ticketów i komentarzy jest Twojego autorstwa, a od pewnego czasu jakość wyraźnie przeszła w ilość. Na miejscu twórców ProteGO Safe zamknąłbym ticketa od razu jako "out of scope".
Zwracanie uwagi na ważne kwestie to _pójście na ilość_? Nawet jeśli wymagane jest włączenie lokalizacji; co za problem aby MC wprost wszystko wyjaśniło? Nawet zwykły FAQ na stronie...

**Comment by SeraMoon** [comment]
@sobaw98247 nie chciałam już tego komentować, ale skoro Ty komentujesz - to moim zdaniem był to atak osobisty, a te wg CoC tu obowiązującego są zabronione. Nie chciałam jednak zwyczajnie robić offtopu. 

Ale odniosę się do tego rzeczowo:
- wskazano mi aby nie poruszać wielu rzeczy w jednym wątku (co mówiąc krótko spowodowałoby bałagan w wątku - słuszne - stąd mamy tematy 198 i 199 a nie jeden 198 połaczony ze 199), 
- staram się obserwować opinie na Google Play - gdy cioś jest podnoszone drugi lub trzeci raz - zgłaszam tutaj - dobra przemilczę ciemny motyw, bo skoro poszłam w ilość a nie jakość można olać celem poprawy mojego zachowania - zgłoszenia tego więc nie będzie z mojej strony), 
- odnośnie jakości - mam prawo być przemęczona / chora (bywa), mam prawo do przeoczeń oraz pomyłki - nieomylna nie jestem, części kwestii nie rozumiem (a nawet gdy wprost pytam bo nie rozumiem - bywa, że odpowiedzi nie dostają...). 

Ilość więc wynika z różnorodności tematów i tak mamy:
- 198 (Regulamin)
- 199 (Polityka Prywatności), 
- 200 (propozycja nie do odrzucenia - kwestia samotorpedowania projektu),
- 202 (propozycja nazwy dla aplikacji - podnoszone minimum 3 razy w sklepie Google przez bardziej patriotycznych użytkowników,
- 204 (przejrzystość komunikacji - znalezione na panoptykonie, że ekipa panoptykonu nie rozumie naszych dialogów - potrzebny był im tłumacz ze skrótowcowo-technicznego na polski!)
- 205 (kwestia usunięcia danych (własna analiza przypadków użycia aplikacji i obecność opisu w dostarczonych z aplikacją dokumentami dla użytkownika (198 i 199) - proszono wyraźnie abym nie podnosiła w 198 kolejnych rzeczy!
- 206 (kolejny temat na który żalą się użytkownicy). 

Coż... może lepiej faktycznire to olać i nie śledzić opinii na Play, bo wiele tematów (telefony rootowane, VPN, właczenie lokalizacji, kilka innychi) pochodzi właśnie z opinii użytkowników. Owszem może tu znaleźć się głupota, gdy 6 osób napisze, że aplikacja wyświetla im wizerunek kosmity (to był żart, ale mogą zgłosić coś prawdopodobnego a nieprawdziwego). 

> Wskazówka - być może okazało się niemożliwe z powodu decyzji architektonicznych podjętych 10 i 5 lat temu (system uprawnień i system uprawnień dynamicznych). 

A odnośnie tego zdania - powiem tyle - projekty rozwija się uaktualniając "decyzje architektoniczne". Często pozostawienie tego niezmienionego może być poważnym błędem architektonicznym lub nawet błędem bezpieczeństwa... Właśnie błędem jest to, że nie podjęto tych decyzji na czas i że nie było dialogu MC <-> G+A mimo zgłoszenia zastrzeżeń i uprzedzenia, że ludzie nie będą się godzić na "lokalizację".

**Comment by blassepl** [comment]
Z zasady rzadko komentuje, raczej tylko czytam, ale... G+A wymaga włączonej lokalizacji do działania. Natomiast aplikacja jako taka dostępu do lokalizacji nie wymaga...
![Screenshot_20200616-180420](https://user-images.githubusercontent.com/46654672/84799194-34c27500-affc-11ea-8385-dd17407defd6.png)

**Comment by SeraMoon** [comment]
@blassepl dzięki za wyjaśnienie. Stąd wynika, że Ministerstwo Cyfryzacji powinno odpowiadać użytkownikom, aby problem zgłosili do Google, bowiem to nie aplikacja ich prosi o lokalizację ale Exposure Notification. Póki będzie MC mówić, że aplikacja wymaga lokalizacji ale nie GPS, użytkownikom utkwi w głowach "aplikacja potrzebuje lokalizacji". 

Jednak nie zmienia to faktu, że ludzie i tak będą odrzucać "lokalizację" póki będzie się nazywała "lokalizacją". 

"have full network access" + "view network connections" oddzielnie od "receive data from internet" też wygląda dziwnie...

**Comment by blassepl** [comment]
full network access - jest potrzebny do nawiązania połączenia z Internetem. Bez tego permission, apka nie może samemu ustanowić połączenia.
view network connections - umożliwia sprawdzenie czy istnieje połączenie z Internetem.
receive data from Internet - umożliwia odebranie aplikacji danych z chmury.

Także te uprawnienia są komplementarne, nie są też uznawane za niosą jakiekolwiek ryzyka - aplikacja nie musi nawet użytkownika prosić o ich przyznanie. Szczerze mówiąc, w obecnym stanie rzeczy niewiele tu już można poprawić poza dokumentacją/opisem aplikacji. I oczywiście bombardowanie Googla pytaniami o taką a nie inną implementacje.

Jednak nawet tu niewiele można zrobić - model prywatności Google zakłada, że skanowanie urządzeń Bluetooth wymaga odpowiedniego uprawnienia (stąd wymóg włączonego bluetooth przez Exposure Notification API). Zarazem wykorzystanie skanu bluetooth do zebrania danych quasi-lokalizacyjnych (skanowanie beaconów, budowanie listy id, itp.) wymaga dodatkowego uprawnienia - korzystania z danych lokalizacyjnych. I logicznie ciężko zaprotestować, że są to w pewien sposób dane lokalizacyjne :) Android dość wyraźnie rozdziela różne rodzaje danych lokalizacyjnych - bluetooth based, network based, precise location oparte o GNSS - ale kto czyta te szczegóły i wie gdzie je znaleźć? ;)

**Comment by potiuk** [comment]
Bardzo dobrze wytłumaczone @blassepl . Dodam że jeśli (albo kiedy) EN będzie zaimplementowane w systemie operacyjnym a nie w Play Services to najpewniej aplikacja nie będzie potrzebować tych uprawnień . W IOS wygląda na to że uprawnienia są w systemie a sama aplikacja ma po prostu nowe uprawnienie 'exposure notification' (ale to do potwierdzenia z osobamii z IOS ).

**Comment by bartosztomczak** [comment]
Temat jest poza kontrolą twórców aplikacji. Prosiliśmy o oficjalne wyjaśnienie w tej sprawie i jest już odpowiedni dokument https://support.google.com/android/answer/9930236?hl=pl

**Comment by blassepl** [comment]
W ramach ciekawostki: Android 11 beta3 nie prosi już o lokalizację dla exposure notification API. Finalna 11 też nie będzie już prosić.

**Comment by potiuk** [comment]
Wygląda na to że głosy krytyki są odbierane i adresowane przez różnych interesariuszy w tym "projekcie'. Dobrze. Oby tak dalej.

**Comment by MateuszRomanow** [comment]
> W ramach ciekawostki: Android 11 beta3 nie prosi już o lokalizację dla exposure notification API. Finalna 11 też nie będzie już prosić.

Zgłaszaliśmy to wiele razy. Zgłoszenia do Google są przyjmowane i potwierdzane. Widać postęp.

**Comment by potiuk** [comment]
A jeśli ktoś jest ciekawy dlaczego jest właśnie tak to specjalista od BLE z mojej firmy napisał bardzo obszerny i techniczny artykuł dokładnie o tym aspekcie tutaj w maju https://www.polidea.com/blog/a-curious-relationship-android-ble-and-location/

**Comment by pkleczko** [comment]
@SeraMoon czy jakieś jeszcze pytania w tej kwestii? jeśli nie to prośba o zamknięcie Issue
