### ISSUE TITLE
Publiczne udostępnienie umowy o wykonanie aplikacji ProteGo Safe

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#210]
**Describe the bug**
Ponieważ projekt jest otwarty, zaś wiele osób chce znać jej treść (minimum 28 użytkowników GitHuba) - zwracam się z prośbą o udostępnienie jej w repozytorium ProteGO-Safe, jako, że w oparciu o treść tej umowy powstaje owa aplikacja. Umowa prawdopodobnie zawiera niezbędne wymagania stawiane aplikacji. 

**To Reproduce**
\x00

**Expected behavior**
Umowa dostępna w specs w repozytorium - jako, że jest **częścią specyfikacji** systemu. 

**Screenshots**
\x00

**Desktop (please complete the following information):**
 - OS: None
 - Browser None
 - Version Protego-Safe v4.2

**Smartphone (please complete the following information):**
 - Device: None
 - OS: None
 - Browser None
 - Version Protego-Safe v4.2

**Additional context**
#128
@Tarvald pisze:
> Umowa nie będzie zwarta w repozytorium bo to nie miejsce na to, natomiast można je 
> otrzymać oficjalną drogą od ministerstwa cyfryzacji.
> Ponad 100 stronicowa umowa jest w opracowaniu przez informatykzakladowy.pl

Myślę, że GitHub spokojnie zniesie 100 stron dokumentacji w postaci umowy zawierającej specyfikację systemu. 

Odsyłanie do Ministerstwa Cyfryzacji, gdy to nie jest zobowiązane odpowiadać na zapytania nie zawierające imienia i nazwiska, gdy użytkownicy jawnie zaznaczyli łapkami w górę, że też chcą poznać treść umowy - jest **wyłudzaniem danych osobowych**, bowiem projekt **Privacy By Design** i **Privacy By Default** powinien umożliwiać zapoznanie się z treścią specyfikacji bez podawania rządowi jakichkolwiek danych użytkowników GitHub, poza publicznie widocznymi. W tym też powinna być jawna treść zawartych umów.

**Comment by Tarvald** [comment]
Na tą chwile nie ma planów przetrzymywania umowy o wykonanie w repozytorium.

**Comment by SeraMoon** [comment]
@Tarvald czekam więc z niecierpliwością na wieści i dokumenty z pierwotną specyfikacją (umowę). Uważam, że jeżeli nie ma się czego wstydzić, to umowa powinna się pojawić na GitHubie - jeżeli ilość transferowanych MB/GB wadzi programistom - można dodać szóste repozytorium w ramach projektu ProteGO-Safe i tam wrzucić obszerne objętościowo dokumenty.

**Comment by SeraMoon** [comment]
> Z ostatniej chwili, temat będzie dyskutowany wkrótce z MC :)

@Tarvald czekam więc z niecierpliwością na wieści i dokumenty z pierwotną specyfikacją (umowę). Uważam, że jeżeli nie ma się czego wstydzić, to umowa powinna się pojawić na GitHubie. Jeżeli ilość transferowanych MB/GB wadzi programistom, można dodać szóste repozytorium w ramach projektu ProteGO-Safe i tam wrzucić obszerne objętościowo dokumenty. 

Wystarczy jakość kopii pozwalająca zapoznać się z treścią.

**Comment by olekstomek** [comment]
Umowy (oprócz osadzenia modułu wykonawczego PWA wewnątrz aplikacji) dostępne w [artykule Tomasza Zielińskiego](https://informatykzakladowy.pl/aplikacja-protego-safe-nie-dziala-czas-zatrzymac-te-inwestycje/#more-954) w sekcji **Koszty produkcji ProteGO Safe.**

**Comment by SeraMoon** [comment]
@olekstomek dzięki za informację, jednak dalej uważam, że umowa powinna znaleźć się w tym samym miejscu co reszta projektu, gwarantując też przy okazji jej nieulotnotność lub ulotność wraz z projektem, którego dotyczy. Trzecie strony to nie jest odpowiednie miejsce na informowanie jakie były założenia i wymagania odnośnie ProteGO-Safe i przypuszczenia moje się potwierdzają - były w niej wymagania, nawet odnośnie kodów QR (jednak większość tekstu jest przede mną). 

@Tarvald może więc dodasz do repozytorium, skoro już jest publiczna ta umowa? Przydałby się jeszcze Aneks 3, którego brakuje u Informatyka Zakładowego.

**Comment by tomekziel** [comment]
> Przydałby się jeszcze Aneks 3

Napisałaś na temat umowy wiele postów, tymczasem od wszystkiego co zechcesz dzieli Cię jeden e-mail wysłany na adres mc@mc.gov.pl

**Comment by Tarvald** [comment]
@tomekziel 
Niestety @SeraMoon  nie chce ujawnić swoich danych osobowych, mimo że wszyscy tutaj są jawni :)))

@SeraMoon 
Umowy nie będzie zawartej w repozytorium. Można do niej uzyskać dostęp w taki sposób jak mówi @tomekziel 

Mówi o tym ustawa o dostępie do informacji publicznej.

**Comment by pkleczko** [comment]
wątek został omówiony, zamykam go.
