### ISSUE TITLE
Czy to jest "klapa" projektu, czy nie ?

### ISSUE THREAD

**Issue by Dr-Kownacki** [ProteGO-Safe/specs#213]
Przepraszam za przewrotny tytuł wątku ale dawno nie pisałem tutaj a nurtują mnie poniższe  pytania/przemyślenia:

1) 
Czy można dowiedzieć się ile było dokładnie pobrań łącznie Android/iOS ? Ile osób tego realnie używa w Polsce ? Jaki jest trend pobrań ? Może jakiś wykres macie ?

2)
Ile osób z zakażonych miało aplikację i **dokonano uploadu ich kluczy** ?

3)
Czy Zespół tworzący aplikację ma jakikolwiek wpływ na formę jej reklamy w telewizji ???
Moim zdaniem Wasza praca / szansa dla kraju przez ten zły "marketing" może zostać po prostu wręcz zmarnowana:

Dla mnie ta reklama to jest niestety totalne NIEPOROZUMIENIE, nie jest jasna i czytelna. 
Całkowicie irracjonalne moim zdaniem jest użycie głosu "starszego lektora" i od pierwszej chwili osoby "młode" będą to moim zdaniem ignorować po prostu w taki sam sposób jak reklamę np. kleju do protez zębowych (przepraszam ale muszę być szczery, tu zastrzegam że nie jest złośliwość względem kogokolwiek).

Ta reklama w telewizji jest stanowczo przekombinowana i ośmielam się postawić tezę że przy (chyba) tak stosunkowo małej (?) liczbie pobrań ona po prostu nie działa a **być może wręcz odstręcza wiele osób**.

Ogólnie w mediach cisza o temacie, a w dodatku udaje się że "wirus jest w odwrocie" co mnie jako lekarzowi nie mieści się po prostu w głowie... 

Przekaz powinien być **precyzyjny, klarowny, jasny, prosty i czytelny** a nie przez 90% czasu opowiadać "bajkę" której nikt niewtajemniczony nie zrozumie i zupełnie brak w niej impulsu do działania. **Wręcz usypia** (czujność!).

To nie jest przecież jakaś reklama piwa żeby opowiadać wydumane historyjki (usypiającym) tonem gawędziarza, moim zdaniem to musi być KONKRET.

Ciekawy jestem jakie są przemyślenia innych zaangażowanych tutaj osób o tej reklamie/kampanii.

Być może się mylę ale przy tak małej (?) liczbie pobrań właśnie w wakacje kiedy aplikacja tym bardziej jest potrzebna to jest naprawdę bardzo duże rozczarowanie...

Z drugiej strony,  jeśli zmanipulowani ludzie nie noszą nigdzie nawet masek, to jak tu spodziewać się powszechności użycia aplikacji, chociaż ta tym bardziej wobec powszechnego "rozprężenia" jest właśnie teraz potrzebna... Paradoks.

Pozdrawiam Autorów i wszystkich tutaj zaangażowanych.

**Comment by potiuk** [comment]
Bardzo dobry artykuł na ten temat tutaj: 

https://www.technologyreview.com/2020/07/10/1005027/8-million-people-14-alerts-why-some-covid-19-apps-are-staying-silent/

Moja ocena sytuacji: 

Rządy (włączając rząd Polski) śpieszyły się żeby być "pierwsze" i żeby pokazać jak bardzo "walczą z pandemią". U nas dodatkowo podsycane przez wybory. Dodatkowo niektórzy "technokraci" którzy trochę zwietrzyli tu szansę na swoje miejsce jako liderów mesjanistycznego wykorzystanie technologii do tego że dzięki nim "ludzkość zostnie uratowana" podsycali ten hype.

Przez to same rządy i technokraci napędzili sobie i mediom napędziły "Hype" na to że BT-Contact Tracing rozwiąże wrzystkie problemy z Contact Tracingiem. Na szczęście ludzie okazali się bardziej odporni na ten hype.

Jak w przypadku praktycznie każdej technologii to się zdarza jesteśmy teraz w miejscu krzywej Gartnera (https://www.gartner.com/en/research/methodologies/gartner-hype-cycle) zwanym "Trough of Disillusionment". W tym przypadku "Peak of inflated expectations" był niesamowicie napędzony przez to że rządy same siebie zapędziły w kozi róg. Chciały to wykorzystać - przy okazji - do śledzenia swoich obywateli więc wielokrotne powtarzanie "technologie ratujące życie", "musimy działać szybko nawet jeśli nie do końca to jest prywatne", "nie mamy czasu żeby dyskutować bo trzeba robić" i "działamy dla dobra was wszystkich więc czemu się rzucacie" - to ostatnie do osób które od początku wołały o poszanowanie prywatności i o to, żeby przede wszystkim przygotowąć się na tradycyjny "contact tracing" a BT traktować tylko jako dodatek.

Drogi - jak w przypadku każdej technologii - są dwie. Albo okaże się że to faktycznie klapa, albo okaże śię że nauczeni doświadczeniem jesteśmy w stanie POWOLI wspiąć się po "slope of enlightenment" w kierunku "Plateau of productivity" gdzie zrozumiemy co taka technologia nam daje i jak ją mądrze i efektywnie wykorzystać. 

Według mnie, to państwa narodowe są tu podmiotami które mogą podjąć jjakiekolwiek decyzje - to one są odpowiedzialne za hype i za sposób wprowadzenia tej technologii w życie, nikt inny. Nie da się tego zrzucić na Google + Apple ani na protestujących aktywistów - obecne "through of disilussionment" ma podobny wymiar i w państwach które wprowadziły obowiązek instalacji aplikacji, i w państwach w których są zcentralizowane rozwiązania i w państwach, które stosują Exposure Notification. 

Rozwiązanie a) klapa - jest najprostsze. Ogłośmy że technologia nie działa i przesuńmy działania marketingowo-hype'owe na inne obszary (gdzie można zyskać punkty polityczne). A najlepiej zrzućmy winę za to na innych. To się, niestety najprawdopodobniej stanie, bo alternatywa jest dużo trudniejsza, bardziej ryzykowna a poza tym (to na końcu) wcale chyba naszemu rządowi niepotrzebna. 

Rozwiązanie b) w końcu rzetelne zastanowienie się i porządne wprowadzenie średnio-falowo a nie już rozwiązania które bęðzie - choćby częściowo - działać jest dużo trudniejsze, mniej medialne i nie można na nim zbijać kapitału politycznego. To rozwiązanie musi być kombinacją procedur, logistyki i zbudowania (z wyprzedzeniem, przygotowaniem i przeszkoleniem) rzetelnej kadry ludzi którzy będą umieli robić "contact tracing" w których technologia BT ich będzie wspomagać, a nie zastępować. Bardzo dobry przykład jak tego nie robić z UK, gdzie > 10.000  contact tracerów zorganizowanych przez agencję "body shoppingu" https://www.nytimes.com/2020/06/17/world/europe/uk-contact-tracing-coronavirus.html  przez wiele tygodni byli (i dalej są) opłacani za robienie niczego, nie byłi w żaden sposób przeszkoleni a cały system okazał się totalną klapą. Zorganizowanie takiego systemu wymaga kompetencji, doświadczenia w zarządzaniu ludźmi i procesami, umiejętności zorganizowania i przeszkolenia odpowiednich kadr i zrobienia tego w taki sposób,  żeby można było skalę tego systemu dostosowywać do bieżącej sytuacji (I np. spodziewanego wzrostu liczby zachorowań jesienią). To wszystko jest szalenie skomplikowane - może łatwo wykazać niekompetencje ludzi w to zaangażowanych, trudno takie działania wykorzystać medialnie - jedym słowem brudna, trudna robota, za którą nikt nikogo nie pochwali i nie da się na tym zbić kapitału. Elementem tego powinno być (według mnie) pogodzenie się z tym, że aplikacja jest niepotrzebna większości ludzi i że o wiele lepszym pomysłem jest faktyczne dogadanie się przez wszystkie rządy z Google i Apple, żeby system działał bez konieczności instalowania aplikacji - jedynie przez "zgodę" na dołączenie do "Exposure Notification". Gdyby wszyscy interesariusze zgodnie stwierdzi "to jest słuszna koncepcja" i zgodnie jednym głosem zaczęli o tym mówić to wtedy jest szansa na to, że rozwiązanie stanie się bardziej powszechne - czyli też bardziej użyteczne.

To rozwiązanie może mieć szansę na wprowadzenie w państwach w których są "mądrzy rządzacy" którym zależy na tym żeby problem faktycznie rozwiązać.

Obawiam się że to nie u nas niestety. Moim skromnym zdaniem rządowi wcale nie musi zależeć na rozwiązaniu problemu pandemii. O wiele łatwiej się rządzi kiedy można społeczeństwo "straszyć", nakładać "arbitralne" niczym nie uzasadnione ograniczenia, manipulować opinią publiczną prezentując liczby zakażeń co do których rząd ma faktyczną kontrolę, w końcu wprowadzając chyłkiem swoje od dawna trudne do wprowadzenia przepisy przy okazji kolejnych "Tarcz Antykryzysowych". 

Może jestem zbytnim sceptykiem, ale nie liczyłbym na to, że nasz rząd zrobi wszystko, żeby problem rozwiązać.

**Comment by Dr-Kownacki** [comment]
Dzięki @potiuk  za jak zawsze dogłębne odniesienie do tematu.

Tym bardziej mnie to zastanawia jak poczytałem w poleconym artykule o MILIONACH instalacji w innych krajach np. w Niemczech... Ministerstwo Cyfryzacji podaje chyba ok.200 tys pobrań dotąd w Polsce (?).

A przecież prostą czytelną reklamą można dotrzeć do praktycznie 100% społeczeństwa, **wystarczy codziennie o 19:29 konsekwentnie podawać prosty i krótki 15s komunikat przez miesiąc w TVP1**, zwłaszcza że teraz w okresie wakacyjnym to jest szczególnie przydatne praktycznie... Wtedy byłaby nadzieja na miliony instalacji.

W moim przekonaniu ogólnie Służba Zdrowia może też jakoś tutaj pomóc. 
Jakby jakieś plakaty były porozwieszane na Izbach Przyjęć, w przychodniach etc. to też info trafiłoby do teoretycznie statystycznie bardziej narażonych osób zwłaszcza w ośrodkach onkologicznych.
Być może jest też tutaj pole do działania dla Ministerstwa Zdrowia żeby to jakoś wypromować. Taki pomysł.

Dodatkowo (jak zawsze tutaj podkreślałem) w moim przekonaniu dodatkowa opcja "**ręcznego logowania kontaktów" przez QR-kody** jeżeli jest realne bliskie spotkanie być może pozwoliłoby skuteczniej działać wspólnie z "automatem". 
Tylko pozostaje kwestia że pewnie nie da się zrobić takiego override "siłowego" żeby wzajemnie po prostu "wstrzyknąć sobie" te klucze "na skróty" za bilateralną zgodą... Bo jak rozumiem API A+G to jest Black Box jednak i nie można chyba (???)

Jak zawsze podkreślałem takie dodatkowe "ręczne" rozwiązanie byłoby idealne z różnych powodów dla służby zdrowia  i cały czas wypatruję takiej opcji w ProteGo Safe. 
Nawet jeżeli nie wykorzysta się do tego API to chyba "w warstwie powyżej" taka LOKALNA baza danych kontaktów/spotkań mogłaby przecież sobie działać i w razie zakażenia poprzez SMS/mail uzyskane ze zbieranych QR-kodów ostrzec innych.

Nadal czekam na jakiś respons od Autorów w temacie statystyk i ich przemyśleń na realne zwiększenie popularyzacji aplikacji :-)

**Comment by bartosztomczak** [comment]
@Dr-Kownacki - Ostatnio pojawiła się druga bardziej opisowa reklama, czy według Pana idzie w dobrym kierunku?

**Comment by Dr-Kownacki** [comment]
@bartosztomczak:
Nie, ja znam tylko tego "gawędziarza" - czyli lektora jakby rodem wprost z  dubbingu "Władcy Pierścieni" ;-)))
Sorry ale dla mnie to istny Gandalf z głosu, a tu trzeba "nowocześnie" moim skromnym zdaniem...

Nie jestem wyrocznią ale tak ja to szczerze czuję i dlatego piszę a nie żeby komuś dopiec czy coś obśmiać, zależy mi bardzo na sukcesie tego projektu i powszechności pobrań. 
Bo skoro ja "świadomy" tak to odbieram to tym bardziej ktoś "niewtajemniczony" chyba...

**Link jakiś macie do tej "nowej"  reklamy ?** Bo ja całkiem niedawno tę "starą" widziałem w TV wręcz w ostatnich dniach, jakieś motylki etc...

**Comment by bartosztomczak** [comment]
@Dr-Kownacki 
Niestety nie znalazłem oficjalnego źródła - https://www.youtube.com/watch?v=n3d-O8iYuC0

**Comment by Dr-Kownacki** [comment]
Super, no i to jest **KONKRET** !

Ja dałbym dodatkowo nazwę cały czas widoczną większymi literami w jednym stałym miejscu ekranu, tak żeby absolutnie każdy zdążył zapamiętać/zapisać.

Jakby to szło np. przed głównym wydaniem "Wiadomości" przez miesiąc-dwa zawsze na końcu bloku reklamowego to jest szansa na wielki sukces pobrań idący w miliony, czego Autorom i wszystkim szczerze życzę. 
Tak żeby na "po wakacjach" to już prawie wszyscy w Polsce to mieli, bo to będzie bardzo ważne moim zdaniem i życie wtedy to realnie zweryfikuje już w warunkach "drugiej fali" COVID...

No i z uporem maniaka przypominam się Autorom o te QR-kody i "lokalną bazę" :-) 

.

**Comment by potiuk** [comment]
No i całkiem niezłe podsumowanie tego co działo się do tej pory https://spidersweb.pl/plus/2020/07/polska-aplikacja-do-walki-z-panademia-niewypal

**Comment by tomekziel** [comment]
> Czy można dowiedzieć się ile było dokładnie pobrań łącznie Android/iOS ?

Ćwierć miliona.

> Ile osób z zakażonych miało aplikację i **dokonano uploadu ich kluczy** ?

Właśnie piszę o tym artykuł, wkleję link gdy go opublikuję.

> Jakby to szło np. przed głównym wydaniem "Wiadomości" przez miesiąc-dwa zawsze na końcu bloku reklamowego to jest szansa na wielki sukces pobrań idący w miliony, czego Autorom i wszystkim szczerze życzę.

Wiadomości w TVP ogląda mniej niż 10% Polaków.

**Comment by sobaw98247** [comment]
Artykuł @tomekziel: https://informatykzakladowy.pl/aplikacja-protego-safe-nie-dziala-czas-zatrzymac-te-inwestycje

Statystyki w innych krajach: https://qz.com/1880457/global-contact-tracing-app-downloads-lag-behind-effective-levels/

**Comment by tomekziel** [comment]
> Ile osób z zakażonych miało aplikację i **dokonano uploadu ich kluczy** ?

Wskazany w poprzednim wpisie artykuł zachowuje aktualność. Od 23 czerwca do dziś - 7 sesji uploadu, 21 kluczy. Najnowszy upload - 2020-07-14.

**Comment by MadryPan1987** [comment]
https://www.onet.pl/informacje/onetwiadomosci/koronawirus-w-hiszpanii-barcelona-oglasza-lockdown-z-powodu-pandemii-koronawirusa/r8cfqxp,79cfc278

https://www.onet.pl/informacje/onetwiadomosci/koronawirus-epidemia-wyrwala-sie-w-ameryce-spod-kontroli-i-zagraza-reelekcji-trumpa/ecf60hm,79cfc278

**Comment by Dr-Kownacki** [comment]
@MadryPan1987 :

Meanwhile in Poland... 

https://tvn24.pl/polska/koronawirus-w-polsce-skrocenie-dystansu-spolecznego-zmiany-dla-kibicow-projekt-rozporzadzenia-rady-ministrow-4640650

 ;-) czy raczej  ;-(  ...

**Comment by MadryPan1987** [comment]
@Dr-Kownacki 
No to jest najgorsze :(((
Ale ProteGo to nie jest bron na teraz, to bron przyszłosci, a szczegolnie w dzialniach miedzy innymi krajami.
Kraje turystyczne długo nie wytrzymają kolejnych lockdownów. Zresztą kraje nie turystyczne równierz.
Może się okazać że aplikacje typu protego będą niezbędne w przyszłosci.
A tym czasem cieszym się że nie musimy ich używać, ale też cieszymy się że je mamy i mam nadzieje że bedą ulepszane.
Strasznie bym widział wersje Lite którą omówilem tutaj #214.
Myśle że rozwiązała by dużą czesć problemu, równierz ze strony marketingowej :))

**Comment by potiuk** [comment]
Pomysł z #214  to nic innego jak to o czym od początku mówili Google i Apple (nawet lepiej - bo w ogóle bez aplikacji). Ja bym już nie wydawał ani grosza na wersje lite tylko namawiam rząd, żeby dogadał się z pozostałymi rządami i razem ustalili z Google i Apple że oni otworzą swój kod, a kraje będą to promować i zrezygnują ze swoich aplikacji do "codziennego użytku" i większość ludzi po prostu namawiać do włączenia "Exposure Notification" w telefonie. Tak jak to wielokrotnie pisałem - według mnie to jedyna szansa na uzyskanie powszechności rozwiązania. 

I od paru miesięcy czekam kiedy to się stanie (bo to, że się stanie to nie mam wątpliwości). Po raz kolejny napiszę to co już mówiłem. Google + Apple celowo nic nie mówiło o tym scenariuszu, żeby nie zniechęcać państw to dołączania do systemu (bo państwa miały nadzieję że jednak uda się sprawić że apka coś tam śledząca będzie zainstalowana u dużej liczby ludzi. Teraz, kiedy państwa zobaczą że to mrzonka, temat może wrócić.

Czekam niecierpliwie, nie instalując aplikacji (bo wierzę, że nie będę tego musiał robić w ogóle).

**Comment by SeraMoon** [comment]
> Z drugiej strony, jeśli zmanipulowani ludzie nie noszą nigdzie nawet masek, to jak tu spodziewać się powszechności użycia aplikacji, chociaż ta tym bardziej wobec powszechnego "rozprężenia" jest właśnie teraz potrzebna... Paradoks.

Zmanipulowani? To właśnie ci którzy nie dają się zmanipulować. Koncert manipulacji był widoczny między 28 czerwca a 12 lipca. Ja przestałam już wierzyć w jakiekolwiek informacje "oficjalne od rządu". Prawdziwe zwyczajnie nie istnieją po tym co widziałam co działo się w Polsce. Przy wręczaniu "czeków" też nie było maseczek i jakoś ludzie żyją, a "wirus jakoś się nie rozrósł". 

Nie mówię, że C0V1D nie istnieje, tylko zwyczajnie jest statystycznie tak samo prawdopodobne, że umrę jak to że umrę na grypę. Na grypę sezonową corocznie umiera 750 tys. ludzi na świecie. Dotychczas na C0V1D umarło 600 tys. ludzi na świecie. Straszeniu na pewno się nie dam. Maseczkę noszę jedynie ANTYMANDATOWO (i żeby inni nie panikowali, że ich zarażam). O ile ilość wykryć przyspiesza wciąż na świecie o tyle ilość śmierci wyhamowuje. Albo wirus robi się mniej groźny (wypowiedź epidemiologa z Włoch), albo zwyczajnie kraje lubią wywalać coraz więcej pieniędzy na testy przesiewowe.

**Comment by miklobit** [comment]
> I od paru miesięcy czekam kiedy to się stanie (bo to, że się stanie to nie mam wątpliwości). Po raz kolejny napiszę to co już mówiłem. Google + Apple celowo nic nie mówiło o tym scenariuszu, żeby nie zniechęcać państw to dołączania do systemu (bo państwa miały nadzieję że jednak uda się sprawić że apka coś tam śledząca będzie zainstalowana u dużej liczby ludzi. Teraz, kiedy państwa zobaczą że to mrzonka, temat może wrócić.
> 
Jeżeli rządy zostawią sprawy producentom telefonicznych OS'ow to jest bardzo duża szansa, granicząca z pewnością, że dobrowolność używania śledzenia kontaktów sprowadzi się do  prawa użytkownika do jej wyłączenia.  A producenci domyślnie to API włączą. My jako konsumenci i obywatele nie będziemy mieli żadnego skutecznego narzędzia nacisku, żeby tak się nie stało. Tzn będzie dokładnie samo wyjście jak jest wobec praktyk gigantów teraz - albo samo-wykluczenie cyfrowe albo alternatywne OSy na telefon. Jedno i drugie nie do przyjęcia dla 99% ludzi.

**Comment by potiuk** [comment]
> Jeżeli rządy zostawią sprawy producentom telefonicznych OS'ow to jest bardzo duża szansa, granicząca z pewnością, że dobrowolność używania śledzenia kontaktów sprowadzi się do prawa użytkownika do jej wyłączenia. A producenci domyślnie to API włączą. My jako konsumenci i obywatele nie będziemy mieli żadnego skutecznego narzędzia nacisku, żeby tak się nie stało. Tzn będzie dokładnie to samo wyjście jakie jest wobec praktyk gigantów obecnie - albo samo-wykluczenie cyfrowe albo alternatywne OSy na telefon. Jedno i drugie nie do przyjęcia dla 99% ludzi.

A może inaczej. "Bogu co boskie, cesarzowi co cesarskie". Może niech państwa narodowe (oraz EU) zajmą się tym, czym powinny się zajmować - czyli tworzeniem i egzekwowaniem prawa. Dlaczego nie nakazać (prawnie) otwarcia kodu wszystkich komponentów które służą do kontakt tracing (czyli bibliotek Google i Apple i wszystkich serwerów). Dlaczego nie nakazać żeby to było opt-in? Gdyby wszystkie kraje unii takie stanowisko by przedstawiły, Google i Apple nie miało by wyjścia tylko to zaakceptować. W jedności siła. I jednocześnie kraje same sobie narzuciły by otwartość i decentralizację. 

Właśnie po to jest państwo - żeby służyć swoim obywatelom i reprezentować ich interesy. Państwo nie zna się na tworzeniu aplikacji - ale powinno się znać na tworzeniu prawnych zasad, które regulują ich powstawanie w przypadkach w których na przykład chodzi o zdrowie swoich obywateli.

Przykro mi, ale nie wierzę że "państwo" które nie potrafi zadbać nawet o to, żeby ich aplikacja nie przekazywała do Google'a prywatnych danych: jak właśnie niezależni audytorzy: proszę spojrzeć do  #215 znajdują że Twórcy aplikacji sami wysyłają prywatne dane do Google'a mimo, że nie muszą tego robić (a nawet więcej - mimo że inne aplikacje tego rodzaju robią wszystko żeby tego nie robić). 

To właśnie państwo powinno być naszym - obywateli - narzędziem do tego żeby właśnie wykorzystać to że firmy takie jak Google i Apple wiedzą co robią technicznie, a żeby też nadzorować ich żeby nasze dane były bezpieczne.

**Comment by potiuk** [comment]
I jeszcze jedno - są tacy, którzy mówią "nie da się" albo "no jak to, przecież to potrwa miesiącami" etc.  A ja to widzę jako objaw niekompetencji i być może złej woli tych, którzy za nasze - podatników - pieniądze powinni właśnie wykorzystywać to narzędzie, które mają - tworzenie prawa, domaganie się otwartości, możliwości dogadania się z innymi rządami - tak żeby działać na rzecz swoich obywateli. To tu się powinny skupiać ich działania. A jeśli się nie sprawdzą, to powinniśmy ich pożegnać i wybrać innych, bardziej kompetentnych ludzi którzy faktycznie będą nam - obywatelom - służyć, zamiast służyć na przykład swoim partyjnym interesom, przyjaciołom i znajomym.

**Comment by tomekziel** [comment]
> Google i Apple nie miało by wyjścia tylko to zaakceptować

... albo wyłączyć

**Comment by potiuk** [comment]
> > Google i Apple nie miało by wyjścia tylko to zaakceptować
> 
> ... albo wyłączyć

Wtedy można im nakazać włączyć prawnie.

**Comment by potiuk** [comment]
Na przykład tak jak to się stało wczoraj w innej sprawie: https://arstechnica.com/tech-policy/2020/07/court-tosses-us-eu-data-sharing-agreement-amid-us-surveillance-concerns/

**Comment by potiuk** [comment]
I jeszcze jedno - gdyby wszystkie kraje teraz powiedziały jasno G+A że to jedyne wyjście - to najpewniej nikt do sądu nie będzie chętny i po prostu będzie można się dogadać. I tu znowu - kompetencje negocjacyjne, dyplomatyczne do tego są potrzebne, żeby to sprawnie przeprowadzić. I tego na przykład od rządu mojego państwa wymagam.

**Comment by SeraMoon** [comment]
>  albo samo-wykluczenie cyfrowe albo alternatywne OSy na telefon. Jedno i drugie nie do przyjęcia dla 99% ludzi.

Proponuję każdemu, kto tylko jest w stanie żyć bez smartfona. nie mam smartfona i żyję :-) Jak to powiedział Franklin: 
`Ludzie, którzy dla tymczasowego bezpieczeństwa rezygnują z podstawowej wolności, nie zasługują ani na bezpieczeństwo, ani na wolność.` 
ProteGO-Safe i Exposure Notification są właśnie takimi tworami. Co gorsza, ludzie oddadzą swoją wolność, będą chodzić na smyczy dla poczucia bezpieczeństwa a nie realnego bezpieczeństwa 🤦 . 

> To właśnie państwo powinno być naszym - obywateli - narzędziem do tego żeby właśnie wykorzystać to że firmy takie jak Google i Apple wiedzą co robią technicznie, a żeby też nadzorować ich żeby nasze dane były bezpieczne.

Przepraszam, ale obecnie to my jesteśmy narzędziami dla Państwa, aby dało się więcej pieniędzy z nas wyciągnąć (kolejne podatki), oszukać (Duda obiecywał podwyżkę emerytur, szejm powiedsział, że to były tylko życzenia...). Ja nie wierzę, że to Państwo nas przed kimkolwiek obroni za to polecę 
### Skargę przez Europe Direct (wuropa.eu)
lub też wniosek (petycję, apel) do Komisje Europejskiej (też gdzieś tam jest ten formularz). To będzie skuteczniejsze, gdy razem stworzymy taki apel i wyślemy tam niż będziemy błagać o to państwo. 
Aby apel był skuteczny należy podnieść kwestie prywatności oraz RODO - szczególnie na to drugie są podobno dość cięci. 

> 
> 
> > Google i Apple nie miało by wyjścia tylko to zaakceptować
> 
> ... albo wyłączyć

Dokładnie tak, Nie zrobią wyjątku dla Polski. Prawdopdobnie nawet gdyby z rynku im wyciąć całę Europę...

**Comment by SeraMoon** [comment]
>  albo samo-wykluczenie cyfrowe albo alternatywne OSy na telefon. Jedno i drugie nie do przyjęcia dla 99% ludzi.

Proponuję każdemu, kto tylko jest w stanie żyć bez smartfona. nie mam smartfona i żyję :-) Jak to powiedział Franklin: 
`Ludzie, którzy dla tymczasowego bezpieczeństwa rezygnują z podstawowej wolności, nie zasługują ani na bezpieczeństwo, ani na wolność.` 
ProteGO-Safe i Exposure Notification są właśnie takimi tworami. Co gorsza, ludzie oddadzą swoją wolność, będą chodzić na smyczy dla poczucia bezpieczeństwa a nie realnego bezpieczeństwa 🤦 . 

> To właśnie państwo powinno być naszym - obywateli - narzędziem do tego żeby właśnie wykorzystać to że firmy takie jak Google i Apple wiedzą co robią technicznie, a żeby też nadzorować ich żeby nasze dane były bezpieczne.

Przepraszam, ale obecnie to my jesteśmy narzędziami dla państwa (kraju), aby dało się więcej pieniędzy z nas wyciągnąć (kolejne podatki), oszukać (Duda obiecywał podwyżkę emerytur, szejm powiedsział, że to były tylko życzenia...). Ja nie wierzę, że to Państwo nas przed kimkolwiek obroni za to polecę 
### Skargę przez Europe Direct (europa.eu)
lub też wniosek (petycję, apel) do Komisji Europejskiej (też gdzieś tam jest ten formularz). To będzie skuteczniejsze, gdy razem stworzymy taki apel i wyślemy tam niż będziemy błagać o to państwo. 
Aby apel był skuteczny należy podnieść kwestie prywatności oraz RODO - szczególnie na to drugie są podobno dość cięci. 

> 
> 
> > Google i Apple nie miało by wyjścia tylko to zaakceptować
> 
> ... albo wyłączyć

Dokładnie tak (wyłączą, nie dając nic w zamian), Nie zrobią wyjątku dla Polski. Prawdopdobnie nawet gdyby z rynku im wyciąć całę Europę...

**Comment by potiuk** [comment]
> > ... albo wyłączyć
> 
> Dokładnie tak (wyłączą, nie dając nic w zamian), Nie zrobią wyjątku dla Polski. Prawdopdobnie nawet gdyby z rynku im wyciąć całę Europę...

Nie dla Polski. Chodzi o to, żeby wszystkie Państwa jednym głosem mówiły. Tylko do tego trzeba dyplomacji, chęci porozumienia się, woli politycznej ....

**Comment by MadryPan1987** [comment]
> Skargę przez Europe Direct (europa.eu)
@SeraMoon 
Moge prosić o nie fomatowanie tego w taki sposób? Wygląda to tragicznie na telefonie.

**Comment by SeraMoon** [comment]
> 
> 
> > Skargę przez Europe Direct (europa.eu)
> > @SeraMoon
> > Moge prosić o nie fomatowanie tego w taki sposób? Wygląda to tragicznie na telefonie.

Nie wiem co masz na myśli. U mnie działa poprawnie. 
https://i.ibb.co/B2b3KB8/github.jpg
Najlepiej zgłoś problem do osób odpowiedzialnych za GitHuba (Microsoft), bo każdemu może co innego się źle wyświetlać oraz do firmy odpowiedzialnej za rozwój twojej przeglądarki.

**Comment by MateuszRomanow** [comment]
> > > ... albo wyłączyć
> > 
> > 
> > Dokładnie tak (wyłączą, nie dając nic w zamian), Nie zrobią wyjątku dla Polski. Prawdopdobnie nawet gdyby z rynku im wyciąć całę Europę...
> 
> Nie dla Polski. Chodzi o to, żeby wszystkie Państwa jednym głosem mówiły. Tylko do tego trzeba dyplomacji, chęci porozumienia się, woli politycznej ....

"Dobra wola" to kwestia mocno subiektywna, jeżeli mam subiektywnie na bazie doświadczeń ze wszystkich rozmów z innymi krajami powiedzieć czy jest, to tak, jest "wola". Natomiast z faktów:
- wszystkie kraje, które już mają aplikację oraz te które planują ją wdrożyć (czytaj: wszystkie kraje UE) pracują nad wspólnym standardem komunikacji pomiędzy aplikacjami "Interoperacyjność"
- G&A wydają się bardziej zainteresowane współpracą w modelu aplikacyjnym niż braniu całości na siebie
- lakonicznie ( z powodu NDA) powiem, że jest dyskutowana koncepcja, w której narodowe aplikacje będą pre-instalowane (wymagające zgody użytkownika) na iOS i/lub Android. Co ważne w tej koncepcji mowa o aplikacjach, a nie samej funkcjonalności EN działającej poza aplikacjami.
- kontekst i watek Local health Authority jest bardzo ważny i G&A rozumieją, że to jest poza obszarem ich działania, wiec do współpracy potrzebny jest dialog państwa <> G&A
- tai dialog w EU jest już prowadzony, zarówno pomiędzy każdym z państw osobno <> Google/Appe jak i pomiędzy Parlament Europejski <> Google / Apple . Dużo rozmów, dużo "woli", ale postęp nie idzie tak szybko jak wszyscy oczekują. Mówimy to o mocnym R&D również na poziomie politycznym, więc wszystkie strony kreują tą sytuację a nie korzystają z gotowych rozwiązań/doświadczeń (bo ich nie ma) 
- jest dyskutowany w Parlamencie Europejskim budżet nad tworzeniem Europejskiego standardu interoperacyjności. Prace np. Niemiec, które są liderem tego procesu zwolniły, ponieważ czekają na to co zostanie tam ustalone.

**Comment by potiuk** [comment]
> 
> "Dobra wola" to kwestia mocno subiektywna, jeżeli mam subiektywnie na bazie doświadczeń ze wszystkich rozmów z innymi krajami powiedzieć czy jest, to tak, jest "wola". Natomiast z faktów:

Trzymam kciuki żeby wola przerodziła się w fakty. Parafrazując reklamę ProteGO " Wszystko w rękach rządów i G+A".  O to apelowałem od samego początku żeby nie było "my i oni" tylko żeby było razem. Zbyt często pojawiają się głosy że "albo państwa albo G+A" a tymczasem od początku uważam, że trzeba razem.

> * wszystkie kraje, które już mają aplikację oraz te które planują ją wdrożyć (czytaj: wszystkie kraje UE) pracują nad wspólnym standardem komunikacji pomiędzy aplikacjami "Interoperacyjność"

Też o tym pisałem. Znowu to kwestia tylko tego żeby kraje się dogadały co do wymiany danych o zarażonych. Właśnie to że jest jeden standard (G+A) mocno ułatwia zaimplementowanie tego.

> * G&A wydają się bardziej zainteresowane współpracą w modelu aplikacyjnym niż braniu całości na siebie

Nikt nie mówi o braniu całości na siebie. Cała część serwerowa jest dalej w rękach "Health Authorities". 

> * lakonicznie ( z powodu NDA) powiem, że jest dyskutowana koncepcja, w której narodowe aplikacje będą pre-instalowane (wymagające zgody użytkownika) na iOS i/lub Android. Co ważne w tej koncepcji mowa o aplikacjach, a nie samej funkcjonalności EN działającej poza aplikacjami.

Mam nadzieję że to nigdy się nie stanie. To jest bardzo zły pomysł i zupełnie niepotrzebny. 

> * kontekst i watek Local health Authority jest bardzo ważny i G&A rozumieją, że to jest poza obszarem ich działania, wiec do współpracy potrzebny jest dialog państwa <> G&A

Zawsze też tak uważałem.

> * tai dialog w EU jest już prowadzony, zarówno pomiędzy każdym z państw osobno <> Google/Appe jak i pomiędzy Parlament Europejski <> Google / Apple . Dużo rozmów, dużo "woli", ale postęp nie idzie tak szybko jak wszyscy oczekują. Mówimy to o mocnym R&D również na poziomie politycznym, więc wszystkie strony kreują tą sytuację a nie korzystają z gotowych rozwiązań/doświadczeń (bo ich nie ma)

Super. Czekamy na wyniki. 

> * jest dyskutowany w Parlamencie Europejskim budżet nad tworzeniem Europejskiego standardu interoperacyjności. Prace np. Niemiec, które są liderem tego procesu zwolniły, ponieważ czekają na to co zostanie tam ustalone.

No i świetnie.

**Comment by pkleczko** [comment]
@Dr-Kownacki czy możemy zamknąć już to issue? wątek nie jest dalej dyskutowany, proponuję też nie wyciągać wniosków na tego czy projekt jest klapą czy nie po kilku tygodniach działania, kiedy w społeczeństwie widać było rozluźnienie. Oczywiście jak wielokrotnie było wspominane skuteczność działania zależy od ilości użytkowników, ta jest wciąż zbyt mała żeby ją oceniać, ale jak widać po ostatnich wzrostach ilości zachorowań, która przekłada się też na zwiększenie ilości instalacji to się może zmienić za jakiś czas. Dajmy sobie czas na wyciągnięcie konkretnych wniosków. Wywiązała się tutaj fajna dyskusja, ale z racji że wątek został omówiony możemy go zamknąć?
