### ISSUE TITLE
ProteGo Lite

### ISSUE THREAD

**Issue by MadryPan1987** [ProteGO-Safe/specs#214]
Witam,
Kiedy kurz po wersji 4 opadł, a COVID-19 na tą chwile ma się w odwrocie, to zasadne byłby wypuszczenie wersji Lite, dla użytkowników którzy nie zamierzają korzystać z dziennika zdrowia ani porad koronowirusowych.

Aplikacja mogłaby dawać tylko dostęp do COVID API i tyle.
W przypadku podejrzenia koronowirusa a nawet w przypadku udostępnienia kluczy, mogłaby prosić o zainstalowanie pełnej wersji.

Sądze że o ile te wszystkie dodatki są bardzo szlachetne i fajnie że aplikacja została z nimi wydana (lepiej mieć niż niemieć), to dla jak dla mnie totalnie zbędne.

Nie uruchamiam aplikacji ProteGo praktycznie w ogóle. Jednak jestem pewny że ona działa w tle, bo gdy wyłączam BL to dostaje powiadomienie... i to też jest prawie spoko... chociaż moją dziewczynę mocno denerwuje. Jest osobą posiadającą więcej niż jeden telefon i czasami wyłączenie BL to dla niej najlepsza opcja w celu sparowania innych urządzeń

Wersja Lite powinna:

 - posiadać tylko niezbędny kod do obsługi COVID API
 - w koniecznym przypadku prosić o instalacje pełnej wersji
 - tylko jeżeli to niezbędne, posiadać mechanizm do wysyłania kluczy
 - nie posiadać kodu JS
 - z racji mikroskopijnych rozmiarów powinna zostać pokryta w 100% unit testami
 - Jeżeli protokół COVID API nie pozwala na dwie aplikacje w obrębie jednego kraju to specjalnie dla Polski powinna być taka funkcja dostępna, z powodu niskiego rozpropagowania aplikacji, co ma pewnie związek z niewielką liczbe chorych jak na inne kraje świata... jednak nie powinniśmy tracić czujności... Izrael znowu 1000 chorych dziennie i lokale zostały zamknięte... bądźmy przygotowani na powtórny lockdown jeżeli już ma nastąpić.

Plusy wydania wersji lite:

- aplikacja na telefonach użytkowników będzie zajmować mniej miejsca
- aplikacja będzie posiadać tylko niezbędne i najbardziej interesujące funkcje
- aplikacja nie będzie zawierać web view ani PWA
- aplikacja będzie mniej podatna na negatywne oceny w sklepie google play / app store
- aplikacja będzie działać dużo szybciej, gdyż nie będzie musiała angażować web view a co za tym idzie chrome V8 do działania.
- kod aplikacji będzie dużo bardziej zrozumiały dla programistów którzy nie posiadają wiedzy na temat JS oraz React
- aplikacja nie będzie zbierała żadnych dodatkowych danych (nawet na dysku), oprócz tych niezbędnych dla COVID API
- audyt aplikacji będzie dużo prostszy bo sprowadzi się do zrozumienia android / ios studio + COVID API

Żeby nie było zbyt kolorowo to minusy:

- aplikacja nie będzie prowadzić działań profilaktycznych w zwalczaniu COVID, jednak inne media promują profilaktykę (radio / telewizja / radio węzły w sklepach / szkoły / uniwersytety / sklepy / internet)
- aplikacja sama w sobie nie będzie zawierać informacji alarmowych ani profilaktyczny w przypadku wykrycia kontaktu, jednak tutaj można by zrobić 1 ogólny widok z podstawowymi informacjami jak nr telefonu lub informacje o pełnej wersji.

Podsumowując
Funkcje takie jak dziennik zdrowia, porady oraz FAQ to jest to co wszyscy powtarzają wszędzie w kołko. Nie sądzę żeby osoby poniżej 60 roku życia kiedykolwiek z nich skorzystały... to tak jak z grami na telefon, 5 min i nigdy się ich nie włącza.

**Comment by potiuk** [comment]
Do tego w ogóle nie trzeba aplikacji - dokładnie tak (a nawet lepiej bo w ogóle bez aplikacjii) miał działać oryginalny pomysł na który ja czekam od momentu w którm G+A ogłosiło Exposure Notification. Mam nadzieję już wkrótce w ogóle nie trzeba będzie aplikacji - wystarczy zgoda na udział w Exposure Notification na poziomie systemu.

Wielokrotnie pisałem że według mnie tak się to właśnie skończy.

**Comment by kwiszowaty** [comment]
> COVID-19 na tą chwile ma się w odwrocie

Niestety co do tego to mam wątpliwości...

**Comment by SeraMoon** [comment]
> 
> 
> > COVID-19 na tą chwile ma się w odwrocie
> 
> Niestety co do tego to mam wątpliwości...

Powiem tyle, "epidemia" potrwa tyle ile powie rząd Polski. Definicja epidemii jest taka jak każdy widzi - zawarta jest w prawie. Jest tam masa stwierdzeń typu "chyba", "dużo", "znacznie więcej", "nowa choroba" itp. To jest uznaniowe kiedy C0V1D przestanie być uznawany za nową chorobę i kiedy zostanie uznane, że ilość zachorowań jest większa niż w poprzednich okresach (jak długich - tygodniowych, 5-letnich okresach?). 

Tak więc potwierdzam, "epidemia COVID-19" nie skończy się w tym roku. Zwyczajnie zbyt wiele danych o ludziach można zebrać stosując obecne przepisy i zbyt wiele ugrać kosztem niestety tego, że przedsiębiorcy zbankrutują a obywatele się wyprowadzą tam gdzie epidemia się już skończyła. Obecnie chorują też owoce cytrusowe i kozy oraz ścieki z marca 2019 - z taką samą częstością chorujemy w Polsce (% dodatnich testów).

**Comment by MadryPan1987** [comment]
> Powiem tyle, "epidemia" potrwa tyle ile powie rząd Polski. 

Epidemia potrwa tyle ile powiedzą ludzie z wykształceniem medycznym.
To co piszesz jest karalne:
https://www.gov.pl/web/cyfryzacja/koronawirus-w-internecie--razem-przeciw-dezinformacji-i-nieuczciwym-praktykom

I twój post nie ma nic wspólnego z protego lite.

**Comment by SeraMoon** [comment]
@MadryPan1987 nic nie jest karalne, a jeżeli jest to mi to udowodnij. 

Tutaj masz legalną definicję Epidemii:
> „wystąpienie na danym obszarze zakażeń lub zachorowań na chorobę zakaźną w liczbie wyraźnie większej niż we wcześniejszym okresie albo wystąpienie zakażeń lub chorób zakaźnych dotychczas niewystępujących”
> -- Ustawa z dnia 5 grudnia 2008 r. o zapobieganiu i zwalczaniu zakażeń i chorób zakaźnych i ludzi (Dz.U. z 2019 r. poz. 1239).. 

Swoje słowa podtrzymuję - zgodnie z definicją słowa "epidemia" zawartą w polskim prawie.

**Comment by pkleczko** [comment]
@MadryPan1987 w planach nie ma wypuszczenia wersji Lite. czy możemy zamknąć to issue? zaczęło schodzić na polityczne wywody na temat tego ile trwa epidemia.

**Comment by SeraMoon** [comment]
@pkleczko możemy zamknąć to issue. Nie widzę problemu. Obecnie zamiast ProteGO-Lite potrzebne są rzeczy niezbędne dla szpitali, maski, fartuchy, HEPA itp. Przeznaczmy te pieniądze tam, bo tam realnie będą potrzebne. Epidemia nie jest w odwrocie, choć z tych 2 milionów przetestowanych osób - wśród znajomych i znajomych znajomych nie mam ani 1 wymazywanej osoby i ani 1 osoby, która chorowała... Mam mieszane uczucia odnośnie liczb, ale wątek można zamknąć, bo pieniądze potrzebne na rozwój należy przeznaczyć na realne potrzeby, w tym

### walkę z nienawiścią do osób LGBT.

Wstydzę się tego raju.

**Comment by thecodersio** [comment]
Tak jak pisał ostatnio @pkleczko nie ma w planach wersji lite. Temat jest do zamknięcia.
