### ISSUE TITLE
Brak testów (unit, integracyjnych) i platformy testowej

### ISSUE THREAD

**Issue by galuszkak** [ProteGO-Safe/specs#216]
Z tego co zauważyłem, większość, jeśli nie całość wyprodukowanego w tym projekcie kodu nie ma żadnych unit testów ani testów integracyjnych. Czy każdy release to ręczne testowanie aplikacji kodu serwera itd?

Wydaje mi się, że mimo wszystko tego typu aplikacje powinny mieć zalążek platformy testowej, żeby jakość dowiezionego rozwiązania miała chociaż jakąkolwiek gwarancję braku regresji w przyszłości.

Nie chcę tutaj tworzyć wojny TDD lub nic, ale jakakolwiek forma testów automatycznych była by warta rozważenia.

**Comment by SeraMoon** [comment]
Reasumując:
- brak testów,
- brak audytów bezpieczeństwa (#209),
- brak audytów prywatności (#215).

Student by ten projekt tak samo lub lepiej przygotował.

**Comment by MateuszRomanow** [comment]
> Z tego co zauważyłem, większość, jeśli nie całość wyprodukowanego w tym projekcie kodu nie ma żadnych unit testów ani testów integracyjnych. Czy każdy release to ręczne testowanie aplikacji kodu serwera itd?
> 
> Wydaje mi się, że mimo wszystko tego typu aplikacje powinny mieć zalążek platformy testowej, żeby jakość dowiezionego rozwiązania miała chociaż jakąkolwiek gwarancję braku regresji w przyszłości.
> 
> Nie chcę tutaj tworzyć wojny TDD lub nic, ale jakakolwiek forma testów automatycznych była by warta rozważenia.

W dotychczasowym hyper-rapid-developmencie powstał backlog, w którym testy są zacommitowane. W dalszych etapach zadania będą realizowane w ramach roadmapy, która właśnie powstaje w MC. W ramach niej też są testy. Kiedy taki plan powstanie, zorganizujemy kolejne spotkanie Community <> Ministerstwo Cyfryzacji, na którym będzie omówiony. Duży nacisk jest w tym momencie stawiany na interoperacyjność aplikacji i to jest teraz priorytetowo realizowane.

**Comment by SeraMoon** [comment]
@MateuszRomanow kiedy w repozytorium pojawi się pierwszy audyt prywatności (nie myląc z audytem bezpieczeństwa)?

**Comment by potiuk** [comment]
> @MateuszRomanow kiedy w repozytorium pojawi się pierwszy audyt prywatności (nie myląc z audytem bezpieczeństwa)?

Też czekam na to z utęsknieniem.

**Comment by galuszkak** [comment]
@MateuszRomanow zacząłem małe kroki, żeby takowe rzeczy umożliwiać.

Tutaj jakiś mini zrębek początku platformy testującej:
https://github.com/ProteGO-Safe/backend/pull/95

W Androidzie przygotowałem chociaż nałożenie sugestii linter-a który był wybrany w projekcie:
https://github.com/ProteGO-Safe/android/pull/137

Niestety CI tam jest nie chodzące bo nie jest wstrzykiwany klucz i nie działa od dłuższego czasu. Fajnie gdyby ktoś to naprawił, żeby można dodać tam więcej unittestów.

**Comment by thecodersio** [comment]
Cześć @galuszkak 

Dzięki za zainteresowanie naszym projektem oraz jego jakością :1st_place_medal: 

Rzucimy okiem w aktualnej iteracji na przygotowane przez Ciebie PRki i damy feedback - oczywiście jeżeli wszystko będzie ok to wepchniemy to do code base.

**Comment by galuszkak** [comment]
Zamykam.
