### ISSUE TITLE
Tłumaczenie aplikacji na angielski

### ISSUE THREAD

**Issue by MadryPan1987** [ProteGO-Safe/specs#220]
Hej,
Sorka za spam nowymi tematami, ale też nie mogę się doszukać... 
Czy jest w planach wersja angielska albo lepiej... ukraińska?

Mam problem, że współpracownicy z tamtej części świata nie zawsze znają polski, wiem że jest sporo do tłumaczenia ale przydałby się.

**Comment by SeraMoon** [comment]
Powinni pobrać ukraińską aplikację, bowiem w razie choroby powinni zostać pokierowani do ukraińskiej placówki medycznej na test, nie do polskiej.

**Comment by MateuszRomanow** [comment]
> Hej,
> Sorka za spam nowymi tematami, ale też nie mogę się doszukać...
> Czy jest w planach wersja angielska albo lepiej... ukraińska?
> 
> Mam problem, że współpracownicy z tamtej części świata nie zawsze znają polski, wiem że jest sporo do tłumaczenia ale przydałby się.

Tak, jest to w planie i jest to w backlogu. Dodanie wersji angielskiej jest zmianą, która jest najczęściej pojawiającą się prośbą o rozbudowę aplikacji zgłaszaną przez użytkowników. Ministerstwo Cyfryzacji jest poinformowane o rzeczach w backlog.

**Comment by pkleczko** [comment]
Mamy już przygotowaną wersję dostosowaną do obsługi innych języków, ukaże się w wydaniu 4.3.0, które trafi do sklepów na review jeszcze w tym tygodniu (czyli realnie do pobrania w kolejnym tygodniu). Czekamy jeszcze na finalne tłumaczenia na język angielski i ukraiński, dlatego rzeczywista możliwość wybrania / zmiany języka pojawi się w kolejnym wydaniu (4.3.X) - poinformuję kiedy taka wersja rzeczywiście ukaże się w sklepie.

**Comment by MateuszRomanow** [comment]
* W wydaniu 4.4.0, które jest obecnie na testach.

**Comment by pkleczko** [comment]
Wersja 4.4.0 z tłumaczeniami aplikacji na język angielski i ukraiński jest już dostępna w sklepach zarówno dla aplikacji Android jak i iOS.
