### ISSUE TITLE
Apple oraz Google otwarły kod źródłowy EA

### ISSUE THREAD

**Issue by MadryPan1987** [ProteGO-Safe/specs#225]
Cześć,
Google i Apple postanowiło otworzyć kod źródłowy exposure notification api. 
- https://developer.apple.com/exposure-notification/
- https://github.com/google/exposure-notifications-internals

To dobra informacja dla wszystkich aplikacji pomagających w walce z epidemią. <3 <3 <3

**Comment by potiuk** [comment]
Duplikat #191 . Juź o tym.
