### ISSUE TITLE
Większy fundusz na promowanie aplikacji

### ISSUE THREAD

**Issue by MadryPan1987** [ProteGO-Safe/specs#227]
Czy autorzy zamierzają prowadzić promocje aplikacji na nieco większą skale? Kraje z mocny contact tracingiem radzą sobie milion razy lepiej z covid (południowa korea, chiny). Pięć miesięcy od rozpoczęcia pandemii,a dzisiaj mamy dobowy rekord zakażeń

**Comment by pkleczko** [comment]
@MadryPan1987 na to pytanie nie jesteśmy w stanie Ci odpowiedzieć, promocja aplikacji jest po stronie Ministerstwa Cyfryzacji i to do niego powinieneś się skontaktować z takim pytaniem. Tutaj skupiamy się na technicznych aspektach aplikacji

**Comment by MadryPan1987** [comment]
Rozumiem, jednakże wytwarzanie aplikacji to nie tylko technologia. Dzisiaj to bardziej marketing, którego tutaj brak. Wygląda to wszystko na syzyfową prace. Ciągle czytam o tym że sanepid szuka pasażerów autobusu, klientów sklepu meblowego, uczestników mszy świętej itp itd. Jeżeli będziemy ręcznie szukać tych wszystkich ludzi to nie wróże sukcesów.
Kraje które poradziły sobie z pandemią nie szukają za pomocą ludzi a szukają za pomocą technologii.
Nie ufam Polskiemu rządowi w sprawach technologii, wątpię żeby WCz. Pan Kaczyński miał jakiekolwiek pojęcie o smartfonach i to na waszych barkach jest odpowiedzialności naciskania na promocje aplikacji.

Korea Południowa ma wpisany contact tracing w przypadku pandemii w konstytucje, dzięki temu unikneli lockdownu i po dziś dzień 50 mln kraj oscyluje wokół 30 zakażeń dziennie.

**Comment by potiuk** [comment]
@MadryPann1987 - nawołuję żebyś nie wprowadzał chaosu i dezinformacji. Na forum tutejszego GitHuba dorobiliśmy się przynajmniej jednego - jeśli coś piszesz i jest to Twoja opinia, to prosimy o wyraźne zaznaczenie że jest to Twoja opinia, a nie fakt. Jeśli podajesz fakty ("kraje szukają  za pomocą technologii") albo ("30 zakażeń dziennie") to powinieneś podać wiarygodne źródła na podstawie których twierdzisz że to fakt.

Piszę tu w imieniu społeczności która stworzyła się na GitHubie a która nadzoruje powstawanie ProteGoSafe. 

Wszystkie wiarygodne źródła, które już od wielu miesięcy uważnie śledimy  wskazują na to że w żadnym z krajów w którym Contact Tracing został wdrożony, nie udało się uzyskać ani efektu skali ani realnych efektów (są to dosłownie pojedyncze przypadki w których osoba została znaleziona za pomocą "technologii BT contact tracing" . Dyskusję na ten temat - łącznie z wiarygodnymi źródłami, statystykami i naszymi komentarzami możesz znaleźć tu: #213 .

Polecam bardzo zapoznanie się z tym wątkiem zanim impulsywnie odpowiesz na ten wpis - choćby po to żeby nie narażać się na oskarżenia o "trolling" i nie powoływanie się na rzetelne dane, i generalnie narażenie się na bycie ignorowanym/ą.

Konsensus do jakiego - chyba jako społeczność - doszliśmy jest taki że inwestowanie w rozwój aplikacji jeszcze więcej nie ma w tej chwili żadnego sensu. Reklamy w TV nie dały więcej niż 0.5 % "pokrycia" (<200.000 osób), Ministerstwo Cyfryzacji zrobiło bardzo dużo żeby podważyć zaufanie ludzi do takiej aplikacji, do tej pory na przykład nie opublikowano audytów prywatności, które obiecano już parę miesięcy temu. Jakakolwiek inwestycja w aplikację w tej chwili bez spójnej strategii jak osiągnąć (w sposób dobrowolny!) 60% "pokrycia" są straconymi pieniędzmi. O tych 60% możesz poczytać właśnie w źródłach przytoczonych w #213 

A najnowsze dane dotyczące Korei Południowej są takie, że - jak większość krajów - zmagają się ze wzrostem zachorowań https://www.bankier.pl/wiadomosc/Korea-Pld-najwiecej-przypadkow-zakazenia-Covid-19-od-marca-7931654.html - wiadomość sprzed kilku dni, to największy skokowy wzrost liczby zdiagnozowanych osób (113  osób - 27 lipca).

Moja osobista opinia (i jest to opinia właśnie a nie fakt) - jest że rządy narodowe, EU, Google, Apple, NGO, Uniwersytety powinny się porozumieć co do stworzenia wspólnej organizacji nadzorującej Exposure Notification i aplikacje/serwery tworzone i utrzymywane przez rządy i powinna być możliwość dołączenia do Exposure Notification bez konieczności instalowania aplikacji. Od początku taki scenariusz przewidywało rozwiązanie Google + Apple - scenariusz w którym wystarczy wyrazić zgodę na bycie częścią Exposure Notification na poziomie Systemu Operacyjnego/ Play Store. To też według mnie najlepszy sposób na zapewnienie interoperacyjności rozwiązania między krajami. Rządy dalej są podmiotami które przechowują (anonimowo) dane od zarażonych osób i mają kontrolę nad "zgłaszaniem" zarażeń, natomiast to G+A dostarczają technologię/mechanizm wymiany tych informacji przez BT, bez konieczności instalacji aplikacji. Jeśli wszystkie zaangażowane podmioty/interesariusze by się co do tego zgodzili - i było by niezależne ciało, które by nadzorowało prywatność takiego rozwiązania - wtedy można by przeprowadzić skuteczną kampanię (w całej EU) łącznie z tym żeby po instalacjach upgradeów w telefonach każdy dostałby rzetelną informację i łatwy sposób dołączenia do systemu. Ale wymaga to współpracy tych wszystkich interesariuszy. Według mnie to jedyny sposób żeby osiągnąć 60%+

Jeszcze raz powtórzę - Jeśli chciałbyś być poważnie traktowany (lub traktowana - trudno powiedzieć bo na razie się nie przedstawiłeś/aś a Twojej historii na Githubie nie ma) to polecam uważną lekturę tych wątków, które już zostały poruszone i zamieszczanie źródeł to stwierdzeń które przedstawiasz jako fakty.

**Comment by MadryPan1987** [comment]
@potiuk kim ty jesteś żeby mnie do czegoś nawoływać?
Ja mówie że korea południowa nie ma problemu z covidem a ty linkujesz jakiś "stary" artykuł jeszcze do tego który mówi o 100 zakażeniach (gdzie u nas 500 to norma a kraj 2x mniejszy), a na dodatek pochodzi ze strony bankier.pl :D :D :D I tym się różnimy, dla Ciebie to biznes tu być, a ja chce normalnie żyć... 
Proszę bardzo, o to dowód na to że tam nie ma problemu i to dzięki contact tracingowy.
https://www.worldometers.info/coronavirus/country/south-korea/
Jestem wysoce przeciwny ucinaniu funduszy na walke z covid. Co to za pomysł? Wygląda to jak rozsiewanie dezinformacji w stylu Edyty Górniak.

**Comment by SeraMoon** [comment]
Było o tym mówione wielokrotnie, że aplikacje nie przynoszą skutku. powód MOIM ZDANIEM jest prosty - więcej się zarażamy przez dotykanie i wymienianie się wirusami przez przedmioty (w tym wspólne kieliszki, poręcz w autobusi)e, dzieci dotykające siedzenia w autobusie i jedzące coś w nim!!! i wprowadzajace wirusa sobie i "chorujące" bezobjawowo, wciąż zakażające... niż przez kasłanie o ile obiekt jest wietrzony. 

To było bardzo mądre: 
![](https://i.ibb.co/4TLFvJP/bardzo-madry-pan.jpg) 

Rozumiem wskazanie na siebie, że jesteś skonfundowany lub rozbawiony, ale plusowanie **swoich** komentarzy jest myślę, że już wiesz jak odbierane. 

Żeby nie było, że jestem stronnicza.
@potiuk nawołuję do **przestrzegania CoC CNCF**. Nick MadryPan, wskazuje w kontekście języka, że jest Panem, czyli określa siebie mężczyzną. CoC zabrania komentarzy dotyczących płci, identyfikacji i orientacji seksualnej. Nick "MalaTruskawka" też wymagałby, aby o sobie napisał, przedstawił się i powiedział gdzie pracuje? 

**Apeluję o zamknięcie tego wątku.**
