### ISSUE TITLE
Błędne założenia aplikacji a prawdziwa epidemia wirusowa

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#228]
**Describe the bug**
Wątek ten ma za zadanie pokazać, prawdopodobne przyczyny dlaczego ta aplikacja oraz inne, które miały wynik znalezienia kilku przypadków na 10 tysięcy, nie są skuteczne i nie da się uczynić by były skuteczne, na przykładzie konkretnych przypadków. Kratkami pustymi zaznaczam niespełnione wzorce, kratkami zaznaczonymi spełnione. Przybliżam też słabości obecnych rozwiązań "sanitarnych". 
- [x] 5-10 minutowa rozmowa z bliska z osobą zakażoną o ile bokiem dobrze się słyszą na BT ich telefoiny (co jak wykazano nie zawsze jest spełnione),
- [ ] Podanie sobie na "cześć" ręki, w którą wcześniej się kasłało / kichało,
- [ ] Osoba która ufa aplikacji, w ogóle nie dezynfekuje rąk lub o tym zapomina i dotyka poręczy ruchomych lub statycznych schodów, poczym zostawia wirusy u siebie w domu lub dotyka twarzy. Pozostaje niewykryte, bowiem wirusy osoby chorej pozostają na powierzchniach i o ile jest zbieżność przestrzenna, brak jest zbieżności czasowej, aby ProteGO Safe wykrył kontakt. Możliwość zapobiegania: noszenie maski + okularów w tym miejscu lub noszenie przyłbicy - wirus zostanie zatrzymany na etapie przenoszenia do ust, nosa lub oczu
- [ ] Dzieci, których nie da się upilnować - dotykają siedzeń w autobusach (częste!) opierają się o różne przedmioty na które ktoś mógł kichnąć lub nakasłać lub w inny sposób przenieść wirusa. Dzieci potrafią lizać różne przedmioty, ciężko upilnować aby nosiły poprawnie maseczkę i nie dotykały oczu. Możliwe rozwiązanie: nieelektroniczne niestety: maska usztywniana a`la kaganiec, którą ciężko będzie im zdjąć. Brak pomysłu jak zabezpieczyć oczy przed dotknięciem przez dziecko.
- [x] Kaszlnięcie przez osobę chorą w autobusie wprost na przyszłych zakażonych.
- [ ] Kaszlnięcie w autobusie nie wprost, ale kaszlnięcie w kierunku poręczy, kasownika, biletomatu. Wirusy zostają długie godziny lub dni tam i tylko czekają na ich zebranie. Możliwe rozwiązania: małe autobusy: wymuszona dezynfekcja przed wejściem, niewpuszczanie osób, które jej nie przejdą. Duże autobusy - Warszawa, Łódź, Katowice: Obligatoryjna dezynfekcja przestrzeni użytkowych **po każdym kursie** (czyli średnio co 1-2 godzin). Wietrzenie po każdym kursie, nawet kosztem redukcji ilości kursów!
- [ ] Numeratory na Poczcie Polskiej (pracują od około 2 tygodni - nie tylko na poczcie i mamy wzrosty zakażeń!)  - dotykają tego samego niedezynfekowanego numeratora tysiące osób dziennnie. Ostatnie osoby prawie na pewno się zarażą jeżeli dotkną numeratora i dotkną okolic twarzy... Zbiorą zarazki po tysiącu innych osób!!! Osoby bez numerka nie są obsługiwane - z relacji mojej znajomej - musiała użyć numeratora (czyli dotknąć skażonej powierzchni) aby była obsłużona. 
- [ ] Przeprowadzone wybory prezydenckie 2020 - tysiące osób w tym samym lokalu pozostawiły swoje zarazki w niewietrzonym lokalu wyborczym, co powodowało, że osoby przychodzące po godzinie wdychały aerozol osób chorych. Tak zarażają się osoby w szpitalach, placówkach medycznych i **DPS-ach**. Rozwiązaniem było wybory odwołać (stan klęski żywiołowej wprowadzony na 1 dzień, jak najbardziej uzasadniony dla bezpieczeństwa ludzi) lub **przeprowadzić wybory na wolnym powietrzu, gdzie nie dochodzi do kumulacji wirusów** (UV niszczy wirusy na powierzchnii, aerozol jest na bieżąco rozwiewany (neutralizowany). Odpowiednie miejsce głosowania: na świeżym powietrzu przed lokalem wyborczym. 
- [ ] Wesela i pogrzeby - występują te same czynniki zakaźne co w autobusach. Widziałam zdjęcia autobusów i tramwajów z napisami "KORONAWIRUS 98", "KORONAWIRUS 102" wskazującymi nie tylko ilość osób w pojeździe ale i **ryzyko zakażenia** bo ludzie się przemieszczają tam i wytwarzają w zamkniętym pomieszczeniu aerozol oddechowy. Jedyne dodatkowe ryzyko w przypadku wesela to używanie nieswoich kieliszków przez osoby wpół przytomne (za mało wypite by paść, za dużo by ocenić który kieliszek jest swój). Na weselach dobrze kontrolowanych, gdzie ludzie nie używający swoich kieliszków są wypraszane - nie wystąpi większe ryzyko niż w autobusie przesiedzenie godziny (typowe dla Warszawy 2 godziny w autobusie - pojechać gdzieś coś załatwić i wrócić. ProteGO Safe nie zda tutaj rezulatatu z 2 przyczyn - za dużo źródeł sygnału (150 nadajników na 100 m2), jak też nawet gdy nadajnik i odbiornik BT się usłyszą i zdekodują cały niezakłócony komunikat - odległość między ludźmi jest większa niż 2 metry, jednak są w zamkniętym pomieszczeniu.

Temat pozostawiam tutaj ponieważ:
- Ministerstwo Cyfryzacji (@MateuszRomanow) będące członkiem KPRM ma tutaj dostęp i jest powiadamiane o problemach.
- Inne kontakty z KPRM / MC pozostają głuche, bez odpowiedzi.
- Pozostaje tutaj dowód kontaktu i próby przekazania **gdzie umyka nam ostatnio wirus** czego powodem są spore wzrosty.
- Mam nadzieję, że KPRM siądzie nad tymi przypadkami i zanim nakaże na dworze noszenie maseczki (niepotrzebne, aerozol jest rozwiewany przez wiatr), znajdzie rozwiązanie na powyższe kwestie a w szczególności:
- niezasłanianie nosa **lub** ust w śroodkach komunikacji miejskiej i sklepach (na podstawie nagrania z kamer powinien być nałożony mandat prze Policję lub GIS). Ludzie na widok umundurowanych w pojazdach już nie reagują mimo, że dzieli ich 4-6 metrów!!! Popularnym sposobem noszenia maski jest noszenie jej pod brodą lub nasamych ustach,
- częste dezynfekcje, kontrolowane (przez GIS, Policję) pojazdów i pomieszczeń użytku publicznego,
- czeste wietrzenie (wraz z uzyskaniem dowodów na tą czynność) w miejscach pracy - zakłady mięsne, kopalnie, ale też zwykłe biurowce jeżeli są w środku pracownicy. Ostatnio wiele pracodawców powraca do pracy tradycyjnej.
- **umożliwienie normalnych wizyt lekarskich chorym** ponieważ
-- **diagnozy przez telefon są nic nie warte, obejrzenie pacjenta (czy ma wysypkę, czy ma regularny rytm serca, jaki ma puls, czy nie ma początków czerniaka - zauważenie na plecach niepokojącej zmiany, osłuchanie czy coś nie zalega na oskrzelach) jest bardzo ważne do wykrywania poważnych chorób** (@Dr-Kownacki, jesteś w stanie to potwierdzić, że telewizyta nie zastąpi prawdziwej wizyty u prawdziwego lekarza?) Przywrócenie wizyt pod warunkiem używania nieprzerwanie maski N95 / N99 / HEPA (zabezpieczającej przed rozsiewaniem zarazków) + nakazanie dezynfekcji stołu przed pacjentem, siedzenia dla pacjenta, stetoskopu i rąk lekarza przed każdym pacjentem. Osobom, które nie mogą używać maski - umożliwić wizyty w specjalnie ku temu przygotowanych placówkach (lepiej zabezpieczony lekarz, z maską HEPA). Przymus używania wtedy przyłbicy przez pacjenta w każdym momencie gdy jest to możliwe. Gabinet powinien być stale wietrzony, a gdy to jest niemożliwe z przyczyn zachowania prywatności pacjenta i tajemnicy lekarskiej - pomiędzy kolejnymi pacjentami. Maski N95 / N99 / Hepa zapewnia państwo polskie za pośrednictwem przychodni dla faktycznie ich potrzebujących: pacjentów w ilości zgodnej z czasem i sposobem ich eksploatacji.
-- Chory ma prawo do prywatności, a placówki medyczne nagrywają połączenia, tym samym łamiąc zapisy ustaw, w szczególności RODO, 
-- **Jeszcze raz: chory ma prawo do prywatności i tajemnicy lekarskiej, a państwo polskie nagrywa dzięki ustawie inwigilacyjnej wszystkie połączenia telefoniczne.** 
- **egzekwowanie przymusu noszenia przyłbicy** (w pomieszczeniach użyteczności publicznej), jeżeli ktoś nie może używać maseczki. "Nie mogę oddychać" nie jest żadnym uzasadnieniem. Obecnie 10% ludzi nie może oddychać... Może warto ich skierować na test (wymaz z nosogardzieli), dlaczego nie mogą oddychać, gdy nie będą mieć przyłbicy?
- Zakazanie rozporządzeniem stosowania numeratorów i nakazanie, że kolejka ma stać przed Pocztą, nie wewnątrz. 

Mam nadzieję, że to wyjaśnia dlaczego ludzie umierają a ich śmierć lub wylądowanie w szpitalu nie ma nic współnego z koronawirusem poza tym, że byli bezobjawowymi nosicielami i zostaną wpisani potem jako "koronawirus ze współistniejącymi chorobami". Mam nadzieję, że da to do pomyślenia, jeżeli nie KPRM (żądam od Ministrów w KPRM poważnego przemyślenia tych kwestii), to da do myślenia obywatelom, czy są chronieni i jak powinni się zachowywać i na co zwrócić uwagę. 

**BTW. o wizyty "telefoniczne" korzystałam z otwartych przychodni prywatnych i zauważono u mnie na jednej z nich objaw, na który bym nie zwróciła sama uwagi w domu (sprawa nie mogła czekać).** Niniejszym żądam zwrócenia mi części składki NFZ-owej, skoro nie mogę korzystać z tego za co je płacę - **rzetelnego leczenia**. Koronaświrus nie może być tutaj wymówką. Innych gorąco namawiam do pisania również skarg do MZ, ZUS oraz NFZ w tej kwestii, że zostali odcięci od dostępu do lekarza oraz że płacą składki, z których prawie nic nie mają.

Ludzie żalą się też w komentarzach na różnych serwisdach z wiadomościami koronawirusowymi, że bliscy im umarli tylko i wyłącznie przez brak dostępu do tradycyjnej (bardzo potrzebnej i wartościowej!) wizyty lekarskiej. 

**To Reproduce**
1. Temat do pomyślenia
2. Temat do zareagowania

**Expected behavior**
Instrumenty używane przy działaniach sanitarnych powinny mieć wysoką skuteczność. Pacjent powinien mieć fizyczny dostęp do lekarza. 

**Screenshots**
\x00

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
\x00

**Comment by pkleczko** [comment]
Ten wątek jest totalnym offtopem, Twoimi własnymi tezami niepopartymi żadnymi dowodami czy statystykami - nawet nie powołujesz się na jedno wiarygodne źródło. To repozytorium dotyczy projektu aplikacji ProteGO Safe a nie politycznych wywodów czy dyskusji na temat działania polskiej służby zdrowia. Nikt nigdy nie powiedział, że aplikacja będzie blokować kaszlnięcia osób w autobusie albo uprawniać do wizyty u lekarza. Aplikacja ma wspomagać społeczeństwo, ale zawsze najważniejsze jest przestrzeganie zasad higieny osobistej i stosowanie zaleceń GIS/MZ. 

Proszę o zamknięcie tego wątku.
