### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by galuszkak** [ProteGO-Safe/specs#233]
Trwa obecnie Hacktoberfest, co roczny event organizowany przez Digital Ocean, gdzie ludzie mogą kontrybuować do projektów open source.

W obecnym roku, żeby uczestniczyć w tym wydarzeniu trzeba otagować repozytorium w podsumowaniu słowem `hacktoberfest`. Czy twórcy / maintainerzy ProteGO Safe są zainteresowani uczestnictwem w Hacktoberfest?

Zawsze jedna lub dwie porządne kontrybucje to dobry krok naprzód.

**Additional context**
https://hacktoberfest.digitalocean.com/hacktoberfest-update

PS. Wiem, że kontrybucje tutaj są review-owane przez 2-3 miesiące od zewnętrznych kontrybutorów, ale może to będzie dodatkowa motywacja, żeby usprawnić ten bardzo kulejący i nie transparentny proces?

**Comment by galuszkak** [comment]
PS2. Projekt potencjalnie mógłby się też pojawić w zakładce "Projects focused on climate change & COVID-19 relief":
https://hacktoberfest.digitalocean.com/#featured

**Comment by potiuk** [comment]
Dobry pomysł. Tak właśnie działają projekty open-source. Mój [Apache Airflow](https://github.com/apache/airflow) oczywiście jest w Hactoberfeście, organizujemy dwa spotkania w październiku organizowane w ramach Hacktoberfest zapraszając nowych kontrybutorów i robiąc dla nich warsztaty. No i mamy już tak czy inaczej co najmnej kilka osób kontrybuujących w ramach Hactoberfest.

Może twórcy ProteGO mogli by zrobić podobnie?

**Comment by bartosztomczak** [comment]
Witam, to jest bardzo dobry pomysł, dziękujemy. Przekazaliśmy temat do analizy prawnej i opracowania alternatywnej procedury zgłoszenia kontrybutora z zagranicy.

**Comment by potiuk** [comment]
Jeszcze niecałe 3 tygodnie Października. Mam nadzieję że zdążycie z procedurami.

**Comment by pkleczko** [comment]
z racji napiętego harmonogramu musieliśmy odpuścić temat i nie będziemy w stanie przeprocesować tego. chcielibyśmy, ale po prostu nie ma na to czasu aktualnie, to nie nasza zła wola, bo pomysł jest fajny.

**Comment by galuszkak** [comment]
@pkleczko dziękuję za informację.
