### ISSUE TITLE
Z jakich otwartych danych korzysta aplikacja? - dane.gov.pl

### ISSUE THREAD

**Issue by olekstomek** [ProteGO-Safe/specs#243]
Na liście przykładów aplikacji które powstały dzięki otwartym danym [wg dane.gov.pl jest aplikacja](https://dane.gov.pl/pl/application/1244,protego-safe) STOP COVID - ProteGO Safe. 
W jakich funkcjonalnościach aplikacja korzysta z publicznych danych?

**Comment by MateuszRomanow** [comment]
> Na liście przykładów aplikacji które powstały dzięki otwartym danym [wg dane.gov.pl jest aplikacja](https://dane.gov.pl/pl/application/1244,protego-safe) STOP COVID - ProteGO Safe.
> W jakich funkcjonalnościach aplikacja korzysta z publicznych danych?

Linkujemy w kilku miejscach do gov.pl + Test Oceny Ryzyka bazuje na algorytmie dostarczonym przez Ministerstwo Zdrowia
