### ISSUE TITLE
Dodanie dodatkowych dziennych statystyk 

### ISSUE THREAD

**Issue by KoderFPV** [ProteGO-Safe/specs#248]
**Is your feature request related to a problem? Please describe.**
Prośba o dodanie kilku dodatkowych statystyk, które dostepne są na twiterze ministerstwa zdrowia

**Describe the solution you'd like**
Dodanie dziennych statystyk:
- hospitalizacja
- testy PCR
- zlecenia POZ
- testy antygenowe
- zajęte respiratory
- osoby na kwarantanie
- % udział wyników pozytywnych

**Describe alternatives you've considered**
Alternatywnie można by dodać obrazki z raportów MZ z twitera, szybkie ale nie polecam :)

**Additional context**
Fajnie mieć statystki w apce, o ile będą dodawane równie szybko jak statystyki na twiterze / gov.pl

Dla przypomnienia na twiterze podawane są:
10.00 - hospitalizacja / oiom / kwarantanna / wyleczeni
10.30 - zakażeni z podziałem na województwa (kilka minut wczesniej na stronie gov.pl)
10.30 - 11.00 - ilość wykonanych testów

Pozdrawiam

**Comment by olekstomek** [comment]
> wersję 4.10.0, w której aplikacja będzie wyświetlać większą ilośc statystyk COVID-19 i szczepień oraz informacje na temat procesu szczepień w Polsce.

https://github.com/ProteGO-Safe/specs/issues/240#issuecomment-779249091

**Comment by olekstomek** [comment]
Część statystyk wdrożona w aplikacji.

**Comment by KoderFPV** [comment]
Jest tam więcej statystyk niż się spodziewałem, np. na temat szczepień i podział na województwa.

Bardzo pomocne.
Dzięki.

**Comment by olekstomek** [comment]
Czy jest planowanie wdrożenia w aplikacji statystyk dotyczących np. zaszczepionych osób powyżej i poniżej 18 oraz powyżej 5  a poniżej 12 roku życia?
Inny pomysły do zaczerpnięcia z [Raport szczepień przeciwko COVID-19](https://www.gov.pl/web/szczepimysie/raport-szczepien-przeciwko-covid-19).
