### ISSUE TITLE
Co z potencjalnymi zarażeniami drugiego ( i każdego następnego ) stopnia?

### ISSUE THREAD

**Issue by AlexF0rtune** [ProteGO-Safe/specs#29]
Hej, dodane na prośbę @DariuszAniszewski 

Jak w tytule - zastanawiam się, czy ktoś rozważał, jak sprawa będzie wyglądać w sprawie potencjalnych zarażeń dalszych od stopnia pierwszego? Czyli, jeśli mamy zarażonego A, człowieka, który miał kontakt B i jego kontakt C, to czy planowane sa jakieś działania prewencyjne w kierunku C?

**Comment by Dr-Kownacki** [comment]
Świetna uwaga, odniosłem się do podobnego zagadnienia tutaj #63 w czwartym poście od góry.
Co uważasz o takim podejściu ?

**Comment by jakublipinski** [comment]
Szczerze, nie mamy na to pomysłu. Wydaje mi się, że rozwiązanie tego wymagałoby posiadania wszystkich danych na serwerze, czego chcemy unikać.

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.

Po więcej zapraszam do specyfikacji EN G+A.
