### ISSUE TITLE
Tłumaczenia na angielski

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/specs#38]
Zdecydowaliśmy się na opis projektu po polsku, ze względu na to, że jego docelowi (pierwsi) użytkownicy będą z Polski i chcieliśmy aby był dla nich transparentny. 

Jako że jesteśmy pierwszym rozwiązaniem typu `contact-tracing` które jest open-source, jest spore zainteresowanie naszym kodem także z zagranicy. 

Potrzebujemy tłumaczeń na język angielski wszystkich dokumentów, najlepiej wg. kolejności:
- [ ] `specs/README-en.md` które zastąpi `ENGLISH.md`
- [ ] `specs/specs/README-en.md` tłumaczenie `specs/specs/README.md`
- [ ] `specs/specs/data_sharing-en.md` tłumaczenie `specs/specs/data_sharing.md`
- [ ] `specs/specs/api-en.md` tłumaczenie `specs/specs/api.md`
- [ ] `CONTRIBUTING-en.md` tłumaczenie `CONTRIBUTING.md`

**Comment by zuzia-kru** [comment]
Cześć, pracuję nad plikiem `api-en.md` 👍

**Comment by bpaszcza** [comment]
Biorę na siebie `specs/README-en.md`

**Comment by wojdziw** [comment]
Wezmę `specs/specs/README-en.md`

**Comment by bpaszcza** [comment]
Tłumaczę również 'specs/specs/data_sharing-en.md'

**Comment by wojtekszkutnik** [comment]
Podobnie jeśli chodzi o commit messages i tickety, jeśli całość jest po polsku to chyba bardzo ogranicza potencjalną partycypację? Wydaje mi się że w tego typu projekcie całość powinna być prowadzona po angielsku, to może bardzo przyspieszyć development i znacząco zwiększość ilość contributorów :)

**Comment by wojdziw** [comment]
@jakublipinski dałbyś radę dodać nas jako kolaboratorów? Wtedy będziemy mogli zrobić PRa z tłumaczeniami :)

**Comment by jakublipinski** [comment]
Dzięki wielkie za pomoc. Zróbcie proszę [Fork i Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by wojtekszkutnik** [comment]
Tłumaczę CONTRIBUTING.md

**Comment by zuzia-kru** [comment]
Mam pytanie @jakublipinski - w funkcji `/get_status` jest napisane że `last_beacon_id` to "najstarszy `beacon_id` na urządzeniu"...czytając opis mam wrażenie że chodzi o najnowszy `beacon_id`, czyli ten o najpóźniejszej dacie. Mogę się mylić...mógłbyś potwierdzić? Dzięki

**Comment by jakublipinski** [comment]
@zuzia-kru masz rację. Chodzi o najnowszy. Poprawisz też w wersji pl? Wielkie dzięki!

**Comment by zuzia-kru** [comment]
@jakublipinski pewnie :)

**Comment by zuzia-kru** [comment]
@jakublipinski jeszcze jedno, normalnie opisałabym też czy requests są HTTP czy HTTPS, nie wiem czy jest to oczywiste później z punktu widzenia aplikacji czy warto o tym wspomnieć.

**Comment by jakublipinski** [comment]
Nie warto. Wszędzie będzie HTTPS. Starajcie się robić tłumaczenia jeden-do-jeden.

**Comment by rjpramos** [comment]
> Podobnie jeśli chodzi o commit messages i tickety, jeśli całość jest po polsku to chyba bardzo ogranicza potencjalną partycypację? Wydaje mi się że w tego typu projekcie całość powinna być prowadzona po angielsku, to może bardzo przyspieszyć development i znacząco zwiększość ilość contributorów :)

+1, np jestem programista i nie mowie duzo po polsku, bedzie latwiej po angielsku

**Comment by wojdziw** [comment]
To ja wezme jeszcze `CONTRIBUTING-en.md`, umieszcze w tym samym PRze

**Comment by potiuk** [comment]
Mały komentarz. Chwilowo, nie wiadomo, kto jest właścicielem oprogramowania.  Z licencji (#50) wynika że jest to Free Software Foundation co jest niezgodne z rzeczywistością. Nie wiem czy dobrze jest dodawać swoje kontrybucje w momencie w którym nie wiadomo komu się kontrybuuje,

**Comment by potiuk** [comment]
Chciałbym wszystkim zwrócić uwagę, że od około godziny, żeby kontrybuować do aplikacji wszyscy muszą podpisać oświadczenie dodane w tym commicie: https://github.com/ProteGO-app/specs/commit/71881129baddbc8442d7d1b50ccae49d838d1064

**Comment by potiuk** [comment]
Oświadczenie tu https://github.com/ProteGO-app/specs/blob/master/files/oswiadczenie_licencja_GPL_AGPL.pdf

**Comment by jakublipinski** [comment]
Dotyczy nieistniejącego ProteGO 1.0 więc zamykam na prośbę @MateuszRomanow
