### ISSUE TITLE
Stworzenie gittera na potrzeby rozmowy o aplikacji.

### ISSUE THREAD

**Issue by Tarvald** [ProteGO-Safe/specs#39]
Stworznie gittera jako najbardziej zintegrowanego z github'em, w celu rozmowy na temat aplikacji.
Plusem gittera jest to że nie trzeba go instalować, oraz można zalogować się loginem githuba.

Alternatywą mógłby byc slack albo inny komunikator.

Przydałby się przynajmniej 4 pokoje.

- Android
- iOS
- Backend
- Specs

**Comment by AlexF0rtune** [comment]
Rozmawiałem z @DariuszAniszewski i wspominał, że może powstać jakiś slack w jakiejś perspektywie - niech sam otagowany może się wypowie bo ja tu tylko para-biernym obserwatorem jestem : )

**Comment by jakublipinski** [comment]
@Tarvald jestem przeciw. Wydaje mi się, że powinniśmy mieć jedno miejsce komunikacji - GitHub, tak aby każdy miał szanse zapoznać się z ustaleniami i dyskusją. Nie wymagajmy śledzenia kilku kanałów.
