### ISSUE TITLE
Jednolite commit messages, udokumentowanie procesu developmentu 

### ISSUE THREAD

**Issue by wojtekszkutnik** [ProteGO-Safe/specs#42]
Jestem przekonany, że commit messages po polsku to zły pomysł - ogranicza partycypację zagranicznych developerów i wprowadza konwencję obcą większości polskich programistów.

Równolegle z tym proponuję wprowadzenie jednolitej konwencji commit messages (https://chris.beams.io/posts/git-commit/). Jeśli założenie jest takie, że projekt będzie open source'owy, to musimy się trzymać dobrych praktyk przestrzeganych w całej branży.

Prowadzenie dokumentacji w dwóch językach to spory overhead - czy na tym etapie są jakiekolwiek powody dla których warto to robić po polsku?

**Comment by bejo** [comment]
Właśnie miałem opisać podobne "issue". Przyznam się, że początkowo pomyślałem "o, jak miło - repozytoria i commity po polsku!". Jednak @wojtekszkutnik ma rację z językiem angielskim.

Wyobrażam sobie, że w pewnym momencie ta (lub podobna) aplikacja zaadoptowana na poziomie paneuropejskim ułatwi przywrócenie strefy Schengen. Aby to było możliwe zdecydowanie projekt musi przejść na język angielski.

PS. Wspaniały pomysł z aplikacją, gratuluje inicjatywy!

**Comment by kgluszczyk** [comment]
Zdecydowanie zgadzam się, że commity po angielsku pozwolą na lepsze skalowanie projektu. Tak naprawdę wszystkie issusy na githubie powinny również być zgłaszane w EN. Jedyny plus zaczęcia projektu po PL to zwiększenie początkowego zaufania do projektu ludzi nietechnicznych. Btw, dalej czekamy na narzędzie komunikacji pomiędzy zaangażowanymi!

**Comment by Tarvald** [comment]
Moim zdaniem co do tego specyficznego projektu, to trzymanie issues oraz commitów na tym etapie po polsku, jest dobrym rozwiązaniem.
Przyspiesza to komunikacje, oraz zwieksza potencjalne zaangażowanie osób nie technicznych.

Z względu na krótki deadline (bo jak długo chceciecie żyć w kwaranntanie?), to jednak bym się komunikował po polsku.

Na codzień w pracy programisty, oczywiście silnie rekomenduje angielski

**Comment by jakublipinski** [comment]
Zdecydowaliśmy się na kod i komentarze w nim po ang. Wybraliśmy komunikację po polsku, bo przede wszystkim chcemy być transparentni dla ludzi w Polsce. Wiele tematów które tutaj poruszamy jest czytelnych dla osób nietechnicznych. Nie chcę zabierać im możliwości partycypacji.

Tłumaczymy główne dokumenty na angielski (https://github.com/ProteGO-app/specs/issues/38) aby ludzie spoza Polski mogli śledzić co robimy.

Dla mnie też to jest nietypowa sytuacja i pewnie wolałbym wszystko po angielsku, ale w tym wypadku używanie polskiego jest uzasadnione. Niektórzy piszą po angielsku tak czy siak - nie ma z tym problemu. Odpowiadamy po angielsku.

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.

Obecna dokumentacja znajduje się w repozytoriach oraz na wiki repozytoriów
