### ISSUE TITLE
Przerywanie odtwarzania muzyki podczas używania aplikacji.

### ISSUE THREAD

**Issue by Tarvald** [ProteGO-Safe/specs#51]
W singapurskim odpowiedniku tej aplikacji, użytkownicy skarżą się że co około 15 sekund przerywa im na chwile muzyke.
Domyślam się że to z powodu rozgłaszania oraz pobierania danych.

Czy w tej aplikacji będzie występował ten problem? Jak myślicie?

https://play.google.com/store/apps/details?id=sg.gov.tech.bluetrace&hl=en&reviewId=gp%3AAOqpTOGyGUibCRS3cFO7x5uicjieQsDw-Q3cx9jiajBCpEZvEEUGiqjdNpRQ1lKS2eWq475LMG0a9PjvpQD52A

**Comment by jakublipinski** [comment]
Dobre pytanie, warto sprawdzić. Co myślisz @dariuszseweryn ?

**Comment by dariuszseweryn** [comment]
Nie sprawdzałem, ale spodziewam się, że może być to problem. Wątpię by Android dbał o "Quality of Service" a i implementacje sterowników od adaptera Bluetooth różnych dostawców układów mogą mieć (i najczęściej mają) bardzo różną jakość...

Być może dałoby się w jakiś sposób zarządzać rozgłaszaniem lub skanowaniem, w zależności od tego czy urządzenie odtwarza muzykę, choć może to wpływać na skuteczność wykrywania spotkań.

Wiele niewiadomych. Na chwilę obecną nie jestem w stanie nic więcej powiedzieć. Niestety wciąż nie wiem co dokładnie robi `TraceTogether`, bo kod (chyba) wciąż nie jest udostępniony.

**Comment by tomekziel** [comment]
Wygląda na to, że protokół otworzył się wczoraj:
https://github.com/opentrace-community/opentrace-android
