### ISSUE TITLE
Zapisy na testowanie - nie dostałem mejla

### ISSUE THREAD

**Issue by robert-skarzycki** [ProteGO-Safe/specs#70]
Hej,

Zapisałem się na testowanie aplikacji w piątek, nie dostałem do dziś mejla z instrukcjami. Jakiś błąd po mojej stronie czy "zapchała się" kolejka do wysyłki?

**Comment by Dr-Kownacki** [comment]
ja również :-)

**Comment by jakublipinski** [comment]
Czekamy na review od Apple i Google (wersje do testów też przechodzą review).

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.
