### ISSUE TITLE
Mamy pierwszą wersję designów okna status

### ISSUE THREAD

**Issue by jakublipinski** [ProteGO-Safe/specs#8]

**Comment by rtpm** [comment]
Czy dopuszcza się możliwość weryfikacji pomiędzy użytkownikami,  poprzez zweryfikowanie użytkownika (np. okazany i zeskanowany kod QR - może być w odpowiednim kolorze, który wskazuje dodatkowo status), ale 
chcemy sprawdzić to na swoim urządzeniu. ?

Myślę, że zapisy o lokalizacji są dość kontrowersyjne - chodzi chyba o zbiór "spotkanych" urządzeń.
Być może pochodzą z poprzedniej specyfikacji lub wymagają dokładniejszego określenia.

Nie wiem jakie są dalsze losy projektu. Być może powstaną kiedyś "zachęty" do używania apki, gdyż mogłaby się stać furtką do wejścia do np. niektórych miejsc publicznych.. ale nie o to chodzi w tym zapytaniu.

W tym przypadku jest niebezpieczeństwo "zapożyczenia" urządzenia od kogoś innego,
oszukania (na różny sposób, np. obrazek gdy skanowany jest kod QR) weryfikującego i tutaj pojawiałby się problem pełniejszej weryfikacji,
gdzie zwrócona byłaby pełniejsza wersja danych (unikalny identyfikator np. ePUAP), a co najważniejsze zdjęcie użytkownika z bazy PESEL, bo w ten sposób można zweryfikować, że dana osoba to ta osoba i jej urządzenie. To oczywiście wybieganie w przyszłość i nie na obecnym etapie, ale może kiedyś dla potomnych.

**Comment by jakublipinski** [comment]
Dotyczy nieistniejącego ProteGO 1.0 więc zamykam na prośbę @MateuszRomanow
