### ISSUE TITLE
Powiadomienia o obecnym statusie

### ISSUE THREAD

**Issue by theimowski** [ProteGO-Safe/specs#81]
Sugestia odnosząca się do tej [kwestii](https://github.com/ProteGO-app/specs/blob/f65ba684a0d450fa34efa503328aee45c4cd0884/CONTRIBUTING.md#jaki-jest-roadmap-projektu):
> Na pewno będziemy chcieli zachęcić użytkowników do częstszego zaglądania do aplikacji? Masz pomysł jak to zrobić - napisz.

Z racji że aplikacja nie ma głównie działać w tle, a po jej otwarciu nie ma specjalnie dużo interakcji, rzeczywiście użytkownicy mogą apki nie otwierać zbyt często.

Natomiast okresowe powiadomienia typu push (codzienne? co kilka dni?) mogłyby zaintrygować użytkowników i sprowokować do częstszego odwiedzania apki.
Pomysły na przykładowe powiadomienia: 

_Twój status: **POMARAŃCZOWY**.
Zostało 13 dni do przejścia na status zielony, kliknij aby zobaczyć więcej._

_Twój status: **ZIELONY**.
Dzisiaj spotkałeś 5 innych użytkowników ProteGO, kliknij aby sprawdzić szczegóły._

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.
