### ISSUE TITLE
Podawanie numeru telefonu a anonimowość danych na serwerze

### ISSUE THREAD

**Issue by potiuk** [ProteGO-Safe/specs#83]
Bardzo zależy mi na powodzeniu całego projektu i chyba jedną z najważniejszych rzeczy jest społeczna akceptacja projektu. Dlatego bardzo istotny według mnie jest sposób prezentacji (UX) ekranu podawania numeru telefonu (po zmianach wynikających z m.in. #56) wprowadzonych przez @jakublipinski w porozumieniu z Ministerstwem Cyfryzacji w b486959, 694cc66, 336a7bb

Myślę że warto przedyskutować i zastanowić się jaki wpływ będzie miał sposób prezentacji i informacja o konsekwencjach podania numeru w kwestii anonimowości. Oficjalne komunikaty na temat aplikacji wiele mówią o anonimowości danych więc warto żeby osoba podająca swój numer telefonu wiedziała że (być może ?) przestaje być anonimowa.

Podpisałem wczoraj apel fundacji Panoptykon https://panoptykon.org/7-filarow-zaufania dotyczący podstawowych zasad tworzenia aplikacji do walki z COVID-19 i mam na ten temat parę przemyśleń.

Widzę kilka wariantów jak podawanie numeru może być zrealizowane. Chętnie posłucham opinii innych ale przede wszystkim @jakublipinski i Ministerstwo Cyfryzacji (zgodnie z #46 to oni podejmują decyzje w projekcie) który z tych wariantów zostanie wybrany (i mam nadzieję zostanie to udokumentowane w projekcie jako założenie projektowe). 

W każdym z tych wariantów informacja o konsekwencjach dokonanego wyboru powinna zawrzeć się w jednym zdaniu które każdy będzie w stanie zrozumieć i podjąć samodzielnie decyzję (a nie ukryte w długim regulaminie - których nikt nie czyta).

1. "Opt-out" bez informacji na temat wpływu podania numeru na anonimowość danych na serwerze. "Opt-out" znaczy, że podanie numeru jest domyślne i można z niego zrezygnować - myślę, że to najgorszy wariant, bo brakuje w nim transparentności i naraża to aplikację na negatywną kampanię społeczną w mediach ("instaluj ale nie podawaj numeru").

2. "Opt-in" z infomacją wyłącznie o potencjalnych korzyściach - nieco łatwiejszy mechanizm komunikacji z GIS (bez informacji o utracie anonimowości) - "Opt in" znaczy że domyślnie numeru się nie podajue, a trzeba wykonać akcję żeby numer podać. Ten wariant w mojej opinii narażony jest na podobnie negatywną kampanię społeczną. Jest on mniej inwazyjny ale w dalszym ciągu brak mu transparentności.

3. "Opt in" z informacją zarówno o potencjalnych korzyściach jaki i o tym że podając numer tracimy anonimowość. To dobry wariant pod warunkiem że komunikat będzie krótki, czytelny i zrozumiały. 

4. Modyfikacja algorytmu tak żeby podanie numeru nie wpływało absolutnie na anonimowość. Jak dyskutowano w https://github.com/ProteGO-app/specs/issues/34#issuecomment-609676552 jest możliwość modyfikacji działania aplikacji tak, aby numer telefonu był dalej używany do komunikacji z GIS a jednocześnie pozwalał na pełną anonimizację danych wysyłanych na serwer. NIe zmienia to funkcjonalności aplikacji i nie wpływa na możliwości GIS jeśli chodzi o komunikację z osobą zagrożoną. Moim zdaniem, to najlepszy wariant i mam apel - prośbę do @jakublipinski i Ministerstwa Cyfryzacji  by go zaimplementowało. Implementacja w ten sposób w pełni zrealizowało by postulat zgłoszony przez Europejskiego Inspektora Danych Osobowych - Wojciecha Wiewiórowskiego:

* https://www.youtube.com/watch?v=g8b9hvZDjq0
* https://www.bbc.com/news/technology-52189551

Również było by to zgodne z 7 filarami zaufania ogłoszonymi przez fundację Panoptykon https://panoptykon.org/7-filarow-zaufania i podpisaną przez wiele osób (również ją podpisałem). Według mnie tylko rozwiązanie 4. odpowiada na wszystkie poniższe postulaty "7 filarów zaufania":

* 1. Minimalizacja danych, 
* 3. Przechowywanie danych na urządzeniu obywatela
* 4. Anonimizacja
* 5. Czytelna informacja dla obywateli.

Bardzo chętnie wysłuchałbym opinii innych którzy obserwują ten projekt ale przede wszystkim chciałbym (prosibym - nie żądam) żeby Ministerstwo Cyfryzacji i @jakublipinski zdeklarowało, który z powyższych wariantów i dlaczego wybrali (albo może wariant o którym nie pomyślałem). Myślę że dało by to dużą wartość w kwestii zaufania społecznego.

**Comment by jakublipinski** [comment]
@potiuk reprezentujesz w swoich wypowiedziach tylko jedną grupę użytkowników - tych dla których prywatność jest najważniejszą kwestią w ProteGO. Ostatnie zmiany zaadresowały większość postulatów tej grupy. 

Jest jeszcze druga grupa osób dla której najistotniejsze jest zdrowie i pewność, że zostaną skutecznie poinformowani o tym, że mogli zostać zarażeni. Do tej grupy mogą należeć np. osoby starsze, które nie będą codziennie zaglądać do aplikacji. Chciałbym aby aplikacja była użyteczna także dla tej grupy. Postulat https://github.com/ProteGO-app/specs/issues/34#issuecomment-609676552 tego nie rozwiązuje.

Zostawiam UX w rękach UX designerek.

**Comment by potiuk** [comment]
> @potiuk reprezentujesz w swoich wypowiedziach tylko jedn�ą grupę użytkowników - tych dla których prywatność jest najważniejszą kwestią w ProteGO. Ostatnie zmiany zaadresowały większość postulatów tej grup

Myślę że po prostu przestawiłem wachlarz możliwości rozwiązania podawania numeru. Nie reprezentuję nikogo, chciałbym tylko wiedzieć w jaki sposób zostanie rozwiązana ta kwestia i jakie będzie to miało konsekwencje w komunikacji. 

> Jest jeszcze druga grupa osób dla której najistotniejsze jest zdrowie i pewność, że zostaną skutecznie poinformowani o tym, że mogli zostać zarażeni. Do tej grupy mogą należeć np. osoby starsze, które nie będą codziennie zaglądać do aplikacji. Chciałbym aby aplikacja była użyteczna także dla tej grupy. Postulat [#34 (comment)](https://github.com/ProteGO-app/specs/issues/34#issuecomment-609676552) tego nie rozwiązuje.

Mam inne zdanie. Wydaje mi się, że rozwiązuje. Czy mógłbyś powiedzieć gdzie tkwi problem w tym rozwiązaniu ? Podsumuję je tutaj:

1) Numer telefonu jest potwierdzany dokładnie tak jak obecnie, i przechowywany jedynie lokalnie w aplikacji. Nie jest związany z identyfikatorami Bluetooth użytkownika.

2) W momencie w którym aplikacja użytkownika dowiaduje się że ma status "zagrożony" wysyła ten numer w bezpieczny sposób do GIS. GIS wie że powinien sie skontaktować z tą konkretną osobą zidentyfikowaną wg. numeru. Natomiast nie wie w jaki sposób numer telefonu jest związany z identyfikatorami Bluetooth.

Czy nie spełnia to założenia że te osoby zostaną skutecznie poinformowane? Jeśli tak, to w którym miejscu?

**Comment by jakublipinski** [comment]
@potiuk 
1. żeby potwierdzić numer musimy wysłać go na serwer w celu wysłania na niego SMS kodu.
2. aplikacja musiałaby w tle odpytywać sewer o status. staramy się ograniczać działanie app w tle w trosce o baterie

**Comment by potiuk** [comment]
> @potiuk
> 1. żeby potwierdzić numer musimy wysłać go na serwer w celu wysłania na niego SMS kodu.

To jest OK. Jeśli tylko nie będzie to w żaden sposób związane z identyfikatorami bluetooth (nie musi). Potwierdzanie SMS może być całkowicie niezależne od pozostałej części aplikacji.

> 2. aplikacja musiałaby w tle odpytywać sewer o status. staramy się ograniczać działanie app w tle w trosce o baterie

Aplikacja i tak musi o to odpytać choćby po to, żeby zmienić status (zielony/czerwony). Dodatkowo aplikacja i tak przynajmniej raz dziennie odpytuje serwer o identyfikatory bluetooth do rozgłaszania. Można umieściś status jako dodatkowe pole. Uaktualnianie statusu na serwerze prawdopodobnie i tak będzie się odbywało maksimum raz dziennie.

**Comment by jakublipinski** [comment]
> To jest OK. Jeśli tylko nie będzie to w żaden sposób związane z identyfikatorami bluetooth (nie musi). Potwierdzanie SMS może być całkowicie niezależne od pozostałej części aplikacji.

Teraz jest OK, ale za chwilę ktoś powie, że serwerowi nie można ufać i że to nie jest OK.

> Aplikacja i tak musi o to odpytać choćby po to, żeby zmienić status (zielony/czerwony). Dodatkowo aplikacja i tak przynajmniej raz dziennie odpytuje serwer o identyfikatory bluetooth do rozgłaszania. Można umieściś status jako dodatkowe pole. Uaktualnianie statusu na serwerze prawdopodobnie i tak będzie się odbywało maksimum raz dziennie.

Dziś odpytujemy serwer tylko jeśli ktoś otworzy aplikację. Pobieramy wtedy `beacon_id`s na 21 dni do przodu. To co proponujesz to jest gruba zmiana, której nie zrobimy w `1.0`. Jest opcja całkowitej anonimowości, więc nie widzę z tym problemu. Wróćmy ew. do tematu później.

**Comment by potiuk** [comment]
> Teraz jest OK, ale za chwilę ktoś powie, że serwerowi nie można ufać i że to nie jest OK.

Nie wydaje mi się żeby ktokolwiek miał jakikolwiek problem z tym. Ja nie mam. Jest licencja która pilnuje transparentności przede wszystkim aplikacji i bardzo łatwo jest sprawdzić czy komunikacja dotycząca BT jest jakoś powiązana z komunikacją dotyczącą rejestracji.

> > Aplikacja i tak musi o to odpytać choćby po to, żeby zmienić status (zielony/czerwony). Dodatkowo aplikacja i tak przynajmniej raz dziennie odpytuje serwer o identyfikatory bluetooth do rozgłaszania. Można umieściś status jako dodatkowe pole. Uaktualnianie statusu na serwerze prawdopodobnie i tak będzie się odbywało maksimum raz dziennie.

> Dziś odpytujemy serwer tylko jeśli ktoś otworzy aplikację. Pobieramy wtedy `beacon_id`s na 21 dni do przodu. To co proponujesz to jest gruba zmiana, której nie zrobimy w `1.0`. Jest opcja całkowitej anonimowości, więc nie widzę z tym problemu. Wróćmy ew. do tematu później.

Doskonale rozumiem że to spora zmiana. I rozumem że nie da się jej wprowadzić przed świętami. Dlatego nie mówię że jest to konieczne. Według mojej oceny opcja 3. na tą chwilę jest również w pełni akceptowalna i daje ludziom możliwość świadomego podjęcia decyzji, czy chcą faktycznie być poinformowani szybciej/bardziej skutecznie/bez otwierania aplkacji - ale poświęcając anonimowość, czy też chcą tą anonimowość zachować. Wydaje mi się że to rozsądny kompromis.

**Comment by potiuk** [comment]
Mam jeden postulat związany z tym:

> Dziś odpytujemy serwer tylko jeśli ktoś otworzy aplikację. Pobieramy wtedy `beacon_id`s na 21 dni do przodu. To co proponujesz to jest gruba zmiana, której nie zrobimy w `1.0`. Jest opcja całkowitej anonimowości, więc nie widzę z tym problemu. Wróćmy ew. do tematu później.

Jeśli faktycznie chcemy się upewnić, że będziemy mogli wrócić do tematu później to powinny zostać spełnione dwa warunki:

1) Numer telefonu powinien być po potwierdzeniu przechowany lokalnie w aplikacji
2) ""profil" użytkownika na serwerze powinien być identyfikowany unikalnym ID niezwiązanym z numerem telefonu a nie numerem telefonu. Zakładam, że tak właśnie jest - no bo inaczej rozwiązanie nie działało by bez podania numeru.

Duża prośba żeby w wersji 1.0 te warunki były spełnione, tak aby można było rozważyć zaimplementowanie pkt. 4.

**Comment by potiuk** [comment]
A to w zasadzie można zamknąć bo to do poprzedniej wersji.
