### ISSUE TITLE
Aplikacja niepotrzebnie wysyła nadmiarowe informacje

### ISSUE THREAD

**Issue by jasisz** [ProteGO-Safe/specs#85]
Następujące pola nie są potrzebne przy wysyłaniu zapytania `get_status`:
- platform
- os_version
- device_type
- app_version
- lang

Ich wysyłanie (i zapisywanie) nie spełnia w systemie żadnej roli i jest zbędne.

**Comment by jakublipinski** [comment]
`Bluetooth stack`, jego możliwości i ograniczenia jest mocno zależny od urządzenia na którym działa i wersji systemu operacyjnego. Wiedząc które urządzania są wykorzystywane przez użytkowników, możemy priorytetyzować poprawki i testy.
`lang` używane jest do zwracania użytkownikowi z serwera komunikatów w jego języku. Może też nam pozwolić na zdecydowanie które nowe języki uwzględnić w tłumaczeniach (np. ukraiński?)

**Comment by jasisz** [comment]
@jakublipinski Jeżeli takie są cele, to myślę że dla pewności i przejrzystości warto byłoby:
- wskazać je w specs
- nie wiązać tych danych z konkretnym użytkownikiem

Co uważasz?

**Comment by D0han** [comment]
Tłumaczenie na różne języki powinno odbywać się po stronie aplikacji klienckiej, nie po stronie serwera. Serwer powinien zwracać jedynie statusy zdefiniowane w protokole.

**Comment by Tarvald** [comment]
Wątek mocno nie aktualny.
Na tą chwile zamykam w ramach sprzątania starych wątków.
Jeżeli sądzicie że aplikacja nadal wysyła niepotrzebne dane dajcie nam znać :)
