### ISSUE TITLE
Google i API ogłosilo wydanie wspólnego Contact Tracing API i aplikacji

### ISSUE THREAD

**Issue by nuschpl** [ProteGO-Safe/specs#93]
Wiem, że jest wątek z "konkurencją" ale myśle że to moze byc gamechanger - ze wzgledu na rzeczy krytyczne jak komunikacja bluetooth czy brak negatywnego wpływu na baterie  które mogą być standardowo trudne do osiągnięcia.
https://blog.google/documents/57/Overview_of_COVID-19_Contact_Tracing_Using_BLE.pdf

API: https://blog.google/documents/55/Android_Contact_Tracing_API.pdf
Kryptografia: https://blog.google/documents/56/Contact_Tracing_-_Cryptography_Specification.pdf
Warstwa bluetooth: https://blog.google/documents/54/Contact_Tracing_-_Bluetooth_Specification.pdf

Może warto rozwazyc albo calkowita zmiane albo przynajmniej podłaczenie sie równolegle pod to API aby zwiększyc możliwości swojego/innych radaru covid-19.

**Comment by potiuk** [comment]
Absolutnie tak. Myślę że to jest gamechanger ostateczny :)

**Comment by jasisz** [comment]
Szczerze mówiąc, to jestem trochę... zawiedziony tym rozwiązaniem od Google i Apple. Spodziewałem się czegoś rewolucyjnego, a tutaj niestety nic takiego nie ma :D Takie popłuczyny po istniejących rozwiązaniach, z tym że pewnie zagwarantują nie ubijanie aplikacji i wbitę do tego przez jakieś API.

Gorzej pewnie z dostępnością tego API, w szczególności w Androidzie, zanim to dojdzie na większość telefonów...

**Comment by nuschpl** [comment]
Zakladam ze bedzie w Google Play Services jakos podlaczone bez koniecznosci aktualizacji OS czy security. Rozwiazanie Apple/Google jest minimalne bo chodzi o maksymalna prywatnosc - tylko wtedy masz gwarancje duzej bazy uzytkownikow. 
Problem ze newsy o nowych aplikacjach czyta 5% spoleczenstwa, wydaje mi się że skoro jest wsparcie MC i potencjalna promocja to mimo wszystko trzeba działać i wystawić minimalna aplikacje z uprawnieniem do powiadomień aby zebrać baze uzytkownikow - i informowac co dalej, jaki etap rozwoju, korzystac z tego API a w ostatecznosci napisac ze ProteGo sie zamyka i zeby korzystali z aplikacji Google /Apple. Z drugiej strony zostaje furtka gdyby ktoś opt-in chciał jednak  wyslac rzadowi swój status gdyby powstaly "certyfikaty odpornosci" .

**Comment by jasisz** [comment]
To nie jest wcale takie idealne rozwiązanie, jest całkiem sporo wątpliwości.

Oczywiście jest to o niebo lepsze niż to co jest teraz w ProteGO, ale po prostu spodziewałem się jakiegoś świeżego pomysłu. Jakoś nie czuję wcale, że to właśnie jest "rozwiązanie ostateczne".

**Comment by potiuk** [comment]
Ciekawe dlaczego? Co jest nie tak @jasisz konkretnie ?

**Comment by jasisz** [comment]
Te rozwiązania dzielą ze sobą sporo wad, myślę że całkiem fajnym podsumowaniem jest https://eprint.iacr.org/2020/399 (chociaż przyznaję - część wad to po prostu wady rozwiązanie przez Bluetooth).

Podstawową wadą jest to, że identyfikatory użytkowników służą jako identyfikatory spotkań, jest to wspólny punkt wielu rozwiązań, który niesie ze sobą całą masę konsekwencji, również tych  opisanych w dokumencie. Próbowałem przedstawić pewną alternatywę tutaj: https://github.com/DP-3T/documents/issues/112 aby pokazać że można sprobować inaczej.

Bardziej filozoficzną wadą jest z kolei to, że wszystkie systemy zakładają, że "nie-zarażenie" jest stanem normalnym, a zarażenie oznacza że musisz się de facto wyzbyć części prywatności. Nikt nie wie czy w przyszłości nie będzie tak, że większośc będzie jednak zarażona.

**Comment by potiuk** [comment]
> Bardziej filozoficzną wadą jest z kolei to, że wszystkie systemy zakładają, że "nie-zarażenie" jest stanem normalnym, a zarażenie oznacza że musisz się w pewien sposób wyzbyć części prywatności. Nikt nie wie czy w przyszłości nie będzie tak, że większośc będzie jednak zarażona.

@jasisz - > Większość na szczęście tylko przez 14 dni kwarantanny. Jeśli masz lepszy pomysł - to najlepiej wyślij go Google i Apple. Znam sporo inżynierów którzy tam pracują. Myślę że Cię wysłuchają i jeśli będziesz miał lepszy pomysł to go wdrożą

**Comment by potiuk** [comment]
Jakby co @jasisz -> to mogę przekazać. Mam kontakty do odpowiednich osób. Tylko proszę o konkrety

**Comment by nuschpl** [comment]
> Podstawową wadą jest to, że identyfikatory użytkowników służą de facto jako identyfikatory spotkań, jest to wspólny punkt wielu rozwiązań, który niesie ze sobą całą masę konsekwencji, również tych opisanych w dokumencie. Próbowałem przedstawić pewną alternatywę tutaj: [DP-3T/documents#112](https://github.com/DP-3T/documents/issues/112) aby pokazać że można sprobować inaczej.

zerknąlem na szybko ale czy to nie jest jakis challenge response ktory wymaga aktywnej komunikacji obu spotykacjacych sie w tym samym czasie ?  Bo jesli tak to zabije baterie pomijajac inne problemy z zablokowanym ekranem itp

**Comment by jasisz** [comment]
@nuschpl Mój pomysł jest właśnie bez challenge response (były pomysły oparte o handshake, ale tak jak mówisz, jest to problematyczne). U mnie każdy liczy to lokalnie, a na ten dzielony klucz składa się właśnie coś co wiedzą tylko osoby, które w danym czasie były w danym miejscu. Co to jest konkretnie, to kwestia do dyskusji, ale chodzi mi o pokazanie, że można spróbowac jakoś inaczej.

**Comment by nuschpl** [comment]
@jasisz szczerze to nie rozumiem  jak chciałbys to osiągnac
>SharedEphID, which is shared between all people nearby, and on top of that - epoch and location bound in a non-reversible way
od strony bluetooth? Zakladasz ze wszyscy widza takich samych sasiadow i ze nie ma zakłocen ktore spowoduja ze cos do kogos nie doleci. A jesli nie i jakies wariantowe podejscie - to mnostwo liczenia i battery drain

**Comment by jasisz** [comment]
@nuschpl jeżeli coś do kogoś nie doleci, nie oznacza to od razu, że akurat będzie to wybrany klucz. Przy częstej rotacji kluczy jest ogromna szansa że "coś łapniesz".

> zreszta przy takim podziale ludzi na "klatki" gdzie kazdy widzi kazdego, w ogole nie sa nam potrzebne identyfikatory ludzi, wystarczy nr "klatki" zglosic jako zarazony
Nie, ponieważ to pozwalałoby na "zgadywanie hashy" i śledzenie lokalizacji zainfekowanych osób albo interesującyh kogoś obszarów. Dodanie do tego elementu EphID branego nomen omen z powietrza to uniemożliwia.

**Comment by nuschpl** [comment]
Jakos tego nie moge sobie wyobrazic realiability tego nawet w scenariuszu 4 osób względnie przemieszczających sie wokól siebie wchodzac i wychodzac do osiedlowego sklepiku. A tym bardziej dla duzych zbiorowisk typu duzy sklep czy autobus przemieszczajcy sie po miescie . + rozwalić system moze w danym miejscu nawet jedna osoba, w modelu Google/Apple może sobie tylko śmiecić pakietami obciażajac telefony ale system będzie dalej działał. Może rozrysuj to(choćby na kartce) w tamtym watku w formie diagramu z aktorami i komunikatami - co dzieje sie po kolei i w jakich oknach czasowych. Caly czas trzeba pamietac ze nie ma w tym przypadku debugowania na produkcji wiec jeśli system nie bedzie z jakiegos powodu dzialal to nawet nie bedzie o tym wiedzy.

**Comment by macieja** [comment]
Skoro macie Panowie dostęp do Google czy Apple to może by tak lobbować za eliminacją bazy centralnej i dystrybucje informacji o zakażeniach w architekturze blockchain? Po stronie BT myślę że już lepiej nie będzie.

**Comment by potiuk** [comment]
Ale akurat z tego co widzę, to centralnie przechowywane i publicznie dostępne są jedynie Daily Tracking IDs osób zarażonych i zdiagnozowoanych. Pewnie że można by to zrobić a'la blockchain ale pytanie po co, skoro i tak ID takiej osoba musi być pozytywnie zweryfikowana przez Health Authorities i trzymana w bazie? No i każdy w tej architekturze (podobnie jak w blockchain) ma dostęp do pełnej listy Daily Tracking IDs ? 

W czym architektura blockchainowa miała by być lepsza w tym przypadku ? Każde takie ID jest ważne 2 tygodnie a potem jest usuwane z systemu, więc nawet nie można argumentować że istotna jest "niezmienialność" danych historycznych - te ID są efemeryczne i będą się ciągle pojawiały i znikały w sposób zupełnie niezależny.

**Comment by macieja** [comment]
Jeśli byłaby jedna baza światowa utrzymywana przez WHO na publicznej infrastrukturze to nie mam z tym podejściem większego problemu. Musimy sobie jednak zdawać sprawę jakim wielkim zagrożeniem byłoby nadużycie dostępu do takiej bazy:
a) ukrywanie zarażonych
b) fałszywe zarażanie zdrowych ludzi, wymuszając pozostanie na kwarantannie (trudne ale nie niemożliwe)
c) utrata zaufania użytkowników, co jest niezbędne w celu uruchomienia usługi na możliwie jak największej ilości urządzeń

**Comment by potiuk** [comment]
A jak masz zamiar utrudnić to w rozwiązaniu typu blockchain ? W jaki sposób chciałbyś zapewnić że a) b) nie jest możliww e takim rozwiązaniu jeśli i tak potwierdzenie diagnozy ma przychodzić od "health authorities" ? Jakbyś mógł tak konkretnie opisać co się miało by dziać i jak informacja od health authorities miała by w blockchainie się znaleźć w taki sposób żeby nie dało się zrobić a) b)

IMHO problem z rozwiązaniami typu blockchain, jest taki że jeli polegają na tym co dzieje się w  "rzeczywistości" - to cała zaleta blockchainu jest tracona w momencie w którym te dane są przenoszone z rzeczywistości do blockchainu. Blockchain działa fajnie jak od początku do końca wszystko co obsługuje jest "cyfrowe". Chętnie posłuchałbym jak chciałbyś żeby taki system działał - to może być bardzo ciekawa dyskusja :).

**Comment by kierepka** [comment]
https://appleinsider.com/articles/20/04/23/apple-and-googles-contact-tracing-app-to-launch-early-on-april-28

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.
