### ISSUE TITLE
[TECHNOLOGIA] Bluetooth przez ściany

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#96]
Problem ze zdrowymi osobami i oznaczaniem niesłusznie jako zakażona pojawi się w okolicach kwarantanny osób jej przestrzegających. Mieszkania w blokach mają przeciętnie wysokość ok. 2.5-3 metra i stosunkowo cienkie ściany.

Gdy osoba w miejscu kwarantanny (mieszkanie - jest to najczęstsze miejsce kwarantanny) - stoi i trzyma telefon w ręku - ma go na wysokości ok. 1.5m. W mieszkaniu powyżej telefon może leżeć na kanapie lub podłodze i się ładować. Efektywna odległość wynosi mniej niż 2m, błędnie następuje oznaczenie osoby jako zakażonej. 

Ta sama sytuacja ma miejsce gdy telefony leżą w 2 mieszaniach obok siebie pod ścianą. 

Czy jest jakikolwiek sposób wykluczenia tych przypadków w oparciu o bluetooth? Przecież spędzając czas w domu może ta sytuacja trwać nawet godziny... Nawet użycie GPS nie wykluczy tych sytuacji.

**Comment by potiuk** [comment]
IMHO - nie da się uniknąć pewnych "false positives". Dlatego uważam, że (jak opisałem w #54) oznaczenie statusu jako "zagrożony" powinno dawać natychmiastową i bezpłatną przepustkę do zrobienia testów. Na tym powinna polegać rola państwa w tym projekcie. 

A technologia może pomóc zminimalizować te "false positives" - Technologia oparta o API Google API będzie na pewno poważnie przetestowana (podobnie jak to było w przypadku TraceTogether) pod kątem estymowania faktycznych "bliskich" spotkań. To można będzie też udoskonalać w trakcie w miarę jak będą zbierane dane. W zależności od typów urządzeń, od tego czy urządzenie się po rusza, czy nie, i jeszcze pewnie wielu innych sensorów można będzie z coraz większą pewnością obliczyć prawdopodobieństwo, że nastąpiło "bliskie spotkanie". Taka najbardziej podstawowa sprawa w tym konkretnym przypadku - ściany dość skutecznie osłabiają sygnał w częstotliwościach BT a podstawą do określenia jak bliskie będzie spotkanie jest siła sygnału (RSSI) https://en.wikipedia.org/wiki/Received_signal_strength_indication - można swobodnie założyć że ściany na tyle skutecznie osłabiają sygnał, że spotkanie "przez ścianę" nigdy nie będzie "bliskim spotkaniem".

**Comment by SeraMoon** [comment]
Nawet ścianki z gipsu, które mam u siebie w domu (boczne) mają właściwość na tyle znacznego obniżania sygnału bluetooth? 

Szkoda, że nie mam na czym tego przetestować (potrzebne 2 telefony ze zmodyfikowanym androidem, bo już sam android nie daje prywatności) - **test 1.5m spotkanie 2 ludzi na ulicy + 0.5 metrowa odległość + grubość ściany - pod ścianami. **

Należy zwrócić uwagę, że obecnie bezpieczna odległość od osoby kaszlącej to 4m nie 2m (w pomieszczeniu zamnkiętym) - tej odległości nawet na warszawskich chodnikach nie da się "wymusić" bo są znacznie węższe. Dodatkowo na dworzu odległość ta jest wydłużona znacznie w kierunku wiania wiatru. Sensory tu wiele nie pomogą, bo telefon nosi się w kieszeni, gdzie wiatru i kierunku mierzyć nie mogą. 

**OPRACOWAĆ SZCZEPIONKI - APEL DO MINISTRÓW!!! ** Tylko szczepionka wcześnie opracowana i podana na całym świecie spowoduje, że "koronawirus" (SARS-CoV-2) nie stanie się tak powszechny i zmutowany jak koronawirusy 229E czy OC43, na którego już szczepionki nie będzie nigdy. To nam grozi jeżeli nie sprężymy się w porę z eliminacją potencjalnych "hostów" dla wirusa na których może się rozmnażać i mutować dalej. 

Mamy już 3 szczepy i setki mutacji - szczep Ser "S", Leu "L" oraz trzeci którego nazwy nie znam (są już o nim wzmianki, prawdopodobnie jeszcze nie nazwany). Różnią się w zakresie białka "koronki", czyli S. 

To jest walka z koronawirusami (liczba mnoga) nie jednym typem koronawirusa.

**Comment by kierepka** [comment]
To i tak mały pikuś - lekarz, pielęgniarka posiadający telefon i wszystkie osoby działające w służbie zdrowia i blisko szpitali - mają mówić, krótko nie najciekawiej. Każdy z nich gdzie się nie pojawi później będzie generować maksymalnie dużo zgłoszeń.
Wystarczy dostarczyć pizze do szpitala...

**Comment by SeraMoon** [comment]
> Wystarczy dostarczyć pizze do szpitala...

[Koronapizzę](https://www.horecatrends.pl/trendy/119/wloska_pizza_z_koronawirusem_slabym_zartem_francuskiej_telewizji,4004.html)?... wystarczy, że ktoś podrzuci skażoną pizzę i zostanie pizza z nas a aplikacje nic nie dadzą. Jedynie **ułudę bezpieczeństwa**, podobnie jak ułudę bezpieczeństwa dawał dystans 2m. Dobrze, że trzymałam w kolejkach dystans 6m dla własnego bezpieczeństwa. Rząd wiele rzeczy przemilczał. 

poza tym **zapisy na wybory**, zamiast odebrać ode mnie w urzędzie ten p***y wniosek o dopisanie do rejestru i przybić p***ą pieczątkę i podpisać, że wpłynęło, musiałam z urzędu iść i ryzykować zarażenie na poczcie. Mam obawy, że gra się nie toczy o koronawirus ale #GOronaVirus rzędowy. Takie parcie do władzy po trupach powinno skończyć się karą ś***i.   

BTW. mam dość PiSu i mam dość rządu. Nigdy więcej nie zagłosuję na tą p***ą partię.

**Comment by potiuk** [comment]
> Nawet ścianki z gipsu, które mam u siebie w domu (boczne) mają właściwość na tyle znacznego obniżania sygnału bluetooth?

Myślę, że to właśnie jest zadanie dla G+A żeby bardzo porządnie to przetestować i uwzględnić jak najwięcej przypadków.

> Czy to ktoś zmierzył? O ile decybeli obniża się sygnał BT przy ścianie? Jaka to liczba? Ile dla porównania spada sygnał BT pomiędzy odległością 1m i 5m na wolnym powietrzu? Mówienie "jest dobrze" bez dokonania pomiarów (testów) jest niezbyt profesjonalne.

Nikt nie mówi że "jest dobrze". Myślę że Google będą kontyuować to, co zrobili Twórcy TraceTogether. Tutaj jest opisana metodologia i wyniki badań zrobionych w Singapurze na ten temat. https://github.com/opentrace-community/opentrace-calibration

**Comment by potiuk** [comment]
@SeraMoon - czy to odpowiada na Twoje wątpliwości w kwestii technologii? Abstrahując oczywiście od inych kwestii. 

Według mnie, właśnie takie podejście w którym inżynierowie podchodzą solidnie do swojej pracy solidnie, robią badania, obliczenia "back-of-the-envelope" a potem weryfikują to na bazie testów i praktycznych wdrożeń to jest bardzo słuszna droga żeby przynajmniej mieć dane na podstawie których można podejmować decyzje (zamiast od razu dyskredytować pomysł). Myślę że takie podejście jest bardziej konstruktywne i rzeczowe.

**Comment by SeraMoon** [comment]
No właśnie nie odpowiada na moje pytania, bo chciałabym ujrzeć wyniki w decybelach dla
- spotkania 2 ludzi na powietrzu z odległości metr (potencjalnie niebezpieczny kontakt)
- spotkania 2 ludzi na powietrzu z odległości 2 metrów (potencjalnie niebezpieczny kontakt) przez 30 minut,
- spotkanie 2 ludzi na powietrzu z odległości 5 metrów (potencjalnie bezpieczny kontakt
- spotkanie 2 ludzi w odległości 1 metra ale rozdziela ich standardowa ściana, długość spotkania 3 godziny (kontakt całkowicie bezpieczny). 

To jest temat do zmierzenia i zamknięcia dopiero, gdy okaże się, że ściany w 10 budynkach wystarczająco hamowały sygnał. 

Bo tylko to obroni nas przed masą false-positive'ów. 

W przypadku kwarantann ciągłe false-positive - wracasz i znów pozytywny i znów kierują na te testy, to nie jest nic przyjemnego, a wręcz podpowiadającego "wyrzuć ten telefon przez okno".

**Comment by Dr-Kownacki** [comment]
Kochani, podam bardziej trywialny przykład:
WARSZAWSKIE KORKI W GODZINACH SZCZYTU...
Na przykład taki most im Grota-Roweckiego 7-8 rano, to jest piekło. Próbowaliście kiedyś skanować w korku bluetooth? Zobaczycie dziesiątki urządzeń. I teraz niech kilka osób w tym korku ma mijających się pasach okaże się zakażonymi, to gwarantuje nam TYSIĄCE false-positives przy auto-tracingu...
A zatem w trybie "auto" powinien być jakiś "tryb samochodowy", a jak go automatycznie wykryć to już kwestia "domyślania" się przez Google że po tym moście nie chodzi się pieszo tym bardziej pokonując wiele kilometrów w osiach ulic...

Tutaj taki pomysł ewentualnie na jakiś sprzętowy mikro-token, który na stałe zamontowany byłby w naszym samochodzie i w ten sposób aplikacja wiedziałaby że nie powinna skanować wszystkiego co popadnie...
Ewentualnie drugi telefon trzymany tylko w samochodzie jedynie w celach różnicowania "prawdziwych" trafień od tych "samochodowych", z naszej bazy usuwalyby się automatycznie duble trafień z naszego i samochodowego telefonu...

**Comment by potiuk** [comment]
> No właśnie nie odpowiada na moje pytania, bo chciałabym ujrzeć wyniki w decybelach

Widzę że jesteś specjalistką w tej dziedzinie - super! Myślę że każda pomoc i fachowa wiedza w tym temacie się przyda.

Jeśli mogę coś zasugerować - najlepszy sposób na pomoc w tym projekcie (zakładam że chcesz pomóc),  to otwarta dyskusja ma ten temat z inżynierami Google i Apple którzy opublikują swoje API.

Jak zostało ogłoszone w #94 aplikacja wdrożona przez Ministerstwo Cyfryzacji będzie korzystała z tego API. Myślę że jak Google i Apple otwozy swoją implementację to - podobnie jak twórcy TraceTogether będziesz mogła z nimi na ten temat podyskutować. Być może nawet udostępnią jakieś możliwości regulacji tego API przez twórców aplikacji - myślę że jeśli z Twoich dyskusji z Apple i Google wyniknie że w Polsce trzeba trochę ten algorytm dostosować, to na pewno chętnie Twórcy aplikacji wezmą wyniki Twojej dyskusji z nimi pod uwagę.

Jak tylko Google + Apple opublikują swoje API - dam znać gdzie można będzie uderzyć tak żebyś mogła ten wątek pociągnąć dalej. Mogę nawet spróbować uzyskać dostęp do twórców tego API bezpośrednio (jestem ex-Googlerem i mam trochę kontaktów z Googlem do dziś.)

Czy to rozsądna propozycja @SeraMoon ? 

> W przypadku kwarantann ciągłe false-positive - wracasz i znów pozytywny i znów kierują na te testy, to nie jest nic przyjemnego, a wręcz podpowiadającego "wyrzuć ten telefon przez okno".

Tak - to właśnie jest kwestia tego procesu o którym pisałem w #94 - Ministerstwo Cyfryzacji musi tak wymyślić ten proces żeby to nie było "ciągłę false-positives" tylko żeby to było rzadko. Na przykład jak masz sąsiada na kwarantannie to on nie powinien móc "zarażać" - pod warunkiem ze kwarantanna jest pilnowana za pomocą aplikacji "Kwarantanna domowa". To jest cały kompleksowy proces którego aplikacja Contact Tracing powinna być jedynie częścią.

**Comment by potiuk** [comment]
> Kochani, podam bardziej trywialny przykład:
> WARSZAWSKIE KORKI W GODZINACH SZCZYTU...
> Na przykład taki most im Grota-Roweckiego 7-8 rano, to jest piekło. Próbowaliście kiedyś skanować w korku bluetooth? Zobaczycie dziesiątki urządzeń. I teraz niech kilka osób w tym korku ma mijających się pasach okaże się zakażonymi, to gwarantuje nam TYSIĄCE false-positives przy auto-tracingu...

Tu właśnie na przykład może pomóc siła sygnału RSSI (samochód jest dobrym tłumikiem) - patrz wyżej dyskusja z @SeraMoon . Jestem pewien że inżynierowie Google + Apple już na ten temat robią badania. Widzieliście kiedyś korki na autostradzie 101 San Francisco <-> Dolina Krzemowa. Połowa Google'a z Mountain View tam jeździ codziennie. Zapewniam was że myślą o tym jak to rozwiązać.

> A zatem w trybie "auto" powinien być jakiś "tryb samochodowy", a jak go automatycznie wykryć to już kwestia "domyślania" się przez Google że po tym moście nie chodzi się pieszo tym bardziej pokonując wiele kilometrów w osiach ulic...

Tu dodam - że ten problem już jest rozwiązany. W OS Anroid i Apple są specjalne API które wykrywają automatycznie czy człowiek idzie, jedzie na rowerze, jedzie samochodem na podstawie różnych sensorów. Jest ono dostępne już od paru lat i coraz doskonalsze. Myślę że (jak pisałem w innych wątkach) właśnie to że to API jest robione na cały świat przez jednych z najlepszych inżynierów na świecie którzy od dawna implementują systemy na telefony, umożliwi to wykorzystanie wszystkich możliwości które daje technologia a jednocześnie będzie to dostępne dla wszystkich ludzi na całym świecie.

> Tutaj taki pomysł ewentualnie na jakiś sprzętowy mikro-token, który na stałe zamontowany byłby w naszym samochodzie i w ten sposób aplikacja wiedziałaby że nie powinna skanować wszystkiego co popadnie...
> Ewentualnie drugi telefon trzymany tylko w samochodzie jedynie w celach różnicowania "prawdziwych" trafień od tych "samochodowych", z naszej bazy usuwalyby się automatycznie duble trafień z naszego i samochodowego telefonu...

Nic z tego nie jest potrzebne - prawdopodobnie to co już jest w systemach mobilnych + RSSI + testy + kalibracja będą wystarczające do wychwycenia bardzo dużej liczby podobnych przypadków.

**Comment by matsobdev** [comment]
> Nawet ścianki z gipsu, które mam u siebie w domu (boczne) mają właściwość na tyle znacznego obniżania sygnału bluetooth?

Nawet ściana nośna z cegły przy odpowiednich ustawieniach może nie być wystarczająca do stłumienia sygnału. Ja zrobiłem kiedyś apkę randkową działającą na BLE. Niedawno ją zmodyfikowałem, żeby informowała o odległości między telefonami mniejszej niż te ustawowe 2m. Dane dla Androida, bo tylko na tą platformę to zrobiłem. Przy nadawaniu z maksymalną mocą, która jest i tak niższa niż rozgłaszanie dla klasycznego BT (moje spostrzeżenie przy testowaniu różnych scenariuszy BT i BLE) i agresywnym skanowaniu połączonym ze zbieraniem pakietów przez pół sekundy i liczeniem średniej z RSSI to przy -85 dB czasem złapało "matcha". Zbieranie danych z większej ilości odebranych pakietów ma większy sens, niż tylko opieranie się na pojedynczym zgodnym pakiecie.

**Comment by Dr-Kownacki** [comment]
@matsobdev :
To może jakaś aplikacja randkową dla osób zakażonych/wyleczonych z COVID ? Serio :-)
Jest szansa na hit, pamiętaj o mnie jak podbijesz tym świat ;-)))

**Comment by kierepka** [comment]
O tam przez ściany - można i dalej jak się chce i dobrze poustawia takie zabawki:
https://www.msn.com/en-us/lifestyle/rf-buying-guides/best-bluetooth-range-extenders-reviews 

Jak podaje WiKi: "In August 2004, a world-record-setting experiment (see also Bluetooth sniping) showed that the range of Class 2 Bluetooth radios could be extended to 1.78 km (1.11 mi) with directional antennas and signal amplifiers"

**Comment by matsobdev** [comment]
> To może jakaś aplikacja randkową dla osób zakażonych/wyleczonych z COVID ? Serio :-)
> Jest szansa na hit, pamiętaj o mnie jak podbijesz tym świat ;-)))

No tak, pomijając aspekty mutacji wirusa to zainfekowanym wszystko jedno. Może jeszcze wspólne odbywanie kwarantanny po dopasowaniu (dla dobra ogółu, żeby się odizolować od rodziny) :D

**Comment by Dr-Kownacki** [comment]
Moim zdaniem to przez tę izolację i kwarantanny, "zostań w domu"  etc. na pewno na świecie pojawi się za niecały rok zauważalny wyż demograficzny ;-)

**Comment by matsobdev** [comment]
> No właśnie nie odpowiada na moje pytania, bo chciałabym ujrzeć wyniki w decybelach dla

Znaczy tak. Telefon leżący na biurku (Samsung A10 2019, Android 9.0 - maksymalna moc (ADVERTISE_TX_POWER_HIGH), pakiet co 100 ms) nadaje. Odbiera telefon trzymany w ręce (Samsung S7, Android 8.0, odbiór bez przerwy - SCAN_MODE_LOW_LATENCY). Wyniki średnie RSSI z 5 sekund.

- przez ścianę działową (podwójna czerwona cegła plus tynk z obu stron), odległość około 2,5 m: -80 dBm,
- plus 1 m i szafka z talerzami ;): -84 dBm,
- plus 1,5 m i ściana działowa (pojedyncza cegła plus tynk z obu stron) w okolicach lodówki: -96 dBm

**Comment by SeraMoon** [comment]
No czyli ścianka z talerzami czy ścianka na poczcie czy aptece (gdzie łatwo wymienić się wirusami) tłumi tak samo jak ściana z betonu. Jeszcze lepiej niż sądziłam. Wystarczy telefon wrzucić do lepszej torebki i po zabawie. Tymczasem fifrifi czy GSM może mieć zasięg a więc połączenie internetowe jest a sygnału BT "nie ma" i niewykryte przypadki, aplikacja oszukana. 

W drugą stronę pewnie też się znajdą przypadki. Choćby telefon przy szybie samochodu na postoju. Mamy więc i false-negative i false-positive. Technologia do niczego. Do tego należy zaznaczyć, że jeżeli ma być to **anonimowe** to nie ma mowy o androidzie, ale o **podróbach androida**, które też muszą mieć potrzebne funkcje które są zamkniętym opatentowanym kodem Google. 

Co do pytań o współpracę z Google - nie współpracuję z inwigilantami. Mogę porozmawiać o anonimowości, technice, prywatności, ale nie ma mowy o rozmowie nad współpracą z Facebookiem, Google, Apple itp. firmami w jakimkolwiek celu. 

Dziękuję za wykonane testy i szczególnie ten z zakryciem telefonu ręką czy ciałem. 

BTW. Idę opracować pokrowiec, który nie stłumi Wifi i GSM, ale stłumi BT i podczerwień. :smiley_cat:

**Comment by miklobit** [comment]
> IMHO - nie da się uniknąć pewnych "false positives". 
I dlatego , ponieważ nie da się ustalić gdzie "false positives" wystapiły (nie śledzimy lokalizacji) to ryzyko, że z powodu zakażonego sąsiada za ścianą sanepid mnie udupi bez powodu na 2tyg,  jest dla mnie wystarczającym powodem, że przyjęta koncepcja śledzenia kontaktów (nie mówię tu o kwestiach prywatności poruszonych obszernie przez  @SeraMoon ) może być potencjalnie krzywdząca. Zwłaszcza, że prawdopodobnie sygnał z aplikacji będzie traktowany przez sanepid jako wyrocznia, bez żadnej możliwości niezależnej weryfikacji.

**Comment by qLb** [comment]
Pomijajac kwestie techniczne zwizane z BT,BLE oraz ich podatnosci na poziomie sprzetowym jak i oprogramowania mysle, ze do publikacji G+A jakiekolwiek spekulacje w tym temacie sa zwyklym biciem piany.

Co do false-positive/negative - powinnismy wyjasnic sobie jedna rzecz. Nawet najbardziej transparentne raportowanie w systemach opartych o predykcje modelu multizmiennych nie daje wynikow jakkolwiek satysfakcjonujacych. Szczegolnie jesli dostarczone dane na podstawie, ktorych wnioskujemy wynik nie sa wystarczajaco dobrze opisane i zweryfikowane - wtedy w warunkach naturalnych dzieja sie rzeczy niezrozumiale ergo predykcja jest nieskuteczna. Gdy w koncu zrozumiemy, ze problem nie stoi w technologii (licencja OSS moze nam to umozliwic) lub sposobie implementacji (audyt publiczny) lecz danych, na ktorych sie opiera - wtedy swiat ruszy dalej a technologia znow zacznie nam pomagac, tak jak zwykle.

**Comment by SeraMoon** [comment]
Ze względu na wady rozwiązania bluetooth dojdzie do stygmatyzacji ludzi na drodze:
- wymuszenia posiadania telefonu i karty SIM (do masek już zmusili, mimo ich braku, za co kupi je bezdomny?)
- wymuszenia instalacji aplikacji i zmiany ustawień systemu,
- uznania aplikacji za wyrocznię dla sanepidu i rządu. 

Do powyższego zdolny jest rząd i sejm Polski, co zostało pokazane już na etapie dobrowolnej początkowo aplikacji "kwarantanna domowa". Jak nas traktują widać też po dążeniu po trupach do wyborów prezydenckich. Jaki sens ma w ogóle ta aplikacja, gdy rząd i sejm (mowa o większości) każe nam głosować 10 maja w szczycie epidemii? Po co w ogóle używać tej apki, gdy:
- testy nie są przeprowadzane obligatoryjnie u personelu medycznego **(i to oni nas zarażają najczęściej!)**
- 10 lub 17 maja na ulicach potencjalnie pojawią się kolejki obywateli zdolnych do głosowania w ilości 30 milionów -- przed Pocztą Polską (pomijam aspekt braku tajności, równości i bezpośredniości wyborów, jak też potrzeby złamania kwarantanny by pójść zagłosować). po co w ogóle śledzić -- kontakt miał praktycznie każdy z każdym a kontakt z wirusem będzie miał każdy. Po co więc śledzić kontakty? :joy_cat: 

https://oko.press/wirus-jest-w-polsce-od-stycznia/

Ta aplikacja odbije się nam jeszcze czkawką -- programistom ją rozwijającym też. Jeżeli nie teraz to do "programu ochrony przed pedofilami" aby śledzić czy dziecko miało z kimś kontakt, z jakiej odległości i gdzie i kiedy (tak, bo wszyscy będą mieli prawny obowiązek posiadać telefon i włączoną aplikację i przestępca na 100% nie zostawi telefonu w domu). 

BTW. Geje i lesbijki też mogą być nią śledzeni, gdy pojawią się policjanci na marszach równości, aby każdego zidentyfikować? :joy_cat:

**Comment by Dr-Kownacki** [comment]
**i to oni nas zarażają najczęściej!"**

Życzę Ci dużo zdrowia, a teraz odetchnij i jeszcze raz zastanów się że to powinno brzmieć:

**" i oni są zarażani najczęściej"**
(I właśnie dlatego aplikacja powinna mieć wersję/opcję dla medyków o czym od dawna tu piszę )
i zrób **edit** jak już dotrze do Ciebie jaka jest proporcja i kierunek "kto/kogo" zaraża, polecam też dla refleksji poniższą lekturę:

https://wiadomosci.onet.pl/tylko-w-onecie/wstrzasajaca-relacja-lekarki-z-francji-brak-testow-maseczek-reanimacji/wrzm0h6

Cyt.
". Pojawiło się nawet hasło: „Nie będziemy się zajmować zadżumionymi dziećmi”.

Wtedy zrobiło mi się naprawdę przykro, bo z jednej strony społeczeństwo opiera się na nas, każe się nam pracować bez wytchnienia bez żadnych środków zabezpieczających i w chorobie, a z drugiej strony to samo społeczeństwo nie chce mieć z nami nic wspólnego, stara się od nas za wszelką cenę odizolować."

**Comment by SeraMoon** [comment]
> 
> 
> **"i to oni nas zarażają najczęściej!"**
> 
> Życzę Ci dużo zdrowia, a teraz odetchnij i jeszcze raz zastanów się że to powinno raczej brzmieć:
> 
> **" i oni są zarażani najczęściej"**
> (I właśnie dlatego aplikacja powinna mieć wersję/opcję dla medyków o czym od dawna tu piszę, obliczyłem nawet poglądowo w #94 że to jest problem/potrzeba ok.19x większe niż średnio "ogólny")
> 
> i zrób **edit** jak już dotrze do Ciebie jaka jest proporcja i kierunek "kto/kogo" zaraża, polecam też dla refleksji poniższą lekturę, pięknie Twój wpis współgra, brawo:
> ["Niedziela palmowa"- brawa vs. " Ukrzyżuj Go!" ale pięknie i na czasie, 2tys. lat tradycji...]

Nie zamierzam robić edita. **Jak już pisałam, aby lekarz nie przenosił wirusa należy robić obligatoryjne testy**. Prawda jest taka, że zakażają nas lekarze (głównie), w tym zakażają innych pacjentów w szpitalach niekoniecznie jednoimiennych -- zakażają nas obywateli i pielęgniarki, ponieważ nie są obligatoryjnie testowani i nie mają odpowiedniego wyposażenia (maski, TYVEK itp.). Aplikacja sprawy nie rozwiąże. 

Logicznym jest że w skupiuszkach ludzi jak szpitale -- będą infekcje, ale jeżeli nie będzie obligatoryjnych badań personelu -- będzie kiepsko. 

Co mogę polecić: 
- **zakaz pracy w kilku szpitalach na raz -- obecnie problemem jest przenoszenie korony z jednego szpitala do kolejnego**
- ** wprowadzenie pracy tylko przez 3-4 dni w tygodniu dla lekarza i pielęgniarki (po 8h-12h), poczym następuje tydzień bez pracy i tak naprzemiennie -- spowoduje to że jeżeli w Pn lekarz złapie koronę, to nie zaraża w środę bo minęło za mało czasu. W czwartek większość też prawdopodobnie nie będzie jeszcze razażać. Wraca do domu i się obserwuje, jeżeli ma objawy -- bierze urlop lub kieruje się sam do szpitala jednoimiennego. Zanim wróci mija 10 dni, a więc tyle, że objawy już prawie na pewno wystąpią i nie zarazi innych w szpitalu**. 

Nie zaprzeczy Pan tego jeżeli tylko jest Pan Doktorem Medycyny, bo dyplomu tu niestety nie widzimy na Githubie.  


> Wtedy zrobiło mi się naprawdę przykro, bo z jednej strony społeczeństwo opiera się na nas, każe się nam pracować bez wytchnienia bez żadnych środków zabezpieczających i w chorobie, a z drugiej strony to samo społeczeństwo nie chce mieć z nami nic wspólnego, stara się od nas za wszelką cenę odizolować."

Dzięki rządowi, nielegalnym bazom danych nie chcemy mieć styczności - jest jeszcze prywatność. Nie tyle z lekarzami co "ze służbą zdrowia". Kilku znajomych przechorowało to w domu po tym jak dowiedzieli się co PiS wyprawia. Wolą chorować w domu w nieświadomości (nie mają obowiązku tępić choroby, skoro o niej nie wiedzą), ponieważ wolą prywatność. Tyle w temacie. 

Resztę wskazanych punktów dalej podtrzymuję -- po wyborach gdy nas pchną na pocztę i pchną do łamania kwarantanny (trzeba wyjść do skrzynki i odebrać kartę, trzeba złożyć na poczcie) to aplikację można pozostawić w poważaniu, ponieważ każdy złapie "koronę", prawdopodobnie jeszcze płacąc 5-30 tys. zł za to, że wypełnił swój **obywatelski obowiązek zagłosowania w wyborach**. Obłuda rządu -- skoro tak robią to prawda jest taka, że zgodnie z art. 5 Konstytucji RP nie ma żadnego zagrożenia i możemy iść na te wybory kopertowe **i nie ma żadnej korony!**

Za to wszystko jak podchodzimy do służby zdrowia i wszystkiego obecnie -- **niech Pan Panie @Dr-Kownacki podziękuje rządowi i tam składa żale.

**Comment by Dr-Kownacki** [comment]
cyt."Prawda jest taka, że zakażają nas lekarze (głównie), w tym zakażają innych pacjentów w szpitalach niekoniecznie jednoimiennych -- zakażają nas obywateli i pielęgniarki, ponieważ nie są obligatoryjnie testowani i nie mają odpowiedniego wyposażenia"

Gratulacje @SeraMoon za podział społeczeństwa na "**nas obywateli**", "**pielęgniarki**" oraz (tych złych, niebadających się) "**lekarzy**". Pięknie wpisujesz się w powszechną mowę podziałów i uprzedzeń w naszym kraju ...

Twoje niewielkie pojęcie i złą opinie o polskiej ("nie badającej się") służbie zdrowia mam nadzieję choć trochę poprawi poniższy załącznik, którym jeśli pozwolisz zakończę dyskusję - zamiast merytorycznie debatować o technicznych kwestiach aplikacji zalewani jesteśmy m.in. luźno związanymi poglądami nt. m.in. aktualnej sytuacji politycznej etc. a są przecież do tego na pewno znacznie lepsze miejsca w sieci. 

Dużo zdrowia dla wszystkich  i nie dajmy się zwariować i podzielić w tak trudnym czasie ...

![wynik](https://user-images.githubusercontent.com/63192074/79636472-2d0b5f00-8178-11ea-8360-fc8f4b0db490.jpg)

**Comment by SeraMoon** [comment]
> Gratulacje @SeraMoon za podział społeczeństwa na "**nas obywateli**", "**pielęgniarki**" oraz (tych złych, niebadających się) "**lekarzy**". Pięknie wpisujesz się w powszechną mowę podziałów i uprzedzeń w naszym kraju ...

Wskazałam gdzie jest problem. Pielęgniarki tutaj powinien obowiązywać ten sam rygor pracy 3-4 dni, 8-12h wahadłowo (tylko nie zawsze musi się zaczynać od poniedziałku by równomiernie pokryć potrzeby). 

Poza tym w tym momencie atakuje mnie Pan, a trudno nie zauważyć, że żeby zarazić ktoś musi zarażać więc nie -- za próbę wymuszania i Pana charakter, editu nie będzie :joy_cat: 

Co zaś do samych lekarzy i jak nazywają swoich pacjentów w dokumentacji medycznej, gdyby nie fakt, że dbam o swoją prywatność, to bym mogła tu wiele stron dokumentacji wrzucić, gdzie pacjenta nazywa się niewiele słabszymi słowami niż "k***a*. Tak - przez lekarza z dyplomem wpisanego do izby lekarskiej i nie tylko mnie to spotkało gdy się pożaliłam koleżance, okazało się, że i ona u jednego lekarza po wyciągnięciu doc znalazła podobnie opisujące ją epitety. 

## Przypomnienie

Temat brzmi: "[TECHNOLOGIA] Bluetooth przez ściany". Czyli jak wpływają różne przedmioty, w tym ściany na zasięg i szacowanie odległości.  **Rozmawiajmy na ten temat.** Do reszty komentarzy proponuję założyć temat #201 w którym przekaże Pan swoje spostrzeżenia. 

> Twoje niewielkie pojęcie i złą opinie o polskiej ("nie badającej się") służbie zdrowia mam nadzieję choć trochę poprawi poniższy załącznik, którym jeśli pozwolisz zakończę dyskusję 

Nie, dyskusji nie kończę -- bo temat Bluetooth przez ściany" może być niedokończony, odpowiedziałabym Panu załącznikiem, jednak nie zamierzam się ujawniać i publicznie z czyimś nazwiskiem pokazywać wulgaryzmów z dokumentacji medycznej podbite pieczątką lekarską. 

> zamiast merytorycznie debatować o technicznych kwestiach aplikacji zalewani jesteśmy m.in. luźno związanymi poglądami nt. m.in. aktualnej sytuacji politycznej etc. a są przecież do tego na pewno znacznie lepsze miejsca w sieci.

No ale przecież to Pan robi - Pan się przyczepił do mojego sformułowania -- a prawdą jest, że lekarze też zarażają a pielęgniarki i lekarze stanowią 30% zakażonych. Czyżby magicznie na nich kończył się łańcuch infekcji? Nie sądzę. 

Nie wiem po co tutaj formatka badania na SARS-CoV-2, nie wiem co ma wspólnego z tematem tego wątku i co chce Pan przekazać, niemniej jeżeli **nic choćby trochę wspólnego z BT i przeszkodami, to nie jestem zainteresowana odpowiedzią**.

**Comment by SeraMoon** [comment]
Jak na zasięg BT i RSSI wpływa położenie karty (może być nowy dowód osobisty, karta bankomatowa), gdy położone są od zewnętrznej strony, czyli między kartą a ciałem znajduje się telefon? 

Jak sytuacja się zmienia gdy kartę zastąpimy metalowym futerałem na karty, często stosowanym, aby nikt nie mógł ich odczytać?

**Comment by Dr-Kownacki** [comment]
Zarażając wiedzą @SeraMoon proponuję wpisać "bluetooth scanner" w wyszukiwarkę Play pewnej (cytując Cię z innego wątku) "parszywej" firmy...

Jest do pobrania na Androida prawie 20 różnych  przydatnych aplikacji, z których przynajmniej połowa listuje na żywo z BT wartości  -dBm / RSSI dla pobliskich urządzeń BT więc można to sobie samodzielnie sprawdzić i oszacować dla różnych sytuacji i wzajemnych ustawień geometrycznych urządzeń...

**Comment by SeraMoon** [comment]
> 
> 
> Zarażając wiedzą @SeraMoon proponuję wpisać "bluetooth scanner" w wyszukiwarkę Play pewnej (cytując Cię z innego wątku) "parszywej" firmy...
> 
> Jest do pobrania na Androida prawie 20 różnych przydatnych aplikacji, z których przynajmniej połowa listuje na żywo z BT wartości -dBm / RSSI dla pobliskich urządzeń BT więc można to sobie samodzielnie sprawdzić i oszacować dla różnych sytuacji i wzajemnych ustawień geometrycznych urządzeń...

Zapytałam, ponieważ jak wspomniałam nie posiadam tego typu urządzeń, ale jestem dość dobra w opracowywaniu przypadków użycia. 

### Proszę zakończyć prywatę i popatrzeć jaki wizerunek robi sobie Pan tego typu odpowiedziami wnoszącymi NIC do tematu. 

Powyższe przypadki użycia są realnymi przypadkami użycia -- ludzie noszą z sobą karty (często stos kart), papierośnicę, futerały na karty, portfele wypełnione kartami i monetami. Chętnych proszę o testy w konfiguracji powyższej. :smiley_cat:

**Comment by qLb** [comment]
@SeraMoon Nie ma jeszcze zadnego sposobu na przeprowadzenie testu technologi contact tracingu. Wszelkie prace badawczo rozwojowe nad contact tracingiem w tym projekcie zostaly wstrzymane., Dopiero powstala specyfikacja techniczna rozwiazania G+A i jest udostepniona tutaj: https://www.apple.com/covid19/contacttracing 

### Gdy technologia pedzie publicznie dostepna tj. gotowa do testow najpewniej wznowimy prace RnD

Z glebi serca prosze rowniez "dobra umijetnosc w opracowywaniu przypadkow uzycia" stosowac w propagowaniu wlasciwych wzorow uzytkowych a nizeli niewlasciwych w stosunku do narzedzi. Wlasciwie kazde narzedzie mozna zastosowac w niewlasciwy sposob.
