### ISSUE TITLE
Kwestie prawne

### ISSUE THREAD

**Issue by SeraMoon** [ProteGO-Safe/specs#98]
**Sprawa pierwsza:**
Aplikacja domyślnie nie ma opt-out z wysyłania danych do GIS, tymczasem człowiek ma prawo:
- do prywatności (Konwencja Praw Człowieka),
- do poszanowania godności także podczas śmierci (art. 20 i 22 Ustawy o Prawach Pacjenta)
- nie ma prawa wiedząc o chorobie zakażać innych. 

Czy aplikacja wysyłając dane (**a deanonimuje już samo IP, nie ma tu czegoś takiego, że niepodanie numeru to anonimowe użycie, ale pseudonimizowane przez IP i powinno być to napisane wprost**) nie łamie prawa do wyboru jak ktoś "skończy"? Ma prawo być leczony (**gdy chce**), ale ma też prawo zamknąć się na 4 spusty i umrzeć wśród znajomych (gdy tych zaraził bo z nimi non-stop przebywał, ale nie mają objawów lub przeszli to jak przeziębienie) lub też umrzeć samotnie w odosobnieniu. Czy to prawo nie jest złamane przez tą aplikację czy utrzymane?

**Druga rzecz,** gdzie jest moja anonimowość, gdy inne osoby mają porejestrowane wersje aplikacji, ktoś z nich był chory, spotykamy się codziennie i jasne jest, że "anonimowej" osoby należy szukać w pracy lub w rodzinie?

**Sprawa trzecia:**
Należy też dodać, że wbrew woli ludzi w Polsce powstała **scentralizowana** baza danych o ludziach, którzy przeszli chorobę COVID-19. Zakres danych tam gromadzonych to są wszystkie rzeczy, które szpital dowiedział się **pod tajemnicą lekarską** od swoich pacjentów. Ta baza złamała tą tajemnicę i nie ufamy już instytucjom typu szpital jednoimienny czy GIS. Nie ufamy, ponieważ są choroby, które nie są znaczące dla celów określenia ryzyka zakażenia SARS-CoV-2, ale są zbyt intymne lub zbyt wstydliwe by się tam znajdowały (w bazach scentralizowanych rządowych). Choroby te mogą być zauważone przez personel medyczny nawet gdy pacjent je zatai. Żont nie zadbał nawet o to, aby takie dane były usuwane obligatoryjnie przez szpital zanim nastąpi ich przekazanie - wręcz odwrotnie, mają przekazać całą dokumentację medyczną. **Toteż zaufania nigdy nie będzie!** 

Powinna być white-lista kodów ICD-10, które są przesyłane rządowi do tej bazy bo są istotne i powinna być publicznie znana obywatelom. Jednak już postanowiono inaczej i w przypadku minimum 5 tysięcy ludzi złamano tajemnicę lekarską - tajemnicę pomiędzy pacjentem a placówką medyczną!

**Comment by Dr-Kownacki** [comment]
Niestety rozczaruję Cię - od momentu w którym służba zdrowia/jej usługi jest refundowana przez NFZ, który jest płatnikiem i doskonale wie o wszystkich kodach ICD10 pacjenta - pojęcie "tajemnicy" tak jak Ty ją rozumiesz od dawna straciło sens :-)
To wszystko jest zawarte w buchalterii rozliczeń i znajdziesz te informacje o sobie na swoim indywidualnym koncie pacjenta-wszystkie zrefundowane świadczenia/leki etc.

Dodatkowo nie zgodzę się że te "nie-covid" informacje medyczne nie mają znaczenia bo po pierwsze oznaczają ryzyko pacjenta (czy np. jest to pacjent onkologiczny - dużo się o tym mówi) a po drugie meta-anakiza "wszystkich" danych klinicznych pozwolić może na pewne odkrycia np. że pacjenci stosujący jakiś lek x na chorobę y są w większym ryzyku, a pacjenci stosujący lek b na chorobę a mają o wiele lepsze rolowanie.
Takie opracowania są już dostępne np. wobec grupy leków tzw. ACE-inhibitorow.
To są "proste" zależności ale wyobraźmy sobie jakie odkrycia mogą powstać dzięki AI tutaj masz do dyspozycji dane 2mln chorych.

**Comment by SeraMoon** [comment]
> Niestety rozczaruję Cię - od momentu w którym służba zdrowia/jej usługi jest refundowana przez NFZ, który jest płatnikiem i doskonale wie o wszystkich kodach ICD10 pacjenta - pojęcie "tajemnicy" tak jak Ty ją rozumiesz od dawna straciło sens :-)

Na pewno? Część chorób możemy leczyć prywatnie i prosić o prywatne recepty. O tych chorobach nie wie NFZ. Poza tym, gdzie jest napisane, że kod ICD-10 jest przekazywany NFZ podczas wypisania NFZ-owej recepty? Tak tylko dodam, że od PIĘTNASTU lat nie byłam u lekarza NFZ-owego - mam własnych lekarzy prywatnych i **nie wyrażam zgody by w moją historię chorób pchał swój zasyfiały nos polski żont.** Poza tym część kodów jest przypasana do wielu chorób. Co innego szczegółowy wywiad i opis lekarza, niestety, nie zawsze zgodny z tym co powiemy. 

> To wszystko jest zawarte w buchalterii rozliczeń i znajdziesz te informacje o sobie na swoim indywidualnym koncie pacjenta-wszystkie zrefundowane świadczenia/leki etc.

Nie mam konta takowego ponieważ od 15 lat nie raczyłam wybrać nawet lekarza POZ. Nie ma więc tam leków dla mnie, a nawet jeżeli coś prześlizgnęło się nierefundowane - leki te mają wiele zastosowań i nie jest pewne na co je biorę.Skąd będzie wiadomo, czy brałam antybiotyk na zapalenie pochwy czy na zapalenie oskrzeli, skoro dokumentacja jest w placówce prywatnej? Próbowano przepchnąć kiedyś przy obliczaniu refundacji - podanie kodu i nazwy choroby ale **dobrze, że to zablokowali i lekarzowi kazali wyliczyć refundację**. 

> Dodatkowo nie zgodzę się że te "nie-covid" informacje medyczne nie mają znaczenia bo po pierwsze oznaczają ryzyko pacjenta (czy np. jest to pacjent onkologiczny - dużo się o tym mówi) a po drugie meta-analiza "wszystkich" danych klinicznych pozwolić może na pewne odkrycia np. że pacjenci stosujący jakiś lek x na chorobę y są w większym ryzyku, a pacjenci stosujący lek b na chorobę a mają o wiele lepsze rolowanie.

Tak, rokładnie ROLOWANIE. A na poważnie: nie pisałam aby zatajać listę branych leków a listę wstydliwych przypadłości. Powinna być biała lista kodów ICD-1o lub konkretnych schorzeń, które zostaną przekazane. Dodatkowo **moim zdaniem powinna być ta lista przekazywana tylko za zgodą pacjenta, zgodnie z RODO.** Takie przekazanie jakie nastąpiło nie jest zgodne z RODO i nastąpiło przekazanie danych medycznych a może i biometrycznych na przekór woli pacjenta, bez zapytania i to jeszcze wstecz historycznie. 

> Takie opracowania są już dostępne np. wobec grupy leków tzw. ACE-inhibitorow.

Nie pisałam o lekach ale jeszcze raz zaznaczam - o liście chorób, poza tym póki co nie odkryto żadnego związku. Nadal nie wiadomo czy ibuprofen szkodzi czy nie. To jakie leki biorę wiem, że żont wie, bo dostaje to wraz z receptami i e-receptami. **Nie zwiększajmy mu tej wiedzy i protestujmy przeciw odbieraniu nam tajemnicy lekarskiej i łamaniu RODO**. 

> To są "proste" zależności ale wyobraźmy sobie jakie odkrycia mogą powstać dzięki AI tutaj masz do dyspozycji dane 2mln chorych.

AI / IOT to rak, powinni tego zabronić, bowiem często odbywa się to kosztem pogwałcenia praw człowieka o czym pisał panoptykon (polecam przeszukać na "nosidła" stronę panoptykonu). Dla takiego rakowiska nie ma u mnie miejsca ani zgody i **publicznie się sprzeciwiam traktowaniu mnie jak śmiecia i szczura laboratoryjnego**. 

![3xNIE](https://bi.im-g.pl/im/05/1b/15/z22133253V,Logo--3xNIE-.jpg)
dla takiego podejścia.

**Comment by Dr-Kownacki** [comment]
COVID-19 - niestety "prywatnie" (póki co)  się tego nie leczy, ta konkretna choroba jest ustawowo wpisana w przepisy prawa, jest zwalczana z mocy prawa i podlega obowiązkowemu zgłoszeniu. Dyskutujemy o niej i o aplikacji rządowej i stąd ten komentarz.
Jeżeli opłacasz składkę ZUS, lub jakiś podmiot za Ciebie opłaca i chociaż raz jeden lek z refundacją dostałeś to możesz sobie to w portalu pacjenta znaleźć, jest cała historia przechowywana i dostępna - poszukaj to znajdziesz :-)

Znowu Cię rozczaruję ale każda refundacyjna recepta (teraz elektroniczna tylko !) zawiera bardzo dokładne informacje (kod ICD10 etc.) o chorobie z której powodu została wystawiona. Podobnie jest ze wszelkimi skierowaniami na refundowanwe badania diagnostyczne.

Tak, możesz być jak "Jack Reacher" (polecam film z  T. Cruisem są nawet dwie części ), ale przy każdym kontakcie z państwową/prywatną i refundowaną przez NFZ służbą zdrowia zostaje konkretny ślad i szczegółowa informacja z powodów czysto "refundacyjno-finansowych". I przed tym nie uciekniesz jak nie teraz to kiedyś każdego to czeka...

**Comment by SeraMoon** [comment]
> COVID-19 - niestety "prywatnie" (póki co) się tego nie leczy, ta konkretna choroba jest ustawowo wpisana w przepisy prawa, jest zwalczana z mocy prawa i podlega obowiązkowemu zgłoszeniu. Dyskutujemy o niej i o aplikacji rządowej i stąd ten komentarz.
Jeżeli opłacasz składkę ZUS, lub jakiś podmiot za Ciebie opłaca i chociaż raz jeden lek z refundacją dostałeś to możesz sobie to w portalu pacjenta znaleźć, jest cała historia przechowywana i dostępna - poszukaj to znajdziesz :-)

Trudno, skoro prywatnie się tego nie leczy to albo się pokaszle i przesiedzi w domu i wyzdrowieje, albo się umrze, przy Pana podejściu pro-rządowym do łamania praw człowieka (szczególnier w zakresie prywatności). Do chorób, które nigdy nie powinny być przekazywane ministerstwom należą choćby **wszystkie kody z literką F -- czyli mówiąc prosto -- choroby i zaburzenia psychiczne i charakterologiczne**. Zapewne znajdzie się więcej tego typu chorób nieistotnych dla oceny pandemii COVID-19. I mówię jeszcze raz - nie trafiają tam nazwy chorób ani kody -- trafiają tam do tego IKP (?) jedynie spisy przepisanych lekarstw. **Poza tym jak wyżej napisałam -- nie mam obowiązku leczyć COVID-19, bo nie mam obowiązku w ogóle się leczyć ani diagnozować** zgodnie z europejską konwencją praw człowieka. Mam jedynie obowiązek **nie zarażać innych** i pozostanie w domu (aż do wyzdrowienia lub śmierci) spełnia te wymogi. Jeżeli już rozmawiamy ustawami, to proszę przeczytać Konstytucję RP, Europejską Konwencję Praw Człowieka oraz Ustawę o Prawach Pacjenta i RPP. 

BTW. jezeli oprócz zrefundowanych leków i nazw wizyt refundowanych dostępny jest wywiad (**proszę innych o sprawdzenie, jeżeli mają IKP, korzystam z informacji osoby znajomej** - czy widać tam kopię dokumentacji medycznej oraz diagnozy w przypadku innych działań niż chirurgiczne) to jest to raczej niezgodne z RODO i pacjent nie wyrażał na to zgody na formularzach przed badaniem i rejestracją. Dodam **dobrowolnej zgody i zgody wprost** - no o takich mówi RODO - tylko wtedy zgoda jest ważna. 

> Znowu Cię rozczaruję ale każda refundacyjna recepta (teraz elektroniczna tylko !) zawiera bardzo dokładne informacje (kod ICD10 etc.) o chorobie z której powodu została wystawiona. Podobnie jest ze wszelkimi skierowaniami na refundowanwe badania diagnostyczne.

Jeżeli jest tak faktycznie, **to sprawa ta wymaga zbadania zgodności z RODO, ponieważ nikt mnie o tym nie informował**. Zgody na to nie wyraziłam. Kod choroby oraz wywiad zgodnie z prawem **są chronione tajemnicą lekarską i tylko sąd lub dobrowolnie sam pacjent może z tej tajemnicy zwolnić lekarza**. Sprawa niniejszym zostanie przekazana do Rzecznika Praw Obywatelskich. 

> Tak, możesz być jak "Jack Reacher" (polecam film z T. Cruisem są nawet dwie części ), ale przy każdym kontakcie z państwową/prywatną i refundowaną przez NFZ służbą zdrowia zostaje konkretny ślad i szczegółowa informacja z powodów czysto "refundacyjno-finansowych". I przed tym nie uciekniesz jak nie teraz to kiedyś każdego to czeka...

**Powody finansowe (służba prywatna) nie uprawniają nikogo do łamania tajemnicy lekarskiej.** Z tej tajemnicy może poza pacjentem zwolnić jedynie sąd. Każde uzyskanie tych informacji w innym trybie jest **złamaniem prawa zarówno polskiego jak i europejskiego.**

**Comment by Dr-Kownacki** [comment]
Bynajmniej nie mam żadnego "pro" ani "anty" rządowego przekazu tutaj - proszę takich wniosków nie wyciągać bo są stanowczo zbyt daleko idące  :-)
Stwierdzam po prostu "jak jest" zgodnie z moją najlepszą wiedzą i uważam że jest to istotny argument w dyskusji abyśmy wszyscy mogli mieć refleksję jakąś w materii prywatności, dostępu instytucji państwowych do naszych danych zdrowotnych.  Nie oceniam tego, ale przekazuję Wam informację po prostu.
COVID-19 jest wpisany na listę chorób zakaźnych zwalczanych na mocy adekwatnej ustawy obok gruźlicy, kiły i pewnie paru innych też.  Jeśli chodzi o raportowanie świadczeniodawców dla NFZ to w ostatnim czasie wymogi te dramatycznie wzrosły - to są wręcz kwestie ostatnich miesięcy. 
Na pewno można przez google sobie to odszukać - te zarządzenia są publicznie dostępne.

Odbiegamy jednak tutaj zbytnio od tematu, stąd przechodząc do meritum kwestii to co staramy się z moim Kolegą przekazać tutaj na forum jest fakt że "automat BT" mógłby mieć bardziej funkcję wspomagającą a realna-rzetelna informacja biorąca pod uwagę realne ryzyko i interakcje międzyludzkie wymaga naszym zdaniem odrobiny wysiłku i "ręcznego" zalogowania prawdziwego "kontaktu" zbieżnego z definicją WHO.  Jak już w innych wątkach pisałem jest to szczególnie ważne dla przerywania łańcucha zakażeń na poziomie służby zdrowia (ok. 30% zakażonych to pracownicy służby zdrowia) stąd adekwatna "wersja" aplikacji byłaby tu niezmiernie pomocna wszystkim medykom. Dzisiaj odnotowano pierwszy przypadek w Polsce śmieci pracownika służby zdrowia na covid-19 związany z wykonywaniem obowiązków zawodowych, jest to bardzo smutna i symboliczna data dla wszystkich pracowników służby zdrowia...

**Comment by SeraMoon** [comment]
> COVID-19 jest wpisany na listę chorób zakaźnych zwalczanych na mocy adekwatnej ustawy obok gruźlicy, kiły i pewnie paru innych też.

Aby był zwalczony, musi być najpierw zdiagnozowany. 3 zasady, które są zgodne z prawem (prawo do śmierci w godności, europejskie prawa człowieka i obowiązek niezakażania innych) podałam w swoim pierwszym poście. Czy trudno zauważyć, że powyższa opcja (zostanie w domu bez zgłoszenia, gdy ma się objawy) - pozostaje w zgodzie z ustawą i własnymi siłami dążę do "zwalczenia choroby" nie przenosząc jej dalej, a resztę zrobi mój układ immunologiczny lub śmierć? 

Do czego dążę i wytłuszczę to jeszcze raz **podczas wywiadu z pacjentem w szpitalu jest pytanie: jakie leki bierzesz i na co chorujesz, pacjent nie jest informowany, że wbrew jego woli wszystkie te informacje trafią do ministerstwa wbrew jego woli -- państwo jako zwalczające COVID ma jedynie prawo do wiedzy, że pacjent zachorował na COVID, kiłę, gruźlicę itp. wymienione w tej ustawie. Nie ma prawa do wiedzy o takich chorobach wstydliwych jak (wymieniam kody F - nazwy skracam dla czytelności): F10 alkoholizm, F11 używanie (w przeszłości) opiatów, F16 używanie halucynogenów, F20 schizofrenia, F21 zab. schizotypowe, F23 zab. psychotyczne, F30 epizod maniakalny, F31 dwubiegunówka, F32 i F33 depresja, F42 nerwica natręctw, obniżony poziom IQ, F64 zaburzenia identyfikacji płciowej, F65 zaburzenia preferencji seksualnych, F68 zaburzenia zachowania... i można by tak jeszcze wymieniać aż do F99.** 

**O ile dla szpitala mogą to być informacje istotne, bo wyjaśnia to dlaczego brane są dane leki, jednak nie widzę związku COVID-19 i uzasadnienia w przekazywaniu tych danych ministerstwom i do innych baz, które służą do zbierania haków na ludzi (nazwijmy to po imieniu). Później rząd będzie prześladował osoby chore na schizofrenię, nerwicę natręctw czy zaburzenia seksualne tylko dlatego że ma takie widzimisię i nie rozpatrzy ich wniosków na poważnie. Godzi to zarówno w prywatność jak i równość obywateli oraz "niepewność swoich praw" (ryzyko dyskryminacji ze względu na chorobę).**

**To o co tu prowadzę dialog to o zaprzestanie inwigilacji obywateli, zaprzestanie gromadzenia nadmiarowych danych (nie uwierzę w związek schizofrenii, depresji czy pozostałych z listy F w związek z COVID-19) i zakazanie szpitalom przekazywania danych wrażliwych (jakby chociaż choroby i zab. psychiczne) do ministerstw, jak też zaprzestanie wpisywania na e-receptach kodów ICD-10 jeżeli faktycznie są wpisywane.** 

> Jeśli chodzi o raportowanie świadczeniodawców dla NFZ to w ostatnim czasie wymogi te dramatycznie wzrosły - to są wręcz kwestie ostatnich miesięcy.
Na pewno można przez google sobie to odszukać - te zarządzenia są publicznie dostępne.

**Proszę o informacje, gdzie to znajdę i jakie to są konkretnie wymogi i kto ma obowiązek je raportować i na jakiej postawie?** Póki co wygląda na informacje wyssane z palca - brak kodów ICD-10 u znajomych przy przepisanych lekach 2 miesiące temu. 

> Odbiegamy jednak tutaj zbytnio od tematu, stąd przechodząc do meritum kwestii to co staramy się z moim Kolegą przekazać tutaj na forum jest fakt że "automat BT" mógłby mieć bardziej funkcję wspomagającą a realna-rzetelna informacja biorąca pod uwagę realne ryzyko i interakcje międzyludzkie wymaga naszym zdaniem odrobiny wysiłku i "ręcznego" zalogowania prawdziwego "kontaktu" zbieżnego z definicją WHO.

Kwestia automatu BT i jego nieskuteczności została wykazana w temacie #96. Będzie ogrom false-positive i false-negative. Tak więc tutaj w tym temacie trwają teraz dyskusje nad podstawą prawną wprowadzania tego typu aplikacji które na **100% staną się przymusowe**. Oraz przy okazji trwa poznanie prawdziwych przyczyn dla których te aplikacje zostaną wdrożone (dalsza inwigilacja, zmuszanie ludzi do przekazania swoich danych). Być może dalsza ingerencja w życie ludzi pozbycie ich całkowicie tajemnicy lekarskiej, prywatności i godności. 

> Jak już w innych wątkach pisałem jest to szczególnie ważne dla przerywania łańcucha zakażeń na poziomie służby zdrowia (ok. 30% zakażonych to pracownicy służby zdrowia) stąd adekwatna "wersja" aplikacji byłaby tu niezmiernie pomocna wszystkim medykom.

Tak i dlatego czytamy na dzisiejszej gazecie wyborczej, że pielęgniarka czeka już trzeci dzień na test. Aplikacja, która nie potrafi zmierzyć poprawnie odległości z kieszeni przez ścianę, szybę, szafkę z talerzami, ściankę w aptece itp. jest niezmiernie przydatna (ironia). Tak przydatna jak dziura w moście. Potrzebne są obligatoryjne cykliczne testy dla pielęgniarek i lekarzy (a nie dobrowolne), skoro aż 30% chorych to pielęgniarki i lekarze... Dobrowolny test dla lekarza przy **obowiązku tępienia COVID-19**? Wszystko brzmi jak **obłuda**. Mamy dość karmienia nas kłamstwami (niezależnie kto to robi). 

**Dobrze, że przy okazji wyszło, że naszą prywatność rządzący mają głęboko w poważaniu**.

**Comment by Dr-Kownacki** [comment]
Odsyłam do "zarządzeń prezesa NFZ" jest tego mnóstwo.
To że czegoś nie masz na recepcie "widocznego" to nic nie znaczy, ponieważ ta recepta została Ci wystawiona (pomijam pełnopłatną receptę z gabinetu prywatnego) albo podczas hospitalizacji przy wypisie ze szpitala (hospitalizacja refundowana przez NFZ), albo podczas ambulatoryjnej refundowanej wizyty w poradni POZ albo specjalistycznej. W obu przypadkach wszystkie szczegóły tej wizyty i hospitalizacji są raportowane do NFZ adekwatnymi kodami, ponieważ właśnie te kody implikują adekwatne procedury medyczne adekwatnie wycenione w koszyku świadczeń.
Tak więc brak informacji "na recepcie u znajomych" w widoczny sposób nie oznacza że tej informacji nie ma "w systemie". Na kierowaniu na badania kosztochłonne jest to wręcz prost wymagane i bez tego nie zarejestrujesz się na żadne badanie ambulatoryjnie refundowane przez NFZ.
Jeżeli nie zostanie to zgodnie z zarządzeniami NFZ dopełnione/raportowane to placówka-świadczeniodawca nie otrzyma refundacji za takiego pacjenta. 
**Tutaj chciałbym postawić kropkę, ponieważ wątek poboczny donikąd nie prowadzi, skupmy się na aplikacji.**
Być może wielu osobom "nie mieści się w głowie" jak działa system i jakie dane są przekazywane i w "obiegu", jednakże dalsze dociekania najlepiej samemu prowadzić i sprawdzić sobie pod adresem:
https://pacjent.gov.pl/

W moim przekonaniu literalnie te wszystkie dane są obligatoryjnie zbierane co do zasady wyłącznie z powodów "obrachunkowych" i każda wydana złotówka na pacjenta jest bardzo szczegółowo poparta jego danymi klinicznymi gdzie płatnik - NFZ ma praktycznie nieograniczone pole do wglądu do wszelkich danych w trakcie kontroli - czy się to nam podoba czy nie...
**KROPKA :-)**

**Comment by SeraMoon** [comment]
> 
> 
> Odsyłam do "zarządzeń prezesa NFZ" jest tego mnóstwo.
> To że czegoś nie masz na recepcie "widocznego" to nic nie znaczy, ponieważ ta recepta została Ci wystawiona (pomijam pełnopłatną receptę z gabinetu prywatnego) albo podczas hospitalizacji przy wypisie ze szpitala (hospitalizacja refundowana przez NFZ), albo podczas ambulatoryjnej refundowanej wizyty w poradni POZ albo specjalistycznej. W obu przypadkach wszystkie szczegóły tej wizyty i hospitalizacji są raportowane do NFZ adekwatnymi kodami, ponieważ właśnie te kody implikują adekwatne procedury medyczne adekwatnie wycenione w koszyku świadczeń.
> Tak więc brak informacji "na recepcie u znajomych" w widoczny sposób nie oznacza że tej informacji nie ma "w systemie". Na skierowaniu na badania kosztochłonne jest to wręcz wprost wymagane (kod musi być na skierowaniu) i bez tego nie zarejestrujesz się na żadne badanie ambulatoryjnie refundowane przez NFZ.
> Jeżeli nie zostanie to zgodnie z zarządzeniami NFZ dopełnione/raportowane to placówka-świadczeniodawca nie otrzyma refundacji za takiego pacjenta.
> **Tutaj chciałbym postawić kropkę, ponieważ wątek poboczny donikąd nie prowadzi, skupmy się na aplikacji.**
> Być może wielu osobom "nie mieści się w głowie" jak działa system i jakie dane są przekazywane i w "obiegu", jednakże dalsze dociekania najlepiej samemu prowadzić i sprawdzić sobie pod adresem:
> https://pacjent.gov.pl/
> 
> W moim przekonaniu literalnie te wszystkie dane są obligatoryjnie zbierane co do zasady wyłącznie z powodów "obrachunkowych" i każda wydana złotówka na pacjenta jest bardzo szczegółowo poparta jego danymi klinicznymi gdzie płatnik - NFZ ma praktycznie nieograniczone pole do wglądu do wszelkich danych w trakcie kontroli - czy się to nam podoba czy nie...
> **KROPKA :-)**

Toteż trafi sprawa do Rzecznika Praw Obywatelskich oraz do analizy do Urzędu Ochrony Danych Osobowych. Tak nie może być, aby do celów **obrachunkowych** wyciekała tajemnica lekarska. Poza tym powstaje pytanie, **jakim prawem te dane lecą dalej z NFZ?**. 

Szkoda, że nie ma podanych podstaw prawnych. Ułatwiłoby to dochodzenie w tej sprawie. 

Zgodnie bowiem z RODO na podstawie art. 15 ust. 3 mam prawo wiedzieć o wszystkich danych, jakie są przetwarzane i na wydruku e-recepty powinnam widzieć ewentualne kody ICD-10 jeżeli są przekazywane.

**Comment by kierepka** [comment]
@SeraMoon  chyba trochę przesadzasz. Bo tak to zgodnie z (s)RODO trzeba byłoby generować wydruk na x stron by spełnić wszystkie Twoje oczekiwania. 
Zaglądnij proszę co można wyciągnąć z prostych danych z recepty w oparciu o inne serwisy np. OSOZ - https://www.osoz.pl/osoz-mzk/servlet/main/index - tam prawnicy mocno tego pilnują. Możesz się z tego podoktoryzować i wrócić z informacją (jestem ciekawy jakie wnioski wyjdą z tych zapisów), bo na pewno też tu nie jestem w tej kwestii specjalistą, ale ten portal pamiętam jako najlepiej przygotowany pod kątem prawnym.

**Comment by kierepka** [comment]
@SeraMoon no i zobacz jak ładnie lecą w czasie rzeczywistym informacje o receptach: https://www.osoz.pl/core/

**Comment by SeraMoon** [comment]
@kierepka czy jest zgodny z prawem oceni UODO. Jest prosty jeden zapis - z tajemnicy lekarskiej może zwolnić tylko sąd. A pokazane dane nie wskazują aby leciały tam kody ICD-10. Jednak istnieje jeszcze coś takiego jak odpowiedź niezwłoczna przy wystąpieniu z art. 15 ust. 3. Instytucja, firma czy inny organ jest obowiązany udzielić pełnej odpowiedzi, w tym na jakiej podstawie pozyskał dane, kiedy i od kogo.

**Comment by kierepka** [comment]
@SeraMoon  no to poczekamy - na razie nie ma co więcej dyskutować. To już poziom dla prawników nie programistów.

**Comment by SeraMoon** [comment]
> 
> 
> @SeraMoon no to poczekamy - na razie nie ma co więcej dyskutować. To już poziom dla prawników nie programistów.

Nie zwalnia to programistów z napisania tej aplikacji w zgodności z Europejską Konwencją Praw Człowieka, Ustawą o Ochronie Danych Osobowych (i Rozporządzeniem RODO) oraz Ustawą o Prawach Pacjenta i RPP. 

Póki co aplikacja wygląda na pisaną dla rządu i sanepidu, a sanepid będzie traktował ją jak wyrocznię. Jak pokazałam w #96 i #100 aplikacja jest mówiąc krótko nic nie warta, by nie użyć innego określenia.

**Comment by qLb** [comment]
@SaraMoon 

> Kwestia automatu BT i jego nieskuteczności została wykazana w temacie #96. Będzie ogrom false-positive i false-negative. 

Przykro mi ale zgodnie z najlepszymi praktykami badawczymi udowodnic mozna cos na podstawie eksperymentu empirycznego, a z tego co rozumiem nikt z nas nie przedstawil jeszcze takiego eksperymentu poniewaz rozwiazanie G+A nie jest jeszcze gotowe a zatem nie ma na czym eksperymentowac. Proponuje zawiesic topory wojenne i zebrac sile na kolejna bitwe gdy juz bedziemy znali nowy uklad sil. w przeciwnym razie, marnujemy tylko te, ktore nam zostaly do walki z pandemia.

**Comment by kolmir** [comment]
Są też już wytyczne UE co do prywatności w tego typu appkach https://zdrowie.wprost.pl/koronawirus/na-swiecie/10315814/aplikacje-mobilne-do-walki-z-koronawirusem-sa-scisle-wytyczne-komisji-europejskiej.html

**Comment by Tarvald** [comment]
Z powodu dłuższej nieaktywności w tym wątku,
zostanie on automatycznie zamknięty w najbliższym czasie.

Jeżeli ktoś ma coś przeciwko to niech da znać, lub założy wątek zgodny z obecnymi założeniami.

**Comment by SeraMoon** [comment]
Myślę, że inne tematy zastępują obecnie kwestie prywatności podniesione tutaj. Wprowadzenie Progressive Web App - offline oraz napisanie regulaminów zgodnego z faktycznym działaniem aplikacji - rozwiąże te problemy.
